// Canvas2D DimensionCommitter tests (S34 Track C exit criterion).
//
// Verifies:
//   • All 5 arrowhead styles render the right primitives.
//   • save/restore wraps the call (state isolation).
//   • Override flag draws when isFlagged.
//   • Pure: runs in vitest's default Node env using a hand-rolled spy ctx
//     (no canvas package, no THREE).

import { describe, expect, it } from 'vitest';
import type {
  ArrowheadStyle,
  DimensionString,
  EvaluatedDimension,
} from '@pryzm/schemas/annotation/dimension';
import {
  commitDimensions,
  type Canvas2DLike,
  type ViewTransformMatrix,
} from '../src/dimensions.js';

// ── Spy ctx ────────────────────────────────────────────────────────────────

type Call =
  | { op: 'save' }
  | { op: 'restore' }
  | { op: 'setTransform'; m: ViewTransformMatrix }
  | { op: 'beginPath' }
  | { op: 'moveTo'; x: number; y: number }
  | { op: 'lineTo'; x: number; y: number }
  | { op: 'arc'; x: number; y: number; r: number; a0: number; a1: number }
  | { op: 'closePath' }
  | { op: 'stroke' }
  | { op: 'fill' }
  | { op: 'fillText'; text: string; x: number; y: number }
  | { op: 'translate'; x: number; y: number }
  | { op: 'rotate'; angle: number }
  | { op: 'setLineDash'; segs: readonly number[] }
  | { op: 'set'; prop: string; value: unknown };

function makeSpy(): { ctx: Canvas2DLike; calls: Call[] } {
  const calls: Call[] = [];
  let strokeStyle = '';
  let fillStyle = '';
  let lineWidth = 0;
  let font = '';
  let textAlign: CanvasTextAlign = 'start';
  let textBaseline: CanvasTextBaseline = 'alphabetic';
  const ctx: Canvas2DLike = {
    save: () => { calls.push({ op: 'save' }); },
    restore: () => { calls.push({ op: 'restore' }); },
    setTransform: (m) => { calls.push({ op: 'setTransform', m: { ...m } }); },
    beginPath: () => { calls.push({ op: 'beginPath' }); },
    moveTo: (x, y) => { calls.push({ op: 'moveTo', x, y }); },
    lineTo: (x, y) => { calls.push({ op: 'lineTo', x, y }); },
    arc: (x, y, r, a0, a1) => { calls.push({ op: 'arc', x, y, r, a0, a1 }); },
    closePath: () => { calls.push({ op: 'closePath' }); },
    stroke: () => { calls.push({ op: 'stroke' }); },
    fill: () => { calls.push({ op: 'fill' }); },
    fillText: (text, x, y) => { calls.push({ op: 'fillText', text, x, y }); },
    translate: (x, y) => { calls.push({ op: 'translate', x, y }); },
    rotate: (angle) => { calls.push({ op: 'rotate', angle }); },
    setLineDash: (segs) => { calls.push({ op: 'setLineDash', segs: [...segs] }); },
    get strokeStyle() { return strokeStyle; },
    set strokeStyle(v: string) { strokeStyle = v; calls.push({ op: 'set', prop: 'strokeStyle', value: v }); },
    get fillStyle() { return fillStyle; },
    set fillStyle(v: string) { fillStyle = v; calls.push({ op: 'set', prop: 'fillStyle', value: v }); },
    get lineWidth() { return lineWidth; },
    set lineWidth(v: number) { lineWidth = v; calls.push({ op: 'set', prop: 'lineWidth', value: v }); },
    get font() { return font; },
    set font(v: string) { font = v; calls.push({ op: 'set', prop: 'font', value: v }); },
    get textAlign() { return textAlign; },
    set textAlign(v: CanvasTextAlign) { textAlign = v; calls.push({ op: 'set', prop: 'textAlign', value: v }); },
    get textBaseline() { return textBaseline; },
    set textBaseline(v: CanvasTextBaseline) { textBaseline = v; calls.push({ op: 'set', prop: 'textBaseline', value: v }); },
  };
  return { ctx, calls };
}

// ── Test fixtures ──────────────────────────────────────────────────────────

const IDENTITY: ViewTransformMatrix = { a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 };

function makeEvald(overrides: Partial<EvaluatedDimension> = {}): EvaluatedDimension {
  return {
    id: 'dim-test' as EvaluatedDimension['id'],
    valueText: '5000',
    valueMm: 5000,
    p1World: [0, 0],
    p2World: [5000, 0],
    lineY: 50,
    witnessP1: [0, 52],
    witnessP2: [5000, 52],
    isOverride: false,
    isFlagged: false,
    ...overrides,
  };
}

function makeStr(overrides: Partial<DimensionString> = {}): DimensionString {
  return {
    id: 'dim-test' as DimensionString['id'],
    kind: 'linear-element',
    references: [
      { elementId: 'wall' as never, anchor: 'start' },
      { elementId: 'wall' as never, anchor: 'end' },
    ],
    orientation: 'horizontal',
    offsetMm: 50,
    viewId: 'view_001' as DimensionString['viewId'],
    override: null,
    textStyleRef: 'default-dim',
    witnessLines: { offset: 1, extension: 2, weight: 0.18 },
    arrowheads: 'tick',
    isAutoGenerated: true,
    ...overrides,
  };
}

// ── Top-level call ordering ────────────────────────────────────────────────

describe('commitDimensions', () => {
  it('calls save → setTransform → … → restore, in that order', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(ctx, [makeEvald()], new Map([['dim-test', makeStr()]]), 1, IDENTITY);
    expect(calls[0].op).toBe('save');
    expect(calls[1].op).toBe('setTransform');
    expect(calls[calls.length - 1].op).toBe('restore');
  });

  it('skips evaluated dims missing from the strings map', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(ctx, [makeEvald()], new Map(), 1, IDENTITY);
    // Only save / setTransform / restore should fire.
    const ops = calls.map((c) => c.op);
    expect(ops).toEqual(['save', 'setTransform', 'restore']);
  });

  it('renders nothing when evaluated array is empty', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(ctx, [], new Map(), 1, IDENTITY);
    expect(calls.map((c) => c.op)).toEqual(['save', 'setTransform', 'restore']);
  });
});

// ── Witness + dim-line drawing (horizontal) ───────────────────────────────

describe('horizontal dim — witness + dim line', () => {
  it('moves to p1World then to witnessP1, and same for p2', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(ctx, [makeEvald()], new Map([['dim-test', makeStr()]]), 1, IDENTITY);
    const moves = calls.filter((c) => c.op === 'moveTo') as Array<{ op: 'moveTo'; x: number; y: number }>;
    const lines = calls.filter((c) => c.op === 'lineTo') as Array<{ op: 'lineTo'; x: number; y: number }>;
    // First two moveTo/lineTo pairs are the two witness lines.
    expect(moves[0]).toEqual({ op: 'moveTo', x: 0, y: 0 });
    expect(lines[0]).toEqual({ op: 'lineTo', x: 0, y: 52 });
    expect(moves[1]).toEqual({ op: 'moveTo', x: 5000, y: 0 });
    expect(lines[1]).toEqual({ op: 'lineTo', x: 5000, y: 52 });
    // Then the dim line itself.
    expect(moves[2]).toEqual({ op: 'moveTo', x: 0, y: 50 });
    expect(lines[2]).toEqual({ op: 'lineTo', x: 5000, y: 50 });
  });

  it('writes valueText centered between p1 and p2, just above lineY', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(ctx, [makeEvald({ valueText: '5000' })], new Map([['dim-test', makeStr()]]), 1, IDENTITY);
    const text = calls.find((c) => c.op === 'fillText') as { op: 'fillText'; text: string; x: number; y: number };
    expect(text.text).toBe('5000');
    expect(text.x).toBeCloseTo(2500, 5);
    expect(text.y).toBeCloseTo(50 - 1.5, 5); // lineY - TEXT_GAP_MM*scale
  });
});

// ── Vertical text rotation ────────────────────────────────────────────────

describe('vertical dim — text rotation', () => {
  it('translate + rotate(-π/2) wrap the fillText call', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(
      ctx,
      [makeEvald({ p1World: [0, 0], p2World: [0, 3000], lineY: 100, witnessP1: [102, 0], witnessP2: [102, 3000] })],
      new Map([['dim-test', makeStr({ orientation: 'vertical' })]]),
      1,
      IDENTITY,
    );
    const i = calls.findIndex((c) => c.op === 'rotate');
    expect(i).toBeGreaterThan(0);
    expect((calls[i] as { op: 'rotate'; angle: number }).angle).toBeCloseTo(-Math.PI / 2, 5);
    // The save/translate/rotate/fillText/restore subsequence must appear.
    const opsAround = calls.slice(i - 2, i + 3).map((c) => c.op);
    expect(opsAround).toEqual(['save', 'translate', 'rotate', 'fillText', 'restore']);
  });
});

// ── All 5 arrowhead styles ────────────────────────────────────────────────

describe('arrowhead styles', () => {
  function countOps(arrowheads: ArrowheadStyle): {
    fills: number;
    arcs: number;
    closes: number;
    moves: number;
  } {
    const { ctx, calls } = makeSpy();
    commitDimensions(ctx, [makeEvald()], new Map([['dim-test', makeStr({ arrowheads })]]), 1, IDENTITY);
    return {
      fills: calls.filter((c) => c.op === 'fill').length,
      arcs: calls.filter((c) => c.op === 'arc').length,
      closes: calls.filter((c) => c.op === 'closePath').length,
      moves: calls.filter((c) => c.op === 'moveTo').length,
    };
  }

  it('tick: 2 extra moveTo/lineTo + 2 extra strokes (no fill)', () => {
    const r = countOps('tick');
    expect(r.fills).toBe(0);
    expect(r.arcs).toBe(0);
    expect(r.closes).toBe(0);
    // 2 witness moves + 1 dim-line move + 2 tick moves = 5.
    expect(r.moves).toBe(5);
  });
  it('open-arrow: 0 fill, 0 arc, 0 closePath; 2 chevrons add 2 moves', () => {
    const r = countOps('open-arrow');
    expect(r.fills).toBe(0);
    expect(r.arcs).toBe(0);
    expect(r.closes).toBe(0);
    expect(r.moves).toBe(5);
  });
  it('filled-arrow: 2 fills + 2 closePath', () => {
    const r = countOps('filled-arrow');
    expect(r.fills).toBe(2);
    expect(r.closes).toBe(2);
  });
  it('dot: 2 fills + 2 arcs', () => {
    const r = countOps('dot');
    expect(r.fills).toBe(2);
    expect(r.arcs).toBe(2);
  });
  it('none: no extra primitives', () => {
    const r = countOps('none');
    expect(r.fills).toBe(0);
    expect(r.arcs).toBe(0);
    expect(r.closes).toBe(0);
    // 2 witness + 1 dim-line = 3 moveTos only.
    expect(r.moves).toBe(3);
  });
});

// ── Override flag ─────────────────────────────────────────────────────────

describe('override flag', () => {
  it('draws an orange underline when isFlagged=true', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(
      ctx,
      [makeEvald({ isFlagged: true, isOverride: true })],
      new Map([['dim-test', makeStr()]]),
      1,
      IDENTITY,
    );
    // Look for a strokeStyle set to FLAG_COLOUR (#CC4400).
    const flagSet = calls.find((c) => c.op === 'set' && (c as { prop: string; value: unknown }).prop === 'strokeStyle' && (c as { prop: string; value: unknown }).value === '#CC4400');
    expect(flagSet).toBeDefined();
  });

  it('does not draw flag when isFlagged=false', () => {
    const { ctx, calls } = makeSpy();
    commitDimensions(
      ctx,
      [makeEvald()],
      new Map([['dim-test', makeStr()]]),
      1,
      IDENTITY,
    );
    const flagSet = calls.find((c) => c.op === 'set' && (c as { prop: string; value: unknown }).prop === 'strokeStyle' && (c as { prop: string; value: unknown }).value === '#CC4400');
    expect(flagSet).toBeUndefined();
  });
});
