/**
 * @file AICreatePanel.ts
 * @description 4-step wizard UI for AI-powered element generation.
 *
 * CONTRACT (04-BIM §3.1 Tool Layer):
 *  - NEVER mutates stores directly.
 *  - On "Generate" → AIElementFactory.generate() → pushes proposal to commandProposalStore
 *    → fires 'ai-proposal-added' event → AIPanel.showApprovalModal() picks it up.
 *  - Preview mesh uses AIElementEngine.create() directly — no store involvement.
 *  - Preview disposed on reset or panel close.
 *  - ID generated by AIElementFactory (Tool layer), not here.
 *
 * Integration points in Layout.ts:
 *   1. import { createAICreatePanel } from './ai/AICreatePanel';
 *   2. const aiCreatePanel = createAICreatePanel();
 *   3. Add toggleAICreatePanel() beside toggleAIPanel() in header buttons.
 *   4. Add <div id="ai-create-panel-container"> to BUI template (see Layout delta below).
 */

import * as BUI from '@thatopen/ui';
import * as THREE from '@pryzm/renderer-three/three';
import { AIElementFactory } from '@pryzm/ai-host';
import { AIElementEngine } from '@pryzm/geometry-furniture';
import { AIElementConfig } from '@pryzm/geometry-furniture';
import { commandProposalStore } from '@pryzm/command-registry';

// ── Helpers ───────────────────────────────────────────────────────────────────

function escapeHtml(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

function fileToBase64(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => {
            const result = reader.result as string;
            // Strip "data:<mime>;base64," prefix — API wants raw base64
            resolve(result.split(',')[1] ?? '');
        };
        reader.onerror = () => reject(new Error('FileReader failed'));
        reader.readAsDataURL(file);
    });
}

// ── Internal state ────────────────────────────────────────────────────────────

interface State {
    step: 1 | 2 | 3 | 4;
    imageBase64: string;
    imageFileName: string;
    prompt: string;
    generatedConfig: AIElementConfig | null;
    previewGroup: THREE.Group | null;
    isGenerating: boolean;
    error: string;
}

const state: State = {
    step: 1,
    imageBase64: '',
    imageFileName: '',
    prompt: '',
    generatedConfig: null,
    previewGroup: null,
    isGenerating: false,
    error: '',
};

// ── Preview helpers ───────────────────────────────────────────────────────────

function removePreview(): void {
    if (!state.previewGroup) return;
    const scene = window.scene as THREE.Scene | undefined; // TODO(D.4): replace with runtime.scene.three — Phase D.4
    scene?.remove(state.previewGroup);
    state.previewGroup.traverse(child => {
        if (child instanceof THREE.Mesh) {
            child.geometry?.dispose();
            if (Array.isArray(child.material)) {
                child.material.forEach((m: THREE.Material) => m.dispose());
            } else {
                (child.material as THREE.Material)?.dispose();
            }
        }
    });
    state.previewGroup = null;
}

function addPreview(config: AIElementConfig): void {
    removePreview();
    const scene = window.scene as THREE.Scene | undefined; // TODO(D.4): replace with runtime.scene.three — Phase D.4
    if (!scene) return;

    const group = AIElementEngine.create(config);

    const bimManager = window.bimManager; // TODO(D.4): replace via EngineBootstrap split — bimManager destroyed in D.4 — Phase D.4
    const levelId = window.projectContext?.activeLevelId as string | undefined; // TODO(C.3.x): replace with runtime.persistence.projectContext — Phase C.3.x
    const level = levelId ? bimManager?.getLevelById(levelId) : null;
    const baseY = level ? (level.elevation as number) + (config.baseOffset ?? 0) : 0;

    group.position.set(0, baseY, 0);
    group.userData = { isPreview: true };
    scene.add(group);
    state.previewGroup = group;
}

// ── Step indicator helper ─────────────────────────────────────────────────────

function gotoStep(step: 1 | 2 | 3 | 4): void {
    state.step = step;
    console.log(`[AICreatePanel] Transitioning to step ${step}`);
    
    // Use setTimeout to ensure DOM is ready (handles BUI async rendering)
    const updateUI = () => {
        let found = 0;
        ([1, 2, 3, 4] as const).forEach(s => {
            const el = document.getElementById(`ai-create-step-${s}`);
            if (el) {
                el.style.display = s === step ? 'flex' : 'none';
                el.style.flexDirection = 'column';
                found++;
                console.log(`[AICreatePanel] Step ${s}: display=${el.style.display}`);
            }

            const ind = document.getElementById(`ai-create-ind-${s}`);
            if (!ind) return;
            if (s < step)       { ind.style.background = '#28a745'; ind.style.color = '#fff'; }
            else if (s === step){ ind.style.background = '#6600ff'; ind.style.color = '#fff'; }
            else                { ind.style.background = '#e0e0e0'; ind.style.color = '#999'; }
        });
        
        // If not all steps found, retry (handles slow BUI rendering) - max 10 retries
        if (found < 4) {
            console.log(`[AICreatePanel] Not all steps found (${found}/4), retrying...`);
            setTimeout(updateUI, 100);
        } else {
            console.log(`[AICreatePanel] All steps found and updated successfully`);
        }
    };
    
    updateUI();
}

// ── File input handler ────────────────────────────────────────────────────────

async function handleFileInputChange(e: Event): Promise<void> {
    console.log('[AICreatePanel] File input onchange fired');
    const input = e.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) { console.log('[AICreatePanel] No file selected'); return; }
    try {
        console.log(`[AICreatePanel] Processing file: ${file.name}`);
        state.imageBase64 = await fileToBase64(file);
        state.imageFileName = file.name;
        const fn = document.getElementById('ai-create-filename');
        if (fn) {
            fn.textContent = `✓ ${file.name}`;
            console.log('[AICreatePanel] Filename updated in UI');
        }
        console.log('[AICreatePanel] Calling gotoStep(2)...');
        gotoStep(2);
    } catch (err) {
        console.error('[AICreatePanel] File processing error:', err);
        const st = document.getElementById('ai-create-status');
        if (st) {
            st.textContent = 'Failed to read image file.';
            (st as HTMLElement).style.color = '#dc3545';
        }
    }
}

// ── Main generate handler ─────────────────────────────────────────────────────

async function handleGenerate(
    setStatus: (msg: string, isError?: boolean) => void
): Promise<void> {
    console.log('[AICreatePanel] ▶ Generate button clicked - Starting Step 3 → Step 4 flow');
    
    const promptInput = document.getElementById('ai-create-prompt') as HTMLInputElement | null;
    const prompt = promptInput?.value?.trim() ?? state.prompt;
    
    if (!prompt) { 
        console.log('[AICreatePanel] ✗ Prompt empty, aborting generation');
        setStatus('Please describe the element.', true); 
        return; 
    }
    if (!state.imageBase64) { 
        console.log('[AICreatePanel] ✗ No image, aborting generation');
        setStatus('Please upload a photo first.', true); 
        return; 
    }

    const levelId = window.projectContext?.activeLevelId as string | undefined; // TODO(C.3.x): replace with runtime.persistence.projectContext — Phase C.3.x
    if (!levelId) { 
        console.log('[AICreatePanel] ✗ No active level, aborting generation');
        setStatus('No active level. Select one first.', true); 
        return; 
    }

    state.prompt = prompt;
    state.isGenerating = true;
    state.error = '';
    console.log(`[AICreatePanel] Prompt confirmed: "${prompt}"`);
    console.log(`[AICreatePanel] Level ID: ${levelId}`);

    const btn = document.getElementById('ai-create-gen-btn') as HTMLButtonElement | null;
    if (btn) { btn.disabled = true; btn.textContent = '⏳ Generating…'; }
    setStatus('Sending to Claude Vision API…');

    try {
        console.log('[AICreatePanel] Calling AIElementFactory.generate()...');
        const result = await AIElementFactory.generate({
            imageBase64: state.imageBase64,
            prompt,
            levelId,
            position: { x: 0, y: 0, z: 0 },
        });

        state.generatedConfig = result.config;
        console.log(`[AICreatePanel] ✓ Generated config: "${result.config.displayName}"`);
        console.log('[AICreatePanel] Adding preview to scene...');
        addPreview(result.config);

        // Push into the existing proposal/approval pipeline (AIPanel.ts)
        console.log('[AICreatePanel] Adding proposal to commandProposalStore...');
        commandProposalStore.add(result.proposal);
        
        console.log('[AICreatePanel] Dispatching "ai-proposal-added" event to AIPanel...');
        window.runtime?.events?.emit('ai-proposal-added', { proposal: result.proposal }); // F.events.12

        setStatus(`✓ "${result.config.displayName}" ready. Open AI Actions to approve.`);
        console.log('[AICreatePanel] Transitioning to Step 4...');
        gotoStep(4);

    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        state.error = msg;
        console.error('[AICreatePanel] ✗ Generation error:', msg, err);
        setStatus(`Error: ${msg}`, true);
    } finally {
        state.isGenerating = false;
        if (btn) { btn.disabled = false; btn.textContent = '✦ Generate Element'; }
        console.log('[AICreatePanel] Generate flow complete');
    }
}

function handleReset(): void {
    state.step = 1;
    state.imageBase64 = '';
    state.imageFileName = '';
    state.prompt = '';
    state.generatedConfig = null;
    state.error = '';
    removePreview();
    const p = document.getElementById('ai-create-prompt') as HTMLInputElement | null;
    if (p) p.value = '';
    const fn = document.getElementById('ai-create-filename');
    if (fn) fn.textContent = '';
    const st = document.getElementById('ai-create-status');
    if (st) { st.textContent = ''; (st as HTMLElement).style.color = '#555'; }
    gotoStep(1);
}

// ── Event listener attachment ─────────────────────────────────────────────

// Store handler references to allow proper cleanup
const eventHandlers: { [key: string]: EventListener | ((e: any) => void) } = {
    step2Back: () => { gotoStep(1); },
    step3Gen: () => { /* filled in attachEventListeners */ },
    step3Back: () => { gotoStep(2); },
    step4Action: handleOpenAIActions,
    step4Create: handleReset,
    promptKey: handlePromptKeyDown,
};

function attachEventListeners(setStatus: (msg: string, isError?: boolean) => void): void {
    console.log('[AICreatePanel] Attaching all event listeners...');
    
    // Update step3Gen handler with correct setStatus reference
    eventHandlers.step3Gen = () => { handleGenerate(setStatus); };

    // Step 2: Next button
    const step2NextBtn = document.querySelector('#ai-create-step-2 button:nth-of-type(1)') as HTMLButtonElement | null;
    if (step2NextBtn) {
        step2NextBtn.addEventListener('click', handleStep2Next);
        console.log('[AICreatePanel] ✓ Step 2 Next button listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Step 2 Next button not found');
    }

    // Step 2: Back button
    const step2BackBtn = document.querySelector('#ai-create-step-2 button:nth-of-type(2)') as HTMLButtonElement | null;
    if (step2BackBtn) {
        step2BackBtn.addEventListener('click', eventHandlers.step2Back);
        console.log('[AICreatePanel] ✓ Step 2 Back button listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Step 2 Back button not found');
    }

    // Step 3: Generate button
    const step3GenBtn = document.getElementById('ai-create-gen-btn') as HTMLButtonElement | null;
    if (step3GenBtn) {
        step3GenBtn.addEventListener('click', eventHandlers.step3Gen);
        console.log('[AICreatePanel] ✓ Step 3 Generate button listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Step 3 Generate button not found');
    }

    // Step 3: Back button
    const step3BackBtn = document.querySelector('#ai-create-step-3 button:nth-of-type(2)') as HTMLButtonElement | null;
    if (step3BackBtn) {
        step3BackBtn.addEventListener('click', eventHandlers.step3Back);
        console.log('[AICreatePanel] ✓ Step 3 Back button listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Step 3 Back button not found');
    }

    // Step 4: Open AI Actions button
    const step4ActionBtn = document.querySelector('#ai-create-step-4 button:nth-of-type(1)') as HTMLButtonElement | null;
    if (step4ActionBtn) {
        step4ActionBtn.addEventListener('click', eventHandlers.step4Action);
        console.log('[AICreatePanel] ✓ Step 4 Open AI Actions button listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Step 4 Open AI Actions button not found');
    }

    // Step 4: Create Another button
    const step4CreateBtn = document.querySelector('#ai-create-step-4 button:nth-of-type(2)') as HTMLButtonElement | null;
    if (step4CreateBtn) {
        step4CreateBtn.addEventListener('click', eventHandlers.step4Create);
        console.log('[AICreatePanel] ✓ Step 4 Create Another button listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Step 4 Create Another button not found');
    }

    // Step 2: Prompt input Enter key
    const promptInput = document.getElementById('ai-create-prompt') as HTMLInputElement | null;
    if (promptInput) {
        promptInput.addEventListener('keydown', eventHandlers.promptKey);
        console.log('[AICreatePanel] ✓ Prompt input keydown listener attached');
    } else {
        console.warn('[AICreatePanel] ✗ Prompt input not found');
    }
    
    console.log('[AICreatePanel] All event listeners attached successfully');
}

function handleStep2Next(): void {
    console.log('[AICreatePanel] Step 2 Next button clicked');
    const p = (document.getElementById('ai-create-prompt') as HTMLInputElement)?.value?.trim();
    if (!p) { 
        console.log('[AICreatePanel] Prompt is empty');
        const el = document.getElementById('ai-create-status');
        if (el) {
            el.textContent = 'Please enter a description.';
            (el as HTMLElement).style.color = '#dc3545';
        }
        return; 
    }
    state.prompt = p;
    console.log(`[AICreatePanel] Prompt set: "${p}"`);
    gotoStep(3);
}

function handlePromptKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Enter') {
        console.log('[AICreatePanel] Enter key pressed in prompt input');
        handleStep2Next();
    }
}

function handleOpenAIActions(): void {
    console.log('[AICreatePanel] Opening AI Actions panel');
    const panel = document.getElementById('ai-panel-container');
    if (panel) panel.style.display = 'flex';
    window.runtime?.events?.emit('ai-switch-tab', { tab: 'actions' }); // F.events.12
}

// ── Public factory ────────────────────────────────────────────────────────────

export function createAICreatePanel(runtime: import('@pryzm/runtime-composer/types').PryzmRuntime | null = null /* B-runtime createAICreatePanel */): ReturnType<typeof BUI.Component.create> {
    void runtime; /* B-runtime-void createAICreatePanel — TODO(C.3.x): consume once runtime.persistence is wired — Phase C.3.x */
    const setStatus = (msg: string, isError = false): void => {
        const el = document.getElementById('ai-create-status');
        if (!el) return;
        el.textContent = msg;
        (el as HTMLElement).style.color = isError ? '#dc3545' : '#555';
    };

    return BUI.Component.create<HTMLDivElement>(() => {
        // Defer step init and event handler attachment until DOM is ready - use longer delay to ensure BUI rendering
        setTimeout(() => {
            console.log('[AICreatePanel] Initializing panel, going to step 1');
            gotoStep(1);
            
            // CSP (script-src-attr 'none'): the dropzone's click-to-upload was
            // an inline onclick; wire it via addEventListener instead.
            const dropzone = document.getElementById('ai-create-dropzone');
            if (dropzone) {
                dropzone.addEventListener('click', () => {
                    document.getElementById('ai-create-file-input')?.click();
                });
            }

            // Manually attach file input change listener after DOM is ready
            const fileInput = document.getElementById('ai-create-file-input') as HTMLInputElement | null;
            if (fileInput) {
                console.log('[AICreatePanel] Attaching file input change listener');
                fileInput.addEventListener('change', handleFileInputChange);
            } else {
                console.warn('[AICreatePanel] File input not found, will retry...');
                setTimeout(() => {
                    const retryInput = document.getElementById('ai-create-file-input') as HTMLInputElement | null;
                    if (retryInput) {
                        console.log('[AICreatePanel] File input found on retry, attaching listener');
                        retryInput.addEventListener('change', handleFileInputChange);
                    }
                }, 200);
            }

            // Attach all button and input event listeners
            console.log('[AICreatePanel] Attaching all event listeners');
            attachEventListeners(setStatus);
        }, 300);

        return BUI.html`
        <div style="display: flex; flex-direction: column; height: 100%;">

            <!-- Header -->
            <div style="
                padding: 10px 12px; border-bottom: 1px solid rgba(255,255,255,0.15);
                background: var(--app-gradient, linear-gradient(135deg,#8B5CF6 0%,#6600FF 100%));
                display: flex; align-items: center;
                gap: 8px; flex-shrink: 0;
            ">
                <span style="font-size: 1rem; color: #fff;">✦</span>
                <span style="font-size: 0.85rem; color: #fff; font-weight: 700;">AI Element Creator</span>
            </div>

            <!-- Step indicators -->
            <div style="display: flex; gap: 4px; padding: 8px 12px; align-items: center; flex-shrink: 0;">
                ${([1, 2, 3, 4] as const).map(s => BUI.html`
                    <div id="ai-create-ind-${s}" style="
                        width: 22px; height: 22px; border-radius: 50%;
                        background: ${s === 1 ? '#6600ff' : '#e0e0e0'};
                        color: ${s === 1 ? '#fff' : '#999'};
                        display: flex; align-items: center; justify-content: center;
                        font-size: 10px; font-weight: 700; transition: all 0.2s;
                    ">${s}</div>
                    ${s < 4 ? BUI.html`<div style="flex: 1; height: 1px; background: #e0e0e0;"></div>` : BUI.html``}
                `)}
            </div>

            <!-- Step content -->
            <div style="flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 10px;">

                <!-- Step 1: Upload -->
                <div id="ai-create-step-1" style="display: flex; flex-direction: column; gap: 10px;">
                    <div style="font-size: 0.75rem; font-weight: 600; color: #333;">Step 1 — Upload a Reference Photo</div>
                    <div
                        id="ai-create-dropzone"
                        style="border: 2px dashed #ccc; border-radius: 8px; padding: 24px; text-align: center;
                               cursor: pointer; font-size: 0.7rem; color: #888; transition: border-color 0.2s;"
                    >
                        <div style="font-size: 1.5rem; margin-bottom: 8px;">📷</div>
                        <div>Click to upload a photo of the element</div>
                        <div id="ai-create-filename" style="margin-top: 8px; color: #0066cc; font-weight: 600;"></div>
                    </div>
                    <input
                        id="ai-create-file-input"
                        type="file"
                        accept="image/*"
                        style="display: none;"
                    >
                </div>

                <!-- Step 2: Describe -->
                <div id="ai-create-step-2" style="display: none; flex-direction: column; gap: 10px;">
                    <div style="font-size: 0.75rem; font-weight: 600; color: #333;">Step 2 — Describe the Element</div>
                    <input
                        id="ai-create-prompt"
                        type="text"
                        placeholder="e.g. Floor lamp with adjustable pole height…"
                        style="padding: 8px 10px; border: 1px solid #ddd; border-radius: 6px;
                               font-size: 0.75rem; outline: none;"
                    >
                    <button
                        style="padding: 8px; background: #0066cc; color: #fff; border: none;
                               border-radius: 6px; cursor: pointer; font-size: 0.75rem; font-weight: 600;"
                    >Next →</button>
                    <button
                        style="padding: 6px; background: transparent; border: 1px solid #ccc;
                               border-radius: 6px; cursor: pointer; font-size: 0.7rem; color: #666;"
                    >← Back</button>
                </div>

                <!-- Step 3: Review & Generate -->
                <div id="ai-create-step-3" style="display: none; flex-direction: column; gap: 10px;">
                    <div style="font-size: 0.75rem; font-weight: 600; color: #333;">Step 3 — Review & Generate</div>
                    <div style="background: #f8f8ff; border: 1px solid #e0e0ff; border-radius: 6px;
                                padding: 10px; font-size: 0.7rem; color: #444;">
                        <div><strong>Photo:</strong> ${state.imageFileName || '—'}</div>
                        <div style="margin-top: 4px;"><strong>Description:</strong> ${escapeHtml(state.prompt) || '—'}</div>
                        <div style="margin-top: 6px; font-size: 0.65rem; color: #888;">
                            A proposal will be sent for your review before anything is placed in the model.
                        </div>
                    </div>
                    <button
                        id="ai-create-gen-btn"
                        style="padding: 10px; background: linear-gradient(135deg, #7b2d8b, #4a1a6e); color: #fff;
                               border: none; border-radius: 6px; cursor: pointer; font-size: 0.8rem; font-weight: 700;"
                    >✦ Generate Element</button>
                    <button
                        style="padding: 6px; background: transparent; border: 1px solid #ccc;
                               border-radius: 6px; cursor: pointer; font-size: 0.7rem; color: #666;"
                    >← Back</button>
                </div>

                <!-- Step 4: Proposal Ready -->
                <div id="ai-create-step-4" style="display: none; flex-direction: column; gap: 10px;">
                    <div style="font-size: 0.75rem; font-weight: 600; color: #333;">Step 4 — Proposal Ready</div>
                    <div style="background: #e8f5e9; border: 1px solid #a5d6a7; border-radius: 6px;
                                padding: 10px; font-size: 0.7rem; color: #2e7d32;">
                        ✓ Proposal added to <strong>AI Actions</strong>.<br>
                        Open the AI panel → Actions tab → Approve to place the element.
                    </div>
                    <button
                        style="padding: 8px; background: #28a745; color: #fff; border: none;
                               border-radius: 6px; cursor: pointer; font-size: 0.75rem; font-weight: 600;"
                    >Open AI Actions →</button>
                    <button
                        style="padding: 6px; background: transparent; border: 1px solid #ccc;
                               border-radius: 6px; cursor: pointer; font-size: 0.7rem; color: #666;"
                    >Create Another</button>
                </div>

                <!-- Status bar (always visible) -->
                <div id="ai-create-status" style="font-size: 0.65rem; min-height: 18px; color: #555;"></div>
            </div>
        </div>
        `;
    });
}