// E8-TRIAL — DE-PROSE gold rows: Berlin Bebauungsplan 1-19 (Begründung),
// PDF pages 71–75 — section "II.4.3. Maß der baulichen Nutzung, überbaubare
// Grundstücksflächen" through the end of "Höhenfestsetzungen".
//
// ⭐ WHY THIS PLAN. Out-of-sample by construction: the German grammar in
// `packages/ordinance-extraction/src/grammars/german.ts` was authored against
// Berlin 8-30 and 1-14. 1-19 was picked by a stated, outcome-independent rule —
// the FIRST `.pdf` `grund_www` in WFS order (`bplan:b_bp_fs`, STARTINDEX=0,
// COUNT=300) after the two in-sample plans that classified `born-digital-text`.
// Its Producer is `AFPL Ghostscript 8.54`; 107 of 111 pages carry text.
//
// ⚠ DECLARED BIAS. The five pages are the section the document's OWN heading marks
// as the Maß-der-baulichen-Nutzung section. That is structural, not "where the
// numbers parsed", but it is still a rule-bearing selection: it supports precision
// and failure-shape claims, not a document-level recall claim.
//
// ⭐ THE FINDING THIS STRATUM EXISTS TO MEASURE. Berlin states heights as ABSOLUTE
// ELEVATIONS above Normalhöhennull — "eine Traufhöhe von maximal 55,0 m über NHN
// (18,8 m über dem mittleren Geländeniveau)". The building is 18.8 m tall. 55,0 is
// the sea-level elevation of its eaves. The plan states its own Bezugshöhe —
// 36,2 m über NHN — so the conversion is IN THE DOCUMENT and needs no assumption.
// A reader that takes 55,0 as a height overstates by ~2.9x, and `maxHeight_m ∈
// [3, 120]` means the range gate passes it.

import type { GoldRow } from './types.js';

const S = 'DE-PROSE' as const;

export const DE_PROSE_ROWS: readonly GoldRow[] = [
    // ───────────────────────── page 71 — Grundfläche / GRZ ─────────────────────────
    {
        id: 'de-prose/p71-so-grz-07/maxCoverage',
        stratum: S,
        locator: 'p71/grundflaeche-sondergebiet',
        field: 'maxCoverage',
        label: 'NOT-A-PARCEL-RULE',
        value: 0.7,
        unit: null,
        evidence: {
            page: 71,
            quote: 'Die zulässige Grundfläche im Sondergebiet Bundesnachrichtendienst ergibt sich aus den durch Baugrenzen definierten überbaubaren Grundstücksflächen, die eine Fläche von 65.612 m² umfassen und bezogen auf das gesamte Sondergebiet eine GRZ von 0,7 ergeben.',
            anchor: 'eine GRZ von 0,7 ergeben',
        },
        qualifiers: ['computed FROM the Baugrenzen; not itself festgesetzt'],
        reviewerNote:
            'A COMPUTED CONSEQUENCE ("ergeben"), not a Festsetzung. The plan says so explicitly one page later: "Die Festsetzung einer zulässigen Grundfläche oder einer GRZ ist daher entbehrlich." Emitting 0,7 attributes to the Sondergebiet a coverage the plan deliberately declines to set.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p71-wa-mi-grz-06/maxCoverage',
        stratum: S,
        locator: 'p71/grz-wa-mi',
        field: 'maxCoverage',
        label: 'NUMBER',
        value: 0.6,
        unit: 'ratio',
        evidence: {
            page: 71,
            quote: 'In den allgemeinen Wohngebieten und den Mischgebieten können die Grundstücke bis zu einer GRZ von 0,6 überbaut werden.',
            anchor: 'bis zu einer GRZ von 0,6 überbaut werden',
        },
        qualifiers: ['applicability: allgemeine Wohngebiete + Mischgebiete only', 'denominator: Grundstücksfläche (§19(1) BauNVO)'],
        reviewerNote: 'The binding coverage for the WA and MI areas. A true positive target.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p71-baunvo17-04/maxCoverage',
        stratum: S,
        locator: 'p71/baunvo-17-obergrenze',
        field: 'maxCoverage',
        label: 'NOT-A-PARCEL-RULE',
        value: 0.4,
        unit: null,
        evidence: {
            page: 71,
            quote: 'In den allgemeinen Wohngebieten wird die nach § 17 Abs.1 BauNVO bestimmte Grundflächenzahl von höchstens 0,4 überschritten.',
            anchor: 'nach § 17 Abs.1 BauNVO bestimmte Grundflächenzahl von höchstens 0,4',
        },
        qualifiers: ['a NATIONAL statutory ceiling (§17 Abs. 1 BauNVO), explicitly EXCEEDED by this plan'],
        reviewerNote:
            'The BauNVO §17 Obergrenze. It is not this plan\'s value — the sentence exists to say the plan goes ABOVE it. Emitting 0,4 understates by a third and cites a statute the plan overrides.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p71-19-4-overrun-08/maxCoverage',
        stratum: S,
        locator: 'p71/paragraph-19-4-ueberschreitung',
        field: 'maxCoverage',
        label: 'NOT-A-PARCEL-RULE',
        value: 0.8,
        unit: null,
        evidence: {
            page: 71,
            quote: 'Die zulässige Grundfläche darf gemäß § 19 Abs. 4 BauNVO durch Garagen und Stellplätze mit ihren Zufahrten, durch Nebenanlagen im Sinne von § 14 BauNVO und bauliche Anlagen unterhalb der Geländeoberfläche, durch die das Baugrundstück lediglich unterbaut wird, um bis zu 50% bis zu einer GRZ von 0,8 überschritten werden.',
            anchor: 'bis zu 50% bis zu einer GRZ von 0,8 überschritten werden',
        },
        qualifiers: [
            'an OVERRUN cap under §19(4) BauNVO',
            'countable only for Garagen, Stellplätze, Zufahrten, §14 Nebenanlagen and below-ground works',
        ],
        reviewerNote:
            'The §19(4) overrun ceiling for ancillary and below-ground works. It is NOT the buildable coverage of the main building. Emitting 0,8 as maxCoverage overstates the WA/MI coverage by a third.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p71-bwk-grz-08/maxCoverage',
        stratum: S,
        locator: 'p71/gemeinbedarf-bundeswehrkrankenhaus',
        field: 'maxCoverage',
        label: 'NUMBER',
        value: 0.8,
        unit: 'ratio',
        evidence: {
            page: 71,
            quote: 'Bedingt durch die erhöhten Flächenbedarfe von technischen Bauwerken, Zuleitungen und Verkehrsflächen wird auf der Gemeinbedarfsfläche Bundeswehrkrankenhaus eine GRZ von je 0,8 festgesetzt.',
            anchor: 'Gemeinbedarfsfläche Bundeswehrkrankenhaus eine GRZ von je 0,8 festgesetzt',
        },
        qualifiers: ['applicability: Gemeinbedarfsfläche Bundeswehrkrankenhaus only'],
        reviewerNote:
            '⚠ NOTE FOR THE SCORER: 0,8 is a LEGITIMATE value here and a FORBIDDEN one three sentences earlier (the §19(4) overrun). Value-level scoring therefore cannot penalise 0,8 — which is itself the point: distinguishing these two requires the LOCATOR, not the number. That is what the slot arm measures and the claim arm cannot.',
        humanConfirmed: false,
    },

    // ───────────────────────── page 72 — the §19(4) overrun again ─────────────────────────
    {
        id: 'de-prose/p72-tf10-festgesetzte-06/maxCoverage',
        stratum: S,
        locator: 'p72/tf-10-ueberschreitung',
        field: 'maxCoverage',
        label: 'NUMBER',
        value: 0.6,
        unit: 'ratio',
        evidence: {
            page: 72,
            quote: 'Aus gleichem Grund wird auf den Ver- und Entsorgungsflächen Abwasserpumpwerk, Regenrückhaltebecken und Heizkraftwerk durch die textliche Festsetzung Nr. 10 die Überschreitung der festgesetzten GRZ 0,6 bis zu einer GRZ von 1,0 ermöglicht.',
            anchor: 'die Überschreitung der festgesetzten GRZ 0,6',
        },
        qualifiers: ['applicability: Ver- und Entsorgungsflächen', 'restates the FESTGESETZTE value'],
        reviewerNote:
            'The word "festgesetzten" marks 0,6 as the binding base value. It shares a sentence with the 1,0 overrun cap, so a sentence-scoped reject would destroy it — the exact case `RejectPattern.unless` exists for.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p72-tf10-overrun-10/maxCoverage',
        stratum: S,
        locator: 'p72/tf-10-overrun-cap',
        field: 'maxCoverage',
        label: 'NOT-A-PARCEL-RULE',
        value: 1.0,
        unit: null,
        evidence: {
            page: 72,
            quote: '"Bei der Ermittlung der zulässigen Grundfläche darf durch die Grundfläche von Garagen und Stellplätzen und ihren Zufahrten, Nebenanlagen im Sinne des § 14 der Baunutzungsverordnung und bauliche Anlagen unterhalb der Geländeoberfläche die festgesetzte Grundflächenzahl in den Flächen für Versorgungsanlagen und Abwasserbeseitigung bis zu einer Grundflächenzahl von 1,0 überschritten werden." (textliche Festsetzung Nr. 10)',
            anchor: 'bis zu einer Grundflächenzahl von 1,0 überschritten werden',
        },
        qualifiers: ['an OVERRUN cap for ancillary and below-ground works only'],
        reviewerNote:
            '⭐ maxCoverage = 1,0 means 100% of the parcel is built over. The range gate\'s band is [0, 1] INCLUSIVE, so it PASSES. Nothing downstream would catch it. This is the cheapest catastrophic overstatement in the whole trial.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p72-kita-grz-03/maxCoverage',
        stratum: S,
        locator: 'p72/kindertagesstaette-grz',
        field: 'maxCoverage',
        label: 'NUMBER',
        value: 0.3,
        unit: 'ratio',
        evidence: {
            page: 72,
            quote: 'Der Bedarf an möglichst unversiegelten Freiflächen der Kindertagesstätte wird durch eine GRZ von 0,3 berücksichtigt.',
            anchor: 'Kindertagesstätte wird durch eine GRZ von 0,3',
        },
        qualifiers: ['applicability: Gemeinbedarfsfläche Kindertagesstätte only'],
        reviewerNote: 'The lowest binding coverage in the plan. A true positive target.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p72-so-keine-grz/maxCoverage',
        stratum: S,
        locator: 'p72/sondergebiet-keine-grz',
        field: 'maxCoverage',
        label: 'RULE-NOT-VALUE',
        value: null,
        unit: null,
        evidence: {
            page: 72,
            quote: 'Die überbaubaren Grundstücksflächen werden im Sondergebiet durch Baugrenzen festgesetzt, die die Baukörperstellung des im Architektenauswahlverfahren ermittelten Entwurfs nachzeichnen (erweiterte Baukörperausweisung). Die Festsetzung einer zulässigen Grundfläche oder einer GRZ ist daher entbehrlich.',
            anchor: 'Die Festsetzung einer zulässigen Grundfläche oder einer GRZ ist daher entbehrlich',
        },
        qualifiers: ['applicability: Sondergebiet', 'the constraint is GEOMETRIC (Baugrenzen), not a ratio'],
        reviewerNote:
            'The plan explicitly sets NO coverage ratio for the Sondergebiet — the envelope is drawn, not numbered. The honest outcome is a rule reference to the drawing, not a number and not "silent".',
        humanConfirmed: false,
    },

    // ───────────────────────── pages 72–74 — Geschossfläche / GFZ ─────────────────────────
    {
        id: 'de-prose/p72-gfz-32-berechnet/maxFAR',
        stratum: S,
        locator: 'p72/gfz-sondergebiet-berechnet',
        field: 'maxFAR',
        label: 'NOT-A-PARCEL-RULE',
        value: 3.2,
        unit: null,
        evidence: {
            page: 72,
            quote: 'Bei einer Größe des Baugrundstückes von 93.386 m², das allein das Sondergebiet und nicht die dem Grundstück zugeordneten privaten Parkanlagen umfasst, ergibt sich nach Maßgabe von § 20 BauNVO eine GFZ von 3,2.',
            anchor: 'ergibt sich nach Maßgabe von § 20 BauNVO eine GFZ von 3,2',
        },
        qualifiers: ['computed from absolute Geschossflächen ÷ Baugrundstück', 'denominator EXCLUDES the private Parkanlagen'],
        reviewerNote:
            'A computed consequence ("ergibt sich"). The Festsetzung is the absolute Geschossfläche (50.000 / 230.000 / 20.000 m²), not a ratio. Also: 3,2 exceeds the range gate\'s maxFAR band [0.2, 3.0], so this one WOULD be flagged — defence in depth working by accident.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p72-vorgabe-35/maxFAR',
        stratum: S,
        locator: 'p72/gutachterverfahren-vorgabe',
        field: 'maxFAR',
        label: 'NOT-A-PARCEL-RULE',
        value: 3.5,
        unit: null,
        evidence: {
            page: 72,
            quote: 'Sie liegt damit unter der im Rahmen des Gutachterverfahrens festgelegten Vorgabe von 3,5.',
            anchor: 'Gutachterverfahrens festgelegten Vorgabe von 3,5',
        },
        qualifiers: ['a competition brief target, with NO legal force'],
        reviewerNote:
            'A Vorgabe from a design competition. Not a Festsetzung, not a statute, not a value. Included because NO existing reject pattern covers this shape — a corpus that only contained cases the grammar already rejects would be self-certifying.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p73-gfz-30-mit-gruen/maxFAR',
        stratum: S,
        locator: 'p73/gfz-sondergebiet-mit-gruenflaechen',
        field: 'maxFAR',
        label: 'NOT-A-PARCEL-RULE',
        value: 3.0,
        unit: null,
        evidence: {
            page: 73,
            quote: 'Unter Einbeziehung der dem Grundstück zugeordneten privaten Grünflächen beträgt die GFZ 3,0.',
            anchor: 'Unter Einbeziehung der dem Grundstück zugeordneten privaten Grünflächen beträgt die GFZ 3,0',
        },
        qualifiers: ['⭐ a SECOND denominator for the SAME Sondergebiet — gross vs net of the Grünflächen'],
        reviewerNote:
            '⭐ THE DENOMINATOR TEST (control 8). 3,2 and 3,0 are the same building stock over two different land bases. Neither is a Festsetzung. An extractor that emits either without its denominator has lost the only thing that makes the ratio meaningful. ⚠ 3,0 is ALSO a legitimate Festsetzung value elsewhere on this page — so, like 0,8, the value arm cannot separate them.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p73-mi-gbf-gfz-30/maxFAR',
        stratum: S,
        locator: 'p73/gfz-mi1-mi2-bwk',
        field: 'maxFAR',
        label: 'NUMBER',
        value: 3.0,
        unit: 'ratio',
        evidence: {
            page: 73,
            quote: 'In den Mischgebieten MI 1 und MI 2 sowie der Gemeinbedarfsfläche Bundeswehrkrankenhaus erfolgt die Festsetzung einer GFZ von 3,0.',
            anchor: 'erfolgt die Festsetzung einer GFZ von 3,0',
        },
        qualifiers: ['applicability: MI 1, MI 2, Gemeinbedarfsfläche Bundeswehrkrankenhaus'],
        reviewerNote: 'A genuine Festsetzung ("erfolgt die Festsetzung"). True positive target.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p73-wa1-gfz-30/maxFAR',
        stratum: S,
        locator: 'p73/gfz-wa1',
        field: 'maxFAR',
        label: 'NUMBER',
        value: 3.0,
        unit: 'ratio',
        evidence: {
            page: 73,
            quote: 'Auch für das allgemeine Wohngebiet WA 1 erfolgt die Ausweisung einer GFZ von 3,0, die der zum Teil dort vorhandenen Bebauungsdichte und damit den bestehenden Baurechten entspricht und die eine gleichwertige Schließung der vorhandenen Baulücke ermöglicht.',
            anchor: 'für das allgemeine Wohngebiet WA 1 erfolgt die Ausweisung einer GFZ von 3,0',
        },
        qualifiers: ['applicability: WA 1 only'],
        reviewerNote: 'Same value, different area. True positive target.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p73-wa2-wa3-gfz-20/maxFAR',
        stratum: S,
        locator: 'p73/gfz-wa2-wa3',
        field: 'maxFAR',
        label: 'NUMBER',
        value: 2.0,
        unit: 'ratio',
        evidence: {
            page: 73,
            quote: 'Für die allgemeinen Wohngebiete WA 2 und WA 3 wird das Nutzungsmaß durch eine GFZ von 2,0 bestimmt.',
            anchor: 'WA 2 und WA 3 wird das Nutzungsmaß durch eine GFZ von 2,0',
        },
        qualifiers: ['applicability: WA 2 and WA 3 only'],
        reviewerNote:
            '⭐ THE APPLICABILITY TEST. WA 1 gets 3,0 and WA 2/WA 3 get 2,0 in adjacent sentences. A document-level extractor that emits "GFZ = 3,0" for the plan overstates WA 2 and WA 3 by 50%.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p73-baunvo17-gfz-12/maxFAR',
        stratum: S,
        locator: 'p73/baunvo-17-gfz-obergrenze',
        field: 'maxFAR',
        label: 'NOT-A-PARCEL-RULE',
        value: 1.2,
        unit: null,
        evidence: {
            page: 73,
            quote: 'Die durch § 17 Abs. 1 BauNVO bestimmte Obergrenze der GFZ von 1,2 für diese am 1. Juli 1990 überwiegend bebauten allgemeinen Wohngebiete und Mischgebiete wird durch die Ausweisung im Bebauungsplan überschritten.',
            anchor: '§ 17 Abs. 1 BauNVO bestimmte Obergrenze der GFZ von 1,2',
        },
        qualifiers: ['a NATIONAL statutory ceiling, explicitly EXCEEDED by this plan'],
        reviewerNote: 'The §17 GFZ Obergrenze. Not this plan\'s value.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p73-baunvo-so-gfz-24/maxFAR',
        stratum: S,
        locator: 'p73/baunvo-sondergebiet-gfz-max',
        field: 'maxFAR',
        label: 'NOT-A-PARCEL-RULE',
        value: 2.4,
        unit: null,
        evidence: {
            page: 73,
            quote: 'Ebenfalls überschritten wird die durch die BauNVO für Sondergebiete bestimmte maximale GFZ von 2,4.',
            anchor: 'für Sondergebiete bestimmte maximale GFZ von 2,4',
        },
        qualifiers: ['a NATIONAL statutory ceiling for Sondergebiete, explicitly EXCEEDED'],
        reviewerNote:
            'The word "maximale" sits directly in front of the number, which is exactly the shape a max-seeking matcher trusts. It is still a statute, not a Festsetzung.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-kita-gfz-10/maxFAR',
        stratum: S,
        locator: 'p74/kindertagesstaette-gfz',
        field: 'maxFAR',
        label: 'NUMBER',
        value: 1.0,
        unit: 'ratio',
        evidence: {
            page: 74,
            quote: 'Auf der Gemeinbedarfsfläche Kindertagesstätte wird mit einer geringeren Geschossflächenzahl von 1,0 den besonderen Anforderungen dieser Nutzung an eine ausreichende Belichtung und Belüftung Rechnung getragen.',
            anchor: 'geringeren Geschossflächenzahl von 1,0',
        },
        qualifiers: ['applicability: Gemeinbedarfsfläche Kindertagesstätte only'],
        reviewerNote: 'Long-form keyword ("Geschossflächenzahl"), binding value. True positive target.',
        humanConfirmed: false,
    },

    // ───────────────────────── pages 74–75 — Höhenfestsetzungen ─────────────────────────
    {
        id: 'de-prose/p74-bezugshoehe-362/maxHeight_m',
        stratum: S,
        locator: 'p74/bezugshoehe',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 36.2,
        unit: null,
        evidence: {
            page: 74,
            quote: 'Ausgehend vom Straßenniveau der Chausseestraße und der bewegten Topografie des Geländes wird als Bezugshöhe und mittleres Geländeniveau ein Niveau von 36,2 m über NHN zugrunde gelegt.',
            anchor: 'als Bezugshöhe und mittleres Geländeniveau ein Niveau von 36,2 m über NHN',
        },
        qualifiers: ['⭐ THE DATUM ITSELF — the ground elevation every other NHN figure in this plan is measured from'],
        reviewerNote:
            'Not a height at all: the ground. Recorded because it is the key that converts every "m über NHN" figure below into a real height, and because it is the number an unguarded height matcher is most likely to swallow first.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-mindesthoehe-512/maxHeight_m',
        stratum: S,
        locator: 'p74/so-mindesthoehe',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 51.2,
        unit: null,
        evidence: {
            page: 74,
            quote: 'Zur städtebaulichen Fassung der unbebauten Blockränder entlang der Chausseestraße, der Habersaathstraße und der Planstraße wird im Sondergebiet SO eine Gebäudeoberkante von 51,2 m über NHN entsprechend einer Höhe von 15,0 m über dem mittleren Geländeniveau als Mindesthöhe festgesetzt.',
            anchor: 'eine Gebäudeoberkante von 51,2 m über NHN',
        },
        qualifiers: [
            '⭐ it is a MINIMUM height ("als Mindesthöhe festgesetzt"), not a maximum',
            '⭐ 51,2 is an ELEVATION above NHN; the height above ground is 15,0 m and the document says so in the same sentence',
        ],
        reviewerNote:
            '⭐ WRONG TWICE. `Oberkante` is a `de-gebaeudehoehe` keyword and `51,2 m` follows it, so an unguarded matcher emits maxHeight_m = 51,2 — for a MINIMUM, expressed as a SEA-LEVEL ELEVATION, in a plan whose real cap is 21,8 m. That is a 2.35x overstatement inside the range gate\'s band.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-mindesthoehe-150/maxHeight_m',
        stratum: S,
        locator: 'p74/so-mindesthoehe-ueber-gelaende',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 15.0,
        unit: null,
        evidence: {
            page: 74,
            quote: 'entsprechend einer Höhe von 15,0 m über dem mittleren Geländeniveau als Mindesthöhe festgesetzt',
            anchor: 'einer Höhe von 15,0 m über dem mittleren Geländeniveau',
        },
        qualifiers: ['a MINIMUM height above ground, not a maximum'],
        reviewerNote:
            'The correctly-datumed twin of the row above — and STILL not a maxHeight_m, because it is a floor, not a ceiling. Emitting it would understate the cap by 6,8 m while looking perfectly sane.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-hoechstmass-218/maxHeight_m',
        stratum: S,
        locator: 'p74/so-hoechstmass-gebaeudehoehe',
        field: 'maxHeight_m',
        label: 'NUMBER',
        value: 21.8,
        unit: 'm',
        evidence: {
            page: 74,
            quote: 'Das festgesetzte Höchstmaß der Gebäudehöhe (Oberkante OK) orientiert sich mit 58,0 m über NHN (21,8 m über dem mittleren Geländeniveau) an der benachbarten bzw. gegenüberliegenden Bebauung.',
            anchor: '21,8 m über dem mittleren Geländeniveau',
        },
        qualifiers: [
            'applicability: Sondergebiet, the block-edge buildings',
            'datum: above the plan\'s own mittleres Geländeniveau of 36,2 m NHN',
        ],
        reviewerNote:
            '⭐ THE CENTRAL ROW OF THIS STRATUM. Two numbers, one sentence: 58,0 is an elevation, 21,8 is the height. The correct emission is 21,8. Both sit after the keyword `Gebäudehöhe`/`Oberkante`, and the first one a left-to-right matcher meets is the wrong one.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-hoechstmass-580/maxHeight_m',
        stratum: S,
        locator: 'p74/so-hoechstmass-nhn',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 58.0,
        unit: null,
        evidence: {
            page: 74,
            quote: 'Das festgesetzte Höchstmaß der Gebäudehöhe (Oberkante OK) orientiert sich mit 58,0 m über NHN (21,8 m über dem mittleren Geländeniveau) an der benachbarten bzw. gegenüberliegenden Bebauung.',
            anchor: 'mit 58,0 m über NHN',
        },
        qualifiers: ['an ELEVATION above Normalhöhennull, not a height'],
        reviewerNote: '58,0 − 36,2 = 21,8. The plan supplies its own conversion; nothing has to be assumed.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-schwartzkopff-562/maxHeight_m',
        stratum: S,
        locator: 'p74/schwartzkopffstrasse-oberkante',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 56.2,
        unit: null,
        evidence: {
            page: 74,
            quote: 'Die niedrigere Gebäudeoberkante von 56,2 m über NHN für die Gebäude gegenüber der Schwartzkopffstraße resultiert aus dem architektonischen Entwurf und den angestrebten baulichen Proportionen von Haupt- und Kopfgebäuden.',
            anchor: 'Gebäudeoberkante von 56,2 m über NHN',
        },
        qualifiers: ['an ELEVATION above NHN — the height above ground is 20,0 m (56,2 − 36,2)'],
        reviewerNote: 'Same trap, and here the document does NOT restate the height above ground — it must be derived.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-hauptgebaeude-707/maxHeight_m',
        stratum: S,
        locator: 'p74/hauptgebaeude-ok',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 70.7,
        unit: null,
        evidence: {
            page: 74,
            quote: 'In dem für das Hauptgebäude bestimmten Blockinnenbereich der Sondergebietsfläche ist eine Höhe OK von 70,7 m über NHN zulässig.',
            anchor: 'eine Höhe OK von 70,7 m über NHN',
        },
        qualifiers: ['an ELEVATION above NHN — the height above ground is 34,5 m'],
        reviewerNote: 'Emitted raw, this is a 34,5 m building reported as 70,7 m tall.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-baufeld-722/maxHeight_m',
        stratum: S,
        locator: 'p74/baufeld-inneres-oberkante',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 72.2,
        unit: null,
        evidence: {
            page: 74,
            quote: 'Im Inneren des Baufeldes ist eine Gebäudeoberkante von bis zu 72,2 m über NHN möglich.',
            anchor: 'Gebäudeoberkante von bis zu 72,2 m über NHN',
        },
        qualifiers: ['an ELEVATION above NHN — the height above ground is 36,0 m'],
        reviewerNote: 'The tallest NHN figure in the section, and the largest single overstatement available.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p74-entwurf-sieben-og/maxFloors',
        stratum: S,
        locator: 'p74/architekturentwurf-geschosse',
        field: 'maxFloors',
        label: 'NOT-A-PARCEL-RULE',
        value: 7,
        unit: null,
        evidence: {
            page: 74,
            quote: 'Die Höhenfestsetzungen ermöglichen die Umsetzung des ausgewählten Architekturentwurfs, der ein Sockel-, Erd- und sieben Obergeschosse vorsieht.',
            anchor: 'ein Sockel-, Erd- und sieben Obergeschosse vorsieht',
        },
        qualifiers: [
            'describes the WINNING DESIGN, not a Festsetzung',
            '"Obergeschosse" is not "Vollgeschosse" — the plan sets no storey count at all',
        ],
        reviewerNote:
            'A description of an architectural entry. This plan regulates height, never storeys. Any maxFloors emitted from these five pages is fabricated.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-verbindungsbauwerk-467/maxHeight_m',
        stratum: S,
        locator: 'p75/verbindungsbauwerk',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 46.7,
        unit: null,
        evidence: {
            page: 75,
            quote: 'Das Verbindungsbauwerk zwischen dem nördlichen und dem zentralen Baufeld des Sondergebiets wird in der Höhe auf 46,7 m über NHN begrenzt.',
            anchor: 'in der Höhe auf 46,7 m über NHN begrenzt',
        },
        qualifiers: ['an ELEVATION above NHN — the height above ground is 10,5 m', 'applies to ONE connecting structure'],
        reviewerNote: 'A 10,5 m link building. Read raw it becomes 46,7 m — a 4.4x overstatement.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-blockheizwerk-640/maxHeight_m',
        stratum: S,
        locator: 'p75/blockheizwerk-teilflaeche',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 64.0,
        unit: null,
        evidence: {
            page: 75,
            quote: 'Innerhalb einer an der Planstraße gelegenen Teilfläche des Baugebiets wird daher eine Höhe von 64,0 m über NHN ermöglicht.',
            anchor: 'eine Höhe von 64,0 m über NHN ermöglicht',
        },
        qualifiers: ['an ELEVATION above NHN — 27,8 m above ground', 'applies to a named Teilfläche only'],
        reviewerNote: 'Scoped to a sub-area for a Blockheizwerk. Neither the value nor the scope survives a document-level read.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-wa1-th-min-512/maxHeight_m',
        stratum: S,
        locator: 'p75/wa1-traufhoehe-minimum',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 51.2,
        unit: null,
        evidence: {
            page: 75,
            quote: 'Im allgemeinen Wohngebiet WA 1 wird die bauliche Höhe durch eine Traufhöhe TH von mindestens 51,2 m und höchsten 58,0 m über NHN ausgewiesen, mit der eine Schließung der vorhandenen Baulücke mit Bezug auf die Nachbarbebauung ermöglicht wird.',
            anchor: 'Traufhöhe TH von mindestens 51,2 m',
        },
        qualifiers: [
            '⭐ a MINIMUM ("mindestens") inside a sentence that also carries the maximum',
            'an ELEVATION above NHN',
        ],
        reviewerNote:
            '⭐ THE MIN/MAX TEST. One sentence carries a floor (51,2) and a ceiling (58,0), both as NHN elevations, both after the `Traufhöhe (TH)` keyword. Taking the first number after the keyword takes the MINIMUM and calls it a maximum.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-wa1-th-max-580/maxHeight_m',
        stratum: S,
        locator: 'p75/wa1-traufhoehe-maximum',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 58.0,
        unit: null,
        evidence: {
            page: 75,
            quote: 'eine Traufhöhe TH von mindestens 51,2 m und höchsten 58,0 m über NHN',
            anchor: 'höchsten 58,0 m über NHN',
        },
        qualifiers: ['the real WA 1 cap, but as an ELEVATION — 21,8 m above the plan\'s own Geländeniveau'],
        reviewerNote:
            'The correct WA 1 maximum expressed in the wrong frame. The extractable height is 21,8 m, and the plan states that conversion on the previous page.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-wa2-kita-th-512/maxHeight_m',
        stratum: S,
        locator: 'p75/wa2-kita-traufhoehe',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 51.2,
        unit: null,
        evidence: {
            page: 75,
            quote: 'Die bauliche Höhe TH im WA 2 und in der Gemeinbedarfsfläche „Kindertagesstätte" wird auf 51,2 m über NHN beschränkt.',
            anchor: 'wird auf 51,2 m über NHN beschränkt',
        },
        qualifiers: ['an ELEVATION above NHN — 15,0 m above ground', 'applicability: WA 2 and the Kita only'],
        reviewerNote:
            '⚠ 51,2 appears THREE times in this section as three different things: a Sondergebiet MINIMUM, a WA 1 MINIMUM, and a WA 2/Kita MAXIMUM. The number alone carries none of that. Only the locator does.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-uebrige-th-188/maxHeight_m',
        stratum: S,
        locator: 'p75/uebrige-baugebiete-traufhoehe',
        field: 'maxHeight_m',
        label: 'NUMBER',
        value: 18.8,
        unit: 'm',
        evidence: {
            page: 75,
            quote: 'In den übrigen Baugebieten erfolgt die Festsetzung der Höhe durch eine Traufhöhe von maximal 55,0 m über NHN (18,8 m über dem mittleren Geländeniveau).',
            anchor: '18,8 m über dem mittleren Geländeniveau',
        },
        qualifiers: [
            'applicability: "die übrigen Baugebiete" — everything not named above',
            'datum: eaves (Traufhöhe), above the plan\'s mittleres Geländeniveau',
        ],
        reviewerNote:
            'The second of only two extractable heights in the section. The correct value is 18,8; 55,0 is its elevation twin, and it is the number the keyword `Traufhöhe` sits next to.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-uebrige-th-550/maxHeight_m',
        stratum: S,
        locator: 'p75/uebrige-baugebiete-traufhoehe-nhn',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 55.0,
        unit: null,
        evidence: {
            page: 75,
            quote: 'eine Traufhöhe von maximal 55,0 m über NHN (18,8 m über dem mittleren Geländeniveau)',
            anchor: 'Traufhöhe von maximal 55,0 m über NHN',
        },
        qualifiers: ['an ELEVATION above NHN'],
        reviewerNote:
            '⭐ THE SINGLE MOST LIKELY EMISSION IN THE WHOLE TRIAL. Keyword `Traufhöhe`, connective `von maximal`, number `55,0`, unit `m` — the German height matcher\'s pattern in its ideal form. And the answer is 18,8.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-sechsgeschossig/maxFloors',
        stratum: S,
        locator: 'p75/sechsgeschossige-bebauung',
        field: 'maxFloors',
        label: 'NOT-A-PARCEL-RULE',
        value: 6,
        unit: null,
        evidence: {
            page: 75,
            quote: 'Das Maß ermöglicht eine sechsgeschossige Bebauung und vermittelt damit zwischen den zum Teil höheren und auch geringeren Höhen vorhandener Gebäude im Plangebiet und in den angrenzenden Gebieten.',
            anchor: 'ermöglicht eine sechsgeschossige Bebauung',
        },
        qualifiers: ['a CONSEQUENCE of the height rule, in words, not a Festsetzung'],
        reviewerNote: 'The plan sets no storey count. This sentence explains what the height permits; it does not permit it.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/p75-oberkanten-550-500/maxHeight_m',
        stratum: S,
        locator: 'p75/ver-entsorgung-oberkanten',
        field: 'maxHeight_m',
        label: 'NOT-A-PARCEL-RULE',
        value: 50.0,
        unit: null,
        evidence: {
            page: 75,
            quote: 'Die Bebauung der Ver- und Entsorgungsflächen Heizkraftwerk und Abwasserpumpwerk, Regenrückhaltebecken wird durch die Festsetzung von Oberkanten von 55,0 m über NHN bzw. 50,0 m über NHN begrenzt.',
            anchor: 'bzw. 50,0 m über NHN begrenzt',
        },
        qualifiers: ['an ELEVATION above NHN — 13,8 m above ground', 'applicability: Ver- und Entsorgungsflächen'],
        reviewerNote:
            'Note the keyword is PLURAL — "Oberkanten". The German matcher\'s keyword is `Oberkante` followed by `\\s*[)\\]]?\\s*`, which cannot consume the trailing "n". Whether that plural silently protects this sentence is a measurement, not an assumption.',
        humanConfirmed: false,
    },

    // ─────────────── fields the section never states (control 9 denominators) ───────────────
    {
        id: 'de-prose/section/minParcelArea_m2',
        stratum: S,
        locator: 'p71-75/section-wide',
        field: 'minParcelArea_m2',
        label: 'UNKNOWN',
        value: null,
        unit: null,
        evidence: { page: 71, quote: 'Section II.4.3 states no minimum parcel area anywhere on pages 71–75.', anchor: null },
        qualifiers: [],
        reviewerNote: 'Any minParcelArea_m2 emitted from this section is fabricated. Included so the denominator covers absence, not only error.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/section/setback.front',
        stratum: S,
        locator: 'p71-75/section-wide',
        field: 'setback.front',
        label: 'UNKNOWN',
        value: null,
        unit: null,
        evidence: {
            page: 72,
            quote: 'The only distance figures in the section are "ein Abstand von mindestens 30 m" between buildings and "um 5,0 bis 10,0 m zurückversetzten Baukörper" — neither is a festgesetzter Bauwich.',
            anchor: null,
        },
        qualifiers: [],
        reviewerNote: 'No setback is festgesetzt. The two distances present describe urban-design intent, not a parcel rule.',
        humanConfirmed: false,
    },
    {
        id: 'de-prose/section/maxFloors-absent',
        stratum: S,
        locator: 'p71-75/section-wide',
        field: 'maxFloors',
        label: 'UNKNOWN',
        value: null,
        unit: null,
        evidence: {
            page: 74,
            quote: 'The section regulates height by Traufhöhen and Oberkanten over NHN. The words "Vollgeschoss"/"Vollgeschosse" do not appear on pages 71–75 at all.',
            anchor: null,
        },
        qualifiers: [],
        reviewerNote:
            'This plan sets NO storey count. The two storey-like numbers present (seven Obergeschosse, sechsgeschossig) are a design description and a consequence.',
        humanConfirmed: false,
    },
];
