#!/usr/bin/env python3
"""Render SIG-M1-REVIEW-SAMPLE.md from sig-m1-review-sample.json + the concordance result."""
import json
import pathlib

BASE = pathlib.Path('docs/04-reference/jurisdictions/es/es-md/28079-madrid')
d = json.loads((BASE / 'extracted/sig-m1-review-sample.json').read_text(encoding='utf-8'))
conc = json.loads((BASE / 'extracted/quote-concordance-2026-08-01.json').read_text(encoding='utf-8'))
S = d['summary']
T = d['supersessionTrigger']

RISK = {
    'R1': 'segmentation across paragraphs',
    'R2': 'unmodelled condition',
    'R3': 'normalization',
    'R4': 'amended article (divergence)',
}


def esc(s):
    return str(s).replace('|', '\\|').replace('\n', ' ').strip()


def clip(s, n):
    s = esc(s)
    return s if len(s) <= n else s[:n - 1] + '…'


out = []
w = out.append

w('# SIG-M1 — targeted review of the `esMadridPgoum97.ts` transcription')
w('')
w('**Prepared 2026-08-02 for the founder\'s conditional approval.** This is the artefact the')
w('signature is conditioned on:')
w('')
w('> *"The extraction methodology is now sufficiently evidenced. Before publication: complete the')
w('> targeted human review; verify the four residual-risk classes; confirm end-to-end rendering under')
w('> the **pipeline-extracted-unverified** confidence tier. If those pass: **Sign.** No further legal')
w('> review required."*')
w('')
w('> ⚠ **NOTHING IN THIS FILE IS A SIGNATURE, AND IT DOES NOT FLIP A GATE.**')
w('> `MADRID_ENVELOPE_VERIFIED` is `false` and stays `false` until a human signs')
w('> [`../sources/VERIFICATION.md`](../sources/VERIFICATION.md) SIG-M1. This document exists to make')
w('> that decision cheap and checkable — **not** to pre-empt it.')
w('')
w('---')
w('')
w('## §0 — The three preconditions, ticked or not')
w('')
w('| # | Precondition | Status | Evidence |')
w('|---|---|---|---|')
w('| **1** | The targeted human review | 🟡 **ARTEFACT READY — a human has not yet read it** | this file: '
  f'**{S["sampled"]} records** across all **{S["shippedZones"]}** shipped zones, '
  f'**{S["coverageOfShippedPct"]} %** of the {S["shippedZoneRecords"]} records those zones carry |')
w('| **2** | The four residual-risk classes verified | 🟡 **R1–R3 fully enumerated and tabulated below; '
  'R4 has a MECHANISM, not a sample** | §2–§5. R1/R2/R3 are **100 % sampled** — every record carrying '
  'one is in this file. R4 = the supersession trigger in §5 |')
w('| **3** | End-to-end rendering at `pipeline-extracted-unverified` | ✅ **VERIFIED IN CODE** | '
  '`madridPgoum97Wiring.test.ts` §RED-CHIP-NZ7-NZ8 solves **every** NZ-7/NZ-8 grado through '
  '`computeBuildableEnvelope` and asserts the tier; `GISAreaLayout.ts:2596` badges it as the **first** '
  'arm (weakest-wins), so the violet "Estimated" chip cannot shadow the red one. **This is ADR-0286 '
  'in code form for Madrid.** |')
w('')
w('⚠ **Precondition 3 was the one previously believed to BLOCK the signature.** Two separate code')
w('comments (`siteDispatch.ts`, `esMadridPgoum97.ts`) asserted that `ZoningRulesEngine` hard-codes')
w('`estimated-ruleset` and never reads `defaultConfidence`. **Both were stale** — fixed in L-665 by')
w('`§PACK-CONFIDENCE-CEILING`. They were still being quoted as live blockers on the day this review')
w('was commissioned. Corrected in place.')
w('')
w('---')
w('')
w('## §1 — What this review covers, stated honestly')
w('')
w('| | |')
w('|---|---:|')
w(f'| Records in the pack, all zones | {S["packRecordsTotal"]} |')
w(f'| Records in the **23 SHIPPED** zones (the signature\'s scope) | **{S["shippedZoneRecords"]}** |')
w(f'| Records reproduced in this file | **{S["sampled"]}** |')
w(f'| **Coverage of the shipped scope** | **{S["coverageOfShippedPct"]} %** |')
w(f'| Distinct articles cited by the shipped zones | {S["articlesCited"]} |')
w('')
w('**The sample is not random and must not be read as one.** It is the union of:')
w('')
w('- **every** record carrying R1, R2 or R3 — the three sampleable residual-risk classes, at **100 %**; and')
w('- **one clean record per zone**, so a reader can see the ordinary case beside the risky ones.')
w('')
w('⚠ **What 52.4 % coverage does and does not license.** It licenses a signature on the *transcription*')
w('of the risk-bearing material, because that material is covered exhaustively. It does **not** license')
w('a claim that every one of the 231 records has been read by a person. **The unsampled ~48 % are the')
w('records with no detected structural risk** — short, single-paragraph, unconditioned, on an')
w('unamended article. If the signer wants 100 %, say so and the remaining records will be tabulated;')
w('the artefact is generated by `tools/madrid-extract/build_sig_m1_review.py` and re-runs in seconds.')
w('')
w('### The one prior measurement this review rests on')
w('')
tally = conc['summary']['tally']
w(f'**§MADRID-QUOTE-CONCORDANCE** (2026-08-01) re-read **all {conc["summary"]["quotesChecked"]}** '
  '`verbatim` strings in `extracted/*.json` against the filed Compendio '
  f'(`{conc["summary"]["pdf"]}`, {conc["summary"]["pdfPages"]} pp):')
w('')
w('| verdict | n |')
w('|---|---:|')
for k in ('ON-CLAIMED-PAGE', 'SPANS-FROM-CLAIMED', 'ELSEWHERE', 'TABLE-RECONSTRUCTION',
          'NOT-FOUND', 'NO-PAGE-CLAIMED'):
    if k in tally:
        w(f'| `{k}` | {tally[k]} |')
w('')
w('**0 fabricated. 0 cited to a wrong page.** All 48 `NOT-FOUND` were inspected individually and every')
w('one is an explicit `…`/`[…]` elision by the extractor, a substituted terminal full stop, or the')
w('checker\'s own footnote-interleave artefact — never a quote that is not in the document.')
w('')
w('⚠ **That is a CONCORDANCE result and it is not what SIG-M1 asks for.** It proves a string was')
w('**copied** from the Compendio. Whether the *parsed number* correctly **interprets** that string is')
w('the reading only a human can do — and it is exactly what the R1/R2 tables below put in front of one.')
w('')
w('---')
w('')
w('## §2 — How to review this, in one sitting')
w('')
w('For each row: read the **verbatim** column against the **parsed value**, and answer one question —')
w('***does the quote, on its own, justify that value?*** Three outcomes:')
w('')
w('- **OK** — the quote states the value.')
w('- **⚠ INCOMPLETE** — the value is right but a governing condition is missing (this is R1/R2, and it')
w('  is the failure mode aggregate QC cannot see).')
w('- **✖ WRONG** — the value is not what the quote says.')
w('')
w('The article, apartado and **printed page** are given so any row can be checked against')
w('[`../corpus/pdf/COMPENDIO_MPG_NNUU_24-09-2025_PGOUM-97.pdf`](../corpus/pdf/COMPENDIO_MPG_NNUU_24-09-2025_PGOUM-97.pdf)')
w(f'(sha256 `{T["corpusSha256"][:16]}…`). **Printed page = PDF page − 2** throughout Título 8.')
w('')
w('---')
w('')

# ── risk sections ──────────────────────────────────────────────────────────
for code in ('R1', 'R2', 'R3'):
    rows = [r for r in d['sample'] if code in r['risks']]
    w(f'## §3.{code[-1]} — {code}: {RISK[code]} — **{len(rows)} records, 100 % of this class**')
    w('')
    if code == 'R1':
        w('**Why this class matters most.** The number is usually transcribed correctly; the risk is that')
        w('its *governing clause* sits in a paragraph the record did not carry, so the pack applies a')
        w('value in circumstances the ordinance excludes. **Read the quote for what is MISSING**, not for')
        w('whether the digits match.')
    elif code == 'R2':
        w('**Why this class matters.** The quote carries a conditional — *salvo · excepto · siempre que ·')
        w('no obstante · podrá · con carácter excepcional* — and `GeometricRule` has **no field to hold')
        w('it**. The value ships unconditioned. Ask: *would ignoring this condition ever OVER-state the')
        w('envelope?* If yes, that zone needs a refusal or a new rule kind, not a number.')
    else:
        w('**Why this class matters.** The stored string is not literally what the page shows — a')
        w('synthesised table row (`"Menos de 12 | 3 | 11,50"`), a Spanish decimal comma, or an elision.')
        w('Ask: *does the reformatting change the reading?* A pipe-joined row is a reconstruction, and')
        w('calling it `verbatim` is a provenance mislabel worth correcting at source.')
    w('')
    w('| zone | art. | apdo. | pág. | parsed value | verbatim (from the Compendio) | verdict |')
    w('|---|---|---|---:|---|---|---|')
    for r in rows:
        val = r['value']
        val = '—' if val is None else f'`{esc(val)}`' + (f' {esc(r["unit"])}' if r.get('unit') else '')
        extra = []
        if r.get('measurement'):
            extra.append(f'meas={esc(r["measurement"])}')
        if r.get('denominatorScope'):
            extra.append(f'denom={esc(r["denominatorScope"])}')
        pv = f'**{esc(r["param"])}** = {val}' + (f'<br><sub>{" · ".join(extra)}</sub>' if extra else '')
        w(f'| `{esc(r["zone"])}` | {esc(r["articulo"])} | {esc(r["apartado"])} | '
          f'{r["printedPage"]} | {pv} | «{clip(r["verbatim"], 300)}» | ☐ |')
    w('')

# ── R4 trigger ─────────────────────────────────────────────────────────────
w('---')
w('')
w('## §5 — R4: future Compendio divergence — a TRIGGER, not a sample')
w('')
w('**This risk cannot be sampled.** No inspection of today\'s text tells you whether tomorrow\'s')
w('consolidation moves an article. So the mechanism, not a spot-check:')
w('')
w(f'- The filed corpus is pinned by **sha256 `{T["corpusSha256"]}`** ({T["corpusPages"]} pp, PDF')
w(f'  `title` metadata `{T["corpusTitleMeta"]}`). Swapping the PDF without re-running this review')
w('  changes that hash.')
w(f'- **{S["articlesWithAmendments"]} of the {S["articlesCited"]} cited articles already carry an')
w('  amendment footnote in this edition**, recorded per article in `sig-m1-review-sample.json`')
w('  → `supersessionTrigger.articles`. That is the baseline a future edition is diffed against.')
w('- ⚠ **The BOCM texts behind those footnotes are NOT held.** Two matter most:')
w('  **MPG 00/343** (aprob. def. 08.11.2023, BOCM 27.11.2023) and **MPG 00/335** (10.05.2016, BOCM')
w('  19.05.2016). A signature on this transcription is a signature on a **consolidation** — the')
w('  Compendio states on every page that *«la versión oficial … se ha publicado en el BOCM»*.')
w('')
w('**The trigger, concretely:** re-run `build_sig_m1_review.py` against any new Compendio edition and')
w('diff `supersessionTrigger.articles`. **Any article whose amendment set changes invalidates the')
w('signature for that article only** — not for the pack — which keeps re-certification proportionate.')
w('')
w('### Articles carrying an amendment footnote in the filed edition')
w('')
w('| article | pages | amendments recorded on the page |')
w('|---|---|---|')
for art, info in sorted(T['articles'].items()):
    if info['amendments']:
        w(f'| **{esc(art)}** | {", ".join(str(p) for p in info["pages"])} | '
          f'{clip("; ".join(info["amendments"]), 180)} |')
w('')
w('---')
w('')
w('## §6 — What a signature here would and would not mean')
w('')
w('**WOULD certify** — that `esMadridPgoum97.ts` is an accurate transcription of the Compendio 2025')
w(f'for the **{S["shippedZones"]} shipped zones**, publishable at **`pipeline-extracted-unverified`**,')
w('explicitly identified as a machine-generated derivative and not as a manually certified legal')
w('transcription.')
w('')
w('**WOULD NOT certify:**')
w('')
w('- **The six zones excluded as unsignable IN PRINCIPLE** — `4`, `9.1`, `9.2` (height is the')
w('  unresolved *ancho de calle* table, so the pack carries the ordinance FLOOR and **over-states**')
w('  above 9,00 m) and `5.1`, `5.2`, `5.3` (Art. 8.5.6.3 measures to the street **centreline**, which')
w('  `GeometricRule` cannot express, so no front inset is applied and it **over-states** on a narrow')
w('  street). ⚠ **These are defects in the NUMBERS, which no confidence label cures.**')
w('- Anything about the **BOCM** text. This is a consolidation.')
w('- **Norma Zonal 3** — a legally grounded refusal that survives any signature (Art. 8.3.1 governs;')
w('  see `findings/L-678-NZ3-ARTICLE-VERDICT-AND-LAYER-EXTENTS.md`).')
w('- **Norma Zonal 1** — separately signed as SIG-M2 (Doctrine B / ADR-0283).')
w('- Promotion above `pipeline-extracted-unverified`. ⚠ That is a **separate, later** decision: it')
w('  changes `MADRID_PGOUM97_DEFAULT_CONFIDENCE` in the pack, and `capEnvelopeConfidenceToPackDefault`')
w('  is **demote-only** by design (ADR-0286), so a promotion is a deliberate, signed, reviewable edit —')
w('  never a side effect of opening the gate.')
w('')
w('---')
w('*Generated by `tools/madrid-extract/build_sig_m1_review.py` from `extracted/nz*.json` + the filed')
w('corpus. Machine-readable backing: `sig-m1-review-sample.json`. Authority: L-449 · ADR-0283 ·')
w('ADR-0286 · C58 §1.2/§1.6 · C63 §1.6.*')

(BASE / 'extracted/SIG-M1-REVIEW-SAMPLE.md').write_text('\n'.join(out) + '\n', encoding='utf-8')
print('wrote SIG-M1-REVIEW-SAMPLE.md —', len(out), 'lines')
