/**
 * PoolPlanToolHandler — §FIX-POOL-UNREACHABLE (L-5210..L-5216) · ADR-0124 · C100
 *
 * THE PLAN-VIEW ROUTE THAT MAKES A SWIMMING POOL REACHABLE. It is the third of the
 * four axes L-5200 measured as closed:
 *
 *   1. no `PoolStore` was ever constructed              → closed by PluginRegistry
 *   2. no `pool`/`water` storeKey, so the bus threw     → closed by PluginRegistry
 *   3. NOTHING DISPATCHED `pool.create`                 → CLOSED HERE
 *   4. the AI chat classifies `pool.create` class B     → still open (L-5206)
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⭐ THIS FILE CONTAINS NO POOL GEOMETRY. That is the point.
 * ═══════════════════════════════════════════════════════════════════════════════
 * It draws an OUTLINE and dispatches ONE command. Every dimension, every wall,
 * the floor slab, the water body and the hole in the host slab are computed by
 * `buildPoolAssembly()` in `@pryzm/geometry-pool`, which is pure and already
 * tested. There is no second assembly here, no hole-punching routine, and not one
 * dimensional literal — `resolvePoolDimensions()` is the only source of a pool
 * dimension in this repo and `poolNoLiterals.test.ts` enforces that at source level.
 *
 * ⭐ AND NO NEW SHAPE VOCABULARY. The six modes come from `activePoolDrawMode`,
 * which is the union of two EXISTING `@pryzm/geometry-slab` unions, and the
 * closed-loop rings are generated by `boundaryLoopVertices()` — the same generator
 * the slab, floor-finish and ceiling tools call. The founder asked for
 * "linear, ortho — but also circular, ellipse, rectangular"; all six are served by
 * machinery that already shipped, so the strip cannot offer a shape the generator
 * does not implement (§FIX-STAIR-SHAPE-DESYNC's lesson).
 *
 * ── THE ONE GENUINELY POOL-SPECIFIC PROBLEM: WHICH SLAB IS THE HOST? ──────────
 * A pool is cut INTO something. `CreatePoolHandler.canExecute` refuses when
 * `ctx.stores.slab[hostSlabId]` is absent — "a pool with no slab to cut into is not
 * a pool; it is a hole in the air" — so this handler must name a host BEFORE it
 * dispatches, and must refuse legibly when it cannot.
 *
 * Resolution order, strongest first:
 *   1. GEOMETRY — the slab on the active level whose boundary CONTAINS the pool
 *      outline's centroid. This is the natural gesture: draw the pool on the
 *      terrace and the terrace is the host, with nothing to select first.
 *   2. SELECTION — an explicitly selected slab. This is the `OpeningPlanToolHandler`
 *      convention and it is kept as the OVERRIDE for the case geometry cannot
 *      settle: overlapping slabs, or a pool deliberately cut into a slab it is not
 *      centred on.
 *   3. REFUSE, BY NAME (C16 CA-18). Never "silently create nothing", and never
 *      invent a host. The refusal says which of the two routes to use.
 *
 * ⚠ MEASURED CAVEAT, STATED RATHER THAN HIDDEN. The lookup reads the plugin slab
 * DTO store when the runtime exposes it, and falls back to the legacy
 * `window.slabStore`. Those are two stores and this repo already knows they can
 * diverge (the "detached-DTO-mirror condition",
 * PLUGIN-SDK-AND-EXTERNAL-API-READINESS-REGISTER §374). A slab present ONLY in the
 * legacy store will pass this handler's check and then be REFUSED by
 * `canExecute` — which is why the dispatch's rejection is caught and surfaced
 * verbatim below rather than swallowed. That is honest failure, not a fix for the
 * duality; the duality is pre-existing and is recorded as L-5215.
 */

import { createId } from '@pryzm/schemas';
import { pointInPolygonXZ } from '@pryzm/geometry-kernel';
import {
    boundaryLoopVertices, boundaryLoopRefusal, BOUNDARY_LOOP_GESTURE,
    arcSegmentThroughMidpoint, orthoConstrain,
} from '@pryzm/geometry-slab';
import type { PlanToolHandler, PlanToolDrawContext, WorldPoint } from './PlanToolHandler';
import { resolveActivePoolDrawMode, activePoolLoopMode } from './activePoolDrawMode';
// §FIX-PLAN-TOOL-POINTER-UNREACHABLE (L-7004) — the slab that was selected AT THE
// MOMENT THE TOOL WAS ARMED. Arming a plan-only tool now suppresses 3-D selection
// (L-7003, so an armed create tool can no longer pick a wall and attach a gizmo), and
// `SelectionManager.setEnabled(false)` calls `unselectAll()` on the way down. Without
// this snapshot the SELECTION override below would read empty for every pool drawn
// after the fix — a defect introduced by a fix, which is why the snapshot ships in the
// same commit as the suppression rather than after it.
import { armedSelectionId } from './armedSelectionSnapshot';

/** PRYZM purple — the shared preview colour every plan tool draws in. */
const STROKE = '#6600ff';
const FILL_A = 'rgba(102,0,255,0.10)';

/** The minimum vertices any closed outline needs. Not a dimension — a topology fact. */
const MIN_LOOP_VERTS = 3;

/** A slab record as this handler needs to read it — deliberately the narrowest shape. */
interface HostSlabCandidate {
    readonly id: string;
    readonly levelId?: string;
    readonly boundary?: ReadonlyArray<{ x: number; z: number }>;
}

export class PoolPlanToolHandler implements PlanToolHandler {
    private _ctx:         PlanToolDrawContext | null = null;
    private _points:      WorldPoint[] = [];
    private _cursorPoint: WorldPoint | null = null;
    private _loopAnchor:  WorldPoint | null = null;
    private _arcMidPt:    WorldPoint | null = null;
    /** The last refusal, shown on the overlay so it reaches a PERSON, not a console. */
    private _refusal:     string | null = null;

    /** §T-B1 — opt-in stroke preservation: a half-drawn pool survives an excursion
     *  to the toolbar rather than being wiped by a deactivate-on-leave. */
    hasActiveStroke(): boolean {
        return this._points.length > 0 || this._loopAnchor !== null || this._arcMidPt !== null;
    }

    activate(ctx: PlanToolDrawContext): void {
        this._ctx = ctx;
        this._resetStroke();
    }

    deactivate(): void {
        this._clearOverlay();
        this._resetStroke();
        this._ctx = null;
    }

    // ── Interaction ──────────────────────────────────────────────────────────

    onMouseMove(pt: WorldPoint): void {
        // Mode is re-read on EVERY sample (the `WallModePicker.getActiveMode()`
        // contract) so a switch on the mode strip applies to the very next click
        // without re-activating the tool and destroying the stroke.
        const mode = resolveActivePoolDrawMode();

        if (activePoolLoopMode() && this._loopAnchor) {
            this._cursorPoint = pt;
            this._drawPreview();
            return;
        }
        if (mode === 'ortho' && this._points.length > 0) {
            this._cursorPoint = this._orthoSnap(this._points[this._points.length - 1]!, pt);
            this._drawPreview();
            return;
        }
        if (this._points.length > 0) {
            this._cursorPoint = pt;
            this._drawPreview();
        }
    }

    onClick(pt: WorldPoint): void {
        const mode = resolveActivePoolDrawMode();
        // A new click is a new attempt: clear any refusal still on screen so the
        // user is never told why the LAST gesture failed while making a new one.
        this._refusal = null;

        // ── CLOSED-LOOP modes: RECTANGULAR / CIRCULAR / ELLIPTICAL ───────────
        // One gesture, one arm — the ring maths lives in `boundaryLoops`, so all
        // three share it and none of them is special-cased here.
        const loopMode = activePoolLoopMode();
        if (loopMode) {
            if (!this._loopAnchor) {
                this._loopAnchor  = pt;
                this._points      = [pt];
                this._cursorPoint = pt;
                this._drawPreview();
                return;
            }
            const first  = { x: this._loopAnchor.worldX, z: this._loopAnchor.worldZ };
            const second = { x: pt.worldX, z: pt.worldZ };
            const ring = boundaryLoopVertices(loopMode, first, second);
            if (ring.length < MIN_LOOP_VERTS) {
                // ⛔ C16 CA-18 — name the reason AND what does work. Never silently
                // fall back to another shape: a circle that quietly became a
                // rectangle is a worse outcome than a refusal.
                this._refuse(boundaryLoopRefusal(loopMode, first, second)
                    ?? 'That outline is too small to make a pool.');
                return;
            }
            this._points = ring.map(v => ({ worldX: v.x, worldZ: v.z } as WorldPoint));
            this._commit();
            return;
        }

        // ── CURVED — vertex → arc MIDPOINT → arc END (the wall tool's 3-click) ──
        if (mode === 'curved' && this._points.length > 0) {
            if (!this._arcMidPt) {
                this._arcMidPt    = pt;
                this._cursorPoint = pt;
                this._drawPreview();
                return;
            }
            const last = this._points[this._points.length - 1]!;
            const run = arcSegmentThroughMidpoint(
                { x: last.worldX,           z: last.worldZ           },
                { x: this._arcMidPt.worldX, z: this._arcMidPt.worldZ },
                { x: pt.worldX,             z: pt.worldZ             },
            );
            for (const v of run) this._points.push({ worldX: v.x, worldZ: v.z } as WorldPoint);
            this._arcMidPt = null;
            this._drawPreview();
            return;
        }

        // ── LINEAR / ORTHO — accumulate vertices ─────────────────────────────
        const vertex = (mode === 'ortho' && this._points.length > 0)
            ? this._orthoSnap(this._points[this._points.length - 1]!, pt)
            : pt;
        this._points.push(vertex);
        this._drawPreview();
    }

    onDoubleClick(_pt: WorldPoint): void {
        if (activePoolLoopMode()) return;      // closed loops commit on the 2nd click
        if (this._arcMidPt) return;            // don't eat the pending arc END click
        if (this._points.length >= MIN_LOOP_VERTS) this._commit();
    }

    onKeyDown(e: KeyboardEvent): boolean {
        if (e.key === 'Enter' && this._points.length >= MIN_LOOP_VERTS
            && !activePoolLoopMode() && !this._arcMidPt) {
            e.preventDefault();
            this._commit();
            return true;
        }
        if (e.key === 'Backspace' && this._arcMidPt) {
            this._arcMidPt = null;
            this._drawPreview();
            return true;
        }
        if (e.key === 'Backspace' && this._points.length > 0) {
            this._points.pop();
            if (this._points.length === 0) this._loopAnchor = null;
            this._drawPreview();
            return true;
        }
        return false;
    }

    cancel(): void {
        this._resetStroke();
        this._clearOverlay();
    }

    redraw(): void {
        if (this._points.length > 0) this._drawPreview();
    }

    // ── Commit ───────────────────────────────────────────────────────────────

    private _commit(): void {
        const c = this._ctx;
        if (!c || this._points.length < MIN_LOOP_VERTS) return;

        const levelId = c.viewDef.spatial?.levelId;
        if (!levelId) {
            this._refuse('This view has no level, so there is nothing to cut a pool into.');
            return;
        }

        // The outline the user drew IS the pool boundary — and it is also the hole,
        // the wall centreline loop, the floor outline and the water outline. ONE
        // polygon drives all four parts, which is why they cannot drift apart.
        const boundary = this._points.map(p => ({ x: p.worldX, y: 0, z: p.worldZ }));

        const host = this._resolveHostSlab(boundary, levelId);
        if (!host) {
            // ⛔ C16 CA-18 — the refusal names BOTH routes back to success. "A pool
            // with no slab to cut into is not a pool; it is a hole in the air."
            this._refuse(
                'A pool must be cut into a slab. Draw it over a slab on this level, '
                + 'or select the slab first and draw again.',
            );
            return;
        }

        // CA-2 — ids are minted ONCE, HERE, and passed in. `execute()` runs again on
        // REDO, so minting inside the handler would silently produce a DIFFERENT
        // pool the second time. One wall id per boundary EDGE, in boundary order.
        const payload = {
            poolId:      createId('pool'),
            levelId,
            hostSlabId:  host,
            boundary,
            wallIds:     boundary.map(() => createId('wall')),
            floorSlabId: createId('slab'),
            waterId:     createId('water'),
        };

        // ONE dispatch = ONE undo entry across all four stores (C16 §8.6 B-6). The
        // handler uses `produceMultiStoreCommand`; nothing is batched here.
        const dispatch = c.runtime?.bus?.executeCommand('pool.create', payload)
            ?? window.runtime?.bus?.executeCommand('pool.create', payload);

        if (!dispatch) {
            this._refuse('The command bus is not available, so no pool was created.');
            return;
        }

        void Promise.resolve(dispatch).catch((e: unknown) => {
            // ⭐ SURFACE THE BUS'S OWN REASON, VERBATIM. `canExecute` rejections
            // arrive as `CommandBusError: pool.create: canExecute rejected — <why>`,
            // and that `<why>` is the most accurate sentence available (duplicate
            // id, host slab not found, degenerate outline). Swallowing it here is
            // exactly the "reported activation, activated nothing" defect this lane
            // exists to avoid.
            const why = e instanceof Error ? e.message : String(e);
            console.error('[PoolPlanToolHandler] pool.create failed:', why);
            this._refuse(why);
        });

        this._resetStroke();
        this._clearOverlay();
    }

    // ── Host-slab resolution ─────────────────────────────────────────────────

    /**
     * The slab this pool is cut into, or `null`.
     *
     * GEOMETRY FIRST, then SELECTION. See the file header for why that order and
     * why the fallback is kept rather than dropped.
     */
    private _resolveHostSlab(
        boundary: ReadonlyArray<{ x: number; z: number }>,
        levelId: string,
    ): string | null {
        const centroid = this._centroidOf(boundary);

        for (const slab of this._candidateSlabs()) {
            if (slab.levelId !== undefined && slab.levelId !== levelId) continue;
            const ring = slab.boundary;
            if (!ring || ring.length < MIN_LOOP_VERTS) continue;
            if (pointInPolygonXZ(centroid.x, centroid.z, ring)) return slab.id;
        }

        // OVERRIDE — an explicitly selected slab wins when geometry cannot settle
        // it (overlapping slabs, or a pool deliberately off-centre from its host).
        return this._selectedSlabId();
    }

    /**
     * Every slab this handler can see, preferring the PLUGIN DTO store because that
     * is the store `CreatePoolHandler.canExecute` will read. Reading the legacy
     * store alone would let this handler name a host the bus then refuses — the
     * detached-DTO-mirror condition described in the file header.
     */
    private _candidateSlabs(): readonly HostSlabCandidate[] {
        const out: HostSlabCandidate[] = [];

        // 1. The plugin DTO store — the one the bus reads.
        const pluginSlabs = (window as unknown as {
            runtime?: { stores?: Record<string, { getState?: () => Map<string, unknown> }> };
        }).runtime?.stores?.['slab'];
        const state = pluginSlabs?.getState?.();
        if (state) {
            for (const [id, rec] of state) {
                const r = rec as { levelId?: string; boundary?: { x: number; z: number }[] };
                out.push({ id, levelId: r.levelId, boundary: r.boundary });
            }
        }
        if (out.length > 0) return out;

        // 2. The legacy engine store — what the other plan tools read today.
        const legacy = window.slabStore as unknown as { getAll?: () => unknown[] } | undefined; // TODO(TASK-08)
        for (const rec of legacy?.getAll?.() ?? []) {
            const r = rec as { id?: string; levelId?: string; boundary?: { x: number; z: number }[] };
            if (r?.id) out.push({ id: r.id, levelId: r.levelId, boundary: r.boundary });
        }
        return out;
    }

    /**
     * An explicitly selected slab id, if the current selection is one.
     *
     * THREE readings, strongest first, and the third is the one L-7004 added:
     *   1. the live selection's `userData` (a slab mesh is selected right now);
     *   2. the live selection's id, when it carries the `slab` prefix;
     *   3. ⭐ the ARM-TIME snapshot — because arming this tool DISABLES selection and
     *      `setEnabled(false)` unselects everything, so by the time the architect has
     *      drawn the outline readings 1 and 2 are both empty BY CONSTRUCTION. The
     *      snapshot is taken immediately before the suppression; see
     *      `armedSelectionSnapshot.ts`.
     */
    private _selectedSlabId(): string | null {
        const sel = (window as unknown as {
            selectionManager?: {
                getSelectedId?: () => string | null;
                selectedObject?: { userData?: { elementType?: string; id?: string } };
            };
        }).selectionManager;
        const obj = sel?.selectedObject;
        if (obj?.userData?.elementType?.toLowerCase() === 'slab' && obj.userData.id) {
            return obj.userData.id;
        }
        const id = sel?.getSelectedId?.();
        if (id && id.startsWith('slab')) return id;
        const armed = armedSelectionId();
        return armed && armed.startsWith('slab') ? armed : null;
    }

    /** Plan centroid of a ring (vertex average — sufficient for a containment probe). */
    private _centroidOf(ring: ReadonlyArray<{ x: number; z: number }>): { x: number; z: number } {
        let x = 0, z = 0;
        for (const p of ring) { x += p.x; z += p.z; }
        return { x: x / ring.length, z: z / ring.length };
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /** The ONE ortho constraint — the wall tool's, shared via `@pryzm/geometry-slab`. */
    private _orthoSnap(from: WorldPoint, to: WorldPoint): WorldPoint {
        const v = orthoConstrain(
            { x: from.worldX, z: from.worldZ },
            { x: to.worldX,   z: to.worldZ   },
        );
        return { worldX: v.x, worldZ: v.z } as WorldPoint;
    }

    private _resetStroke(): void {
        this._points      = [];
        this._cursorPoint = null;
        this._loopAnchor  = null;
        this._arcMidPt    = null;
    }

    /**
     * Record a refusal AND put it on the overlay.
     *
     * ⭐ A `console.warn` is not a refusal — it is a refusal nobody reads. The
     * founder's "Create Stair" report was exactly this shape: the tool reported
     * success and did nothing. Every path that declines to create a pool comes
     * through here, so the user always learns why.
     */
    private _refuse(message: string): void {
        this._refusal = message;
        this._resetStroke();
        this._drawRefusal();
    }

    private _drawRefusal(): void {
        const c = this._ctx;
        if (!c || !this._refusal) return;
        const { ctx, overlayCanvas, dpr } = c;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        const cssW = overlayCanvas.width  / dpr;
        const cssH = overlayCanvas.height / dpr;
        ctx.clearRect(0, 0, cssW, cssH);
        ctx.save();
        this._drawHint(ctx, cssH, this._refusal);
        ctx.restore();
    }

    private _drawPreview(): void {
        const c = this._ctx;
        if (!c || this._points.length === 0) return;
        const { ctx, overlayCanvas, planCanvas, dpr } = c;
        const mode = resolveActivePoolDrawMode();

        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        const cssW = overlayCanvas.width  / dpr;
        const cssH = overlayCanvas.height / dpr;
        ctx.clearRect(0, 0, cssW, cssH);
        ctx.save();

        // ── CLOSED-LOOP preview ──────────────────────────────────────────────
        // ⭐ Generated from THE SAME ring the commit will use, so what the user
        // aims at cannot diverge from what lands.
        const loopMode = activePoolLoopMode();
        if (loopMode && this._loopAnchor && this._cursorPoint) {
            const ring = boundaryLoopVertices(
                loopMode,
                { x: this._loopAnchor.worldX,  z: this._loopAnchor.worldZ  },
                { x: this._cursorPoint.worldX, z: this._cursorPoint.worldZ },
            );
            const pts = ring.map(v => planCanvas.worldToScreen(v.x, v.z));
            if (pts.length >= MIN_LOOP_VERTS) {
                this._fillPath(ctx, pts);
                this._strokePath(ctx, pts, true);
            }
            this._drawHint(ctx, cssH, `${BOUNDARY_LOOP_GESTURE[loopMode].second} · Esc to cancel`);
            ctx.restore();
            return;
        }

        const screenPts = this._points.map(p => planCanvas.worldToScreen(p.worldX, p.worldZ));

        const trailing: Array<{ sx: number; sy: number }> = [];
        if (this._cursorPoint) {
            if (mode === 'curved' && this._arcMidPt && this._points.length > 0) {
                const last = this._points[this._points.length - 1]!;
                for (const v of arcSegmentThroughMidpoint(
                    { x: last.worldX,           z: last.worldZ           },
                    { x: this._arcMidPt.worldX, z: this._arcMidPt.worldZ },
                    { x: this._cursorPoint.worldX, z: this._cursorPoint.worldZ },
                )) trailing.push(planCanvas.worldToScreen(v.x, v.z));
            } else {
                trailing.push(planCanvas.worldToScreen(this._cursorPoint.worldX, this._cursorPoint.worldZ));
            }
        }

        if (screenPts.length >= MIN_LOOP_VERTS) this._fillPath(ctx, [...screenPts, ...trailing]);
        this._strokePath(ctx, [...screenPts, ...trailing], false);

        if (mode === 'curved' && this._arcMidPt) {
            const m = planCanvas.worldToScreen(this._arcMidPt.worldX, this._arcMidPt.worldZ);
            ctx.fillStyle = STROKE;
            ctx.beginPath(); ctx.arc(m.sx, m.sy, 5, 0, Math.PI * 2); ctx.fill();
        }

        ctx.fillStyle = STROKE;
        for (const p of screenPts) { ctx.beginPath(); ctx.arc(p.sx, p.sy, 4, 0, Math.PI * 2); ctx.fill(); }

        this._drawHint(ctx, cssH, this._hintFor(mode));
        ctx.restore();
    }

    private _hintFor(mode: string): string {
        const label = mode === 'ortho' ? 'Orthogonal' : mode === 'curved' ? 'Curved' : 'Linear';
        if (mode === 'curved' && this._points.length > 0) {
            return this._arcMidPt
                ? 'Curved · Click the arc END point · Backspace to re-pick midpoint'
                : `Curved · Click the arc MIDPOINT${this._points.length >= MIN_LOOP_VERTS ? ' · Enter to close pool' : ''}`;
        }
        const missing = MIN_LOOP_VERTS - this._points.length;
        return this._points.length >= MIN_LOOP_VERTS
            ? `${label} · Dbl-click or Enter to close pool`
            : `${label} · ${missing} more point${missing !== 1 ? 's' : ''} needed`;
    }

    private _fillPath(ctx: CanvasRenderingContext2D, pts: ReadonlyArray<{ sx: number; sy: number }>): void {
        if (pts.length < MIN_LOOP_VERTS) return;
        ctx.globalAlpha = 0.14;
        ctx.fillStyle   = FILL_A;
        ctx.beginPath();
        ctx.moveTo(pts[0]!.sx, pts[0]!.sy);
        for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i]!.sx, pts[i]!.sy);
        ctx.closePath(); ctx.fill();
        ctx.globalAlpha = 1;
    }

    private _strokePath(
        ctx: CanvasRenderingContext2D,
        pts: ReadonlyArray<{ sx: number; sy: number }>,
        close: boolean,
    ): void {
        if (pts.length === 0) return;
        ctx.setLineDash([6, 3]);
        ctx.lineWidth   = 1.5;
        ctx.strokeStyle = STROKE;
        ctx.beginPath();
        ctx.moveTo(pts[0]!.sx, pts[0]!.sy);
        for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i]!.sx, pts[i]!.sy);
        if (close) ctx.closePath();
        ctx.stroke();
        ctx.setLineDash([]);
    }

    private _drawHint(ctx: CanvasRenderingContext2D, cssH: number, text: string): void {
        ctx.font         = 'bold 11px sans-serif';
        ctx.fillStyle    = 'rgba(102,0,255,0.9)';
        ctx.textAlign    = 'left';
        ctx.textBaseline = 'bottom';
        ctx.fillText(text, 12, cssH - 12);
    }

    private _clearOverlay(): void {
        const c = this._ctx;
        if (!c) return;
        c.ctx.setTransform(1, 0, 0, 1, 0, 0);
        c.ctx.clearRect(0, 0, c.overlayCanvas.width, c.overlayCanvas.height);
    }
}
