/**
 * PoolPlanToolHandler — §FIX-POOL-UNREACHABLE (L-5210..L-5216) · ADR-0124 · C100
 *
 * THE PLAN-VIEW ROUTE THAT MAKES A SWIMMING POOL REACHABLE. It is the third of the
 * four axes L-5200 measured as closed:
 *
 *   1. no `PoolStore` was ever constructed              → closed by PluginRegistry
 *   2. no `pool`/`water` storeKey, so the bus threw     → closed by PluginRegistry
 *   3. NOTHING DISPATCHED `pool.create`                 → CLOSED HERE
 *   4. the AI chat classifies `pool.create` class B     → still open (L-5206)
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⭐ THIS FILE CONTAINS NO POOL GEOMETRY. That is the point.
 * ═══════════════════════════════════════════════════════════════════════════════
 * It draws an OUTLINE and dispatches ONE command. Every dimension, every wall,
 * the floor slab, the water body and the hole in the host slab are computed by
 * `buildPoolAssembly()` in `@pryzm/geometry-pool`, which is pure and already
 * tested. There is no second assembly here, no hole-punching routine, and not one
 * dimensional literal — `resolvePoolDimensions()` is the only source of a pool
 * dimension in this repo and `poolNoLiterals.test.ts` enforces that at source level.
 *
 * ⭐ AND NO NEW SHAPE VOCABULARY. The six modes come from `activePoolDrawMode`,
 * which is the union of two EXISTING `@pryzm/geometry-slab` unions, and the
 * closed-loop rings are generated by `boundaryLoopVertices()` — the same generator
 * the slab, floor-finish and ceiling tools call. The founder asked for
 * "linear, ortho — but also circular, ellipse, rectangular"; all six are served by
 * machinery that already shipped, so the strip cannot offer a shape the generator
 * does not implement (§FIX-STAIR-SHAPE-DESYNC's lesson).
 *
 * ── THE ONE GENUINELY POOL-SPECIFIC PROBLEM: WHICH SLAB IS THE HOST? ──────────
 * A pool is cut INTO something. `CreatePoolHandler.canExecute` refuses when
 * `ctx.stores.slab[hostSlabId]` is absent — "a pool with no slab to cut into is not
 * a pool; it is a hole in the air" — so this handler must name a host BEFORE it
 * dispatches, and must refuse legibly when it cannot.
 *
 * Resolution order, strongest first:
 *   1. GEOMETRY — the slab on the active level whose boundary CONTAINS the pool
 *      outline's centroid. This is the natural gesture: draw the pool on the
 *      terrace and the terrace is the host, with nothing to select first.
 *   2. SELECTION — an explicitly selected slab, as the TIE-BREAK when two or more
 *      slabs contain the outline, and as the OVERRIDE for a pool deliberately cut
 *      into a slab it is not centred on.
 *   3. REFUSE, BY NAME (C16 CA-18). Never "silently create nothing", never invent a
 *      host, and never pick one of several arbitrarily.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⛔ §FIX-POOL-HOST-FROM-GEOMETRY (L-10820) — STEPS 1 AND 2 WERE BOTH DEAD, AND
 *    STEP 3 TOLD THE ARCHITECT TO USE THEM.
 * ═══════════════════════════════════════════════════════════════════════════════
 * THE FOUNDER: *"check the pool — is not working — no matter if i select the slab
 * before or after (actually there should not be the need of selecting the slab — it
 * should be like when you place a window in a wall — you don't need to select the
 * wall — same)."* Both orders failed, and they failed for two INDEPENDENT reasons:
 *
 *   • GEOMETRY (step 1) searched for a field no store has. `_candidateSlabs` read
 *     `rec.boundary`, but the legacy `SlabData` the browser actually holds spells its
 *     outline `polygon: {x, y}[]` — LOCAL, with `y` on the Z axis — and has no
 *     `boundary` field at all. Its other source, `window.runtime.stores['slab']`, is
 *     `undefined` in every session: the composed runtime's `stores` is a `StoresSlot`
 *     with five NAMED members and no index signature. Both reads were kept alive
 *     purely by a hand-written `window as unknown as …` cast.
 *   • SELECTION (step 2) was gated on `id.startsWith('slab')`, and his slab's id is
 *     `c0ba8bda-77a4-4f24-a248-fbc78aebed56` — a bare UUID from the 3-D `SlabTool`.
 *
 * Each is documented at the method that carried it. The lesson they share is the one
 * the test file states: every pool suite before this was green because each installed
 * `runtime.stores.slab` with a `boundary` field — a fixture built from this header's
 * CLAIMS rather than from the runtime, which therefore could not falsify them.
 *
 * ⚠ MEASURED CAVEAT, STATED RATHER THAN HIDDEN. The lookup reads the plugin slab
 * DTO store when the runtime exposes it, and falls back to the legacy
 * `window.slabStore`. Those are two stores and this repo already knows they can
 * diverge (the "detached-DTO-mirror condition",
 * PLUGIN-SDK-AND-EXTERNAL-API-READINESS-REGISTER §374). A slab present ONLY in the
 * legacy store will pass this handler's check and then be REFUSED by
 * `canExecute` — which is why the dispatch's rejection is caught and surfaced
 * verbatim below rather than swallowed. That is honest failure, not a fix for the
 * duality; the duality is pre-existing and is recorded as L-5215.
 */

import { createId, isId } from '@pryzm/schemas';
import { pointInPolygonXZ } from '@pryzm/geometry-kernel';
import {
    boundaryLoopVertices, boundaryLoopRefusal, BOUNDARY_LOOP_GESTURE,
    arcSegmentThroughMidpoint, orthoConstrain,
} from '@pryzm/geometry-slab';
// §FIX-POOL-HOST-FROM-GEOMETRY (L-10820) — THE CANONICAL LOCAL→WORLD LIFT, REUSED.
// `SlabData.polygon` is `{x, y}` in the slab's LOCAL frame, where `y` carries the
// plan-Z axis, and `position` is its world origin. That rule is stated in three
// places already (`SlabColumnCoupling.ts:73-78`, `RegionBoundarySources.ts:53`,
// `CreateHandrailRunOnSlabCommand.ts:118-127`) and `slabWorldRing` is the tested
// one — `command-registry/__tests__/HandrailBySlab.test.ts` asserts it. A fourth
// hand-rolled copy here is how the three drift apart, so this imports rather than
// re-derives (C84 §8.d: a comment is not a synchronisation mechanism).
import { slabWorldRing } from '@pryzm/command-registry';
import type { PlanToolHandler, PlanToolDrawContext, WorldPoint } from './PlanToolHandler';
import { resolveActivePoolDrawMode, activePoolLoopMode } from './activePoolDrawMode';
// §FIX-PLAN-TOOL-POINTER-UNREACHABLE (L-7004) — the slab that was selected AT THE
// MOMENT THE TOOL WAS ARMED. Arming a plan-only tool now suppresses 3-D selection
// (L-7003, so an armed create tool can no longer pick a wall and attach a gizmo), and
// `SelectionManager.setEnabled(false)` calls `unselectAll()` on the way down. Without
// this snapshot the SELECTION override below would read empty for every pool drawn
// after the fix — a defect introduced by a fix, which is why the snapshot ships in the
// same commit as the suppression rather than after it.
import { armedSelectionId } from './armedSelectionSnapshot';
// §FIX-PLAN-TOOL-FINISH-GESTURE (L-9301) — the LIVE refusal channel. The overlay draw
// is the second leg, not the only one; see `notifyPlanToolRefusal`'s header.
import { notifyPlanToolRefusal, notifyPlanToolCreated } from '@app/ui/create/activatePlanOnlyTool';

/** PRYZM purple — the shared preview colour every plan tool draws in. */
const STROKE = '#6600ff';
const FILL_A = 'rgba(102,0,255,0.10)';

/** The minimum vertices any closed outline needs. Not a dimension — a topology fact. */
const MIN_LOOP_VERTS = 3;

/**
 * A slab record as this handler needs to read it — deliberately the narrowest shape.
 *
 * ⭐ `ring` IS ALREADY WORLD X/Z. §FIX-POOL-HOST-FROM-GEOMETRY (L-10820): this used to
 * be `boundary?: {x, z}[]` copied straight off the record, and that single field name
 * is what closed the founder's geometric route. THREE stores can answer "which slabs
 * exist" here and they do not agree on the spelling:
 *
 *   • plugin DTO (`plugins/slab/src/store.ts`, the Zod `Slab`) → `boundary: Vec3[]`,
 *     already world;
 *   • legacy engine (`geometry-slab/src/SlabTypes.ts:85-99`) → `polygon: {x, y}[]`
 *     where `y` IS the Z axis and the ring is LOCAL to `position`.
 *
 * The legacy record has NO `boundary` field whatsoever, so `rec.boundary` read
 * `undefined` for every slab in a real project and `_resolveHostSlab` skipped all of
 * them. Normalising to ONE world ring at the point of reading is what stops a second
 * reader from having to know that — and is why the field is named `ring`, not
 * `boundary`: it is a computed world outline, not a stored field of either store.
 */
interface HostSlabCandidate {
    readonly id: string;
    readonly levelId?: string;
    readonly ring?: ReadonlyArray<{ x: number; z: number }>;
}

/**
 * The outcome of asking "which slab is this pool cut into?".
 *
 * A discriminated answer rather than `string | null`, because the THREE ways of not
 * finding a host need THREE different sentences — and the one thing the founder's
 * session proves is that a refusal naming a route the tool has closed is worse than
 * no refusal at all (C16 CA-18).
 */
type HostResolution =
    | { readonly hostId: string; readonly reason?: undefined }
    | { readonly hostId: null; readonly reason: string };

export class PoolPlanToolHandler implements PlanToolHandler {
    private _ctx:         PlanToolDrawContext | null = null;
    private _points:      WorldPoint[] = [];
    private _cursorPoint: WorldPoint | null = null;
    private _loopAnchor:  WorldPoint | null = null;
    private _arcMidPt:    WorldPoint | null = null;
    /** The last refusal, shown on the overlay so it reaches a PERSON, not a console. */
    private _refusal:     string | null = null;

    /** §T-B1 — opt-in stroke preservation: a half-drawn pool survives an excursion
     *  to the toolbar rather than being wiped by a deactivate-on-leave. */
    hasActiveStroke(): boolean {
        return this._points.length > 0 || this._loopAnchor !== null || this._arcMidPt !== null;
    }

    activate(ctx: PlanToolDrawContext): void {
        this._ctx = ctx;
        this._resetStroke();
    }

    deactivate(): void {
        this._clearOverlay();
        this._resetStroke();
        this._ctx = null;
    }

    // ── Interaction ──────────────────────────────────────────────────────────

    onMouseMove(pt: WorldPoint): void {
        // ⭐ §FIX-PLAN-TOOL-FINISH-GESTURE (L-9301) — A REFUSAL OUTLIVES THE POINTER.
        // The overlay clears the canvas at the head of every sample, so without this the
        // reason the last gesture failed is erased by the architect's next 16 ms of
        // mouse movement — measured, A-4. It is cleared by the next CLICK (`onClick`'s
        // first line), because a new attempt is when the old reason stops being true.
        if (this._refusal) {
            this._cursorPoint = pt;
            this._drawRefusal();
            return;
        }
        // Mode is re-read on EVERY sample (the `WallModePicker.getActiveMode()`
        // contract) so a switch on the mode strip applies to the very next click
        // without re-activating the tool and destroying the stroke.
        const mode = resolveActivePoolDrawMode();

        if (activePoolLoopMode() && this._loopAnchor) {
            this._cursorPoint = pt;
            this._drawPreview();
            return;
        }
        if (mode === 'ortho' && this._points.length > 0) {
            this._cursorPoint = this._orthoSnap(this._points[this._points.length - 1]!, pt);
            this._drawPreview();
            return;
        }
        if (this._points.length > 0) {
            this._cursorPoint = pt;
            this._drawPreview();
            return;
        }

        // ⭐⭐ §FIX-POOL-SILENT-BEFORE-FIRST-CLICK (L-7850) — THE IDLE HINT.
        //
        // THE FOUNDER: *"Swimming pool doesn't get created."* His log shows the tool
        // ARMING three times, the session's selection-suppression firing correctly
        // (`reason=tool-activated-selection-disabled`) — and then nothing. No command,
        // no refusal, no elements.
        //
        // ⚠ THE COMMIT PATH IS NOT THE DEFECT, and that was measured before writing a
        // line here: `pointerReachesArmedHandler.spec.ts` ARM A-2 drives THREE real DOM
        // clicks and a real `dblclick` at the real overlay and gets exactly one
        // `pool.create`. The state machine, the overlay, the dblclick forwarding and
        // the commit all work.
        //
        // ⛔ WHAT DID NOT WORK IS THAT UNTIL THE FIRST CLICK LANDED, THIS HANDLER DREW
        // ABSOLUTELY NOTHING. Every arm above returns early on `_points.length === 0`,
        // so an armed pool put not one pixel on the overlay: no preview, no hint, no
        // cursor feedback. Compare `LiftPlanToolHandler`, which draws
        // "Lift · move the pointer over the plan to place the shaft" immediately, and
        // `BalconyPlanToolHandler`, which previews on hover. The pool was the ONLY one
        // of the three plan-only compounds that was invisible while armed — and an
        // armed tool that shows nothing is indistinguishable from a broken one, which
        // is exactly the sentence the founder wrote.
        //
        // ⭐ AND IT NAMES THE CLOSING GESTURE, which is the second half of his earlier
        // report — *"I created a few lines but the creation did not trigger."* A
        // LINEAR/ORTHO pool is an open polyline until a double-click or Enter closes
        // it, and NOTHING on screen said so. `_hintFor` already says it beautifully
        // once a point exists; it simply could not be reached before one did.
        //
        // ⛔ NOT FIXED BY GIVING THE POOL A SINGLE-CLICK COMMIT. The multi-point path
        // IS the feature — the founder's own spec asked for linear / ortho / circular /
        // ellipse / rectangular. The fix is to SAY what the gesture is, not to replace it.
        this._cursorPoint = pt;
        this._drawIdleHint();
    }

    /**
     * The hint an ARMED pool shows before its first click: which mode is live, and what
     * the first gesture is. Mode is re-read on every sample, exactly as every other arm
     * in this handler does, so switching on the strip updates the sentence immediately.
     */
    private _drawIdleHint(): void {
        const c = this._ctx;
        if (!c) return;
        const { ctx, overlayCanvas, dpr } = c;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        const cssW = overlayCanvas.width / dpr;
        const cssH = overlayCanvas.height / dpr;
        ctx.clearRect(0, 0, cssW, cssH);
        ctx.save();
        const loopMode = activePoolLoopMode();
        const mode = resolveActivePoolDrawMode();
        // The closed-loop modes borrow the SHARED gesture table the slab, floor and
        // ceiling tools already use, so a user who learned one is not taught a second
        // grammar for the pool. The open modes state the close explicitly, because
        // "how do I finish this?" is the question that produced the founder's report.
        const label = loopMode
            ? BOUNDARY_LOOP_GESTURE[loopMode].first
            : `${mode === 'ortho' ? 'Orthogonal' : mode === 'curved' ? 'Curved' : 'Linear'} · ` +
              `click the first corner · dbl-click or Enter closes the pool`;
        this._drawHint(ctx, cssH, `Pool · ${label}`);
        ctx.restore();
    }

    onClick(pt: WorldPoint): void {
        const mode = resolveActivePoolDrawMode();
        // A new click is a new attempt: clear any refusal still on screen so the
        // user is never told why the LAST gesture failed while making a new one.
        this._refusal = null;

        // ── CLOSED-LOOP modes: RECTANGULAR / CIRCULAR / ELLIPTICAL ───────────
        // One gesture, one arm — the ring maths lives in `boundaryLoops`, so all
        // three share it and none of them is special-cased here.
        const loopMode = activePoolLoopMode();
        if (loopMode) {
            if (!this._loopAnchor) {
                this._loopAnchor  = pt;
                this._points      = [pt];
                this._cursorPoint = pt;
                this._drawPreview();
                return;
            }
            const first  = { x: this._loopAnchor.worldX, z: this._loopAnchor.worldZ };
            const second = { x: pt.worldX, z: pt.worldZ };
            const ring = boundaryLoopVertices(loopMode, first, second);
            if (ring.length < MIN_LOOP_VERTS) {
                // ⛔ C16 CA-18 — name the reason AND what does work. Never silently
                // fall back to another shape: a circle that quietly became a
                // rectangle is a worse outcome than a refusal.
                this._refuse(boundaryLoopRefusal(loopMode, first, second)
                    ?? 'That outline is too small to make a pool.');
                return;
            }
            this._points = ring.map(v => ({ worldX: v.x, worldZ: v.z } as WorldPoint));
            this._commit();
            return;
        }

        // ── CURVED — vertex → arc MIDPOINT → arc END (the wall tool's 3-click) ──
        if (mode === 'curved' && this._points.length > 0) {
            if (!this._arcMidPt) {
                this._arcMidPt    = pt;
                this._cursorPoint = pt;
                this._drawPreview();
                return;
            }
            const last = this._points[this._points.length - 1]!;
            const run = arcSegmentThroughMidpoint(
                { x: last.worldX,           z: last.worldZ           },
                { x: this._arcMidPt.worldX, z: this._arcMidPt.worldZ },
                { x: pt.worldX,             z: pt.worldZ             },
            );
            for (const v of run) this._points.push({ worldX: v.x, worldZ: v.z } as WorldPoint);
            this._arcMidPt = null;
            this._drawPreview();
            return;
        }

        // ── LINEAR / ORTHO — accumulate vertices ─────────────────────────────
        const vertex = (mode === 'ortho' && this._points.length > 0)
            ? this._orthoSnap(this._points[this._points.length - 1]!, pt)
            : pt;
        this._points.push(vertex);
        this._drawPreview();
    }

    onDoubleClick(_pt: WorldPoint): void {
        if (activePoolLoopMode()) return;      // closed loops commit on the 2nd click
        if (this._arcMidPt) return;            // don't eat the pending arc END click
        if (this._points.length >= MIN_LOOP_VERTS) this._commit();
    }

    onKeyDown(e: KeyboardEvent): boolean {
        if (e.key === 'Enter' && this._points.length >= MIN_LOOP_VERTS
            && !activePoolLoopMode() && !this._arcMidPt) {
            e.preventDefault();
            this._commit();
            return true;
        }
        if (e.key === 'Backspace' && this._arcMidPt) {
            this._arcMidPt = null;
            this._drawPreview();
            return true;
        }
        if (e.key === 'Backspace' && this._points.length > 0) {
            this._points.pop();
            if (this._points.length === 0) this._loopAnchor = null;
            this._drawPreview();
            return true;
        }
        return false;
    }

    cancel(): void {
        this._resetStroke();
        this._clearOverlay();
    }

    redraw(): void {
        if (this._points.length > 0) this._drawPreview();
    }

    // ── Commit ───────────────────────────────────────────────────────────────

    private _commit(): void {
        const c = this._ctx;
        if (!c || this._points.length < MIN_LOOP_VERTS) return;

        const levelId = c.viewDef.spatial?.levelId;
        if (!levelId) {
            this._refuse('This view has no level, so there is nothing to cut a pool into.');
            return;
        }

        // The outline the user drew IS the pool boundary — and it is also the hole,
        // the wall centreline loop, the floor outline and the water outline. ONE
        // polygon drives all four parts, which is why they cannot drift apart.
        const boundary = this._points.map(p => ({ x: p.worldX, y: 0, z: p.worldZ }));

        const host = this._resolveHostSlab(boundary, levelId);
        if (host.hostId === null) {
            // ⛔ C16 CA-18 — the refusal names a route that is actually OPEN.
            //
            // ⭐ §FIX-POOL-HOST-FROM-GEOMETRY (L-10820). This used to be ONE sentence
            // for all three failures: *"A pool must be cut into a slab. Draw it over a
            // slab on this level, or select the slab first and draw again."* Both
            // halves of that instruction were impossible at the time it was printed —
            // geometry could not resolve a host at all (`_candidateSlabs` read a field
            // no store has), and "select the slab first" was gated on an id PREFIX the
            // founder's slab did not carry. A product that instructs an impossible
            // action is the L-10686 / L-10682 family (intent stored, nothing moved;
            // value shown, nothing dispatched), and this was the third instance.
            //
            // The sentence now comes from the resolver, which is the only thing that
            // knows WHICH of the three worlds this is.
            this._refuse(host.reason);
            return;
        }

        // ⭐⭐ §FIX-POOL-HOST-FROM-GEOMETRY (L-10821) — THE HOST IS FOUND BUT MAY NOT BE
        // ADDRESSABLE, AND THAT IS A DIFFERENT SENTENCE FROM "THERE IS NO SLAB HERE".
        //
        // MEASURED, not theorised. `Pool.hostSlabId` is `idRef('slab')`
        // (schemas/src/elements/Pool.ts:82) → `/^slab_[0-9A-HJKMNP-TV-Z]{26}$/`, and
        // `defineElement` applies the same regex to `Slab.id` itself
        // (base/BaseNode.ts:35-41). So a slab whose id is NOT canonical cannot exist in
        // the plugin DTO store the bus reads, and naming it as a host earns a raw
        // `CommandBusError: pool.create: canExecute rejected — Expected slab_<ulid> id`.
        //
        // ⚠ THAT IS THE FOUNDER'S SLAB. His console reads
        // `id=c0ba8bda-77a4-4f24-a248-fbc78aebed56 type=Slab` — a bare UUID, because
        // only `SlabPlanToolHandler` mints `createId('slab')`. The 3-D `SlabTool`
        // (SlabTool.ts:431), `SlabPickWallsController` (:219) and `ProjectLoader`
        // (which restores whatever id was saved) all go through the LEGACY
        // `CreateSlabCommand`/`commandManager`, which never meets Zod — so those slabs
        // live in the legacy store ONLY and carry uncanonical ids.
        //
        // ⛔ NOT PAPERED OVER BY MINTING A NEW ID HERE. The host is an EXISTING element;
        // inventing an id for it would name a slab that does not exist and cut the hole
        // in nothing. And NOT fixed by relaxing the schema either — that would let
        // `pool.create` reference a slab the bus still cannot find, trading a legible
        // refusal for a silent no-op. The real repair is that slabs have two id
        // vocabularies and only one of them reaches the bus; that is a slab-seam
        // migration, it is recorded as the open half of this defect, and it is NOT
        // something to half-do underneath a pool tool.
        //
        // What belongs HERE is telling the truth: the tool found the host, and cannot
        // use it, and why.
        if (!isId(host.hostId, 'slab')) {
            this._refuse(
                'This pool is over a slab that was created before the current slab format '
                + `("${host.hostId}"), and the pool command cannot reference it yet. Draw a new `
                + 'slab with the Slab tool over this area and put the pool on that one.',
            );
            return;
        }

        // CA-2 — ids are minted ONCE, HERE, and passed in. `execute()` runs again on
        // REDO, so minting inside the handler would silently produce a DIFFERENT
        // pool the second time. One wall id per boundary EDGE, in boundary order.
        const payload = {
            poolId:      createId('pool'),
            levelId,
            hostSlabId:  host.hostId,
            boundary,
            wallIds:     boundary.map(() => createId('wall')),
            floorSlabId: createId('slab'),
            waterId:     createId('water'),
        };

        // ONE dispatch = ONE undo entry across all four stores (C16 §8.6 B-6). The
        // handler uses `produceMultiStoreCommand`; nothing is batched here.
        const dispatch = c.runtime?.bus?.executeCommand('pool.create', payload)
            ?? window.runtime?.bus?.executeCommand('pool.create', payload);

        if (!dispatch) {
            this._refuse('The command bus is not available, so no pool was created.');
            return;
        }

        void Promise.resolve(dispatch).then(() => {
            // ⭐ §FIX-PLAN-TOOL-FINISH-GESTURE (L-9305) — SAY THAT IT EXISTS.
            // A pool commits four stores and, until `CommandEventBridge` grows a
            // `case 'pool.create'`, draws NOTHING (measured — see
            // `notifyPlanToolCreated`'s header). Success and refusal are the same
            // number of pixels, which is the founder's whole report.
            notifyPlanToolCreated(
                `Swimming pool created — ${boundary.length} sides, cut into the slab below.`,
            );
        }).catch((e: unknown) => {
            // ⭐ SURFACE THE BUS'S OWN REASON, VERBATIM. `canExecute` rejections
            // arrive as `CommandBusError: pool.create: canExecute rejected — <why>`,
            // and that `<why>` is the most accurate sentence available (duplicate
            // id, host slab not found, degenerate outline). Swallowing it here is
            // exactly the "reported activation, activated nothing" defect this lane
            // exists to avoid.
            const why = e instanceof Error ? e.message : String(e);
            console.error('[PoolPlanToolHandler] pool.create failed:', why);
            this._refuse(why);
        });

        this._resetStroke();
        this._clearOverlay();
    }

    // ── Host-slab resolution ─────────────────────────────────────────────────

    /**
     * The slab this pool is cut into, or a NAMED reason why there is none.
     *
     * ⭐ GEOMETRY DECIDES. §FIX-POOL-HOST-FROM-GEOMETRY (L-10820) — the founder:
     * *"there should not be the need of selecting the slab — it should be like when
     * you place a window in a wall — you don't need to select the wall — same."*
     * That is exactly the `OpeningPlanToolHandler` rule for a window: the host is
     * whatever the gesture LANDS ON, resolved by containment, and selection plays no
     * part in the ordinary case. A window's host is found by proximity to a wall
     * CENTRELINE (a 1-D chord); a pool's is found by point-in-polygon against a slab
     * RING. A slab is horizontal and a pool is drawn in plan directly over it, so the
     * containment test is strictly SIMPLER than the wall case — no offset, no
     * perpendicular distance, no reach tolerance to tune.
     *
     * SELECTION IS NOT A FALLBACK ANY MORE — IT IS A TIE-BREAK, and only that. It is
     * kept (never deleted) because it is the only honest answer to overlapping slabs,
     * which geometry genuinely cannot settle.
     *
     * ⛔ AMBIGUITY IS A QUESTION, NEVER A COIN TOSS. Two slabs under one outline and
     * nothing selected is REFUSED with the count, not resolved by iteration order.
     * The founder's standing rule is ASK, never auto-edit; silently cutting a hole in
     * whichever slab the store happened to yield first is an auto-edit with a 50%
     * chance of being wrong, and the wrong one is a hole in a floor somebody meant to
     * keep.
     */
    private _resolveHostSlab(
        boundary: ReadonlyArray<{ x: number; z: number }>,
        levelId: string,
    ): HostResolution {
        const centroid   = this._centroidOf(boundary);
        const candidates = this._candidateSlabs();
        const onLevel    = candidates.filter(
            s => s.levelId === undefined || s.levelId === levelId,
        );

        const containing: HostSlabCandidate[] = [];
        for (const slab of onLevel) {
            const ring = slab.ring;
            if (!ring || ring.length < MIN_LOOP_VERTS) continue;
            if (pointInPolygonXZ(centroid.x, centroid.z, ring)) containing.push(slab);
        }

        // ── ONE slab under the outline: the ordinary case, and the whole feature ──
        if (containing.length === 1) return { hostId: containing[0]!.id };

        const selected = this._selectedSlabId(candidates);

        // ── MORE THAN ONE: the selection disambiguates, or we ASK ────────────────
        if (containing.length > 1) {
            if (selected && containing.some(s => s.id === selected)) {
                return { hostId: selected };
            }
            return {
                hostId: null,
                reason:
                    `${containing.length} slabs overlap here, so it is not clear which one the `
                    + 'pool should be cut into. Select the slab you mean BEFORE choosing the Pool '
                    + 'tool, then draw again.',
            };
        }

        // ── NONE contains it. An explicitly selected slab is still a legitimate
        //    OVERRIDE — a pool deliberately cut off-centre from its host — and that
        //    intent is unambiguous because the architect stated it.
        if (selected) return { hostId: selected };

        // ── Say WHICH of the two "no host" worlds this is. They are different
        //    problems and they have different fixes, so they get different sentences
        //    (§CONTEXT-DATA-HONESTY: "no slab exists" and "you drew it off the slab"
        //    must not be the same value).
        if (onLevel.length === 0) {
            return {
                hostId: null,
                reason:
                    'There is no slab on this level, and a pool is a hole cut into one. '
                    + 'Draw the terrace or floor slab first, then draw the pool on top of it.',
            };
        }
        return {
            hostId: null,
            reason:
                `The pool outline is not over any of the ${onLevel.length} slab(s) on this level. `
                + 'Draw it inside a slab — the slab underneath becomes its host automatically.',
        };
    }

    /**
     * The world X/Z outline of ONE slab record, from whichever store produced it.
     *
     * ⚠ TWO SPELLINGS, AND THE SECOND ONE IS THE PRODUCTION ONE. The plugin DTO
     * record (the Zod `Slab`) carries `boundary: Vec3[]` in WORLD coordinates. The
     * legacy engine record (`SlabData`) carries `polygon: {x, y}[]` where `y` is the
     * Z axis and the ring is LOCAL to `position`. `boundary` is tried first because
     * when it is present it needs no lift; `polygon` goes through `slabWorldRing`,
     * the tested canonical conversion, because getting that lift wrong puts the probe
     * at the world origin instead of on the slab — a silent, plausible-looking wrong
     * answer rather than a visible failure.
     */
    private _ringOf(rec: unknown): ReadonlyArray<{ x: number; z: number }> | undefined {
        const r = rec as {
            boundary?: ReadonlyArray<{ x?: number; z?: number }>;
            polygon?: ReadonlyArray<{ x: number; y: number }>;
            position?: { x: number; y: number; z: number };
        };
        const b = r?.boundary;
        if (Array.isArray(b) && b.length >= MIN_LOOP_VERTS
            && typeof b[0]?.x === 'number' && typeof b[0]?.z === 'number') {
            return b as ReadonlyArray<{ x: number; z: number }>;
        }
        return slabWorldRing({ polygon: r?.polygon, position: r?.position }) ?? undefined;
    }

    /**
     * Every slab this handler can see, from EVERY store that can answer — merged, not
     * raced.
     *
     * ⛔ §FIX-POOL-HOST-FROM-GEOMETRY (L-10820). This method used to read exactly two
     * sources and `return` after the first that was non-empty. BOTH were wrong in
     * production and the early return meant the second never got a chance to be:
     *
     *   1. `window.runtime.stores['slab']` — **`undefined` in every real session.**
     *      `window.runtime` is the COMPOSED `PryzmRuntime` (engineLauncher.ts:179) and
     *      its `stores` is a `StoresSlot`: five NAMED members, no index signature
     *      (runtime-composer/src/types.ts:2800-2834). The read compiled only because
     *      it goes through a hand-written `window as unknown as { runtime?: { stores?:
     *      Record<string, …> } }` cast asserting a shape the runtime does not have —
     *      an `any` seam standing exactly where the defect lived.
     *   2. `window.slabStore.getAll()` read as `rec.boundary` — and `SlabData` has no
     *      `boundary` field at all (SlabTypes.ts:85-99). Every candidate therefore
     *      arrived with `boundary: undefined` and was skipped by the containment loop.
     *
     * Source 1 IS RETAINED, not deleted: it is the correct read for the day the
     * composed runtime does expose per-kind plugin stores, and it costs one optional
     * chain. What changed is that it is no longer the only one consulted, and no
     * source short-circuits the others — a slab present in exactly one store is still
     * a slab the architect can see on screen, so it must be a slab this tool can host
     * on. First writer of an id wins; later sources fill gaps.
     */
    private _candidateSlabs(): readonly HostSlabCandidate[] {
        const byId = new Map<string, HostSlabCandidate>();
        const add = (id: string | undefined, rec: unknown): void => {
            if (!id || byId.has(id)) return;
            const r = rec as { levelId?: string };
            byId.set(id, { id, levelId: r?.levelId, ring: this._ringOf(rec) });
        };

        const runtime = (window as unknown as {
            runtime?: {
                stores?: {
                    readonly elements?: { get?: (kind: string) => unknown };
                    readonly [key: string]: unknown;
                };
            };
        }).runtime;

        // 1. A per-kind plugin DTO store, IF the composed runtime ever exposes one.
        //    Retained deliberately — see the header. Today this yields nothing.
        const pluginSlabs = runtime?.stores?.['slab'] as
            { getState?: () => Map<string, unknown> } | undefined;
        const state = pluginSlabs?.getState?.();
        if (state && typeof state[Symbol.iterator] === 'function') {
            for (const [id, rec] of state) add(id, rec);
        }

        // 2. ⭐ THE ADR-0318 AUTHORITATIVE ELEMENT STORE — the one the composed runtime
        //    really does expose, and the one `ProjectSerializer` and the fragment
        //    builders read. `storeRegistry.register('slab', slabStore)`
        //    (composeRuntime.ts:1621-1628) registers the SAME geometry-slab singleton
        //    that `window.slabStore` points at, so this and source 3 usually agree —
        //    but reaching it through the runtime rather than a window global is the
        //    supported route, and it is the one that survives TASK-08.
        const authoritative = runtime?.stores?.elements?.get?.('slab') as
            { getAll?: () => unknown[] } | undefined;
        for (const rec of authoritative?.getAll?.() ?? []) {
            add((rec as { id?: string })?.id, rec);
        }

        // 3. The legacy engine store — what every other plan tool reads today.
        const legacy = window.slabStore as unknown as { getAll?: () => unknown[] } | undefined; // TODO(TASK-08)
        for (const rec of legacy?.getAll?.() ?? []) {
            add((rec as { id?: string })?.id, rec);
        }

        return [...byId.values()];
    }

    /**
     * An explicitly selected slab id, if the current selection is one — the TIE-BREAK
     * for overlapping slabs, no longer the fallback for "geometry found nothing".
     *
     * THREE readings, strongest first, and the third is the one L-7004 added:
     *   1. the live selection's `userData.elementType === 'slab'` (a slab mesh is
     *      selected right now — the only reading that carries its own type evidence);
     *   2. the live selection's id, when a slab with that id exists;
     *   3. ⭐ the ARM-TIME snapshot — because arming this tool DISABLES selection and
     *      `setEnabled(false)` unselects everything, so by the time the architect has
     *      drawn the outline readings 1 and 2 are both empty BY CONSTRUCTION. The
     *      snapshot is taken immediately before the suppression; see
     *      `armedSelectionSnapshot.ts`.
     *
     * ⛔ §FIX-POOL-HOST-FROM-GEOMETRY (L-10820) — READINGS 2 AND 3 WERE `id.startsWith
     * ('slab')`, AND THAT IS WHY "SELECT THE SLAB FIRST" NEVER WORKED. The founder's
     * console names his slab `c0ba8bda-77a4-4f24-a248-fbc78aebed56` — a bare UUID.
     * Only `SlabPlanToolHandler` mints `createId('slab')` → `slab_<ULID>`; the 3-D
     * `SlabTool` (SlabTool.ts:431), `SlabPickWallsController` (:219) and every slab
     * restored by `ProjectLoader` use `crypto.randomUUID()`. So the snapshot L-7004
     * added specifically to keep this route alive was captured correctly and then
     * thrown away one line later by a string test.
     *
     * The question is now answered by IDENTITY — "is there a slab with this id?" —
     * against the same candidate set geometry just searched. A gate that classifies by
     * NAME is satisfied by renaming and defeated by not-renaming; asking the store is
     * the only form of the question that cannot be wrong about an id it can see.
     */
    private _selectedSlabId(candidates: readonly HostSlabCandidate[]): string | null {
        const isSlab = (id: string | null | undefined): id is string =>
            !!id && candidates.some(c => c.id === id);

        const sel = (window as unknown as {
            selectionManager?: {
                getSelectedId?: () => string | null;
                selectedObject?: { userData?: { elementType?: string; id?: string } };
            };
        }).selectionManager;
        const obj = sel?.selectedObject;
        if (obj?.userData?.elementType?.toLowerCase() === 'slab' && obj.userData.id) {
            return obj.userData.id;
        }
        const id = sel?.getSelectedId?.();
        if (isSlab(id)) return id;
        const armed = armedSelectionId();
        return isSlab(armed) ? armed : null;
    }

    /** Plan centroid of a ring (vertex average — sufficient for a containment probe). */
    private _centroidOf(ring: ReadonlyArray<{ x: number; z: number }>): { x: number; z: number } {
        let x = 0, z = 0;
        for (const p of ring) { x += p.x; z += p.z; }
        return { x: x / ring.length, z: z / ring.length };
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /** The ONE ortho constraint — the wall tool's, shared via `@pryzm/geometry-slab`. */
    private _orthoSnap(from: WorldPoint, to: WorldPoint): WorldPoint {
        const v = orthoConstrain(
            { x: from.worldX, z: from.worldZ },
            { x: to.worldX,   z: to.worldZ   },
        );
        return { worldX: v.x, worldZ: v.z } as WorldPoint;
    }

    private _resetStroke(): void {
        this._points      = [];
        this._cursorPoint = null;
        this._loopAnchor  = null;
        this._arcMidPt    = null;
    }

    /**
     * Record a refusal AND put it on the overlay.
     *
     * ⭐ A `console.warn` is not a refusal — it is a refusal nobody reads. The
     * founder's "Create Stair" report was exactly this shape: the tool reported
     * success and did nothing. Every path that declines to create a pool comes
     * through here, so the user always learns why.
     */
    private _refuse(message: string): void {
        this._refusal = message;
        this._resetStroke();
        this._drawRefusal();
        // ⭐⭐ §FIX-PLAN-TOOL-FINISH-GESTURE (L-9301) — AND SAY IT WHERE IT SURVIVES.
        // The overlay draw above is erased by the very next pointer sample: the overlay
        // clears the canvas at the head of every `mousemove`, and `_resetStroke()` has
        // just emptied `_points`, so `onMouseMove` redraws the IDLE HINT over the reason.
        // Measured in `planOnlyToolFinishGesture.spec.ts` A-4 — the sentence lasted one
        // frame. `runtime.toasts` is the channel `initUI` uses for every message the user
        // actually reads (L-7005), and it is why "the swimming pool would not create"
        // now arrives as "a pool must be cut into a slab" instead of as silence.
        notifyPlanToolRefusal(message);
    }

    private _drawRefusal(): void {
        const c = this._ctx;
        if (!c || !this._refusal) return;
        const { ctx, overlayCanvas, dpr } = c;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        const cssW = overlayCanvas.width  / dpr;
        const cssH = overlayCanvas.height / dpr;
        ctx.clearRect(0, 0, cssW, cssH);
        ctx.save();
        this._drawHint(ctx, cssH, this._refusal);
        ctx.restore();
    }

    private _drawPreview(): void {
        const c = this._ctx;
        if (!c || this._points.length === 0) return;
        const { ctx, overlayCanvas, planCanvas, dpr } = c;
        const mode = resolveActivePoolDrawMode();

        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        const cssW = overlayCanvas.width  / dpr;
        const cssH = overlayCanvas.height / dpr;
        ctx.clearRect(0, 0, cssW, cssH);
        ctx.save();

        // ── CLOSED-LOOP preview ──────────────────────────────────────────────
        // ⭐ Generated from THE SAME ring the commit will use, so what the user
        // aims at cannot diverge from what lands.
        const loopMode = activePoolLoopMode();
        if (loopMode && this._loopAnchor && this._cursorPoint) {
            const ring = boundaryLoopVertices(
                loopMode,
                { x: this._loopAnchor.worldX,  z: this._loopAnchor.worldZ  },
                { x: this._cursorPoint.worldX, z: this._cursorPoint.worldZ },
            );
            const pts = ring.map(v => planCanvas.worldToScreen(v.x, v.z));
            if (pts.length >= MIN_LOOP_VERTS) {
                this._fillPath(ctx, pts);
                this._strokePath(ctx, pts, true);
            }
            this._drawHint(ctx, cssH, `${BOUNDARY_LOOP_GESTURE[loopMode].second} · Esc to cancel`);
            ctx.restore();
            return;
        }

        const screenPts = this._points.map(p => planCanvas.worldToScreen(p.worldX, p.worldZ));

        const trailing: Array<{ sx: number; sy: number }> = [];
        if (this._cursorPoint) {
            if (mode === 'curved' && this._arcMidPt && this._points.length > 0) {
                const last = this._points[this._points.length - 1]!;
                for (const v of arcSegmentThroughMidpoint(
                    { x: last.worldX,           z: last.worldZ           },
                    { x: this._arcMidPt.worldX, z: this._arcMidPt.worldZ },
                    { x: this._cursorPoint.worldX, z: this._cursorPoint.worldZ },
                )) trailing.push(planCanvas.worldToScreen(v.x, v.z));
            } else {
                trailing.push(planCanvas.worldToScreen(this._cursorPoint.worldX, this._cursorPoint.worldZ));
            }
        }

        if (screenPts.length >= MIN_LOOP_VERTS) this._fillPath(ctx, [...screenPts, ...trailing]);
        this._strokePath(ctx, [...screenPts, ...trailing], false);
        // ⭐ §FIX-PLAN-TOOL-FINISH-GESTURE (L-9304) — SHOW THE EDGE THAT WILL CLOSE.
        //
        // THE FOUNDER: *"if I create 3 segments on preview and click Enter the 4th
        // should connect with the first point"* — and it always did. `_commit()` treats
        // `_points` as a RING (first vertex not repeated, the slab/boundary-line
        // convention), so three segments have always produced a four-sided pool. What
        // was missing is that NOTHING ON SCREEN SAID SO: the preview stroked an open
        // polyline, so the closing edge existed only in the commit. Asking a person to
        // trust an edge they cannot see is how "it doesn't work" gets reported about
        // something that works.
        //
        // Drawn fainter and in a longer dash than the drawn edges, because it is the
        // edge the TOOL will add, not one the architect has placed. The wall tool has
        // never needed this: it commits each segment as it goes, so its closing
        // segment is a real wall the moment Enter lands.
        this._strokeClosingHint(ctx, [...screenPts, ...trailing]);

        if (mode === 'curved' && this._arcMidPt) {
            const m = planCanvas.worldToScreen(this._arcMidPt.worldX, this._arcMidPt.worldZ);
            ctx.fillStyle = STROKE;
            ctx.beginPath(); ctx.arc(m.sx, m.sy, 5, 0, Math.PI * 2); ctx.fill();
        }

        ctx.fillStyle = STROKE;
        for (const p of screenPts) { ctx.beginPath(); ctx.arc(p.sx, p.sy, 4, 0, Math.PI * 2); ctx.fill(); }

        this._drawHint(ctx, cssH, this._hintFor(mode));
        ctx.restore();
    }

    private _hintFor(mode: string): string {
        const label = mode === 'ortho' ? 'Orthogonal' : mode === 'curved' ? 'Curved' : 'Linear';
        if (mode === 'curved' && this._points.length > 0) {
            return this._arcMidPt
                ? 'Curved · Click the arc END point · Backspace to re-pick midpoint'
                : `Curved · Click the arc MIDPOINT${this._points.length >= MIN_LOOP_VERTS ? ' · Enter to close pool' : ''}`;
        }
        const missing = MIN_LOOP_VERTS - this._points.length;
        return this._points.length >= MIN_LOOP_VERTS
            ? `${label} · Dbl-click or Enter to close pool`
            : `${label} · ${missing} more point${missing !== 1 ? 's' : ''} needed`;
    }

    private _fillPath(ctx: CanvasRenderingContext2D, pts: ReadonlyArray<{ sx: number; sy: number }>): void {
        if (pts.length < MIN_LOOP_VERTS) return;
        ctx.globalAlpha = 0.14;
        ctx.fillStyle   = FILL_A;
        ctx.beginPath();
        ctx.moveTo(pts[0]!.sx, pts[0]!.sy);
        for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i]!.sx, pts[i]!.sy);
        ctx.closePath(); ctx.fill();
        ctx.globalAlpha = 1;
    }

    private _strokePath(
        ctx: CanvasRenderingContext2D,
        pts: ReadonlyArray<{ sx: number; sy: number }>,
        close: boolean,
    ): void {
        if (pts.length === 0) return;
        ctx.setLineDash([6, 3]);
        ctx.lineWidth   = 1.5;
        ctx.strokeStyle = STROKE;
        ctx.beginPath();
        ctx.moveTo(pts[0]!.sx, pts[0]!.sy);
        for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i]!.sx, pts[i]!.sy);
        if (close) ctx.closePath();
        ctx.stroke();
        ctx.setLineDash([]);
    }

    /**
     * §FIX-PLAN-TOOL-FINISH-GESTURE (L-9304) — the edge Enter / double-click will add.
     *
     * A pool outline is a RING; the open modes just build it one vertex at a time. Below
     * three points there is nothing to close, so nothing is drawn — the hint appears at
     * exactly the moment the gesture becomes finishable, which also makes the sentence
     * `_hintFor()` prints ("Dbl-click or Enter to close pool") visible at the same instant.
     */
    private _strokeClosingHint(
        ctx: CanvasRenderingContext2D,
        pts: ReadonlyArray<{ sx: number; sy: number }>,
    ): void {
        if (pts.length < MIN_LOOP_VERTS) return;
        const first = pts[0]!;
        const last  = pts[pts.length - 1]!;
        ctx.save();
        ctx.setLineDash([2, 5]);
        ctx.lineWidth   = 1;
        ctx.globalAlpha = 0.55;
        ctx.strokeStyle = STROKE;
        ctx.beginPath();
        ctx.moveTo(last.sx, last.sy);
        ctx.lineTo(first.sx, first.sy);
        ctx.stroke();
        ctx.restore();
        ctx.setLineDash([]);
    }

    private _drawHint(ctx: CanvasRenderingContext2D, cssH: number, text: string): void {
        ctx.font         = 'bold 11px sans-serif';
        ctx.fillStyle    = 'rgba(102,0,255,0.9)';
        ctx.textAlign    = 'left';
        ctx.textBaseline = 'bottom';
        ctx.fillText(text, 12, cssH - 12);
    }

    private _clearOverlay(): void {
        const c = this._ctx;
        if (!c) return;
        c.ctx.setTransform(1, 0, 0, 1, 0, 0);
        c.ctx.clearRect(0, 0, c.overlayCanvas.width, c.overlayCanvas.height);
    }
}
