/**
 * SiteworksPlanToolHandler — THE DRAW GESTURE. C116 §11 · ADR-0384 · C11 · C16 CA-2 · P6.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⭐ THE FOUNDER'S REPORT, AND WHAT WAS ACTUALLY MISSING
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 *   *"the new category tab is created — but it doesn't work — none of the elements on
 *    selection works, the element doesn't create anything on neither PRYZM 2D view or
 *    PRYZM 3D view."*
 *
 * The `siteworks` family was complete on every other axis — L0 schema, four registers,
 * five verbs, a store, persistence, a renderer (`842a5cf0`) and a rail category. What
 * it had was three buttons that PLACED a surface at the plan ORIGIN, which is a long
 * way from *"linear design — like a wall"* and, on a plan scrolled anywhere else, is
 * indistinguishable from creating nothing at all. `siteworksRailTools.ts` said so in
 * its own header and named the extraction that was owed. This is that extraction's
 * second caller.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⛔ THIS FILE CONTAINS NO STROKE STATE MACHINE AND NO DIMENSIONAL LITERAL
 * ═══════════════════════════════════════════════════════════════════════════════
 * The polyline — ortho constraint, three-click arc, closed-loop shapes, Backspace,
 * Enter-closes, the refusal that survives a pointer sample — is `PlanPolylineStroke`,
 * shared verbatim with `BoundaryLinePlanToolHandler`. A second copy here is
 * [[same-rule-two-implementations]], and the guarding test would stay green on
 * whichever copy it happened to measure.
 *
 * Every dimension resolves through the schema's CITED defaults —
 * `SITEWORKS_DEFAULT_WIDTH_M[role]` (road 7.00 m Norma 3.1-IC · pedestrian 1.80 m
 * VIV/561/2010 · parking 5.00 m `convention`) and `SITEWORKS_DEFAULT_THICKNESS_M`.
 * ⛔ Not one of those numbers is retyped in this file; a retyped citation is a
 * citation that can drift away from the ordinance it names.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⭐ FORM IS READ OFF THE GESTURE, NEVER ASKED FOR (ADR-0384 D1/D2)
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 *     OPEN finish  (double-click, or Enter on a chain)      → `linear`
 *                  centreline = the vertices · widthM = the role's cited default
 *     CLOSED finish (Enter on a ring, or rectangular /      → `areal`
 *                    circular / elliptical)                    boundary = the ring
 *
 * ⛔ AND THE SWEPT RING IS NEVER STORED — C116 is explicit that a stored ring destroys
 * authored intent and goes stale on the next `setWidth`. The PREVIEW calls
 * `sweepCentrelineToRing`, the family's one authority, so what the architect aims at
 * is generated by the same function the renderer will use; and the COMMIT sends the
 * centreline, because that is what the record is.
 */

import { createId } from '@pryzm/schemas';
import {
    SITEWORKS_DEFAULT_WIDTH_M,
    SITEWORKS_DEFAULT_THICKNESS_M,
    type SiteworksRole,
} from '@pryzm/schemas';
import { sweepCentrelineToRing } from '@pryzm/geometry-siteworks';
import type { PlanToolHandler, PlanToolDrawContext, WorldPoint } from './PlanToolHandler';
import {
    PlanPolylineStroke,
    loopGestureHint,
    PLAN_STROKE_PURPLE,
    type StrokePoint,
    type StrokeUnderlayContext,
    type PlanStrokeStyle,
} from './PlanPolylineStroke';
import {
    resolveActiveSiteworksDrawMode,
    activeSiteworksLoopMode,
    resolveActiveSiteworksRole,
} from './activeSiteworksAuthoring';
import { notifyPlanToolCreated } from '@app/ui/create/activatePlanOnlyTool';

/**
 * TWO vertices, not three — the same floor the boundary line takes, for the same
 * reason. A single straight run from A to B is a perfectly good road centreline, and
 * the L0 schema agrees: *"A LINEAR siteworks surface needs a centreline of at least 2
 * points."* Only the CLOSED forms need three, and the schema enforces that half too.
 */
const MIN_PATH_VERTS = 2;
const MIN_LOOP_VERTS = 3;

/**
 * A SOLID centreline, not the boundary line's dashed construction stroke.
 *
 * ⭐ THE DIFFERENCE IS SEMANTIC, NOT DECORATIVE. A boundary line is a setting-out line
 * — dashed, because it is a construction that will never be built. A road is BUILT
 * FABRIC: it gets a solid centreline over a translucent band showing the real swept
 * width, so the architect is aiming at the surface rather than at an abstraction of it.
 */
const SITEWORKS_STYLE: PlanStrokeStyle = Object.freeze({
    colour: PLAN_STROKE_PURPLE,
    lineWidth: 1.6,
    dash: Object.freeze([]) as readonly number[],
    vertexDotRadius: 4,
});

/** Human names for the refusal and confirmation sentences. */
const ROLE_LABEL: Readonly<Record<SiteworksRole, string>> = Object.freeze({
    road: 'Road',
    parking: 'Parking',
    pedestrian: 'Pedestrian surface',
});

export class SiteworksPlanToolHandler implements PlanToolHandler {
    /**
     * ⭐ ONE STROKE, CONFIGURED — the whole gesture, borrowed rather than rebuilt.
     * Bound in the field initialiser so `hasActiveStroke()` is answerable before the
     * first `activate()`, which is what `anyPlanSurfaceHasStroke()` asks on Escape.
     */
    private readonly _stroke = new PlanPolylineStroke({
        minPathVerts: MIN_PATH_VERTS,
        minLoopVerts: MIN_LOOP_VERTS,
        resolveMode: resolveActiveSiteworksDrawMode,
        resolveLoopMode: activeSiteworksLoopMode,
        style: SITEWORKS_STYLE,
        underlay: (u) => this._paintSweptBand(u),
        hint: (s) => this._hint(s.mode, s.loopMode, s.vertexCount, s.awaitingArcEnd, s.canClose),
        finish: (pts, closed, ctx, stroke) => this._create(pts, closed, ctx, stroke),
    });

    hasActiveStroke(): boolean {
        return this._stroke.hasActiveStroke();
    }

    // ⭐ THE STROKE HOLDS THE CONTEXT, NOT THIS CLASS. A second copy of `_ctx` here
    // would be a second answer to "which surface am I drawing on", and the finish
    // target is handed the live one as an argument precisely so the two cannot drift.
    activate(ctx: PlanToolDrawContext): void { this._stroke.attach(ctx); }
    deactivate(): void { this._stroke.detach(); }

    onMouseMove(pt: WorldPoint): void { this._stroke.onMouseMove(pt); }
    onClick(pt: WorldPoint): void { this._stroke.onClick(pt); }
    onDoubleClick(_pt: WorldPoint): void { this._stroke.onDoubleClick(); }
    onKeyDown(e: KeyboardEvent): boolean { return this._stroke.onKeyDown(e); }
    cancel(): void { this._stroke.cancel(); }
    redraw(): void { this._stroke.redraw(); }

    // ── The FINISH TARGET ────────────────────────────────────────────────────

    /**
     * ⭐ P6 — DISPATCH, NEVER A STORE WRITE. And the id is minted HERE, at the gesture,
     * not inside the handler: `execute()` runs AGAIN on redo (C16 CA-2), so an id
     * minted downstream would differ the second time and orphan every reference that
     * named the first.
     */
    private _create(
        points: readonly StrokePoint[],
        closed: boolean,
        ctx: PlanToolDrawContext,
        stroke: PlanPolylineStroke,
    ): void {
        const role = resolveActiveSiteworksRole();
        const label = ROLE_LABEL[role];

        // ⛔ REFUSE RATHER THAN DEFAULT TO A LEVEL THE USER IS NOT LOOKING AT.
        // §CONTEXT-DATA-HONESTY (L-581/L-616) — "we could not tell which storey is
        // active" and "the ground storey" must never share a value. The renderer
        // already refuses to draw a surface whose storey does not resolve (842a5cf0),
        // so an invented id here would produce a record that exists and is invisible.
        const levelId = ctx.viewDef.spatial?.levelId;
        if (!levelId) {
            stroke.refuse(`This view has no level, so there is nothing to lay a ${label.toLowerCase()} on.`);
            return;
        }

        const widthM = SITEWORKS_DEFAULT_WIDTH_M[role].valueM;
        const thickness = SITEWORKS_DEFAULT_THICKNESS_M.valueM;
        const vertices = points.map((p) => ({ x: p.x, y: 0, z: p.z }));

        // ⭐ THE GESTURE DECIDES THE FORM. Nothing was asked and nothing is stored:
        // an open chain IS a centreline, a closed ring IS a boundary.
        const spec = closed
            ? {
                siteworksId: createId('siteworks'),
                levelId,
                role,
                form: 'areal' as const,
                centreline: [],
                boundary: vertices,
                holes: [],
                thickness,
            }
            : {
                siteworksId: createId('siteworks'),
                levelId,
                role,
                form: 'linear' as const,
                centreline: vertices,
                widthM,
                boundary: [],
                holes: [],
                thickness,
            };

        // ⚠ A LINEAR SURFACE WHOSE CENTRELINE CANNOT SWEEP IS REFUSED BEFORE THE BUS,
        // with the sweeper's OWN sentence. `sweepCentrelineToRing` is the authority the
        // renderer will call; asking it here means a hairpin that produces no footprint
        // is named at the gesture rather than committed as an invisible record. C11
        // §7.6 — "a dead click behind a perfect preview".
        if (!closed) {
            const swept = sweepCentrelineToRing(vertices, widthM);
            if (!swept.ok) {
                stroke.refuse(`${label} not created — ${swept.reason}`);
                return;
            }
        }

        const bus = ctx.runtime?.bus ?? window.runtime?.bus;
        const dispatch = bus?.executeCommand('siteworks.batch.create', { surfaces: [spec] });
        if (!dispatch) {
            stroke.refuse(`The command bus is not available, so no ${label.toLowerCase()} was created.`);
            return;
        }

        void Promise.resolve(dispatch).then(() => {
            // ⭐ SAY THAT IT EXISTS, BY NAME (L-9305). The founder's *"it doesn't
            // create"* is the only reading available to someone who drew a shape and
            // then saw nothing they could attribute to it — and a road laid on a plan
            // he has scrolled away from is exactly that.
            notifyPlanToolCreated(
                closed
                    ? `${label} area created — ${vertices.length}-point boundary.`
                    : `${label} created — ${vertices.length}-point centreline at ${widthM.toFixed(2)} m wide.`,
            );
        }).catch((e: unknown) => {
            // ⭐ SURFACE THE BUS'S OWN REASON, VERBATIM. `canExecute` rejections arrive
            // as `CommandBusError: siteworks.batch.create: canExecute rejected — <why>`,
            // and that `<why>` is the most accurate sentence available. Swallowing it
            // is the "reported activation, activated nothing" defect.
            const why = e instanceof Error ? e.message : String(e);
            console.error('[SiteworksPlanToolHandler] siteworks.batch.create failed:', why);
            stroke.refuse(why);
        });
    }

    // ── Preview ──────────────────────────────────────────────────────────────

    /**
     * ⭐ THE BAND IS THE FAMILY'S OWN SWEEP, NOT A SECOND ONE.
     *
     * `sweepCentrelineToRing` is C116's named authority (C84 EI-1) and is what the mesh
     * builder resolves through. Painting the preview from a locally-computed offset
     * would be a second sweep — and a second sweep LOOKS right on screen long after it
     * has stopped agreeing with the geometry that ships, which is precisely the class
     * of defect `842a5cf0` refused inside the renderer.
     *
     * ⚠ It is skipped for a CLOSED gesture: an areal surface has no centreline and no
     * width, so there is nothing to sweep — the ring the stroke already draws IS the
     * footprint.
     */
    private _paintSweptBand(u: StrokeUnderlayContext): void {
        if (u.closed || u.points.length < MIN_PATH_VERTS) return;
        const role = resolveActiveSiteworksRole();
        const widthM = SITEWORKS_DEFAULT_WIDTH_M[role].valueM;
        const swept = sweepCentrelineToRing(
            u.points.map((p) => ({ x: p.x, y: 0, z: p.z })),
            widthM,
        );
        // A sweep that cannot resolve draws NOTHING and says nothing here — the refusal
        // belongs at the commit, where the architect has finished asking. A preview
        // that shouted every frame while a hairpin was mid-drag would be unusable.
        if (!swept.ok || swept.ring.length < MIN_LOOP_VERTS) return;

        const pts = swept.ring.map((p) => u.toScreen(p.x, p.z));
        u.ctx.save();
        u.ctx.beginPath();
        u.ctx.moveTo(pts[0]!.sx, pts[0]!.sy);
        for (let i = 1; i < pts.length; i++) u.ctx.lineTo(pts[i]!.sx, pts[i]!.sy);
        u.ctx.closePath();
        u.ctx.fillStyle = 'rgba(102,0,255,0.13)';
        u.ctx.fill();
        u.ctx.setLineDash([]);
        u.ctx.lineWidth = 1;
        u.ctx.strokeStyle = 'rgba(102,0,255,0.45)';
        u.ctx.stroke();
        u.ctx.restore();
    }

    /**
     * ⭐ THE HINT ASKS THE PREDICATE. It does not re-derive "can I close?" from a vertex
     * count of its own: a hint that names ENTER while ENTER refuses teaches the
     * architect the feature is broken — the C87 §13.8 CW-Poly-1 defect. One rule, two
     * readers.
     */
    private _hint(
        mode: string,
        loopMode: string | null,
        vertexCount: number,
        awaitingArcEnd: boolean,
        canClose: boolean,
    ): string {
        const role = resolveActiveSiteworksRole();
        const widthM = SITEWORKS_DEFAULT_WIDTH_M[role].valueM;
        const head = `${ROLE_LABEL[role]} · ${widthM.toFixed(2)} m wide`;

        if (loopMode) return `${head} · ${loopGestureHint(loopMode as never)}`;
        if (mode === 'curved' && vertexCount > 0) {
            if (awaitingArcEnd) return `${head} · Click the arc END point · Backspace to re-pick midpoint`;
            const tail = canClose
                ? ' · Enter to CLOSE into an area · Dbl-click to finish the run'
                : (vertexCount >= MIN_PATH_VERTS ? ' · Enter to finish the run' : '');
            return `${head} · Click the arc MIDPOINT${tail}`;
        }
        const label = mode === 'ortho' ? 'Orthogonal' : mode === 'curved' ? 'Curved' : 'Linear';
        if (canClose) {
            return `${head} · ${label} · Enter to CLOSE into an AREA · Dbl-click to finish as a run`;
        }
        const missing = MIN_PATH_VERTS - vertexCount;
        return vertexCount >= MIN_PATH_VERTS
            ? `${head} · ${label} · Dbl-click or Enter to finish · 1 more point to close an area`
            : `${head} · ${label} · ${missing} more point${missing !== 1 ? 's' : ''} needed`;
    }
}
