// @vitest-environment node
//
// L-13117 — A WALL MUST CARRY WHERE IT CAME FROM, AND CARRY IT ACROSS A RELOAD.
// ═══════════════════════════════════════════════════════════════════════════════
//
// §ENVELOPE-WALLS-FOLLOW shipped and works — but ONLY where the semantic graph recorded a
// `wall —boundedBy→ envelope` row, and exactly ONE producer in the tree writes those rows
// (`buildFromDesignExecutor.ts`; re-verified 2026-09-07 by
// `rg -n 'recordEnvelopeWallLinks' apps packages plugins` → the producer, its spec, and
// nothing else). So a building the founder generated by any OTHER route reports "No walls
// are linked to this envelope yet." on a face drag and moves nothing.
//
// ⛔ THE FIX IS NOT A SECOND RECORDER. A recorder per generator is N places to forget, and
// C80 §0.1(4) already names the durable instrument — `ElementProvenanceIndex` — which
// nothing calls, blocked on the measured fact that `Wall` carries `provenance: {origin,
// detail?}` with NO ELEMENT ID and that `serializeWall` wrote no provenance for walls at
// all. A link carried by the wall itself is derivable from the model; a side table is not.
//
// ─── WHAT THIS FILE PROVES, AND WHAT IT DOES NOT — stated, not implied ────────
//
// PROVEN BEHAVIOURALLY (executed, real command + real store, C16 CA-21):
//   · the RELOAD half — `CreateWallCommand` carries `derivedFrom` onto the record;
//   · THE OLD-PROJECT CASE — a wall record written before this field existed reloads
//     unchanged and lands on `undefined`, never `[]`;
//   · the three-value distinction absent / empty / present survives the round trip.
//
// PROVEN BY SOURCE PARITY, NOT BY AN EXECUTED SAVE: the WRITE half. There are FIVE
// hand-written whitelists on this field's path — two `serializeWall` twins, the legacy
// `ProjectLoader`, the DEFAULT-ON `ImportProjectCommand`, and the schema mirror in
// `WallTypes.ts` — and their DIVERGENCE is the documented failure mode: `serializeWall`'s
// own comment says "these two allow-lists diverging is how `function` was silently dropped
// on reload", and §PERSIST-DEFAULT-PATH (L-1211) found FOUR fields that survived the save
// and died on the path that actually ships. Executing `ProjectSerializer.serialize` needs a
// ~20-store bundle plus `window`, and hand-building those neighbours is the
// [[fake-more-capable-than-real]] trap. So the save half is asserted over the REAL SOURCE
// TEXT of all five, and that limitation is named here rather than papered over.
//
// ⛔ NOT PROVEN HERE, and named so nobody reads this file as claiming it: that the CASCADE
// reads the persisted field. That is the follow-up in L-13117; a persisted field nothing
// reads yet is harmless, and a half-migrated format is the outcome this ordering avoids.

import { describe, it, expect, beforeEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { WallStore } from '@pryzm/geometry-wall';
import type { WallDerivation } from '@pryzm/geometry-wall';
import { ProjectContext } from '@pryzm/core-app-model';
import { CreateWallCommand } from '@pryzm/command-registry';
import { elementRegistry } from '@pryzm/core-app-model/element-registry';
import { ElementDerivationSchema } from '@pryzm/schemas/provenance';

const REPO = resolve(__dirname, '../../..');
const LEVEL_ID = 'L0';
const LEVEL = { id: LEVEL_ID, name: 'Ground', elevation: 0, height: 3, childrenIds: [] };

const SERIALIZER_APP = resolve(REPO, 'apps/editor/src/engine/persistence/ProjectSerializer.ts');
const SERIALIZER_PC = resolve(REPO, 'packages/persistence-client/src/loader/ProjectSerializer.ts');
const LOADER_LEGACY = resolve(REPO, 'apps/editor/src/engine/persistence/ProjectLoader.ts');
const LOADER_DEFAULT = resolve(REPO, 'packages/command-registry/src/project/ImportProjectCommand.ts');
const WALL_TYPES = resolve(REPO, 'packages/geometry-wall/src/WallTypes.ts');
const DERIVATION_SCHEMA = resolve(REPO, 'packages/schemas/src/provenance/ElementDerivation.ts');

const read = (p: string) => readFileSync(p, 'utf8');

/** Strip line and block comments so a field NAMED ONLY IN PROSE cannot satisfy a parity check. */
function decomment(src: string): string {
    return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');
}

function makeLevelProvider() {
    return {
        getLevelById: (id: string) => (id === LEVEL_ID ? { ...LEVEL } : undefined),
        getLevels: () => [{ ...LEVEL }],
    };
}

function newStore(): WallStore {
    return new WallStore(
        new ProjectContext(),
        makeLevelProvider() as unknown as ConstructorParameters<typeof WallStore>[1],
    );
}

/**
 * The FOUR `bimManager` methods `CreateWallCommand` actually calls, and no more — the same
 * fixture `L999SideFinishSurvivesReload.test.ts` uses, for the same reason: a fake built
 * wider than the caller's need is a fake that cannot falsify anything.
 */
function ctxFor(store: WallStore): any {
    return {
        bimManager: {
            getLevelById: (id: string) => (id === LEVEL_ID ? { ...LEVEL } : undefined),
            getLevels: () => [{ ...LEVEL }],
            registerElement: () => { /* identity only; nothing here reads it back */ },
            unregisterElement: () => { /* idem */ },
        },
        stores: { wallStore: store, wallSystemTypeStore: undefined },
    };
}

/**
 * The EXACT projection `serializeWall` applies to this field, mirrored from the live
 * serialiser (`apps/editor/src/engine/persistence/ProjectSerializer.ts`). Kept as a
 * function so the round trip below walks the real shape — and pinned to its master by the
 * source-parity block at the bottom of this file, C84 EI-8a.
 */
function serializeDerivedFrom(wall: any): unknown {
    return Array.isArray(wall.derivedFrom)
        ? wall.derivedFrom.map((d: any) => ({ ...d }))
        : undefined;
}

const SHELL_EDGE_3: WallDerivation = {
    sourceElementId: 'SE-ground',
    sourceKind: 'space-envelope',
    edgeIndex: 3,
    generator: 'buildFromDesign',
    claim: 'primary',
    role: 'shell',
};

function createWall(
    store: WallStore,
    id: string,
    derivedFrom?: WallDerivation[],
): boolean {
    return new CreateWallCommand(id, {
        start: { x: 0, z: 0 }, end: { x: 5, z: 0 },
        height: 3, thickness: 0.1, levelId: LEVEL_ID,
        ...(derivedFrom !== undefined ? { derivedFrom } : {}),
    }).execute(ctxFor(store)).success;
}

describe('L-13117 — the wall carries its origin out to a snapshot and back', () => {
    // `elementRegistry` is a MODULE SINGLETON whose `registerSemantic` throws on a duplicate
    // id — a redo-safety guard. A reload re-registers the SAME ids, which is exactly what the
    // round trips below do, so it is cleared per test rather than dodged with fresh ids: the
    // wall keeping its identity across the reload is the property under test.
    beforeEach(() => { elementRegistry.clear(); });

    it('RELOAD HALF, executed — CreateWallCommand carries derivedFrom onto the record', () => {
        // ── Session 1: a generator stamps the lineage at creation.
        const live = newStore();
        expect(createWall(live, 'w0', [SHELL_EDGE_3])).toBe(true);

        const authored = live.getById('w0') as any;
        expect(authored.derivedFrom, 'precondition: the store preserved the stamp').toEqual([SHELL_EDGE_3]);

        // ── SAVE: what `serializeWall` writes for this field.
        const persisted = serializeDerivedFrom(authored) as WallDerivation[];
        expect(persisted).toEqual([SHELL_EDGE_3]);
        // Deep-copied, never aliased — the snapshot must not hold a live reference into the store.
        expect(persisted[0]).not.toBe(authored.derivedFrom[0]);

        // ── PROJECT CLOSED, then RELOAD through the real create path.
        elementRegistry.clear();
        const reloaded = newStore();
        expect(createWall(reloaded, 'w0', persisted)).toBe(true);

        // §CA-21 executed read-back on the reloaded record.
        const after = reloaded.getById('w0') as any;
        expect(
            after.derivedFrom,
            'the envelope→wall lineage died on reload — the cascade would work in the session '
            + 'the building was generated in and silently not afterwards, which is worse than '
            + 'never having shipped it: it is intermittent by reload.',
        ).toEqual([SHELL_EDGE_3]);
    });

    // ── THE OLD-PROJECT CASE ────────────────────────────────────────────────────
    //
    // ⭐ THE ONE THAT MATTERS MOST, because it is the only case that exists on real
    // customer data today: EVERY wall in EVERY saved project has no `derivedFrom`.
    it('OLD PROJECT — a wall saved before this field existed reloads, and lands on UNDEFINED not []', () => {
        // A wall record exactly as a pre-L-13117 build wrote it: no `derivedFrom` key at all.
        const legacyRecord: Record<string, unknown> = {
            id: 'w-legacy',
            type: 'wall',
            levelId: LEVEL_ID,
            baseLine: [{ x: 0, y: 0, z: 0 }, { x: 5, y: 0, z: 0 }],
            height: 3,
            thickness: 0.1,
            baseOffset: 0,
            openings: [],
            childrenIds: [],
            properties: {},
        };
        expect('derivedFrom' in legacyRecord, 'fixture precondition: a legacy record has no key').toBe(false);

        // The loader's projection: `(wall as {derivedFrom?}).derivedFrom` — undefined, forwarded.
        const fromLoader = (legacyRecord as { derivedFrom?: WallDerivation[] }).derivedFrom;
        expect(fromLoader).toBeUndefined();

        const store = newStore();
        expect(
            createWall(store, 'w-legacy', fromLoader),
            'a legacy project must still LOAD — a persisted-format change that refuses old data '
            + 'is not a migration, it is a data-loss event with a version number.',
        ).toBe(true);

        const after = store.getById('w-legacy') as any;

        // ⛔ THE ASSERTION THIS WHOLE TEST EXISTS FOR (§CONTEXT-DATA-HONESTY — failure and
        // empty are DIFFERENT VALUES). `undefined` says "PRYZM does not know where this wall
        // came from". `[]` would say "PRYZM looked, and this wall belongs to no envelope".
        // The second is a positive claim nobody is entitled to make about a legacy wall, and
        // it is the claim a single `?? []` anywhere on this path would fabricate — silently,
        // for every wall in every existing project, which is L-616's shape exactly.
        expect(
            after.derivedFrom,
            'a legacy wall was given an EMPTY lineage. Empty is a positive finding ("no source '
            + 'element"); absent is the honest one ("not recorded"). Find the `?? []` and remove it.',
        ).toBeUndefined();

        // ⚠ MEASURED, AND NAMED RATHER THAN ASSERTED AWAY. The KEY is PRESENT on the
        // record with value `undefined`, because `CreateWallCommand`'s `wallData` literal
        // names `derivedFrom` unconditionally — exactly as it names `joinIntent`,
        // `wallProfile`, `sideFinishes` and `rakeAngleDeg`. This test asserted
        // `!('derivedFrom' in after)` on the first run and that was WRONG: it asserted a
        // property the surrounding convention does not have, and diverging from four
        // neighbouring fields to satisfy it would have been the surprise, not the fix.
        //
        // What actually matters is preserved and is asserted above and below: the VALUE is
        // `undefined`, never `[]`, so no legacy wall acquires a positive "belongs to no
        // envelope" claim; and `JSON.stringify` omits an `undefined` value, so the snapshot
        // is byte-identical to a pre-L-13117 one.
        //
        // ⛔ The residual, stated so a future reader is not caught by it: a consumer that
        // asks `'derivedFrom' in wall` gets TRUE for a legacy wall. Ask for the VALUE
        // (`wall.derivedFrom === undefined`), never for the key.
        expect('derivedFrom' in after, 'convention check — see the note above').toBe(true);

        // And it re-serialises byte-identically to a pre-L-13117 snapshot (C47 §1.2).
        expect(serializeDerivedFrom(after)).toBeUndefined();
        expect(JSON.parse(JSON.stringify({ derivedFrom: serializeDerivedFrom(after) })))
            .toEqual({});
    });

    it('KNOWN-EMPTY is not ABSENT — a stamping producer that found no source round-trips as []', () => {
        const live = newStore();
        expect(createWall(live, 'w-empty', [])).toBe(true);

        const authored = live.getById('w-empty') as any;
        expect(authored.derivedFrom, 'an explicit empty claim is preserved, not erased').toEqual([]);

        const persisted = serializeDerivedFrom(authored);
        expect(persisted, 'and it SURVIVES the save — [] is a value, not a missing one').toEqual([]);

        elementRegistry.clear();
        const reloaded = newStore();
        expect(createWall(reloaded, 'w-empty', persisted as WallDerivation[])).toBe(true);
        expect((reloaded.getById('w-empty') as any).derivedFrom).toEqual([]);
    });

    it('TWO CLAIMS on one wall survive — the shape C80 needs to call a contest', () => {
        // C80: two sources placing one wall differently is CONTESTED — dropped and surfaced,
        // never last-write-wins. That verdict is only STATABLE if both rival claims can be
        // present on the record, which is why this field is an array and not a single row.
        const both: WallDerivation[] = [
            SHELL_EDGE_3,
            { sourceElementId: 'R-kitchen', sourceKind: 'space-envelope', edgeIndex: 0,
              generator: 'buildFromDesign', claim: 'also', role: 'partition' },
        ];
        const live = newStore();
        expect(createWall(live, 'w-both', both)).toBe(true);

        const persisted = serializeDerivedFrom(live.getById('w-both') as any) as WallDerivation[];
        expect(persisted).toHaveLength(2);
        expect(persisted.map(d => d.sourceElementId)).toEqual(['SE-ground', 'R-kitchen']);
        expect(persisted.map(d => d.claim)).toEqual(['primary', 'also']);
    });

    it('AN UNRECOVERABLE EDGE IS -1, AND -1 IS NOT 0', () => {
        // `designEnvelopeWallLink.ts` already uses this sentinel: after a ring is welded, the
        // edge a wall came from may not be identifiable. Defaulting that to 0 would attach a
        // real wall to the wrong face and move the WRONG WALL on the first cascade, with
        // nothing in the model to say why.
        const welded: WallDerivation = {
            ...SHELL_EDGE_3, edgeIndex: -1, ringWelded: true,
        };
        const live = newStore();
        expect(createWall(live, 'w-welded', [welded])).toBe(true);
        const persisted = serializeDerivedFrom(live.getById('w-welded') as any) as WallDerivation[];
        expect(persisted[0]!.edgeIndex).toBe(-1);
        expect(persisted[0]!.ringWelded).toBe(true);
    });
});

// ─────────────────────────────────────────────────────────────────────────────
// THE L0 RECORD ITSELF
// ─────────────────────────────────────────────────────────────────────────────

describe('L-13117 — ElementDerivationSchema refuses the rows that would be lies', () => {
    it('accepts a well-formed claim', () => {
        expect(ElementDerivationSchema.safeParse(SHELL_EDGE_3).success).toBe(true);
    });

    it('refuses a claim that names no source — a claim with no subject is not a claim', () => {
        expect(ElementDerivationSchema.safeParse({ ...SHELL_EDGE_3, sourceElementId: '' }).success).toBe(false);
    });

    it('refuses an unattributable row — a reader that cannot name the producer cannot age it', () => {
        expect(ElementDerivationSchema.safeParse({ ...SHELL_EDGE_3, generator: '' }).success).toBe(false);
    });

    it('refuses an edge index below the -1 sentinel, and refuses a fractional one', () => {
        expect(ElementDerivationSchema.safeParse({ ...SHELL_EDGE_3, edgeIndex: -2 }).success).toBe(false);
        expect(ElementDerivationSchema.safeParse({ ...SHELL_EDGE_3, edgeIndex: 1.5 }).success).toBe(false);
        expect(ElementDerivationSchema.safeParse({ ...SHELL_EDGE_3, edgeIndex: -1 }).success).toBe(true);
    });

    it('is STRICT — a key nobody declared is a key nobody restores', () => {
        const r = ElementDerivationSchema.safeParse({ ...SHELL_EDGE_3, envelopeRole: 'ground' });
        expect(
            r.success,
            'an undeclared key was accepted. This record round-trips through two serialisers and '
            + 'two loaders that copy DECLARED fields only, so a silently-accepted key lets a '
            + 'producer believe it recorded something the next reload will drop.',
        ).toBe(false);
    });
});

// ─────────────────────────────────────────────────────────────────────────────
// SOURCE PARITY — the five hand-written whitelists, read from source, not mirrored
// ─────────────────────────────────────────────────────────────────────────────

describe('L-13117 — every whitelist on the path names the field', () => {
    // Each entry is (path, human name, what breaks when it is absent). The MESSAGE is the
    // point: a bare `toContain` failure tells the next reader nothing about the consequence.
    const WHITELISTS: ReadonlyArray<readonly [string, string, string]> = [
        [SERIALIZER_APP, 'apps/editor serializeWall (THE SAVE PATH)',
            'the lineage is destroyed by the next save — the L-927 joinIntent defect exactly'],
        [SERIALIZER_PC, 'persistence-client serializeWall (the twin)',
            'the two allow-lists have diverged, which is how `function` was silently dropped on reload'],
        [LOADER_LEGACY, 'apps/editor ProjectLoader (the LEGACY restore path)',
            'the field is written perfectly and dies one frame after the loader reads it'],
        [LOADER_DEFAULT, 'ImportProjectCommand (the DEFAULT-ON restore path)',
            'the field survives on the path nobody runs and dies on the path that ships — §PERSIST-DEFAULT-PATH (L-1211) found FOUR fields in exactly this state'],
    ];

    for (const [path, name, consequence] of WHITELISTS) {
        it(`${name} carries derivedFrom`, () => {
            expect(decomment(read(path)), `${consequence}.`).toContain('derivedFrom');
        });
    }

    it('the CLONE paths DROP it — a copy is not the element it was copied from', () => {
        // Inherited through `serializeWallSnapshot`'s `{...wall}` spread, a clone would claim
        // to BE an edge it is not, and an envelope face-drag would face a contest manufactured
        // by a clone rather than by the model. The joinIntent census (L-927) pinned exactly
        // this inheritance for the same three commands.
        for (const f of ['CopyElementCommand', 'MirrorElementCommand', 'OffsetElementCommand']) {
            const src = decomment(read(resolve(REPO, `packages/command-registry/src/operations/${f}.ts`)));
            expect(
                src,
                `${f} does not drop derivedFrom, so a cloned wall inherits a claim about a PLACE `
                + 'it does not occupy.',
            ).toMatch(/delete\s*\([^)]*\)\.derivedFrom;/);
        }
    });

    // ── C84 EI-8a: the licensed copy is pinned to its master by an executed comparison ──
    it('WallData.WallDerivation mirrors ElementDerivationSchema field-for-field', () => {
        // `packages/geometry-wall` does not declare `@pryzm/schemas` as a dependency
        // (measured 2026-09-07), so the runtime interface is a MIRROR of the L0 zod record
        // rather than an import of it. A comment is not a synchronisation mechanism — C84
        // §8.d — and this repo has watched that mechanism fail twice. This is the pin.
        const mirrorSrc = read(WALL_TYPES);
        const m = /export interface WallDerivation \{([\s\S]*?)\n\}/.exec(mirrorSrc);
        expect(m, 'the WallDerivation declaration moved — re-point this extractor').toBeTruthy();
        const mirrored = Array.from(
            decomment(m![1]!).matchAll(/^\s{4}([A-Za-z][A-Za-z0-9]*)\??:/gm),
        ).map(x => x[1]!).sort();

        const master = Object.keys(ElementDerivationSchema.shape).sort();

        expect(
            mirrored,
            'The WallTypes.ts mirror has drifted from ElementDerivationSchema. Update the MIRROR '
            + '(WallTypes.ts) — not this test — so the persisted record and the runtime type are '
            + 'the same set of fields. A field on one and not the other round-trips as undefined, '
            + 'silently.',
        ).toEqual(master);

        // And the master is where the rationale lives, so it must still be findable.
        expect(read(DERIVATION_SCHEMA)).toContain('EDGE_INDEX_UNRECOVERABLE');
    });
});
