// DimensionStore unit tests — backfills the S31 supplement deliverable
// alongside the S35 host wiring.
//
// Verifies:
//   • Inherited Store<DimensionString> roundtrip (applyPatch / getState).
//   • Per-view settings: get / set / clear, idempotent on equal value.
//   • Overrides: get / set / clear, idempotent on equal value, finite-check.
//   • Independent listener buses for dims / overrides / view-settings.
//   • `clear()` wipes all three maps and fires one notification per bus.

import { describe, expect, it } from 'vitest';
import {
  DimensionStore,
  type DimensionViewSettings,
} from '../src/DimensionStore.js';
import type { DimensionString } from '@pryzm/schemas/annotation/dimension';

// ── Tiny fixture helpers ──────────────────────────────────────────────────

function makeDim(id: string, overrides: Partial<DimensionString> = {}): DimensionString {
  return {
    id: id as DimensionString['id'],
    kind: 'linear-element',
    references: [
      { elementId: 'wall_a' as never, anchor: 'start' },
      { elementId: 'wall_a' as never, anchor: 'end' },
    ],
    orientation: 'horizontal',
    offsetMm: 8,
    viewId: 'view_001' as DimensionString['viewId'],
    override: null,
    textStyleRef: 'default-dim',
    witnessLines: { offset: 1, extension: 2, weight: 0.18 },
    arrowheads: 'tick',
    isAutoGenerated: false,
    ...overrides,
  };
}

const SETTINGS_PER_ELEMENT: DimensionViewSettings = {
  autoDimensionMode: 'per-element',
  autoDimensionOffset: 200,
  showOverallDimensions: false,
};

// ── Dimensions map (inherited Store behaviour) ────────────────────────────

describe('DimensionStore — dimensions map', () => {
  it('round-trips via applyPatch + getState', () => {
    const s = new DimensionStore();
    expect(s.size()).toBe(0);
    const dim = makeDim('dim-001');
    s.applyPatch([{ op: 'add', path: ['dim-001'], value: dim }]);
    expect(s.size()).toBe(1);
    expect(s.getState().get('dim-001')).toEqual(dim);
  });

  it('emits inherited dirty on dimensions add', () => {
    const s = new DimensionStore();
    let fired = 0;
    const dispose = s.subscribeDirty(() => { fired++; });
    s.applyPatch([{ op: 'add', path: ['dim-001'], value: makeDim('dim-001') }]);
    expect(fired).toBe(1);
    dispose();
  });
});

// ── Overrides map ─────────────────────────────────────────────────────────

describe('DimensionStore — overrides', () => {
  it('set then get returns the value', () => {
    const s = new DimensionStore();
    s.setOverride('dim-001' as DimensionString['id'], 3500);
    expect(s.getOverride('dim-001' as DimensionString['id'])).toBe(3500);
  });

  it('idempotent set with same value does NOT notify', () => {
    const s = new DimensionStore();
    let fired = 0;
    s.subscribeOverridesDirty(() => { fired++; });
    s.setOverride('dim-001' as DimensionString['id'], 3500);
    s.setOverride('dim-001' as DimensionString['id'], 3500);
    expect(fired).toBe(1);
  });

  it('clear removes the entry and notifies', () => {
    const s = new DimensionStore();
    let fired = 0;
    s.subscribeOverridesDirty(() => { fired++; });
    s.setOverride('dim-001' as DimensionString['id'], 3500);
    s.clearOverride('dim-001' as DimensionString['id']);
    expect(s.getOverride('dim-001' as DimensionString['id'])).toBeUndefined();
    expect(fired).toBe(2); // set + clear
  });

  it('throws on non-finite override value', () => {
    const s = new DimensionStore();
    expect(() => s.setOverride('dim-001' as DimensionString['id'], NaN)).toThrow();
    expect(() => s.setOverride('dim-001' as DimensionString['id'], Infinity)).toThrow();
  });

  it('clearOverride is a no-op on an unknown id', () => {
    const s = new DimensionStore();
    let fired = 0;
    s.subscribeOverridesDirty(() => { fired++; });
    s.clearOverride('dim-not-pinned' as DimensionString['id']);
    expect(fired).toBe(0);
  });
});

// ── ViewSettings map ──────────────────────────────────────────────────────

describe('DimensionStore — viewSettings', () => {
  it('round-trips per-view settings', () => {
    const s = new DimensionStore();
    s.setViewSettings('view_001', SETTINGS_PER_ELEMENT);
    const got = s.getViewSettings('view_001');
    expect(got?.autoDimensionMode).toBe('per-element');
    expect(got?.autoDimensionOffset).toBe(200);
  });

  it('idempotent set with shallow-equal value does NOT notify', () => {
    const s = new DimensionStore();
    let fired = 0;
    s.subscribeViewSettingsDirty(() => { fired++; });
    s.setViewSettings('view_001', SETTINGS_PER_ELEMENT);
    s.setViewSettings('view_001', { ...SETTINGS_PER_ELEMENT });
    expect(fired).toBe(1);
  });

  it('mode switch fires a notification', () => {
    const s = new DimensionStore();
    let lastChanged: ReadonlySet<string> | null = null;
    s.subscribeViewSettingsDirty((changed) => { lastChanged = changed; });
    s.setViewSettings('view_001', SETTINGS_PER_ELEMENT);
    s.setViewSettings('view_001', { ...SETTINGS_PER_ELEMENT, autoDimensionMode: 'room-bounding' });
    expect(lastChanged?.has('view_001')).toBe(true);
  });

  it('clearViewSettings removes the entry and notifies', () => {
    const s = new DimensionStore();
    let fired = 0;
    s.subscribeViewSettingsDirty(() => { fired++; });
    s.setViewSettings('view_001', SETTINGS_PER_ELEMENT);
    s.clearViewSettings('view_001');
    expect(s.getViewSettings('view_001')).toBeUndefined();
    expect(fired).toBe(2);
  });

  it('rejects empty viewId', () => {
    const s = new DimensionStore();
    expect(() => s.setViewSettings('', SETTINGS_PER_ELEMENT)).toThrow();
  });

  it('stored entry is frozen — caller mutation does not corrupt store state', () => {
    const s = new DimensionStore();
    s.setViewSettings('view_001', { ...SETTINGS_PER_ELEMENT });
    const stored = s.getViewSettings('view_001')!;
    expect(() => {
      (stored as { autoDimensionMode: string }).autoDimensionMode = 'off';
    }).toThrow();
  });
});

// ── Listener bus independence ─────────────────────────────────────────────

describe('DimensionStore — listener bus independence', () => {
  it('overrides bus and viewSettings bus do not cross-fire', () => {
    const s = new DimensionStore();
    let overrideHits = 0;
    let viewHits = 0;
    s.subscribeOverridesDirty(() => { overrideHits++; });
    s.subscribeViewSettingsDirty(() => { viewHits++; });
    s.setOverride('dim-001' as DimensionString['id'], 1234);
    expect(overrideHits).toBe(1);
    expect(viewHits).toBe(0);
    s.setViewSettings('view_001', SETTINGS_PER_ELEMENT);
    expect(overrideHits).toBe(1);
    expect(viewHits).toBe(1);
  });

  it('clear() resets all three maps and fires each bus once', () => {
    const s = new DimensionStore();
    let dimHits = 0, overrideHits = 0, viewHits = 0;
    s.subscribeDirty(() => { dimHits++; });
    s.subscribeOverridesDirty(() => { overrideHits++; });
    s.subscribeViewSettingsDirty(() => { viewHits++; });

    s.applyPatch([{ op: 'add', path: ['dim-001'], value: makeDim('dim-001') }]);
    s.setOverride('dim-001' as DimensionString['id'], 1234);
    s.setViewSettings('view_001', SETTINGS_PER_ELEMENT);

    s.clear();

    expect(s.size()).toBe(0);
    expect(s.getOverride('dim-001' as DimensionString['id'])).toBeUndefined();
    expect(s.getViewSettings('view_001')).toBeUndefined();
    // 1 add + 1 clear = 2 dim hits.
    expect(dimHits).toBe(2);
    // 1 set + 1 clear = 2 override hits.
    expect(overrideHits).toBe(2);
    // 1 set + 1 clear = 2 view-settings hits.
    expect(viewHits).toBe(2);
  });
});
