/**
 * areaStandards — which measured-area standard PRYZM is reporting under, and
 * what each of its classes can ACTUALLY be measured from today.
 *
 * Layer Affected:  UI — Analysis surface (L7)
 * File:            apps/editor/src/ui/analysis/areaStandards.ts
 * ADR:             ADR-0343 §D.6 (honesty) · §U.3 (the open standard decision)
 * SPEC:            SPEC-ANALYSIS-SURFACE-AND-WIDGETS §4.5
 * Issue log:       L-3640 (this module) · L-3641 (the centreline finding)
 *
 * ═════════════════════════════════════════════════════════════════════════════
 * ⭐ THE MEASUREMENT THAT DECIDED THE SHAPE OF THIS FILE
 * ═════════════════════════════════════════════════════════════════════════════
 * The `gfa-nia` refusal card lists three missing things, and its THIRD reads:
 * *"Wall-centreline vs internal-face measurement. The standards differ, and the
 * difference is several percent on a real building."* It is written as an OPEN
 * QUESTION. It is not one — it has an answer, and the answer was sitting in the
 * geometry kernel the whole time.
 *
 * ⛔ MEASURED 2026-08-22, C01 §6 rule 6 (cite the command):
 *     grep -n "centerline" packages/geometry-kernel/src/producers/room.ts
 *   :59  "Wall ids whose CENTERLINE edge contributed to the boundary."
 *   :64  "Half-edge graph from wall CENTERLINES"
 *
 * Every `room.area` in this product is the area enclosed by the WALL
 * CENTRELINES. That is an exact measurement of a real thing — and it is NOT the
 * plane any published standard measures on:
 *
 *   SIA 416 NGF, IPMS 3, RICS NIA  → the INTERNAL dominant face  (centreline OVERSTATES)
 *   SIA 416 GF/BGF, IPMS 1, GEA    → the EXTERNAL face           (centreline UNDERSTATES)
 *
 * So the honest product is NOT "call the centreline sum GFA and move on". It is:
 * report the centreline figure AS the centreline figure, name every class of the
 * selected standard, and mark each one measured or not with the reason. The sign
 * of the error is KNOWN; that is worth far more than a plausible number.
 *
 * ═════════════════════════════════════════════════════════════════════════════
 * ⭐ WHICH STANDARD IS THE DEFAULT, AND WHY IT IS NOT SETTLED BY THE COUNT
 * ═════════════════════════════════════════════════════════════════════════════
 * The brief said: adopt SIA 416 as the default ONLY if it is already the
 * most-referenced standard in the repo; otherwise adopt the one the code leans
 * on. Both halves were measured, and the second one has no referent:
 *
 *   grep -rniE "\bSIA[ -]?416\b"  → 16 · IPMS → 4 · RICS (word-boundary) → 13
 *
 * ⚠ SIA leads — but EVERY ONE of those 16 is this product SAYING IT DOES NOT
 * HAVE IT: the `sia-416` refusal card, ADR-0343, the SPEC row, and a test. A
 * count generated by a refusal card is not the repo "leaning on" a standard; it
 * is the repo describing a hole, and reading it as adoption is the
 * [[confident-register-rows-are-the-wrong-ones]] trap exactly.
 *
 * ⛔ AND THE OTHER HALF IS EMPTY. There is NO standard the code leans on. The
 * only implemented area rule in the product is
 * `ScheduleExtractor.ts:567` — `actualGFA = Σ rooms[].computed.area` — which is
 * the centreline sum under a label ("GFA") that no standard would recognise for
 * it. That is not "leaning on RICS"; it is one line of arithmetic wearing an
 * acronym.
 *
 * So the default is SIA 416 on the brief's tie-break, and it is recorded here
 * that the count did not settle it — the count is self-referential and the
 * alternative was empty. It is SWITCHABLE, and switching is the point: the same
 * building has several different, all-correct areas, and this surface's job is
 * to make that visible rather than to pick one and hide the rest.
 *
 * L7 file. Frozen tables + module state. No THREE (P2), no rAF (P3), no
 * `(window as any)` (P4), no store writes (P6) — it reads no store at all;
 * `analysisReadModel.ts` owns every store read on this surface.
 */

import type { CoverageRow, CoverageState } from './AnalysisTypes';

/** The plane a class is measured on. The whole disagreement lives here. */
export type MeasurementPlane =
  /** Inner face of the enclosing construction. */
  | 'internal-face'
  /** Outer face of the external envelope. */
  | 'external-face'
  /** Wall centreline — what PRYZM's room producer actually uses. */
  | 'centreline'
  /** A derived ratio or a count, not an area measured on a plane. */
  | 'derived';

export type AreaStandardId = 'sia-416' | 'ipms' | 'rics-comp' | 'pryzm-centreline';

export interface AreaClassDef {
  /** The standard's own code — SIA writes GF/NGF/KF, IPMS writes IPMS 1..3. */
  readonly code: string;
  readonly label: string;
  readonly plane: MeasurementPlane;
  /**
   * ⛔ ADOPTED VERBATIM from the take-off's `CoverageState` (ADR-0343 §D.6).
   * A second three-state enum with slightly different names would be two
   * honesty vocabularies, which is zero honesty vocabularies.
   */
  readonly state: CoverageState;
  /** WHY, in words. A `NOT_MEASURED` class with no reason is a blank, not a fact. */
  readonly note: string;
}

export interface AreaStandardDef {
  readonly id: AreaStandardId;
  readonly label: string;
  /** Where it has force. A ratio means something different under another one. */
  readonly jurisdiction: string;
  readonly classes: readonly AreaClassDef[];
  /**
   * The one sentence the card prints on its face about THIS standard's relation
   * to what PRYZM can actually measure.
   */
  readonly verdict: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// The shared reason. Written ONCE and referenced, because it is the same fact
// four times and four hand-written copies would drift.
// ─────────────────────────────────────────────────────────────────────────────

const CENTRELINE_NOTE =
  'PRYZM measures a room polygon on the WALL CENTRELINE — `geometry-kernel/src/producers/room.ts:64`, ' +
  '"Half-edge graph from wall centerlines". This class is measured on a different plane, so the figure ' +
  'this product can produce is not this class. The SIGN of the error is known and the surface states it; ' +
  'the magnitude is bracketed per storey from the bounding walls\' thickness, not guessed.';

const NEEDS_SPACE_CLASS =
  'Needs a per-space classification that no room in PRYZM carries. Mapping the room-type vocabulary onto ' +
  'this class is a NORMATIVE decision that must be authored and reviewed, not a lookup — the same ' +
  'reasoning ADR-0343 §U.3 left open.';

const NEEDS_CONSTRUCTION_FOOTPRINT =
  'Needs the wall, shaft and column FOOTPRINT polygons per storey. The wall records exist; their ' +
  'per-storey swept footprint is not projected anywhere a reader could sum it.';

// ─────────────────────────────────────────────────────────────────────────────

const SIA_416: AreaStandardDef = {
  id: 'sia-416',
  label: 'SIA 416 (2003)',
  jurisdiction: 'Switzerland — SIA. The ratio gauges mean something else elsewhere.',
  verdict:
    'PRYZM can measure NONE of SIA 416\'s classes today, and the blocker is not the standard: it is that ' +
    'every area this product holds is measured on the wall centreline, and SIA measures on the inner and ' +
    'outer faces. The centreline sum is reported beside this table AS a centreline sum.',
  classes: Object.freeze([
    { code: 'GF',  label: 'Geschossfläche (gross storey area)', plane: 'external-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} GF also needs the external envelope footprint, which is not projected.` },
    { code: 'KF',  label: 'Konstruktionsfläche (construction area)', plane: 'external-face', state: 'NOT_MEASURED',
      note: NEEDS_CONSTRUCTION_FOOTPRINT },
    { code: 'NGF', label: 'Nettogeschossfläche (net storey area)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: CENTRELINE_NOTE },
    { code: 'HNF', label: 'Hauptnutzfläche (primary usable area)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_SPACE_CLASS}` },
    { code: 'NNF', label: 'Nebennutzfläche (ancillary usable area)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_SPACE_CLASS}` },
    { code: 'VF',  label: 'Verkehrsfläche (circulation area)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_SPACE_CLASS} Corridors ARE rooms in PRYZM, so the population exists — its classification does not.` },
    { code: 'FF',  label: 'Funktionsfläche (services area)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_SPACE_CLASS} Plant rooms are not distinguished from other rooms.` },
    { code: 'HNF:NGF', label: 'Efficiency ratio HNF : NGF', plane: 'derived', state: 'NOT_MEASURED',
      note: 'ADR-0343 §D.6 H3 — a ratio needs BOTH operands MEASURED. Neither of these is. Drawing it at zero would put a confident dial on screen reporting a standard this product has never implemented.' },
  ]),
};

const IPMS: AreaStandardDef = {
  id: 'ipms',
  label: 'IPMS for Residential/Office Buildings',
  jurisdiction: 'International — IPMSC. Adopted into RICS since the 2015 edition.',
  verdict:
    'Same blocker as SIA, one class further out: IPMS additionally requires balconies, terraces and ' +
    'covered galleries to be measured and reported SEPARATELY, and PRYZM has no model that distinguishes ' +
    'an external covered space from an internal room.',
  classes: Object.freeze([
    { code: 'IPMS 1', label: 'Whole building, external face, per storey', plane: 'external-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} IPMS 1 also requires external covered areas be included and stated separately; nothing marks a space as external.` },
    { code: 'IPMS 2', label: 'Internal dominant face, all interior', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} "Internal dominant face" is itself a rule about glazing proportion per wall segment, which needs a per-segment façade read.` },
    { code: 'IPMS 3', label: 'Occupier area (exclusive occupation)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_SPACE_CLASS} It also needs the OCCUPIER, i.e. a tenancy or unit entity — the same missing entity the unit-mix card names.` },
    { code: 'Limited use', label: 'Limited-use areas, reported apart', plane: 'internal-face', state: 'NOT_MEASURED',
      note: 'Needs a headroom / usability rule per space. Room records carry a height but no headroom classification, and no space is flagged limited-use.' },
  ]),
};

const RICS_COMP: AreaStandardDef = {
  id: 'rics-comp',
  label: 'RICS Code of Measuring Practice (6th ed.)',
  jurisdiction: 'UK — RICS. GEA/GIA/NIA are the planning and valuation vocabulary here.',
  verdict:
    'The closest of the three to something PRYZM could reach, because GIA and NIA are both single-plane ' +
    'sums over spaces — but both are measured to a face, and PRYZM measures to a centreline.',
  classes: Object.freeze([
    { code: 'GEA', label: 'Gross External Area', plane: 'external-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_CONSTRUCTION_FOOTPRINT}` },
    { code: 'GIA', label: 'Gross Internal Area', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} GIA includes internal walls and columns, which the room polygons exclude by construction — the room graph's faces stop at the walls.` },
    { code: 'NIA', label: 'Net Internal Area (usable)', plane: 'internal-face', state: 'NOT_MEASURED',
      note: `${CENTRELINE_NOTE} ${NEEDS_SPACE_CLASS} NIA excludes stairs, lifts, plant and WCs serving the building — an exclusion list, per space.` },
    { code: 'GEA:NIA', label: 'Efficiency ratio GEA : NIA', plane: 'derived', state: 'NOT_MEASURED',
      note: 'H3 again — both operands unmeasured. `targetGFA` exists in the schedule extractor and is a TARGET from the brief; rendering it as an operand would be inventing the measurement from the requirement.' },
  ]),
};

/**
 * The fourth entry, and it is NOT a standard — it is what PRYZM actually does.
 *
 * ⭐ IT IS IN THE PICKER ON PURPOSE. The other three are all NOT_MEASURED, and a
 * picker whose every option refuses would read as a broken control rather than
 * as a boundary. This option is the one that MEASURES, it is labelled as
 * non-normative in its own name and jurisdiction line, and choosing it is how a
 * reader sees the real figure with its real basis instead of an acronym it does
 * not satisfy.
 */
const PRYZM_CENTRELINE: AreaStandardDef = {
  id: 'pryzm-centreline',
  label: 'PRYZM room-boundary sum (NOT a published standard)',
  jurisdiction:
    '⛔ NONE. This is not IPMS, RICS or SIA and must never be quoted as any of them. It is the arithmetic ' +
    'this product performs, named honestly so it can be checked.',
  verdict:
    'The only area class this build can measure. It is the area enclosed by the WALL CENTRELINES of each ' +
    'room, summed per storey — exact for that definition, and the definition is stated on every figure. ' +
    'Against any published standard it OVERSTATES the net classes and UNDERSTATES the gross ones.',
  classes: Object.freeze([
    { code: 'RCA', label: 'Room centreline area, per storey', plane: 'centreline', state: 'MEASURED',
      note: 'Σ of each room\'s cached polygon area (`Room.area`, produced by `produceRoom` from the wall-centreline half-edge graph). Every contributing room is click-through selectable.' },
    { code: 'ROOMS', label: 'Rooms counted per storey', plane: 'derived', state: 'MEASURED',
      note: 'A count, not an area. Reported beside the sum so a storey with one huge room and a storey with twenty small ones do not read alike.' },
    { code: 'Δface', label: 'Centreline → internal-face correction, BRACKETED', plane: 'derived', state: 'COUNTED_ONLY',
      note: 'Reported as an INTERVAL, never a point value. Per room the true correction is Σ(edge length × that edge\'s wall thickness ÷ 2); PRYZM caches the room PERIMETER but not per-edge attribution, so the bracket uses the thinnest and thickest bounding wall. It ignores corner effects of order t², a few hundredths of m² per corner at 0.2 m walls. It is a bound, not an estimate.' },
  ]),
};

export const AREA_STANDARDS: readonly AreaStandardDef[] = Object.freeze([
  SIA_416,
  IPMS,
  RICS_COMP,
  PRYZM_CENTRELINE,
]);

/**
 * The default. See the header: the count that nominally chose it is
 * self-referential, and the alternative the brief offered ("the one the code
 * already leans on") has no referent. Recorded rather than presented as settled.
 */
export const DEFAULT_AREA_STANDARD: AreaStandardId = 'sia-416';

let _standard: AreaStandardId = DEFAULT_AREA_STANDARD;

export function areaStandard(): AreaStandardDef {
  return AREA_STANDARDS.find((s) => s.id === _standard) ?? SIA_416;
}

export function setAreaStandard(id: AreaStandardId): void {
  if (AREA_STANDARDS.some((s) => s.id === id)) _standard = id;
}

export function areaStandardById(id: string): AreaStandardDef | undefined {
  return AREA_STANDARDS.find((s) => s.id === id);
}

/**
 * The selected standard's class table, in the surface's coverage vocabulary.
 *
 * ⛔ The `family` column carries the standard's OWN code and its plane, so a
 * reader can see at a glance that seven rows say `internal-face` while the one
 * measured row says `centreline`. That single column is the whole argument of
 * this card, and it is data rather than prose.
 */
export function areaCoverageRows(std: AreaStandardDef = areaStandard()): readonly CoverageRow[] {
  return std.classes.map((c) => ({
    family: `${c.code} — ${c.label}  ·  plane: ${c.plane}`,
    state: c.state,
    note: c.note,
  }));
}
