/**
 * FurnitureCategoryDataA.ts
 *
 * Furniture registry data (Part A): Sofas, Chairs, Tables, Beds,
 * Wardrobes, Bedroom, Outdoor categories.
 * Extracted from FurnitureCategoryRegistry.ts (WS-B S85-WIRE).
 */

import type { FurnitureCategoryDescriptor } from './FurnitureCategoryTypes';

// FurnitureMaterial and FurnitureType are used inline in the data via
// TypeScript structural typing — imported so type-checking is enforced.
import type { FurnitureMaterial, FurnitureType } from '@pryzm/geometry-furniture';

// Suppress "declared but not used" for type-only imports used structurally.
void (undefined as unknown as FurnitureMaterial);
void (undefined as unknown as FurnitureType);

export const CATEGORIES_A: readonly FurnitureCategoryDescriptor[] = [
    {
        id: 'sofas',
        label: 'Sofas',
        description: 'Sofas, armchairs, sectionals',
        items: [
            {
                type: 'corner_sofa',
                label: 'Corner Sofa',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.9, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'white_corner_sofa',
                label: 'White Corner Sofa',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.9, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#e8e2d5',
            },
            {
                type: 'white_sofa_1seat',
                label: 'White Sofa 1-Seat',
                // ~1.05 wide × 0.95 deep × 0.85 tall — wider than tall so the
                // silhouette reads as an armchair, not a cubic stool.
                defaultDimensions: { width: 1.05, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#e8e2d5',
            },
            {
                type: 'white_sofa_2seat',
                label: 'White Sofa 2-Seat',
                defaultDimensions: { width: 1.85, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#e8e2d5',
            },
            {
                type: 'white_sofa_3seat',
                label: 'White Sofa 3-Seat',
                defaultDimensions: { width: 2.55, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#e8e2d5',
            },

            // ── Sofa colour variants (3 colours × 3 seat counts = 9 cards) ──
            // All routed to WhiteSofaBuilder (same construction logic as
            // CornerSofaBuilder: base, individual cushions, structural back,
            // back cushions, both arms, four legs).  Colour is set per card
            // via defaultColor and forwarded by FurnitureDragDropHandler.
            // Charcoal grey
            {
                type: 'sofa_1seat',
                label: 'Sofa 1-Seat — Charcoal',
                defaultDimensions: { width: 1.05, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#4a4a4a',
            },
            {
                type: 'sofa_2seat',
                label: 'Sofa 2-Seat — Charcoal',
                defaultDimensions: { width: 1.85, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#4a4a4a',
            },
            {
                type: 'sofa_3seat',
                label: 'Sofa 3-Seat — Charcoal',
                defaultDimensions: { width: 2.55, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#4a4a4a',
            },
            // Beige / sand
            {
                type: 'sofa_1seat',
                label: 'Sofa 1-Seat — Beige',
                defaultDimensions: { width: 1.05, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#c5b09a',
            },
            {
                type: 'sofa_2seat',
                label: 'Sofa 2-Seat — Beige',
                defaultDimensions: { width: 1.85, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#c5b09a',
            },
            {
                type: 'sofa_3seat',
                label: 'Sofa 3-Seat — Beige',
                defaultDimensions: { width: 2.55, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#c5b09a',
            },
            // Navy blue
            {
                type: 'sofa_1seat',
                label: 'Sofa 1-Seat — Navy',
                defaultDimensions: { width: 1.05, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#2e3a4f',
            },
            {
                type: 'sofa_2seat',
                label: 'Sofa 2-Seat — Navy',
                defaultDimensions: { width: 1.85, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#2e3a4f',
            },
            {
                type: 'sofa_3seat',
                label: 'Sofa 3-Seat — Navy',
                defaultDimensions: { width: 2.55, length: 0.95, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                defaultColor: '#2e3a4f',
            },


            // ── Barcelona-style sofa family (black leather + chrome inox) ────
            // Same palette and X-frame language as the Barcelona lounge chair
            // and ottoman. Depth held at 0.85 m, height 0.76 m; width grows
            // by seat count. Corner unit is an L-shape sharing the same arm.
            {
                type: 'barcelona_sofa_1seat',
                label: 'Barcelona Sofa 1-Seat',
                defaultDimensions: { width: 1.10, length: 0.85, height: 0.76, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'barcelona_sofa_2seat',
                label: 'Barcelona Sofa 2-Seat',
                defaultDimensions: { width: 1.85, length: 0.85, height: 0.76, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'barcelona_sofa_3seat',
                label: 'Barcelona Sofa 3-Seat',
                defaultDimensions: { width: 2.60, length: 0.85, height: 0.76, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'barcelona_corner_sofa',
                label: 'Barcelona Corner Sofa',
                defaultDimensions: { width: 2.60, length: 1.85, height: 0.76, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },

            {
                type: 'kave_sofa',
                label: 'Sofa (Kave)',
                defaultDimensions: { width: 2.5, length: 1.5, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Sofas/sofa/model.glb',
                thumbnailPath: '/items/Sofas/sofa/thumbnail.webp',
            },
            {
                type: 'kave_bean_bag',
                label: 'Bean Bag',
                defaultDimensions: { width: 1.0, length: 1.0, height: 0.7, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Sofas/bean-bag/model.glb',
                thumbnailPath: '/items/Sofas/bean-bag/thumbnail.webp',
            },
            {
                type: 'kave_lounge_chair',
                label: 'Lounge Chair',
                defaultDimensions: { width: 1.0, length: 1.5, height: 1.1, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Sofas/lounge-chair/model.glb',
                thumbnailPath: '/items/Sofas/lounge-chair/thumbnail.webp',
            },
            {
                type: 'kave_livingroom_chair',
                label: 'Living Room Chair',
                defaultDimensions: { width: 1.5, length: 1.5, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Sofas/livingroom-chair/model.glb',
                thumbnailPath: '/items/Sofas/livingroom-chair/thumbnail.webp',
            },
            {
                type: 'wip_sofa_48',
                label: 'Sofa 48',
                defaultDimensions: { width: 2.5, length: 1.5, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Sofas/sofa-48/model.glb',
                thumbnailPath: '/items/Sofas/sofa-48/thumbnail.webp',
            },
            {
                type: 'wip_sofa',
                label: 'Sofa Classic',
                defaultDimensions: { width: 2.2, length: 1.0, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Sofas/sofa-wip/model.glb',
                thumbnailPath: '/items/Sofas/sofa-wip/thumbnail.webp',
            },
        ],
    },
    {
        id: 'chairs',
        label: 'Chairs',
        description: 'Dining, office, accent chairs',
        items: [
            {
                type: 'chair',
                label: 'Chair',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'dining_chair',
                label: 'Dining Chair',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'chair_oak_solid',
                label: 'Oak Chair Solid',
                defaultDimensions: { width: 0.54, length: 0.56, height: 0.86, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'chair_oak_slim',
                label: 'Oak Chair Slim',
                defaultDimensions: { width: 0.52, length: 0.55, height: 0.9, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'chair_textile_wood_arm',
                label: 'Textile Wood Armchair',
                defaultDimensions: { width: 0.68, length: 0.62, height: 0.82, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_oak_curved_uph',
                label: 'Oak Curved Upholstered Chair',
                defaultDimensions: { width: 0.54, length: 0.56, height: 0.84, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_3leg_terracotta',
                label: 'Terracotta 3-Leg Curved Chair',
                defaultDimensions: { width: 0.62, length: 0.62, height: 0.80, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_3leg_obejita_black',
                label: 'Obejita 3-Leg Black-Metal Chair',
                defaultDimensions: { width: 0.62, length: 0.62, height: 0.80, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_4leg_obejita_wood',
                label: 'Obejita 4-Leg Wood Tub Chair',
                defaultDimensions: { width: 0.78, length: 0.78, height: 0.78, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_barcelona_black',
                label: 'Barcelona Lounge Chair',
                defaultDimensions: { width: 0.78, length: 0.78, height: 0.76, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_cesca_tan',
                label: 'Cesca Cantilever Chair (Tan)',
                defaultDimensions: { width: 0.50, length: 0.55, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'chair_barcelona_ottoman_black',
                label: 'Barcelona Ottoman',
                defaultDimensions: { width: 0.62, length: 0.55, height: 0.40, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'kave_dining_chair',
                label: 'Dining Chair (Kave)',
                defaultDimensions: { width: 0.5, length: 0.5, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Chairs/dining-chair/model.glb',
                thumbnailPath: '/items/Chairs/dining-chair/thumbnail.webp',
            },
            {
                type: 'kave_office_chair',
                label: 'Office Chair',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Chairs/office-chair/model.glb',
                thumbnailPath: '/items/Chairs/office-chair/thumbnail.webp',
            },
            {
                type: 'kave_stool',
                label: 'Stool',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Chairs/stool/model.glb',
                thumbnailPath: '/items/Chairs/stool/thumbnail.webp',
            },
            {
                type: 'wip_chair_glb',
                label: 'Chair',
                defaultDimensions: { width: 0.7, length: 0.7, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Chairs/chair-glb/model.glb',
                thumbnailPath: '/items/Chairs/chair-glb/thumbnail.webp',
            },
        ],
    },
    {
        id: 'tables',
        label: 'Tables',
        description: 'All table types and desks',
        items: [
            {
                type: 'table',
                label: 'Table',
                defaultDimensions: { width: 1.0, length: 2.0, height: 0.75, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'dining_table',
                label: 'Dining Table',
                defaultDimensions: { width: 1.0, length: 2.0, height: 0.75, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'dining_table_marble_brass',
                label: 'Marble & Brass Dining Table',
                defaultDimensions: { width: 1.20, length: 1.20, height: 0.75, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'coffee_table',
                label: 'Coffee Table',
                defaultDimensions: { width: 1.0, length: 0.6, height: 0.45, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'entrance_table',
                label: 'Entrance Table',
                defaultDimensions: { width: 1.2, length: 0.4, height: 0.75, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'bedside_table',
                label: 'Bedside Table',
                defaultDimensions: { width: 0.5, length: 0.4, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'table_marble_cone',
                label: 'Marble Cone Table',
                defaultDimensions: { width: 1.15, length: 1.15, height: 0.74, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'table_glass_wood_cylinder',
                label: 'Corrugated Glass Table',
                defaultDimensions: { width: 1.1, length: 1.1, height: 0.74, baseOffset: 0.0 },
                defaultMaterial: 'glass',
            },
            {
                type: 'table_wood_double_conic',
                label: 'Double-Conic Oak Table',
                defaultDimensions: { width: 1.2, length: 1.2, height: 0.75, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'table_wood_4leg',
                label: 'Four-Leg Oak Table',
                defaultDimensions: { width: 1.6, length: 0.9, height: 0.75, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'table_ceramic_curve',
                label: 'Curved Ceramic Table',
                defaultDimensions: { width: 1.35, length: 0.85, height: 0.74, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'kave_coffee_table',
                label: 'Coffee Table (Kave)',
                defaultDimensions: { width: 2.0, length: 1.5, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Tables/coffee-table/model.glb',
                thumbnailPath: '/items/Tables/coffee-table/thumbnail.webp',
            },
            {
                type: 'kave_dining_table',
                label: 'Dining Table (Kave)',
                defaultDimensions: { width: 2.5, length: 1.0, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Tables/dining-table/model.glb',
                thumbnailPath: '/items/Tables/dining-table/thumbnail.webp',
            },
            {
                type: 'kave_office_table',
                label: 'Office Table',
                defaultDimensions: { width: 2.0, length: 1.0, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Tables/office-table/model.glb',
                thumbnailPath: '/items/Tables/office-table/thumbnail.webp',
            },
            {
                type: 'kave_tv_stand',
                label: 'TV Stand',
                defaultDimensions: { width: 2.0, length: 0.5, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Tables/tv-stand/model.glb',
                thumbnailPath: '/items/Tables/tv-stand/thumbnail.webp',
            },
            {
                type: 'kave_bedside_table',
                label: 'Bedside Table (Kave)',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Tables/bedside-table/model.glb',
                thumbnailPath: '/items/Tables/bedside-table/thumbnail.webp',
            },
            {
                type: 'wip_coffee_table_avarta',
                label: 'Coffee Table Avarta',
                defaultDimensions: { width: 1.2, length: 0.6, height: 0.45, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Tables/coffee-table-avarta/model.glb',
                thumbnailPath: '/items/Tables/coffee-table-avarta/thumbnail.webp',
            },
        ],
    },
    {
        id: 'beds',
        label: 'Beds',
        description: 'Beds and bed frames',
        items: [
            {
                type: 'bed',
                label: 'Bed',
                defaultDimensions: { width: 1.8, length: 2.0, height: 1.0, baseOffset: 0.2 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'kave_double_bed',
                label: 'Double Bed',
                defaultDimensions: { width: 2.0, length: 2.5, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Bedroom/double-bed/model.glb',
                thumbnailPath: '/items/Bedroom/double-bed/thumbnail.webp',
            },
            {
                type: 'kave_single_bed',
                label: 'Single Bed',
                defaultDimensions: { width: 1.5, length: 2.5, height: 0.7, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Bedroom/single-bed/model.glb',
                thumbnailPath: '/items/Bedroom/single-bed/thumbnail.webp',
            },
            {
                type: 'kave_bunkbed',
                label: 'Bunk Bed',
                defaultDimensions: { width: 2.0, length: 1.5, height: 1.6, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/bunkbed/model.glb',
                thumbnailPath: '/items/Bedroom/bunkbed/thumbnail.webp',
            },
            // ── Japanese Bed Collection (parametric fragments — BedEngine) ──
            // No glbPath / thumbnailPath: the drag-drop handler routes these
            // through CreateFurnitureCommand and FurnitureFactory dispatches
            // to JapaneseBedBuilder → BedEngine.  Carousel thumbnails are
            // auto-rendered by FurnitureThumbnailService from the same builder.
            {
                type: 'japanese_platform_bed',
                label: 'Platform Bed (Japanese)',
                defaultDimensions: { width: 1.90, length: 2.35, height: 0.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'japanese_float_bed',
                label: 'Float Bed (Japanese)',
                defaultDimensions: { width: 2.4, length: 2.0, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'japanese_walnut_bed',
                label: 'Walnut Bed (Japanese)',
                defaultDimensions: { width: 2.10, length: 2.60, height: 0.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'nordic_bed',
                label: 'Nordic Bed',
                defaultDimensions: { width: 1.80, length: 2.20, height: 0.50, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'solid_wood_bed',
                label: 'Solid Wood Bed',
                defaultDimensions: { width: 1.75, length: 2.20, height: 0.55, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
        ],
    },
    {
        id: 'wardrobes',
        label: 'Wardrobes',
        description: 'Wardrobes, closets, walk-in cabinets',
        items: [
            {
                type: 'wardrobe',
                label: 'Wardrobe',
                defaultDimensions: { width: 1.0, length: 0.6, height: 2.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'corner_wardrobe',
                label: 'Corner Wardrobe',
                defaultDimensions: { width: 1.0, length: 0.6, height: 2.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'wardrobe_glass_door',
                label: 'Wardrobe Glass Door',
                defaultDimensions: { width: 1.0, length: 0.6, height: 2.4, baseOffset: 0.0 },
                defaultMaterial: 'glass',
            },
            // ── Parametric wardrobe cabinet layouts ──────────────────────────
            {
                type: 'wardrobe_straight',
                label: 'Straight Wardrobe',
                defaultDimensions: { width: 2.40, length: 0.60, height: 2.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/wardrobe-straight.svg',
                parametric: true,
            } as any,
            {
                type: 'wardrobe_l_shape',
                label: 'L-Shape Wardrobe',
                defaultDimensions: { width: 2.40, length: 0.60, height: 2.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/wardrobe-l-shape.svg',
                parametric: true,
            } as any,
            {
                type: 'wardrobe_u_shape',
                label: 'Walk-In (U-Shape)',
                defaultDimensions: { width: 2.40, length: 0.60, height: 2.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/wardrobe-u-shape.svg',
                parametric: true,
            } as any,
            {
                type: 'wardrobe_straight_tall',
                label: 'Straight + Top Module',
                defaultDimensions: { width: 2.40, length: 0.60, height: 2.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/wardrobe-straight.svg',
                parametric: true,
            } as any,
            {
                type: 'wardrobe_l_shape_tall',
                label: 'L-Shape + Top Module',
                defaultDimensions: { width: 2.40, length: 0.60, height: 2.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/wardrobe-l-shape.svg',
                parametric: true,
            } as any,
            {
                type: 'wardrobe_u_shape_tall',
                label: 'Walk-In + Top Module',
                defaultDimensions: { width: 2.40, length: 0.60, height: 2.40, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/wardrobe-u-shape.svg',
                parametric: true,
            } as any,
            {
                type: 'kave_closet',
                label: 'Wardrobe (Kave)',
                defaultDimensions: { width: 2.0, length: 1.0, height: 2.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/closet/model.glb',
                thumbnailPath: '/items/Bedroom/closet/thumbnail.webp',
            },
            {
                type: 'wip_white_wardrobe',
                label: 'White Wardrobe',
                defaultDimensions: { width: 1.5, length: 0.6, height: 2.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/white-wardrobe/model.glb',
                thumbnailPath: '/items/Bedroom/white-wardrobe/thumbnail.webp',
            },
            {
                type: 'kave_storage_closet',
                label: 'Wardrobe',
                defaultDimensions: { width: 2.0, length: 1.0, height: 2.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/closet/model.glb',
                thumbnailPath: '/items/Bedroom/closet/thumbnail.webp',
            },
        ],
    },
    {
        id: 'bedroom',
        label: 'Bedroom',
        description: 'Bedroom accessories — dresser, mirrors',
        items: [
            {
                type: 'kave_dresser',
                label: 'Dresser',
                defaultDimensions: { width: 1.5, length: 1.0, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/dresser/model.glb',
                thumbnailPath: '/items/Bedroom/dresser/thumbnail.webp',
            },
            {
                type: 'kave_round_mirror',
                label: 'Round Mirror',
                defaultDimensions: { width: 1.0, length: 0.1, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'glass',
                glbPath: '/items/Bedroom/round-mirror/model.glb',
                thumbnailPath: '/items/Bedroom/round-mirror/thumbnail.webp',
            },
            {
                type: 'kave_rect_mirror',
                label: 'Rectangular Mirror',
                defaultDimensions: { width: 1.0, length: 0.1, height: 1.5, baseOffset: 0.0 },
                defaultMaterial: 'glass',
                glbPath: '/items/Bedroom/rectangular-mirror/model.glb',
                thumbnailPath: '/items/Bedroom/rectangular-mirror/thumbnail.webp',
            },
        ],
    },
    {
        id: 'outdoor',
        label: 'Outdoor',
        description: 'Garden and terrace furniture',
        items: [
            {
                type: 'kave_sunbed',
                label: 'Sunbed',
                defaultDimensions: { width: 1.0, length: 1.5, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Outdoor/sunbed/model.glb',
                thumbnailPath: '/items/Outdoor/sunbed/thumbnail.webp',
            },
            {
                type: 'kave_patio_umbrella',
                label: 'Patio Umbrella',
                defaultDimensions: { width: 0.5, length: 0.5, height: 3.7, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Outdoor/patio-umbrella/model.glb',
                thumbnailPath: '/items/Outdoor/patio-umbrella/thumbnail.webp',
            },
            {
                type: 'kave_tree',
                label: 'Tree',
                defaultDimensions: { width: 1.0, length: 1.0, height: 5.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/tree/model.glb',
                thumbnailPath: '/items/Outdoor/tree/thumbnail.webp',
            },
            {
                type: 'kave_bush',
                label: 'Bush',
                defaultDimensions: { width: 3.0, length: 1.0, height: 1.1, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/bush/model.glb',
                thumbnailPath: '/items/Outdoor/bush/thumbnail.webp',
            },
            {
                type: 'kave_hedge',
                label: 'Hedge',
                defaultDimensions: { width: 2.0, length: 0.5, height: 1.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/hedge/model.glb',
                thumbnailPath: '/items/Outdoor/hedge/thumbnail.webp',
            },
            {
                type: 'kave_fir_tree',
                label: 'Fir Tree',
                defaultDimensions: { width: 1.0, length: 1.0, height: 5.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/fir-tree/model.glb',
                thumbnailPath: '/items/Outdoor/fir-tree/thumbnail.webp',
            },
            {
                type: 'kave_palm',
                label: 'Palm Tree',
                defaultDimensions: { width: 1.5, length: 1.5, height: 6.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/palm/model.glb',
                thumbnailPath: '/items/Outdoor/palm/thumbnail.webp',
            },
            {
                type: 'kave_fence',
                label: 'Fence',
                defaultDimensions: { width: 2.0, length: 0.1, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/fence/model.glb',
                thumbnailPath: '/items/Outdoor/fence/thumbnail.webp',
            },
            {
                type: 'kave_low_fence',
                label: 'Low Fence',
                defaultDimensions: { width: 2.0, length: 0.1, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/low-fence/model.glb',
                thumbnailPath: '/items/Outdoor/low-fence/thumbnail.webp',
            },
            {
                type: 'kave_medium_fence',
                label: 'Medium Fence',
                defaultDimensions: { width: 2.0, length: 0.1, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/medium-fence/model.glb',
                thumbnailPath: '/items/Outdoor/medium-fence/thumbnail.webp',
            },
            {
                type: 'kave_high_fence',
                label: 'High Fence',
                defaultDimensions: { width: 2.0, length: 0.1, height: 1.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Outdoor/high-fence/model.glb',
                thumbnailPath: '/items/Outdoor/high-fence/thumbnail.webp',
            },
            {
                type: 'kave_hydrant',
                label: 'Fire Hydrant',
                defaultDimensions: { width: 0.4, length: 0.4, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Outdoor/hydrant/model.glb',
                thumbnailPath: '/items/Outdoor/hydrant/thumbnail.webp',
            },
            {
                type: 'kave_parking_spot',
                label: 'Parking Spot',
                defaultDimensions: { width: 2.5, length: 5.0, height: 0.01, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Outdoor/parking-spot/model.glb',
                thumbnailPath: '/items/Outdoor/parking-spot/thumbnail.webp',
            },
            {
                type: 'kave_tesla',
                label: 'Tesla Car',
                defaultDimensions: { width: 2.0, length: 4.7, height: 1.4, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Outdoor/tesla/model.glb',
                thumbnailPath: '/items/Outdoor/tesla/thumbnail.webp',
            },
            // ── Parametric Outdoor Tree Library — 25 species (Arbol T-01..T-25) ──
            // No glbPath: dispatch goes through FurnitureFactory → TreeBuilder
            // → ParametricTreeEngine.create(speciesId).  Plan view is rendered
            // by treePlanSymbolBuilder (TreePlanSymbolBuilder.ts) which mirrors
            // the architectural symbols on the Arbol T-1..T-25 reference plate.
            {
                type: 'arbol_t_01',
                label: 'Arbol T-01 — Generic Deciduous',
                defaultDimensions: { width: 6.0, length: 6.0, height: 8.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_02',
                label: 'Arbol T-02 — Generic Round',
                defaultDimensions: { width: 5.2, length: 5.2, height: 7.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_03',
                label: 'Arbol T-03 — A_CEDRO',
                defaultDimensions: { width: 6.8, length: 6.8, height: 12.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_04',
                label: 'Arbol T-04 — A_GUAYACAN AMARILLO',
                defaultDimensions: { width: 6.0, length: 6.0, height: 9.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_05',
                label: 'Arbol T-05 — A_URAPAN',
                defaultDimensions: { width: 6.4, length: 6.4, height: 10.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_06',
                label: 'Arbol T-06 — A_CIPRES',
                defaultDimensions: { width: 5.6, length: 5.6, height: 10.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_07',
                label: 'Arbol T-07 — A_NOGAL',
                defaultDimensions: { width: 7.2, length: 7.2, height: 11.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_08',
                label: 'Arbol T-08 — A_ALAMO',
                defaultDimensions: { width: 4.8, length: 4.8, height: 14.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_09',
                label: 'Arbol T-09 — A_CASCO DE BUEY',
                defaultDimensions: { width: 6.8, length: 6.8, height: 8.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_10',
                label: 'Arbol T-10 — A_PINO COLOMBIANO',
                defaultDimensions: { width: 2.8, length: 2.8, height: 16.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_11',
                label: 'Arbol T-11 — A_ALISO',
                defaultDimensions: { width: 6.0, length: 6.0, height: 9.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_12',
                label: 'Arbol T-12 — A_TULIPAN AFRICANO',
                defaultDimensions: { width: 6.8, length: 6.8, height: 10.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_13',
                label: 'Arbol T-13 — A_PINO',
                defaultDimensions: { width: 4.0, length: 4.0, height: 12.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_14',
                label: 'Arbol T-14 — A_MOLLE COSTEÑO',
                defaultDimensions: { width: 7.2, length: 7.2, height: 8.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_15',
                label: 'Arbol T-15 — A_MURALLA EXOTICA',
                defaultDimensions: { width: 4.8, length: 4.8, height: 6.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_16',
                label: 'Arbol T-16 — A_TILO',
                defaultDimensions: { width: 6.0, length: 6.0, height: 9.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_17',
                label: 'Arbol T-17 — A_ROBLE',
                defaultDimensions: { width: 7.2, length: 7.2, height: 11.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_18',
                label: 'Arbol T-18 — A_PALMA DE CERA',
                defaultDimensions: { width: 4.4, length: 4.4, height: 18.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_19',
                label: 'Arbol T-19 — A_CEREZO',
                defaultDimensions: { width: 6.0, length: 6.0, height: 7.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_20',
                label: 'Arbol T-20 — A_SANGRE DE GRADO',
                defaultDimensions: { width: 6.4, length: 6.4, height: 9.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_21',
                label: 'Arbol T-21 — A_JACARANDA',
                defaultDimensions: { width: 7.2, length: 7.2, height: 10.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_22',
                label: 'Arbol T-22 — A_PINO CANDELABRO',
                defaultDimensions: { width: 4.8, length: 4.8, height: 12.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_23',
                label: 'Arbol T-23 — A_PALMA CUBANA',
                defaultDimensions: { width: 5.2, length: 5.2, height: 14.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_24',
                label: 'Arbol T-24 — A_FICUS ORNAMENTAL',
                defaultDimensions: { width: 6.0, length: 6.0, height: 8.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
            {
                type: 'arbol_t_25',
                label: 'Arbol T-25 — A_SAUCE',
                defaultDimensions: { width: 6.8, length: 6.8, height: 9.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/parametric-tree.svg',
            },
        ],
    },
];
