/**
 * FurnitureCategoryDataB.ts
 *
 * Furniture registry data (Part B): Decor, Soft Furnishings, Lighting,
 * Kitchen, Bathroom, Storage, Kids, Teens, Pets, Technical categories.
 * Extracted from FurnitureCategoryRegistry.ts (WS-B S85-WIRE).
 */

import type { FurnitureCategoryDescriptor } from './FurnitureCategoryTypes';
import type { FurnitureMaterial, FurnitureType } from '@pryzm/geometry-furniture';

void (undefined as unknown as FurnitureMaterial);
void (undefined as unknown as FurnitureType);

export const CATEGORIES_B: readonly FurnitureCategoryDescriptor[] = [
    {
        id: 'decor',
        label: 'Decor',
        description: 'Plants, chimneys, decorative items',
        items: [
            {
                type: 'chimney',
                label: 'Chimney',
                defaultDimensions: { width: 0.8, length: 0.4, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plant_01',
                label: 'Plant 1',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_02',
                label: 'Plant 2',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_03',
                label: 'Plant 3',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_04',
                label: 'Plant 4',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_05',
                label: 'Plant 5',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_06',
                label: 'Plant 6',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_07',
                label: 'Plant 7',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'plant_08',
                label: 'Plant 8',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
            },
            {
                type: 'kave_indoor_plant',
                label: 'Indoor Plant',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.7, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/indoor-plant/model.glb',
                thumbnailPath: '/items/Decor/indoor-plant/thumbnail.webp',
            },
            {
                type: 'kave_cactus',
                label: 'Cactus',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/cactus/model.glb',
                thumbnailPath: '/items/Decor/cactus/thumbnail.webp',
            },
            {
                type: 'kave_picture',
                label: 'Wall Art / Picture',
                defaultDimensions: { width: 2.0, length: 0.2, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/picture/model.glb',
                thumbnailPath: '/items/Decor/picture/thumbnail.webp',
            },
            {
                type: 'kave_wall_art_06',
                label: 'Wall Art',
                defaultDimensions: { width: 1.5, length: 0.1, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/wall-art-06/model.glb',
                // thumbnailPath omitted — bundled webp has a green background
                // that doesn't match the rest of the panel; fall back to the
                // white-backed SVG icon instead.
            },
            {
                type: 'kave_rect_carpet',
                label: 'Rectangular Carpet',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Decor/rectangular-carpet/model.glb',
                thumbnailPath: '/items/Decor/rectangular-carpet/thumbnail.webp',
            },
            {
                type: 'kave_round_carpet',
                label: 'Round Carpet',
                defaultDimensions: { width: 2.5, length: 2.5, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Decor/round-carpet/model.glb',
                thumbnailPath: '/items/Decor/round-carpet/thumbnail.webp',
            },
            {
                type: 'kave_guitar',
                label: 'Guitar',
                defaultDimensions: { width: 0.5, length: 0.5, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/guitar/model.glb',
                thumbnailPath: '/items/Decor/guitar/thumbnail.webp',
            },
            {
                type: 'kave_piano',
                label: 'Piano',
                defaultDimensions: { width: 2.0, length: 1.0, height: 1.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/piano/model.glb',
                thumbnailPath: '/items/Decor/piano/thumbnail.webp',
            },
            {
                type: 'kave_wine_bottle',
                label: 'Wine Bottle',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'glass',
                glbPath: '/items/Decor/wine-bottle/model.glb',
                thumbnailPath: '/items/Decor/wine-bottle/thumbnail.webp',
            },
            {
                type: 'kave_books',
                label: 'Books',
                defaultDimensions: { width: 0.8, length: 0.3, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Decor/books/model.glb',
                thumbnailPath: '/items/Decor/books/thumbnail.webp',
            },
            {
                type: 'kave_small_indoor_plant',
                label: 'Small Indoor Plant',
                defaultDimensions: { width: 0.4, length: 0.4, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/small-indoor-plant/model.glb',
                thumbnailPath: '/items/Decor/small-indoor-plant/thumbnail.webp',
            },
            {
                type: 'kave_flat_screen_tv',
                label: 'Flat Screen TV',
                defaultDimensions: { width: 1.5, length: 0.1, height: 0.9, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Decor/flat-screen-tv/model.glb',
                thumbnailPath: '/items/Decor/flat-screen-tv/thumbnail.webp',
            },
            {
                type: 'kave_television',
                label: 'Television',
                defaultDimensions: { width: 1.2, length: 0.5, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Decor/television/model.glb',
                thumbnailPath: '/items/Decor/television/thumbnail.webp',
            },
            {
                type: 'kave_easel',
                label: 'Easel',
                defaultDimensions: { width: 0.6, length: 0.5, height: 1.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/easel/model.glb',
                thumbnailPath: '/items/Decor/easel/thumbnail.webp',
            },
            {
                type: 'kave_trash_bin',
                label: 'Trash Bin',
                defaultDimensions: { width: 0.4, length: 0.4, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Decor/trash-bin/model.glb',
                thumbnailPath: '/items/Decor/trash-bin/thumbnail.webp',
            },
            {
                type: 'kave_computer',
                label: 'Computer',
                defaultDimensions: { width: 0.6, length: 0.5, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Decor/computer/model.glb',
                thumbnailPath: '/items/Decor/computer/thumbnail.webp',
            },
            {
                type: 'kave_fruits',
                label: 'Fruits',
                defaultDimensions: { width: 0.4, length: 0.4, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/fruits/model.glb',
                thumbnailPath: '/items/Decor/fruits/thumbnail.webp',
            },
        ],
    },
    {
        id: 'soft_furnishings',
        label: 'Soft Furnishings',
        description: 'Curtains, rugs, cushions',
        items: [
            {
                type: 'parametric_chevron_carpet',
                label: 'Chevron Carpet',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.004, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'parametric_patchwork_carpet',
                label: 'Patchwork Carpet',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.004, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'parametric_stripe_carpet',
                label: 'Stripe Carpet',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.004, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'kave_soft_rect_carpet',
                label: 'Rectangular Rug',
                defaultDimensions: { width: 3.0, length: 2.0, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Decor/rectangular-carpet/model.glb',
                thumbnailPath: '/items/Decor/rectangular-carpet/thumbnail.webp',
            },
            {
                type: 'kave_soft_round_carpet',
                label: 'Round Rug',
                defaultDimensions: { width: 2.5, length: 2.5, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Decor/round-carpet/model.glb',
                thumbnailPath: '/items/Decor/round-carpet/thumbnail.webp',
            },
            {
                type: 'kave_shower_rug',
                label: 'Shower Rug',
                defaultDimensions: { width: 1.0, length: 0.5, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Soft Furnishings/shower-rug/model.glb',
                thumbnailPath: '/items/Soft Furnishings/shower-rug/thumbnail.webp',
            },
        ],
    },
    {
        id: 'lighting',
        label: 'Lighting',
        description: 'Lamps and lighting fixtures',
        items: [
            {
                type: 'lamp',
                label: 'Lamp',
                defaultDimensions: { width: 0.3, length: 0.3, height: 1.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'kave_ceiling_lamp',
                label: 'Ceiling Lamp',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/ceiling-lamp/model.glb',
                thumbnailPath: '/items/Lighting/ceiling-lamp/thumbnail.webp',
            },
            {
                type: 'kave_ceiling_light',
                label: 'Ceiling Light',
                defaultDimensions: { width: 1.0, length: 1.0, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/ceiling-light/model.glb',
                thumbnailPath: '/items/Lighting/ceiling-light/thumbnail.webp',
            },
            {
                type: 'kave_circular_ceiling_light',
                label: 'Circular Ceiling Light',
                defaultDimensions: { width: 1.0, length: 1.0, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/circular-ceiling-light/model.glb',
                thumbnailPath: '/items/Lighting/circular-ceiling-light/thumbnail.webp',
            },
            {
                type: 'kave_rect_ceiling_light',
                label: 'Rectangular Ceiling Light',
                defaultDimensions: { width: 2.0, length: 1.0, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/rectangular-ceiling-light/model.glb',
                thumbnailPath: '/items/Lighting/rectangular-ceiling-light/thumbnail.webp',
            },
            {
                type: 'kave_recessed_light',
                label: 'Recessed Light',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/recessed-light/model.glb',
                thumbnailPath: '/items/Lighting/recessed-light/thumbnail.webp',
            },
            {
                type: 'kave_floor_lamp',
                label: 'Floor Lamp',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.9, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/floor-lamp/model.glb',
                thumbnailPath: '/items/Lighting/floor-lamp/thumbnail.webp',
            },
            {
                type: 'kave_table_lamp',
                label: 'Table Lamp',
                defaultDimensions: { width: 0.5, length: 1.0, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/table-lamp/model.glb',
                thumbnailPath: '/items/Lighting/table-lamp/thumbnail.webp',
            },
            {
                type: 'kave_ceiling_fan',
                label: 'Ceiling Fan',
                defaultDimensions: { width: 1.5, length: 1.5, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/ceiling-fan/model.glb',
                thumbnailPath: '/items/Lighting/ceiling-fan/thumbnail.webp',
            },
            {
                type: 'kave_suspended_fireplace',
                label: 'Suspended Fireplace',
                defaultDimensions: { width: 0.8, length: 0.5, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/suspended-fireplace/model.glb',
                thumbnailPath: '/items/Lighting/suspended-fireplace/thumbnail.webp',
            },
            {
                type: 'kave_wood_tapered_floor_lamp',
                label: 'Wood Tapered Floor Lamp',
                defaultDimensions: { width: 0.6, length: 0.6, height: 1.7, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Lighting/wood-tapered-floor-lamp/model.glb',
                thumbnailPath: '/items/Lighting/wood-tapered-floor-lamp/thumbnail.webp',
            },
            {
                type: 'kave_torchiere_floor_lamp',
                label: 'Torchiere Floor Lamp',
                defaultDimensions: { width: 0.4, length: 0.4, height: 1.8, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Lighting/torchiere-floor-lamp/model.glb',
                thumbnailPath: '/items/Lighting/torchiere-floor-lamp/thumbnail.webp',
            },
            {
                type: 'kave_pendant_bell_lamp',
                label: 'Pendant Bell Lamp',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.7, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Lighting/pendant-bell-lamp/model.glb',
                thumbnailPath: '/items/Lighting/pendant-bell-lamp/thumbnail.webp',
            },
        ],
    },
    {
        id: 'kitchen',
        label: 'Kitchen',
        description: 'Appliances and kitchen furniture',
        items: [
            // ── Parametric cabinet layouts ──────────────────────────────────────
            {
                type: 'kitchen_straight',
                label: 'Straight Run',
                defaultDimensions: { width: 3.0, length: 0.60, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-straight.svg',
                parametric: true,
            } as any,
            {
                type: 'kitchen_l_shape',
                label: 'L-Shape Run',
                defaultDimensions: { width: 3.0, length: 0.60, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-l-shape.svg',
                parametric: true,
            } as any,
            {
                type: 'kitchen_u_shape',
                label: 'U-Shape Run',
                defaultDimensions: { width: 3.0, length: 0.60, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-u-shape.svg',
                parametric: true,
            } as any,
            {
                type: 'kitchen_island',
                label: 'Island',
                defaultDimensions: { width: 1.5, length: 1.0, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-island.svg',
                parametric: true,
            } as any,
            {
                type: 'kitchen_straight_tall',
                label: 'Straight + Wall Cabinets',
                defaultDimensions: { width: 3.0, length: 0.60, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-straight-tall.svg',
                parametric: true,
            } as any,
            {
                type: 'kitchen_l_shape_tall',
                label: 'L-Shape + Wall Cabinets',
                defaultDimensions: { width: 3.0, length: 0.60, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-l-shape-tall.svg',
                parametric: true,
            } as any,
            {
                type: 'kitchen_u_shape_tall',
                label: 'U-Shape + Wall Cabinets',
                defaultDimensions: { width: 3.0, length: 0.60, height: 0.90, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                thumbnailPath: '/thumbnails/kitchen-u-shape-tall.svg',
                parametric: true,
            } as any,
            // ── Catalog appliances ──────────────────────────────────────────────
            {
                type: 'kave_stove',
                label: 'Stove',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/stove/model.glb',
                thumbnailPath: '/items/Kitchen/stove/thumbnail.webp',
            },
            {
                type: 'kave_fridge',
                label: 'Fridge',
                defaultDimensions: { width: 1.0, length: 1.0, height: 2.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/fridge/model.glb',
                thumbnailPath: '/items/Kitchen/fridge/thumbnail.webp',
            },
            {
                type: 'kave_freezer',
                label: 'Freezer',
                defaultDimensions: { width: 1.0, length: 1.0, height: 2.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/freezer/model.glb',
                thumbnailPath: '/items/Kitchen/freezer/thumbnail.webp',
            },
            {
                type: 'kave_microwave',
                label: 'Microwave',
                defaultDimensions: { width: 1.0, length: 0.5, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/microwave/model.glb',
                thumbnailPath: '/items/Kitchen/microwave/thumbnail.webp',
            },
            {
                type: 'kave_toaster',
                label: 'Toaster',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/toaster/model.glb',
                thumbnailPath: '/items/Kitchen/toaster/thumbnail.webp',
            },
            {
                type: 'kave_coffee_machine',
                label: 'Coffee Machine',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/coffee-machine/model.glb',
                thumbnailPath: '/items/Kitchen/coffee-machine/thumbnail.webp',
            },
            {
                type: 'kave_kettle',
                label: 'Kettle',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/kettle/model.glb',
                thumbnailPath: '/items/Kitchen/kettle/thumbnail.webp',
            },
            {
                type: 'kave_kitchen_counter',
                label: 'Kitchen Counter',
                defaultDimensions: { width: 2.0, length: 1.0, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kitchen/kitchen-counter/model.glb',
                thumbnailPath: '/items/Kitchen/kitchen-counter/thumbnail.webp',
            },
            {
                type: 'kave_kitchen_cabinet',
                label: 'Kitchen Cabinet',
                defaultDimensions: { width: 2.0, length: 1.0, height: 1.1, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kitchen/kitchen-cabinet/model.glb',
                thumbnailPath: '/items/Kitchen/kitchen-cabinet/thumbnail.webp',
            },
            {
                type: 'kave_kitchen_fridge',
                label: 'Kitchen Fridge',
                defaultDimensions: { width: 1.0, length: 1.0, height: 2.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/kitchen-fridge/model.glb',
                thumbnailPath: '/items/Kitchen/kitchen-fridge/thumbnail.webp',
            },
            {
                type: 'kave_kitchen_shelf',
                label: 'Kitchen Shelf',
                defaultDimensions: { width: 1.5, length: 0.4, height: 1.8, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/kitchen-shelf/model.glb',
                thumbnailPath: '/items/Kitchen/kitchen-shelf/thumbnail.webp',
            },
            {
                type: 'kave_kitchen_utensils',
                label: 'Kitchen Utensils',
                defaultDimensions: { width: 0.3, length: 0.3, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/kitchen-utensils/model.glb',
                thumbnailPath: '/items/Kitchen/kitchen-utensils/thumbnail.webp',
            },
            {
                type: 'kave_hood',
                label: 'Range Hood',
                defaultDimensions: { width: 1.0, length: 0.6, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/hood/model.glb',
                thumbnailPath: '/items/Kitchen/hood/thumbnail.webp',
            },
            {
                type: 'kave_cutting_board',
                label: 'Cutting Board',
                defaultDimensions: { width: 0.4, length: 0.3, height: 0.02, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kitchen/cutting-board/model.glb',
                thumbnailPath: '/items/Kitchen/cutting-board/thumbnail.webp',
            },
            {
                type: 'kave_frying_pan',
                label: 'Frying Pan',
                defaultDimensions: { width: 0.4, length: 0.4, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/frying-pan/model.glb',
                thumbnailPath: '/items/Kitchen/frying-pan/thumbnail.webp',
            },
            {
                type: 'kave_kitchen_set',
                label: 'Kitchen Set',
                defaultDimensions: { width: 3.0, length: 1.0, height: 2.4, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kitchen/kitchen/model.glb',
                thumbnailPath: '/items/Kitchen/kitchen/thumbnail.webp',
            },
            {
                type: 'wip_retro_fridge',
                label: 'Retro Fridge',
                defaultDimensions: { width: 0.7, length: 0.7, height: 1.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kitchen/retro-fridge/model.glb',
                thumbnailPath: '/items/Kitchen/retro-fridge/thumbnail.webp',
            },
        ],
    },
    {
        id: 'bathroom',
        label: 'Bathroom',
        description: 'Bathroom fixtures and accessories — sourced from Services/Plumbing',
        // ── Services/Plumbing consolidation ─────────────────────────────────
        // Every item below uses a `"plumbing:<family>:<variant>"` sentinel so
        // FurnitureDragDropHandler routes the drop through
        // CreatePlumbingFixtureCommand, and FurnitureGeometryFactory renders
        // the thumbnail via the LOD400 plumbing geometry factories (toilet,
        // shower, accessory). The previous bathroom_* furniture types were
        // deleted as duplicates — the entire Bathroom carousel is now a
        // window into the Plumbing system. See
        // docs/01_ELEMENTS/11_Bathroom_Contract/BATHROOM-FILE-INVENTORY.md.
        items: [
            // Trim items still in the Furniture pipeline (no plumbing equivalents).
            {
                type: 'shower_glass_panel',
                label: 'Shower Panel',
                defaultDimensions: { width: 0.9, length: 0.01, height: 2.0, baseOffset: 0.0 },
                defaultMaterial: 'glass',
            },
            {
                type: 'toilet_radiator',
                label: 'Towel Radiator',
                defaultDimensions: { width: 0.5, length: 0.05, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            // ── Toilets (Plumbing — 4 LOD400 variants) ──────────────────────
            {
                type: 'plumbing:toilet:wall_hung_square',
                label: 'Wall-Hung Square Toilet',
                defaultDimensions: { width: 0.36, length: 0.54, height: 0.42, baseOffset: 0.40 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:toilet:wall_hung_round',
                label: 'Wall-Hung Round Toilet',
                defaultDimensions: { width: 0.38, length: 0.58, height: 0.42, baseOffset: 0.40 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:toilet:close_coupled_square',
                label: 'Close-Coupled Square Toilet',
                defaultDimensions: { width: 0.40, length: 0.68, height: 0.78, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:toilet:close_coupled_round',
                label: 'Close-Coupled Round Toilet',
                defaultDimensions: { width: 0.42, length: 0.72, height: 0.82, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            // ── Sink (Plumbing — pedestal default) ──────────────────────────
            {
                type: 'plumbing:sink:default',
                label: 'Pedestal Basin',
                defaultDimensions: { width: 0.65, length: 0.45, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            // ── Bath (Plumbing — built-in default) ──────────────────────────
            {
                type: 'plumbing:bath:default',
                label: 'Standard Bathtub',
                defaultDimensions: { width: 1.70, length: 0.75, height: 0.60, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            // ── Showers (Plumbing — 4 LOD400 variants) ──────────────────────
            {
                type: 'plumbing:shower:shower_system_shelf',
                label: 'Rain System with Shelf',
                defaultDimensions: { width: 0.40, length: 0.20, height: 2.20, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:shower:shower_system_simple',
                label: 'Rain System (Simple)',
                defaultDimensions: { width: 0.40, length: 0.20, height: 2.20, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:shower:shower_cabinet_sliding',
                label: 'Glass Cabinet — Sliding',
                defaultDimensions: { width: 0.90, length: 0.90, height: 2.00, baseOffset: 0.0 },
                defaultMaterial: 'glass',
            },
            {
                type: 'plumbing:shower:shower_cabinet_open',
                label: 'Glass Cabinet — Open',
                defaultDimensions: { width: 0.90, length: 0.90, height: 2.00, baseOffset: 0.0 },
                defaultMaterial: 'glass',
            },
            // ── Accessories (Plumbing — 6 LOD400 variants) ──────────────────
            {
                type: 'plumbing:accessory:washing_machine',
                label: 'Washing Machine',
                defaultDimensions: { width: 0.60, length: 0.60, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:accessory:toilet_brush',
                label: 'Toilet Brush',
                defaultDimensions: { width: 0.10, length: 0.10, height: 0.40, baseOffset: 0.0 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:accessory:toilet_paper',
                label: 'Toilet Paper Holder',
                defaultDimensions: { width: 0.18, length: 0.10, height: 0.12, baseOffset: 0.80 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:accessory:laundry_bag',
                label: 'Laundry Hamper',
                defaultDimensions: { width: 0.40, length: 0.40, height: 0.55, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
            {
                type: 'plumbing:accessory:iron',
                label: 'Steam Iron',
                defaultDimensions: { width: 0.26, length: 0.13, height: 0.18, baseOffset: 0.85 },
                defaultMaterial: 'metal',
            },
            {
                type: 'plumbing:accessory:ironing_board',
                label: 'Ironing Board',
                defaultDimensions: { width: 0.40, length: 1.30, height: 0.85, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
            },
        ],
    },
    {
        id: 'storage',
        label: 'Storage',
        description: 'Shelving, cabinets, wardrobes',
        items: [
            {
                type: 'kave_bookshelf',
                label: 'Bookshelf',
                defaultDimensions: { width: 1.0, length: 0.5, height: 2.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Storage/bookshelf/model.glb',
                thumbnailPath: '/items/Storage/bookshelf/thumbnail.webp',
            },
            {
                type: 'kave_shelf',
                label: 'Wall Shelf',
                defaultDimensions: { width: 1.0, length: 0.7, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Storage/shelf/model.glb',
                thumbnailPath: '/items/Storage/shelf/thumbnail.webp',
            },
            {
                type: 'kave_storage_dresser',
                label: 'Dresser',
                defaultDimensions: { width: 1.5, length: 1.0, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/dresser/model.glb',
                thumbnailPath: '/items/Bedroom/dresser/thumbnail.webp',
            },
            {
                type: 'kave_coat_rack',
                label: 'Coat Rack',
                defaultDimensions: { width: 0.5, length: 0.5, height: 1.8, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Storage/coat-rack/model.glb',
                thumbnailPath: '/items/Storage/coat-rack/thumbnail.webp',
            },
            {
                type: 'kave_small_kitchen_cabinet',
                label: 'Small Cabinet',
                defaultDimensions: { width: 1.0, length: 0.5, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Storage/small-kitchen-cabinet/model.glb',
                thumbnailPath: '/items/Storage/small-kitchen-cabinet/thumbnail.webp',
            },
        ],
    },
    {
        id: 'kids',
        label: 'Kids',
        description: "Children's room furniture",
        items: [
            {
                type: 'kave_kids_bunkbed',
                label: 'Bunk Bed',
                defaultDimensions: { width: 2.0, length: 1.5, height: 1.6, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Bedroom/bunkbed/model.glb',
                thumbnailPath: '/items/Bedroom/bunkbed/thumbnail.webp',
            },
            {
                type: 'kave_car_toy',
                label: 'Car Toy',
                defaultDimensions: { width: 0.5, length: 0.8, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kids/car-toy/model.glb',
                thumbnailPath: '/items/Kids/car-toy/thumbnail.webp',
            },
            {
                type: 'kave_toy',
                label: 'Toy',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Kids/toy/model.glb',
                thumbnailPath: '/items/Kids/toy/thumbnail.webp',
            },
            {
                type: 'kave_outdoor_playhouse',
                label: 'Playhouse',
                defaultDimensions: { width: 0.5, length: 1.0, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kids/outdoor-playhouse/model.glb',
                thumbnailPath: '/items/Kids/outdoor-playhouse/thumbnail.webp',
            },
            {
                type: 'kave_kids_skate',
                label: 'Skateboard',
                defaultDimensions: { width: 1.0, length: 0.5, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kids/skate/model.glb',
                thumbnailPath: '/items/Kids/skate/thumbnail.webp',
            },
            {
                type: 'kave_ball',
                label: 'Ball',
                defaultDimensions: { width: 0.5, length: 0.5, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'fabric',
                glbPath: '/items/Kids/ball/model.glb',
                thumbnailPath: '/items/Kids/ball/thumbnail.webp',
            },
            {
                type: 'kave_kids_scooter',
                label: 'Scooter',
                defaultDimensions: { width: 0.5, length: 1.0, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kids/scooter/model.glb',
                thumbnailPath: '/items/Kids/scooter/thumbnail.webp',
            },
        ],
    },
    {
        id: 'teens',
        label: 'Teens',
        description: 'Teenage room furniture',
        items: [
            {
                type: 'kave_barbell',
                label: 'Barbell',
                defaultDimensions: { width: 1.5, length: 0.3, height: 0.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Teens/barbell/model.glb',
                thumbnailPath: '/items/Teens/barbell/thumbnail.webp',
            },
            {
                type: 'kave_exercise_bike',
                label: 'Exercise Bike',
                defaultDimensions: { width: 1.0, length: 1.0, height: 1.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Teens/exercise-bike/model.glb',
                thumbnailPath: '/items/Teens/exercise-bike/thumbnail.webp',
            },
            {
                type: 'kave_threadmill',
                label: 'Treadmill',
                defaultDimensions: { width: 1.5, length: 0.8, height: 1.3, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Teens/threadmill/model.glb',
                thumbnailPath: '/items/Teens/threadmill/thumbnail.webp',
            },
            {
                type: 'kave_pool_table',
                label: 'Pool Table',
                defaultDimensions: { width: 2.7, length: 1.5, height: 0.9, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Teens/pool-table/model.glb',
                thumbnailPath: '/items/Teens/pool-table/thumbnail.webp',
            },
            {
                type: 'kave_teens_guitar',
                label: 'Guitar',
                defaultDimensions: { width: 0.5, length: 0.5, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/guitar/model.glb',
                thumbnailPath: '/items/Decor/guitar/thumbnail.webp',
            },
            {
                type: 'kave_teens_piano',
                label: 'Piano',
                defaultDimensions: { width: 2.0, length: 1.0, height: 1.5, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Decor/piano/model.glb',
                thumbnailPath: '/items/Decor/piano/thumbnail.webp',
            },
            {
                type: 'kave_stereo_speaker',
                label: 'Stereo Speaker',
                defaultDimensions: { width: 0.5, length: 0.5, height: 1.0, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Teens/stereo-speaker/model.glb',
                thumbnailPath: '/items/Teens/stereo-speaker/thumbnail.webp',
            },
            {
                type: 'kave_teens_skate',
                label: 'Skateboard',
                defaultDimensions: { width: 1.0, length: 0.5, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'wood',
                glbPath: '/items/Kids/skate/model.glb',
                thumbnailPath: '/items/Kids/skate/thumbnail.webp',
            },
            {
                type: 'kave_barbell_stand',
                label: 'Barbell Stand',
                defaultDimensions: { width: 1.5, length: 0.6, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Teens/barbell-stand/model.glb',
                thumbnailPath: '/items/Teens/barbell-stand/thumbnail.webp',
            },
            {
                type: 'kave_basket_hoop',
                label: 'Basketball Hoop',
                defaultDimensions: { width: 1.0, length: 0.3, height: 2.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Teens/basket-hoop/model.glb',
                thumbnailPath: '/items/Teens/basket-hoop/thumbnail.webp',
            },
            {
                type: 'kave_sewing_machine',
                label: 'Sewing Machine',
                defaultDimensions: { width: 0.5, length: 0.3, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Teens/sewing-machine/model.glb',
                thumbnailPath: '/items/Teens/sewing-machine/thumbnail.webp',
            },
            {
                type: 'kave_teens_scooter',
                label: 'Scooter',
                defaultDimensions: { width: 0.5, length: 1.2, height: 1.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Kids/scooter/model.glb',
                thumbnailPath: '/items/Kids/scooter/thumbnail.webp',
            },
        ],
    },
    {
        id: 'pets',
        label: 'Pets',
        description: 'Pet furniture and accessories',
        items: [
            // PLANNED: pet_bed, cat_tree, dog_kennel
        ],
    },
    {
        id: 'technical',
        label: 'Technical',
        description: 'HVAC, safety, smart home devices',
        items: [
            {
                type: 'kave_air_conditioner',
                label: 'Air Conditioner',
                defaultDimensions: { width: 1.0, length: 0.3, height: 0.4, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/air-conditioner/model.glb',
                thumbnailPath: '/items/Technical/air-conditioner/thumbnail.webp',
            },
            {
                type: 'kave_air_conditioner_block',
                label: 'AC Block',
                defaultDimensions: { width: 0.8, length: 0.8, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/air-conditioner-block/model.glb',
                thumbnailPath: '/items/Technical/air-conditioner-block/thumbnail.webp',
            },
            {
                type: 'kave_ac_block',
                label: 'AC Block (Compact)',
                defaultDimensions: { width: 0.6, length: 0.6, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/ac-block/model.glb',
                thumbnailPath: '/items/Technical/ac-block/thumbnail.webp',
            },
            {
                type: 'kave_air_conditioning',
                label: 'Air Conditioning Unit',
                defaultDimensions: { width: 1.2, length: 0.4, height: 0.5, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/air-conditioning/model.glb',
                thumbnailPath: '/items/Technical/air-conditioning/thumbnail.webp',
            },
            {
                type: 'kave_thermostat',
                label: 'Thermostat',
                defaultDimensions: { width: 0.1, length: 0.03, height: 0.15, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/thermostat/model.glb',
                thumbnailPath: '/items/Technical/thermostat/thumbnail.webp',
            },
            {
                type: 'kave_alarm_keypad',
                label: 'Alarm Keypad',
                defaultDimensions: { width: 0.15, length: 0.05, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/alarm-keypad/model.glb',
                thumbnailPath: '/items/Technical/alarm-keypad/thumbnail.webp',
            },
            {
                type: 'kave_electric_panel',
                label: 'Electric Panel',
                defaultDimensions: { width: 0.5, length: 0.1, height: 0.8, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/electric-panel/model.glb',
                thumbnailPath: '/items/Technical/electric-panel/thumbnail.webp',
            },
            {
                type: 'kave_ev_wall_charger',
                label: 'EV Wall Charger',
                defaultDimensions: { width: 0.4, length: 0.15, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/ev-wall-charger/model.glb',
                thumbnailPath: '/items/Technical/ev-wall-charger/thumbnail.webp',
            },
            {
                type: 'kave_smoke_detector',
                label: 'Smoke Detector',
                defaultDimensions: { width: 0.15, length: 0.15, height: 0.05, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/smoke-detector/model.glb',
                thumbnailPath: '/items/Technical/smoke-detector/thumbnail.webp',
            },
            {
                type: 'kave_fire_alarm',
                label: 'Fire Alarm',
                defaultDimensions: { width: 0.15, length: 0.15, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/fire-alarm/model.glb',
                thumbnailPath: '/items/Technical/fire-alarm/thumbnail.webp',
            },
            {
                type: 'kave_fire_detector',
                label: 'Fire Detector',
                defaultDimensions: { width: 0.12, length: 0.12, height: 0.08, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/fire-detector/model.glb',
                thumbnailPath: '/items/Technical/fire-detector/thumbnail.webp',
            },
            {
                type: 'kave_fire_extinguisher',
                label: 'Fire Extinguisher',
                defaultDimensions: { width: 0.2, length: 0.2, height: 0.6, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/fire-extinguisher/model.glb',
                thumbnailPath: '/items/Technical/fire-extinguisher/thumbnail.webp',
            },
            {
                type: 'kave_sprinkler',
                label: 'Sprinkler',
                defaultDimensions: { width: 0.1, length: 0.1, height: 0.1, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/sprinkler/model.glb',
                thumbnailPath: '/items/Technical/sprinkler/thumbnail.webp',
            },
            {
                type: 'kave_exit_sign',
                label: 'Exit Sign',
                defaultDimensions: { width: 0.4, length: 0.05, height: 0.2, baseOffset: 0.0 },
                defaultMaterial: 'metal',
                glbPath: '/items/Technical/exit-sign/model.glb',
                thumbnailPath: '/items/Technical/exit-sign/thumbnail.webp',
            },
        ],
    },
];
