// G8 — `validateRoomDaylight` pure validator
// (APARTMENT-DIMENSIONAL-CONSTRAINTS-AND-SPATIAL-PROPORTION-FRAMEWORK-2026-05-29
// §9.8; pairs with A.38 daylight rule-checker).
//
// The framework's twin to `validateFrontage` (D2.5): frontage checks
// "is the room on the perimeter at all"; this validator checks "does
// the room actually receive light" — i.e. has at least one window on
// one of its perimeter edges, with aperture area meeting the Building
// Reg minimum (10 % of floor area for habitable rooms by default).
//
// HARD-rejects habitable rooms with `frontage: 'required'` (master /
// bedroom / living / kitchen per programRules.ts) that have NO window
// on any perimeter edge. This is the "WINDOWLESS BEDROOM" anti-pattern
// the single-apartment fix-pass spec called out.
//
// SOFT-penalises habitable rooms whose aperture is below 10 % of their
// floor area (most jurisdictions' habitability floor); penalty scales
// with shortfall.
//
// L2-pure: no THREE / DOM / RNG. Tests in plain Node. Reads ONLY the
// room rects + window placements; the room↔window association is
// derived from window-on-room-edge geometry (no separate join required).

import type { RoomType } from '../types.js';
import type { DimensionalValidation, ValidationFinding } from './types.js';

const EPS = 1e-4; // 0.1 mm tolerance.

/** Habitable room types that MUST have natural light per programRules.ts. */
const HABITABLE_REQUIRED: ReadonlySet<RoomType> = new Set<RoomType>([
    'master',
    'bedroom',
    'living',
    'kitchen',
]);

/** Habitable room types that should PREFER natural light (soft). */
const HABITABLE_PREFERRED: ReadonlySet<RoomType> = new Set<RoomType>([
    'dining',
    'study',
]);

/** Minimum aperture area as a fraction of floor area (10 % Building Reg default). */
const APERTURE_FLOOR_RATIO_MIN = 0.10;

export interface RoomDaylightInput {
    readonly roomId: string;
    readonly type: RoomType;
    readonly name?: string;
    /** Axis-aligned rectangle in metres. x0 < x1, z0 < z1. */
    readonly rect: { readonly x0: number; readonly z0: number; readonly x1: number; readonly z1: number };
}

/**
 * A window in PLAN coordinates (XZ metres). Generated by the apartment
 * layout pipeline — the offset+width are projected onto the room edge
 * to compute the aperture-on-room overlap.
 *
 * `wallSpan` is the wall segment the window sits in, as an axis-aligned
 * 2-point pair. `width` is the window aperture along the wall; `height`
 * (mm) maps to aperture area when multiplied by the width.
 */
export interface DaylightWindowInput {
    readonly a: { readonly x: number; readonly z: number };
    readonly b: { readonly x: number; readonly z: number };
    /** Aperture width along the wall, metres. */
    readonly widthM: number;
    /** Aperture height, metres. */
    readonly heightM: number;
}

interface ScoredRoom {
    readonly apertureArea: number;
    readonly floorArea: number;
}

function labelOf(r: RoomDaylightInput): string {
    return r.name ?? r.roomId;
}

function rectArea(r: RoomDaylightInput['rect']): number {
    return (r.x1 - r.x0) * (r.z1 - r.z0);
}

/**
 * Project the window's `[a, b]` segment onto the room's perimeter and
 * return the overlap length in metres. Zero when the window doesn't
 * touch any room edge.
 *
 * Axis-aligned rects + axis-aligned windows (D-TGL invariant) keep this
 * a cheap 1D-overlap check per side.
 */
function windowRoomOverlap(
    rect: RoomDaylightInput['rect'],
    win: DaylightWindowInput,
): number {
    // Window axis: horizontal (a.z == b.z) or vertical (a.x == b.x).
    const isHorizontal = Math.abs(win.a.z - win.b.z) < EPS;
    const isVertical = Math.abs(win.a.x - win.b.x) < EPS;
    if (!isHorizontal && !isVertical) return 0;

    if (isHorizontal) {
        const z = win.a.z;
        const wxLo = Math.min(win.a.x, win.b.x);
        const wxHi = Math.max(win.a.x, win.b.x);
        // Check the two horizontal sides of the rect (z0, z1).
        let total = 0;
        for (const rz of [rect.z0, rect.z1]) {
            if (Math.abs(z - rz) > EPS) continue;
            const lo = Math.max(wxLo, rect.x0);
            const hi = Math.min(wxHi, rect.x1);
            if (hi > lo) total += hi - lo;
        }
        return total;
    }
    // vertical
    const x = win.a.x;
    const wzLo = Math.min(win.a.z, win.b.z);
    const wzHi = Math.max(win.a.z, win.b.z);
    let total = 0;
    for (const rx of [rect.x0, rect.x1]) {
        if (Math.abs(x - rx) > EPS) continue;
        const lo = Math.max(wzLo, rect.z0);
        const hi = Math.min(wzHi, rect.z1);
        if (hi > lo) total += hi - lo;
    }
    return total;
}

function scoreRoom(
    room: RoomDaylightInput,
    windows: readonly DaylightWindowInput[],
): ScoredRoom {
    const floorArea = rectArea(room.rect);
    let apertureArea = 0;
    for (const win of windows) {
        const overlap = windowRoomOverlap(room.rect, win);
        if (overlap > EPS) {
            apertureArea += overlap * win.heightM;
        }
    }
    return { apertureArea, floorArea };
}

/**
 * Validate every room against the G8 daylight rules.
 *
 *   - HABITABLE_REQUIRED + no window → HARD reject (windowless bedroom).
 *   - HABITABLE_REQUIRED + aperture < 10 % floor → SOFT (insufficient daylight).
 *   - HABITABLE_PREFERRED + no window → SOFT (loss-of-quality).
 *   - Service / circulation rooms → no rule (corridor / bath / wc accepted windowless).
 */
export function validateRoomDaylight(
    rooms: readonly RoomDaylightInput[],
    windows: readonly DaylightWindowInput[],
): DimensionalValidation {
    const hard: ValidationFinding[] = [];
    const soft: ValidationFinding[] = [];

    for (const room of rooms) {
        const isRequired = HABITABLE_REQUIRED.has(room.type);
        const isPreferred = HABITABLE_PREFERRED.has(room.type);
        if (!isRequired && !isPreferred) continue;

        const { apertureArea, floorArea } = scoreRoom(room, windows);
        const apertureRatio = floorArea > 0 ? apertureArea / floorArea : 0;
        const label = labelOf(room);

        if (apertureArea < EPS) {
            // No window at all.
            if (isRequired) {
                hard.push({
                    roomId: room.roomId,
                    severity: 'hard',
                    metric: 'noWindow',
                    delta: 1.0,
                    reason: `${label} (${room.type}) has no window — habitable rooms MUST receive natural light (G8)`,
                });
            } else {
                soft.push({
                    roomId: room.roomId,
                    severity: 'soft',
                    metric: 'noWindowPreferred',
                    delta: 0.6,
                    reason: `${label} (${room.type}) has no window — preferred-frontage room should receive daylight`,
                });
            }
            continue;
        }

        if (isRequired && apertureRatio < APERTURE_FLOOR_RATIO_MIN - EPS) {
            const shortfall = APERTURE_FLOOR_RATIO_MIN - apertureRatio;
            const delta = Math.min(1, shortfall / APERTURE_FLOOR_RATIO_MIN);
            soft.push({
                roomId: room.roomId,
                severity: 'soft',
                metric: 'apertureBelowMinimum',
                delta,
                reason: `${label} (${room.type}) aperture ${(apertureRatio * 100).toFixed(1)} % < ${(APERTURE_FLOOR_RATIO_MIN * 100).toFixed(0)} % floor area — daylight below habitability minimum`,
            });
        }
    }

    return {
        admissible: hard.length === 0,
        hardFindings: hard,
        softFindings: soft,
    };
}
