// WallOpeningLegacyAdapterHandler — PRYZM3 handler for the legacy bus command
// `wall.opening.create` (dispatched by DoorPlanToolHandler / WindowPlanToolHandler).
//
// §P2.3 (IMPL-PLAN-2026-05-17): replaces the E.5.6 bridge in initBusHandlers.ts
// that called _cmExec(new CreateWallOpeningCommand(...)).  C11 §3 compliance:
// no wall-opening creation goes through the legacy commandManager.
//
// PAYLOAD:
//   { wallId: string, openingData: { id, elementId, type, offset, width, height,
//     sillHeight, ...extra } }
//   id + elementId are pre-generated by the plan tool before dispatch so both
//   the PRYZM3 Immer store and the legacy WallStore (via the initTools.ts
//   wall.opening.created bridge) share the same stable IDs.
//
// IMMER WRITE:
//   If the wall exists in the PRYZM3 Immer store (walls created via bus after P2.1),
//   the opening is added to `wall.openings` and `wall.childrenIds` atomically.
//   If the wall is legacy-only (pre-P2.1), the draft mutation is a no-op for Immer;
//   the initTools.ts bridge still fires via PatchEmitter and calls
//   WallStore.addOpening() → WallRebuildCoordinator → mesh rebuild.
//
// VALIDATION:
//   canExecute performs lightweight structural checks only — wall-in-store checks
//   are intentionally omitted because the wall may be in the legacy store only
//   (transitional state while P2.1 migration is in progress on existing projects).

import {
  produceCommand,
  withHandlerSpan,
  type CommandHandler,
  type HandlerContext,
  type HandlerResult,
  type ValidationResult,
} from '@pryzm/plugin-sdk';
import type { WallsState } from '../store.js';

export interface WallOpeningLegacyAdapterPayload {
  readonly wallId: string;
  readonly openingData: Readonly<Record<string, unknown>>;
}

type WallHandlerStores = Readonly<{ wall: WallsState } & Record<string, unknown>>;

export class WallOpeningLegacyAdapterHandler
  implements CommandHandler<WallOpeningLegacyAdapterPayload, WallHandlerStores>
{
  readonly type = 'wall.opening.create';
  readonly affectedStores = ['wall'] as const;

  canExecute(
    _ctx: HandlerContext<WallHandlerStores>,
    cmd: WallOpeningLegacyAdapterPayload,
  ): ValidationResult {
    if (typeof cmd.wallId !== 'string' || cmd.wallId.length === 0) {
      return { valid: false, reason: 'wallId must be a non-empty string' };
    }
    const d = cmd.openingData;
    if (typeof d !== 'object' || d === null) {
      return { valid: false, reason: 'openingData must be an object' };
    }
    if (d.type !== 'door' && d.type !== 'window') {
      return { valid: false, reason: "openingData.type must be 'door' or 'window'" };
    }
    if (typeof d.offset !== 'number' || !Number.isFinite(d.offset as number) || (d.offset as number) < 0) {
      return { valid: false, reason: 'openingData.offset must be a finite number ≥ 0' };
    }
    if (typeof d.width !== 'number' || !Number.isFinite(d.width as number) || (d.width as number) <= 0) {
      return { valid: false, reason: 'openingData.width must be a finite number > 0' };
    }
    if (typeof d.height !== 'number' || !Number.isFinite(d.height as number) || (d.height as number) <= 0) {
      return { valid: false, reason: 'openingData.height must be a finite number > 0' };
    }
    if (typeof d.sillHeight !== 'number' || !Number.isFinite(d.sillHeight as number) || (d.sillHeight as number) < 0) {
      return { valid: false, reason: 'openingData.sillHeight must be a finite number ≥ 0' };
    }
    return { valid: true };
  }

  execute(
    ctx: HandlerContext<WallHandlerStores>,
    cmd: WallOpeningLegacyAdapterPayload,
  ): HandlerResult {
    return withHandlerSpan(
      this.type + '.handler',
      { 'pryzm.command.type': this.type },
      () => {
        const d = cmd.openingData;
        const id        = (typeof d.id        === 'string' && d.id.length > 0)        ? d.id        as string : crypto.randomUUID();
        const elementId = (typeof d.elementId === 'string' && d.elementId.length > 0) ? d.elementId as string : crypto.randomUUID();
        const opening   = { ...d, id, elementId };

        const [next, forward, inverse] = produceCommand<WallsState>(
          ctx.stores.wall,
          draft => {
            const w = draft[cmd.wallId];
            // §P2.3: wall may be legacy-only (pre-P2.1) — skip Immer write if not
            // present; the initTools.ts wall.opening.created bridge handles the mesh.
            if (w === undefined) return;
            w.openings = [...(w.openings ?? []), opening as Parameters<typeof Array.prototype.push>[0]];
            if (!w.childrenIds.includes(elementId)) {
              w.childrenIds = [...w.childrenIds, elementId];
            }
          },
        );
        return { forward, inverse, nextStates: { wall: next } };
      },
    );
  }
}
