// DimensionString schema tests (S31 / Phase 2B Supplement §A1).
//
// Exit criteria covered:
//   • All 6 `kind` values round-trip through `DimensionStringSchema.parse`.
//   • Default values applied when omitted (offsetMm, override,
//     witnessLines, arrowheads, isAutoGenerated, textStyleRef).
//   • Reference / orientation invariants enforced.
//   • Branded IDs preserved by the parser.

import { describe, expect, it } from 'vitest';
import {
  DimensionStringSchema,
  DimensionAutoModeSchema,
  DimensionKindSchema,
  type DimensionKind,
  type DimensionString,
} from '../src/annotation/dimension.js';

const baseRefs = [
  { elementId: 'wall_01H8X0000000000000000000', anchor: 'start' as const },
  { elementId: 'wall_01H8X0000000000000000000', anchor: 'end' as const },
];

function buildSeed(kind: DimensionKind): unknown {
  const seed: Record<string, unknown> = {
    id: `dim_${kind}`,
    kind,
    references: baseRefs,
    orientation: kind === 'angular' ? 'angular' : 'horizontal',
    viewId: 'view_plan_lvl1',
  };
  // angular needs ≥ 3 refs; round trips with a third anchor for parity.
  if (kind === 'angular') {
    seed.references = [
      ...baseRefs,
      { elementId: 'wall_01H8X0000000000000000000', anchor: 'center' as const },
    ];
  }
  return seed;
}

describe('DimensionStringSchema — S31 exit', () => {
  it('round-trips all 6 kind values without loss', () => {
    for (const kind of DimensionKindSchema.options) {
      const parsed: DimensionString = DimensionStringSchema.parse(buildSeed(kind));
      expect(parsed.kind).toBe(kind);
      // re-parse the inferred output: byte-identical round-trip on the
      // public fields (defaults + branded ids preserved).
      const reparsed = DimensionStringSchema.parse(parsed);
      expect(reparsed).toEqual(parsed);
    }
  });

  it('applies defaults when fields are omitted', () => {
    const d = DimensionStringSchema.parse({
      id: 'dim_defaults',
      kind: 'linear-element',
      references: baseRefs,
      orientation: 'horizontal',
      viewId: 'view_plan_lvl1',
    });
    expect(d.offsetMm).toBe(8);
    expect(d.override).toBeNull();
    expect(d.arrowheads).toBe('tick');
    expect(d.isAutoGenerated).toBe(false);
    expect(d.textStyleRef).toBe('default-dim');
    expect(d.witnessLines.offset).toBe(1);
    expect(d.witnessLines.extension).toBe(2);
    expect(d.witnessLines.weight).toBeCloseTo(0.18, 6);
  });

  it('rejects fewer than 2 references', () => {
    expect(() => DimensionStringSchema.parse({
      id: 'dim_invalid',
      kind: 'linear-element',
      references: [baseRefs[0]],
      orientation: 'horizontal',
      viewId: 'view_plan_lvl1',
    })).toThrow();
  });

  it('preserves auto-generated metadata when produced by DimensionProducer (S33)', () => {
    const auto = DimensionStringSchema.parse({
      id: 'dim_auto',
      kind: 'linear-chain',
      references: baseRefs,
      orientation: 'horizontal',
      viewId: 'view_plan_lvl1',
      isAutoGenerated: true,
      autoMode: 'per-element',
      override: 3200,
    });
    expect(auto.isAutoGenerated).toBe(true);
    expect(auto.autoMode).toBe('per-element');
    expect(auto.override).toBe(3200);
  });

  it('accepts every DimensionAutoMode discriminator', () => {
    for (const mode of DimensionAutoModeSchema.options) {
      const d = DimensionStringSchema.parse({
        id: `dim_${mode}`,
        kind: 'linear-element',
        references: baseRefs,
        orientation: 'horizontal',
        viewId: 'view_plan_lvl1',
        isAutoGenerated: true,
        autoMode: mode,
      });
      expect(d.autoMode).toBe(mode);
    }
  });
});
