// §PL-INDICATIVE-RATE (lane PL-COST-AND-CREATE-HOUSE, 2026-09-06) — STR §25.7's
// *"adjustable cost per m² giving a cost estimate BEFORE going into detail"*.
//
// ══════════════════════════════════════════════════════════════════════════════
// ⭐ WHY THIS IS A SECOND ESTIMATOR AND NOT A PARAMETER ON THE FIRST ONE
// ══════════════════════════════════════════════════════════════════════════════
// `RegionalBuildingCost.ts` next door already computes a building-level €/m²
// figure, and it is a GOOD one: `ES_BARCELONA_ICIO_2026` is a municipal fiscal
// ordinance published in the BOPB, ten cited groups, published correction
// factors, a licence sentence, a `RatePriceProvenance`. `resolveBuildingCostModels`
// walks jurisdiction → region → country and **REFUSES rather than substituting a
// neighbour's number**.
//
// That refusal is correct and it is also why the founder cannot get a figure. The
// shipped module count is ONE. Outside Barcelona the honest published answer is
// *"nothing covers here"*, and STR §25.7 asks for something different and equally
// legitimate: *"I, the user, assume €1,800/m² — what does that make this?"*
//
// ⛔ THE TEMPTING SHORTCUT IS TO SYNTHESISE A `RegionalBuildingCostModel` FROM
//    THE USER'S NUMBER AND FEED IT TO `estimateBuildingCost`. That is forbidden
//    here, and the reason is [[fake-more-capable-than-real]]: every consumer of
//    `BuildingCostEstimate` — the 5D panel, the CSV, `RatePriceProvenance` —
//    reads its fields as *published, cited, licence-cleared*. A user's guess
//    wearing that type is a guess with a citation attached, and one refactor
//    later it is in an export that says `provenance.itemCode`. So the two
//    estimators share a FILE NEIGHBOURHOOD and a discipline, never a type.
//
// ══════════════════════════════════════════════════════════════════════════════
// ⛔ THE FIVE RULES THIS MODULE ENCODES — each inherited from a paid-for defect
// ══════════════════════════════════════════════════════════════════════════════
//  1. **THE RATE'S SOURCE IS IN THE TYPE.** `IndicativeRate.source` is the closed
//     union `'user-supplied'` — one member today. A future published rate cannot
//     be laundered in under this name without widening the union in a diff a
//     reviewer sees. C38 §1.1 requires every cost row to cite a source; the
//     user's own assumption is a source, and naming it is what makes it one.
//  2. **CURRENCY IS EXPLICIT, NEVER INFERRED FROM LOCALE** (C38 §1.2, verbatim).
//     There is no default. A rate typed without a currency is a refusal.
//  3. **FAILURE ≠ EMPTINESS.** Five refusal arms with five different sentences.
//     "You have not set a rate" and "no envelope has been declared" demand
//     opposite next actions from the user, and rendering both as `—` is
//     [[context-data-honesty-family]], this repo's most-repeated defect.
//  4. **THE STATEMENT IS BUILT HERE, NOT IN THE UI.** Same discipline as
//     `estimateBuildingCost`: the sentence that must travel with the figure is
//     generated by the producer, so a second surface cannot render the number
//     without what it is.
//  5. **IT IS NEVER IN A TOTAL.** Like `BuildingCostEstimate`, this figure is not
//     a `CostItem`, is not summed into `CostSummary.pricedTotal`, and never
//     reaches `applyRates()`. It answers ONE question on its own.
//
// PURE: no I/O, no clock, no RNG, no DOM, no THREE. Deterministic. Never throws.

/**
 * A rate the USER set. There is exactly one `source` member and that is the point
 * — see rule 1 in the header.
 */
export interface IndicativeRate {
  /** Currency units per square metre. Must be finite and > 0; 0 is a refusal, not a free build. */
  readonly amountPerM2: number;
  /**
   * ISO-4217, explicit per C38 §1.2. ⛔ NO DEFAULT AND NO LOCALE INFERENCE — a
   * figure whose currency was guessed is a figure that is wrong by a factor
   * nobody can see.
   */
  readonly currency: string;
  /**
   * ⛔ CLOSED UNION, ONE MEMBER. This field exists so that the answer to
   * *"where did this rate come from?"* is in the data rather than in a comment.
   */
  readonly source: 'user-supplied';
  /** When the user typed it (ISO-8601), so a stale assumption never reads as fresh. */
  readonly setAtIso: string;
}

/**
 * The area an indicative estimate multiplies, carrying its own basis and caveat —
 * the same shape discipline as `MeasuredBuiltArea`, deliberately NOT the same type.
 *
 * ⛔ `MeasuredBuiltArea` means *measured off a take-off*. At the envelope stage
 * nothing has been modelled and there is no take-off, so reusing that type would
 * assert a measurement that did not happen. `basis` and `caveat` are required and
 * are validated non-empty, because an area with no stated basis is the beginning
 * of every "confidently wrong number" in this repo's history.
 */
export interface IndicativeArea {
  readonly areaM2: number;
  /** Where the number came from, in words. Required, non-empty. */
  readonly basis: string;
  /** How it differs from the quantity a builder would price. Required, non-empty. */
  readonly caveat: string;
}

/** Why no figure could be produced. Every arm has its own sentence — see rule 3. */
export type IndicativeCostRefusal =
  | 'no-rate'
  | 'rate-not-positive'
  | 'currency-missing'
  | 'no-area'
  | 'area-not-positive'
  | 'area-basis-missing';

export interface IndicativeCostEstimate {
  readonly rate: IndicativeRate;
  readonly area: IndicativeArea;
  readonly currency: string;
  /** `rate.amountPerM2 × area.areaM2`, rounded to the cent. The whole answer. */
  readonly amount: number;
  /**
   * The sentence that MUST accompany the figure. Generated here (rule 4). It
   * names the rate as the user's own, names the area's basis, and says in words
   * that this is not a quotation and not in any total.
   */
  readonly statement: string;
}

export type IndicativeCostOutcome =
  | { readonly ok: true; readonly estimate: IndicativeCostEstimate }
  | { readonly ok: false; readonly reason: IndicativeCostRefusal; readonly text: string };

/**
 * The refusal sentences. Exported so a renderer prints the producer's words
 * rather than inventing its own — the same reason `estimateBuildingCost` builds
 * its statement internally.
 */
export const INDICATIVE_COST_REFUSAL_TEXT: Readonly<Record<IndicativeCostRefusal, string>> =
  Object.freeze({
    'no-rate':
      'No cost rate has been set. Type a cost per m² above and PRYZM will multiply it by the '
      + 'area declared on this site. The rate is YOUR assumption — PRYZM ships no published rate '
      + 'for most places and will not invent one.',
    'rate-not-positive':
      'A cost per m² must be greater than zero. A rate of zero is not a free building; it is a '
      + 'rate nobody has decided yet, and PRYZM will not print a €0 estimate that looks like one.',
    'currency-missing':
      'No currency was set for this rate. PRYZM never infers a currency from your locale (C38 '
      + '§1.2) — a figure whose currency was guessed is wrong by a factor nobody can see.',
    'no-area':
      'No area has been declared on this site yet, so there is nothing to multiply. Draw a level '
      + 'envelope — or set a target ground-floor area — and this estimate appears. This is a '
      + 'finding about the project, NOT a failure to read it.',
    'area-not-positive':
      'The declared area is zero or negative, so no estimate is possible. This is a defect in the '
      + 'area, not in the rate.',
    'area-basis-missing':
      'The area reached this estimator with no stated basis, so PRYZM will not multiply it. An '
      + 'area whose provenance is unknown produces a cost whose provenance is unknown.',
  });

const isFiniteNumber = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v);
const round2 = (v: number): number => Math.round(v * 100) / 100;

/**
 * Compute the indicative estimate. Pure, total, side-effect free; never throws.
 *
 * Returns `{ ok: false }` — never a zero and never a partial figure — for every
 * state in which the answer would be a guess. Rounding is to the cent on the
 * product only, so `estimateAtIndicativeRate` is reproducible byte-for-byte over
 * the same inputs (C38 §1.14's determinism rule, applied one stage earlier).
 */
export function estimateAtIndicativeRate(
  rate: IndicativeRate | null | undefined,
  area: IndicativeArea | null | undefined,
): IndicativeCostOutcome {
  const refuse = (reason: IndicativeCostRefusal): IndicativeCostOutcome =>
    ({ ok: false, reason, text: INDICATIVE_COST_REFUSAL_TEXT[reason] });

  if (!rate || !isFiniteNumber(rate.amountPerM2)) return refuse('no-rate');
  if (!(rate.amountPerM2 > 0)) return refuse('rate-not-positive');
  if (typeof rate.currency !== 'string' || rate.currency.trim().length === 0) {
    return refuse('currency-missing');
  }
  if (!area || !isFiniteNumber(area.areaM2)) return refuse('no-area');
  if (!(area.areaM2 > 0)) return refuse('area-not-positive');
  if (typeof area.basis !== 'string' || area.basis.trim().length === 0
    || typeof area.caveat !== 'string' || area.caveat.trim().length === 0) {
    return refuse('area-basis-missing');
  }

  const currency = rate.currency.trim();
  const amount = round2(rate.amountPerM2 * area.areaM2);
  const statement =
    `≈ ${rate.amountPerM2} ${currency}/m² × ${round2(area.areaM2)} m² (${area.basis}). `
    + `THE RATE IS YOUR OWN ASSUMPTION, set ${rate.setAtIso} — it is not a published rate, it is `
    + `not cited to any ordinance or price book, and PRYZM has not checked it against anything. `
    + `THIS IS AN ESTIMATE, NOT A QUOTATION, AND IT IS NOT IN ANY TOTAL. `
    + `The area is a study: ${area.caveat}`;

  return {
    ok: true,
    estimate: { rate, area, currency, amount, statement },
  };
}

/**
 * ⭐ THE COMPARISON THAT KEEPS THE USER'S GUESS HONEST WHERE A PUBLISHED FIGURE
 * EXISTS.
 *
 * In Barcelona both estimators can answer, and the two answers can differ by a
 * lot. Showing only the user's number there would hide a cited figure PRYZM
 * already has; showing only the published one would ignore the user's explicit
 * decision. So this returns a sentence naming BOTH numbers and their ratio —
 * the founder's standing hard-stopper doctrine ("refuse with BOTH numbers")
 * applied to a disagreement that is not a refusal.
 *
 * Returns `null` when there is nothing to compare, which the caller renders as
 * *nothing* — never as "they agree".
 */
export function compareIndicativeToPublishedRate(
  indicative: IndicativeRate | null | undefined,
  publishedRatePerM2: number | null | undefined,
  publishedLabel: string | null | undefined,
): string | null {
  if (!indicative || !isFiniteNumber(indicative.amountPerM2) || !(indicative.amountPerM2 > 0)) return null;
  if (!isFiniteNumber(publishedRatePerM2) || !(publishedRatePerM2 > 0)) return null;
  const label = typeof publishedLabel === 'string' && publishedLabel.trim().length > 0
    ? publishedLabel.trim()
    : 'the published rate for this place';
  const ratio = round2(indicative.amountPerM2 / publishedRatePerM2);
  const direction = ratio > 1 ? 'above' : ratio < 1 ? 'below' : 'the same as';
  if (ratio === 1) {
    return `Your rate of ${indicative.amountPerM2} ${indicative.currency}/m² is ${direction} `
      + `${label} (${round2(publishedRatePerM2)}).`;
  }
  return `Your rate of ${indicative.amountPerM2} ${indicative.currency}/m² is ${ratio}× `
    + `${direction} ${label} (${round2(publishedRatePerM2)} per m²). PRYZM does not say which is `
    + `right — the published figure is cited and yours is not, and yours may reflect something the `
    + `published one does not cover.`;
}
