/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Command Layer — Data Platform: IFC Hierarchy
 * File:             src/commands/hierarchy/CreateSiteCommand.ts
 * Contract:         docs/00_Contracts/01-BIM-ENGINE-CORE-CONTRACT.md §2
 *                   docs/00_Contracts/03-BIM-SEMANTIC-MODEL-CONTRACT.md §2
 *
 * Creates a Site node in HierarchyStore. Undo removes it.
 * ID must be generated by the caller (§2.6 — never inside execute()).
 */

import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext
} from '../types';
import type { SiteData } from '@pryzm/core-app-model';

export interface CreateSiteInput {
    id: string;
    name: string;
    code?: string;
    description?: string;
    address?: string;
    country?: string;
    coordinates?: { lat: number; lng: number };
    grossSiteArea?: number;
    planningRef?: string;
    createdBy?: string;
}

export class CreateSiteCommand implements Command {
    readonly affectedStores = ["hierarchy"] as const;
    id = crypto.randomUUID();
    type = CommandType.CREATE_SITE;
    timestamp = Date.now();
    targetIds: string[];

    constructor(private input: CreateSiteInput) {
        this.targetIds = [input.id];
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        if (!ctx.stores.hierarchyStore) {
            return { ok: false, reason: 'HierarchyStore not available in CommandContext' };
        }
        if (!this.input.name.trim()) {
            return { ok: false, reason: 'Site name must not be empty' };
        }
        if (ctx.stores.hierarchyStore.has(this.input.id)) {
            return { ok: false, reason: `Site id already exists: ${this.input.id}` };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        const now = Date.now();
        const site: SiteData = {
            id: this.input.id,
            type: 'site',
            name: this.input.name.trim(),
            code: this.input.code,
            description: this.input.description,
            address: this.input.address,
            country: this.input.country,
            coordinates: this.input.coordinates,
            grossSiteArea: this.input.grossSiteArea,
            planningRef: this.input.planningRef,
            parentId: undefined,
            templateId: undefined,
            plannedData: { customProperties: {} },
            syncState: 'no-template',
            metadata: {
                createdAt: now,
                modifiedAt: now,
                createdBy: this.input.createdBy ?? 'user',
                version: 1,
            },
        };

        ctx.stores.hierarchyStore!.add(site);

        return { success: true, affectedElementIds: [this.input.id] };
    }

    undo(ctx: CommandContext): CommandResult {
        ctx.stores.hierarchyStore?.remove(this.input.id);
        return { success: true, affectedElementIds: [this.input.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
            payload: this.input,
        };
    }
}
