/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Command Layer — Data Platform: IFC Hierarchy
 * File:             src/commands/hierarchy/CreateHierarchyLevelCommand.ts
 * Contract:         docs/00_Contracts/01-BIM-ENGINE-CORE-CONTRACT.md §2
 *                   docs/00_Contracts/03-BIM-SEMANTIC-MODEL-CONTRACT.md §2
 *
 * Creates a Level node that bridges HierarchyStore to a real BimManager level.
 * canExecute validates:
 *   1. buildingId exists in hierarchyStore (type='building')
 *   2. ctx.bimManager.getLevelById(bimLevelId) != null (real spatial level exists)
 * Undo removes the level node.
 * ID must be generated by caller (§2.6).
 */

import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext
} from '../types';
import type { LevelData } from '@pryzm/core-app-model';

export interface CreateHierarchyLevelInput {
    id: string;
    buildingId: string;
    bimLevelId: string;
    name: string;
    code?: string;
    description?: string;
    grossFloorArea?: number;
    levelNumber?: string;
    levelFunction?: string;
    createdBy?: string;
}

export class CreateHierarchyLevelCommand implements Command {
    readonly affectedStores = ["hierarchy"] as const;
    id = crypto.randomUUID();
    type = CommandType.CREATE_HIERARCHY_LEVEL;
    timestamp = Date.now();
    targetIds: string[];

    constructor(private input: CreateHierarchyLevelInput) {
        this.targetIds = [input.id];
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        if (!ctx.stores.hierarchyStore) {
            return { ok: false, reason: 'HierarchyStore not available in CommandContext' };
        }
        if (!this.input.name.trim()) {
            return { ok: false, reason: 'Level name must not be empty' };
        }
        const building = ctx.stores.hierarchyStore.getById(this.input.buildingId);
        if (!building || building.type !== 'building') {
            return { ok: false, reason: `Parent building not found: ${this.input.buildingId}` };
        }
        // Bridge validation: the bimLevelId must reference a real BimManager level
        const bimLevel = ctx.bimManager.getLevelById(this.input.bimLevelId);
        if (!bimLevel) {
            return { ok: false, reason: `BimManager level not found: ${this.input.bimLevelId}` };
        }
        if (ctx.stores.hierarchyStore.has(this.input.id)) {
            return { ok: false, reason: `Level id already exists: ${this.input.id}` };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        const now = Date.now();
        const level: LevelData = {
            id: this.input.id,
            type: 'level',
            name: this.input.name.trim(),
            code: this.input.code,
            description: this.input.description,
            parentId: this.input.buildingId,
            buildingId: this.input.buildingId,
            bimLevelId: this.input.bimLevelId,
            grossFloorArea: this.input.grossFloorArea,
            levelNumber: this.input.levelNumber,
            levelFunction: this.input.levelFunction,
            templateId: undefined,
            plannedData: { customProperties: {} },
            syncState: 'no-template',
            metadata: {
                createdAt: now,
                modifiedAt: now,
                createdBy: this.input.createdBy ?? 'user',
                version: 1,
            },
        };

        ctx.stores.hierarchyStore!.add(level);

        return { success: true, affectedElementIds: [this.input.id] };
    }

    undo(ctx: CommandContext): CommandResult {
        ctx.stores.hierarchyStore?.remove(this.input.id);
        return { success: true, affectedElementIds: [this.input.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
            payload: this.input,
        };
    }
}
