/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Command Layer — Data Platform: IFC Hierarchy
 * File:             src/commands/hierarchy/CreateBuildingCommand.ts
 * Contract:         docs/00_Contracts/01-BIM-ENGINE-CORE-CONTRACT.md §2
 *                   docs/00_Contracts/03-BIM-SEMANTIC-MODEL-CONTRACT.md §2
 *
 * Creates a Building node under a Site in HierarchyStore.
 * canExecute validates siteId exists in hierarchyStore.
 * Undo removes the building node.
 * ID must be generated by caller (§2.6).
 */

import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext
} from '../types';
import type { BuildingData } from '@pryzm/core-app-model';

export interface CreateBuildingInput {
    id: string;
    siteId: string;
    name: string;
    code?: string;
    description?: string;
    grossInternalArea?: number;
    numberOfStoreys?: number;
    buildingUse?: string;
    yearOfCompletion?: number;
    ifcGuid?: string;
    createdBy?: string;
}

export class CreateBuildingCommand implements Command {
    readonly affectedStores = ["hierarchy"] as const;
    id = crypto.randomUUID();
    type = CommandType.CREATE_BUILDING;
    timestamp = Date.now();
    targetIds: string[];

    constructor(private input: CreateBuildingInput) {
        this.targetIds = [input.id];
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        if (!ctx.stores.hierarchyStore) {
            return { ok: false, reason: 'HierarchyStore not available in CommandContext' };
        }
        if (!this.input.name.trim()) {
            return { ok: false, reason: 'Building name must not be empty' };
        }
        const site = ctx.stores.hierarchyStore.getById(this.input.siteId);
        if (!site || site.type !== 'site') {
            return { ok: false, reason: `Parent site not found: ${this.input.siteId}` };
        }
        if (ctx.stores.hierarchyStore.has(this.input.id)) {
            return { ok: false, reason: `Building id already exists: ${this.input.id}` };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        const now = Date.now();
        const building: BuildingData = {
            id: this.input.id,
            type: 'building',
            name: this.input.name.trim(),
            code: this.input.code,
            description: this.input.description,
            parentId: this.input.siteId,
            siteId: this.input.siteId,
            grossInternalArea: this.input.grossInternalArea,
            numberOfStoreys: this.input.numberOfStoreys,
            buildingUse: this.input.buildingUse,
            yearOfCompletion: this.input.yearOfCompletion,
            ifcGuid: this.input.ifcGuid,
            templateId: undefined,
            plannedData: { customProperties: {} },
            syncState: 'no-template',
            metadata: {
                createdAt: now,
                modifiedAt: now,
                createdBy: this.input.createdBy ?? 'user',
                version: 1,
            },
        };

        ctx.stores.hierarchyStore!.add(building);

        return { success: true, affectedElementIds: [this.input.id] };
    }

    undo(ctx: CommandContext): CommandResult {
        ctx.stores.hierarchyStore?.remove(this.input.id);
        return { success: true, affectedElementIds: [this.input.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
            payload: this.input,
        };
    }
}
