/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Command Layer — Data Platform: IFC Hierarchy
 * File:             src/commands/hierarchy/CreateUnitCommand.ts
 * Contract:         docs/00_Contracts/01-BIM-ENGINE-CORE-CONTRACT.md §2
 *                   docs/00_Contracts/03-BIM-SEMANTIC-MODEL-CONTRACT.md §2
 *
 * Creates a Unit node under a Level in HierarchyStore.
 * canExecute validates levelId exists in hierarchyStore with type='level'.
 * Undo removes the unit node.
 * ID must be generated by caller (§2.6).
 */

import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext
} from '../types';
import type { UnitData } from '@pryzm/core-app-model';

export interface CreateUnitInput {
    id: string;
    levelId: string;
    name: string;
    code?: string;
    description?: string;
    unitType?: string;
    unitNumber?: string;
    grossUnitArea?: number;
    numberOfRooms?: number;
    department?: string;
    createdBy?: string;
}

export class CreateUnitCommand implements Command {
    readonly affectedStores = ["hierarchy"] as const;
    id = crypto.randomUUID();
    type = CommandType.CREATE_UNIT;
    timestamp = Date.now();
    targetIds: string[];

    constructor(private input: CreateUnitInput) {
        this.targetIds = [input.id];
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        if (!ctx.stores.hierarchyStore) {
            return { ok: false, reason: 'HierarchyStore not available in CommandContext' };
        }
        if (!this.input.name.trim()) {
            return { ok: false, reason: 'Unit name must not be empty' };
        }
        const level = ctx.stores.hierarchyStore.getById(this.input.levelId);
        if (!level || level.type !== 'level') {
            return { ok: false, reason: `Parent level not found or wrong type: ${this.input.levelId}` };
        }
        if (ctx.stores.hierarchyStore.has(this.input.id)) {
            return { ok: false, reason: `Unit id already exists: ${this.input.id}` };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        const now = Date.now();
        const unit: UnitData = {
            id: this.input.id,
            type: 'unit',
            name: this.input.name.trim(),
            code: this.input.code,
            description: this.input.description,
            parentId: this.input.levelId,
            levelId: this.input.levelId,
            unitType: this.input.unitType,
            unitNumber: this.input.unitNumber,
            grossUnitArea: this.input.grossUnitArea,
            numberOfRooms: this.input.numberOfRooms,
            department: this.input.department,
            templateId: undefined,
            plannedData: { customProperties: {} },
            syncState: 'no-template',
            metadata: {
                createdAt: now,
                modifiedAt: now,
                createdBy: this.input.createdBy ?? 'user',
                version: 1,
            },
        };

        ctx.stores.hierarchyStore!.add(unit);

        return { success: true, affectedElementIds: [this.input.id] };
    }

    undo(ctx: CommandContext): CommandResult {
        ctx.stores.hierarchyStore?.remove(this.input.id);
        return { success: true, affectedElementIds: [this.input.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
            payload: this.input,
        };
    }
}
