/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Semantic Model (Type definitions — no runtime code)
 * File:             src/core/catalog/AssetCatalogTypes.ts
 * Contract:         01-BIM-ENGINE-CORE-CONTRACT §3.1
 *
 * TypeScript interfaces for the AssetCatalog subsystem (Phase 3).
 * Mirrors AssetCatalogSchema.ts exactly — no divergence permitted.
 *
 * An AssetCatalogEntry represents a single equipment archetype whose
 * physical dimensions and clearance requirements can be referenced by
 * RoomRequirements and the DiagnosticMaterialManager ghost-render lens.
 */

// ── Category ──────────────────────────────────────────────────────────────────

export type AssetCategory =
  | 'medical-imaging'
  | 'patient-care'
  | 'diagnostic'
  | 'sterilization'
  | 'laboratory'
  | 'it-infrastructure'
  | 'furniture'
  | 'hvac'
  | 'other';

// ── Parameters ────────────────────────────────────────────────────────────────

export interface AssetCatalogParameters {
  /** Human-readable equipment name — used as lookup key from DeltaMap metrics. */
  name: string;
  category: AssetCategory;
  /** Bounding-box dimensions in millimetres (converted to metres in builders). */
  width_mm: number;
  depth_mm: number;
  height_mm: number;
  /** Peak electrical demand in kilowatts. Optional — informational only. */
  powerDraw_kw?: number;
  /** Total weight in kilograms. Optional — used for structural load notes. */
  weight_kg?: number;
  /**
   * Required clearance bubble radius in millimetres around the asset footprint.
   * Used by DiagnosticMaterialManager to render clearance discs in assets lens.
   */
  clearanceRadius_mm?: number;
}

// ── Metadata ──────────────────────────────────────────────────────────────────

export interface AssetCatalogMetadata {
  createdAt:  number;
  modifiedAt: number;
  createdBy:  string;
  version:    number;
}

// ── Entry (top-level entity) ──────────────────────────────────────────────────

export interface AssetCatalogEntry {
  /** Stable UUID — supplied by caller, never generated by store. */
  id: string;
  /** Discriminator — always 'AssetCatalogEntry'. */
  type: 'AssetCatalogEntry';
  /**
   * All catalog entries share the sentinel levelId 'CATALOG'.
   * They are project-level assets, not assigned to any specific floor.
   */
  levelId: 'CATALOG';
  parameters: AssetCatalogParameters;
  metadata:   AssetCatalogMetadata;
}

// ── Partial update shape ──────────────────────────────────────────────────────

export interface AssetCatalogParamUpdate {
  parameters?: Partial<AssetCatalogParameters>;
}
