// CreateBalconyHandler — ONE gesture, ONE undo entry, THREE kinds of member.
//
// §FEAT-BALCONY-COMPOUND (L-5600) · C103 §6 · C16 §8.6 · C11 §11.2 · ADR-0333
//
// ═══════════════════════════════════════════════════════════════════════════════
// READ THE UNDO ARGUMENT BEFORE CHANGING ANYTHING.
// ═══════════════════════════════════════════════════════════════════════════════
//
// Creating a balcony touches FOUR stores:
//
//     balcony   ← the compound parent (new)
//     slab      ← the cantilever plate (new)
//     floor     ← the floor finish     (new)
//     handrail  ← N railing runs, one per FREE edge (new)
//
// C16 §8.6 B-6 is unambiguous and was measured, not assumed:
//
//   > "One gesture = one undo entry" is bought by dispatching ONE command (one
//   >  produceCommand → one Immer patch pair → one ring entry). It is NEVER bought
//   >  by holding a batch open. `runBatch()` is UNDO-NEUTRAL.
//
// So this is ONE command — not five, and not five wrapped in a `runBatch`, which
// would still cost the user five Ctrl+Zs.
//
// ⛔ AND IT IS DELIBERATELY *NOT* A `CompositeCommand`. That class reports success
// unconditionally `true` in BOTH directions and counts children ATTEMPTED rather
// than LANDED (L-2401). A compound built on it would report a balcony it had not
// created. `produceMultiStoreCommand` emits ONE patch pair whose inverse is
// generated by Immer from the actual mutation, so "the undo undoes what happened"
// is a property of the machinery rather than a claim in a comment.
//
// A balcony spans four stores, and a multi-store command routes its patches by
// `path[0] === storeKey` (CommandBus.ts + `applyRingBufferSide`; the §U-B6 guard
// hard-errors otherwise). `produceCommand` / `produceWithPatchesPerStore` emit
// store-RELATIVE paths, so their patches would route to NOTHING and Ctrl+Z would
// silently do nothing at all. `produceMultiStoreCommand()` is the ONLY correct
// chokepoint for this handler.
//
// ─── ⚠ WHY THE WALL STORE IS *NOT* DECLARED, AND THE HOST GEOMETRY IS PASSED IN ──
// The assembly needs the host wall's CENTRELINE to decide which edges are free. The
// obvious move is to declare `wall` in `affectedStores` and read it from
// `ctx.stores.wall`. That is refused here for two reasons:
//
//   1. `affectedStores` is the UNDO ROUTING declaration (CA-6 / §U-B6). Naming a
//      store this command never writes makes the declaration untrue, and the next
//      author cannot tell a read-only entry from a write the command forgot to make.
//   2. `execute()` RE-RUNS ON REDO. A centreline read from the store at redo time is
//      a DIFFERENT value if the wall moved in between — the balcony would silently
//      change shape on redo. A value carried in the payload cannot (CA-2's reasoning,
//      applied to geometry rather than to ids).
//
// So the caller resolves the segment once, at the gesture, and passes it. A caller
// that names a `hostWallId` and cannot resolve its baseline is REFUSED by name — see
// `BalconyHostWallError` for why that is a refusal rather than a quiet degradation.

import {
  produceMultiStoreCommand,
  withHandlerSpan,
  type CommandHandler,
  type HandlerContext,
  type HandlerResult,
  type ValidationResult,
} from '@pryzm/plugin-sdk';
import {
  buildBalconyAssembly,
  resolveFreeEdges,
  type BalconySystemType,
  type HostWallSegment,
} from '@pryzm/geometry-balcony';
import { Balcony } from '@pryzm/plugin-sdk';
import { BalconyBoundaryError, BalconyHostWallError, BalconyMemberIdError } from '../errors.js';
import type { BalconiesState, BalconyData } from '../store.js';

/**
 * The payload. Every id is PRE-MINTED by the caller (the tool), never generated in
 * here — CA-2: ids MUST be identical across redo, and `execute()` runs again on redo.
 * Minting inside would give a DIFFERENT balcony on redo, silently.
 */
export interface CreateBalconyPayload {
  readonly balconyId: string;
  readonly levelId: string;
  /** Plan outline, WORLD coords, OPEN loop. THE single source of truth. */
  readonly boundary: readonly { x: number; y: number; z: number }[];

  /** The wall this balcony attaches to. Absent = free-standing (railed all round). */
  readonly hostWallId?: string;
  /** Arc length along the host centreline to the balcony's LEFT edge, metres. */
  readonly hostOffset?: number;
  /**
   * The host wall's CENTRELINE, resolved by the caller at the gesture.
   * REQUIRED whenever `hostWallId` is set — see the header for why it is not read
   * from a store here.
   */
  readonly hostSegment?: HostWallSegment;

  // ── Pre-minted member ids ──────────────────────────────────────────────────
  readonly slabId: string;
  readonly floorId: string;
  /** One per FREE edge of `boundary`, in free-edge order. */
  readonly railingIds: readonly string[];

  // ── Optional parametric overrides — unset resolves via systemType → default ──
  readonly width?: number;
  readonly projection?: number;
  readonly railingHeight?: number;
  readonly slabThickness?: number;
  readonly finishThickness?: number;
  readonly systemTypeId?: string;
  readonly railingTypeId?: string;
  readonly finishTypeId?: string;
  readonly materialId?: string;
  readonly materialColor?: string;
  /** Resolved system type (tier 2 of the dimension chain). */
  readonly systemType?: BalconySystemType;
}

/** The stores a balcony touches. All four MUST be declared — see the header. */
type BalconyHandlerStores = Readonly<
  {
    balcony: BalconiesState;
    slab: Record<string, unknown>;
    floor: Record<string, unknown>;
    handrail: Record<string, unknown>;
  } & Record<string, unknown>
>;

// eslint-disable-next-line pryzm/store-single-channel -- CA-6/§U-B6: this command
// REALLY writes four stores; declaring fewer drops the undeclared stores' patches
// from undo routing (Ctrl+Z would remove the balcony record but leave its slab,
// finish and railings in the model). The rule has no multi-store option; the
// declaration below is the truth.
export class CreateBalconyHandler
  implements CommandHandler<CreateBalconyPayload, BalconyHandlerStores>
{
  readonly type = 'balcony.create';

  /**
   * CA-6 / §U-B6. FOUR stores, because the command really does write four. Declaring
   * fewer would silently DROP the undeclared store's patches from undo routing —
   * Ctrl+Z would then remove the balcony and LEAVE ITS RAILING FLOATING IN THE AIR,
   * which is strictly worse than no feature.
   */
  // eslint-disable-next-line pryzm/store-single-channel -- CA-6/§U-B6: see above.
  readonly affectedStores = ['balcony', 'slab', 'floor', 'handrail'] as const;

  canExecute(
    ctx: HandlerContext<BalconyHandlerStores>,
    cmd: CreateBalconyPayload,
  ): ValidationResult {
    if (typeof cmd.balconyId !== 'string' || cmd.balconyId.length === 0) {
      return { valid: false, reason: 'balconyId must be a non-empty string' };
    }
    if (ctx.stores.balcony[cmd.balconyId]) {
      return { valid: false, reason: `duplicate balcony id: ${cmd.balconyId}` };
    }
    if (!Array.isArray(cmd.boundary) || cmd.boundary.length < 3) {
      return { valid: false, reason: 'balcony boundary needs >= 3 vertices' };
    }
    // ⭐ CA-3 — a NAMED host that cannot be resolved is a refusal, never a silent
    // fall-through to the free-standing branch. Taking that branch would rail the
    // doorway shut, and "failure" and "no host" would have become the same value.
    if (cmd.hostWallId !== undefined && cmd.hostSegment === undefined) {
      return {
        valid: false,
        reason:
          `balcony names host wall ${cmd.hostWallId} but no hostSegment was resolved for it. ` +
          `Resolve the wall's centreline at the gesture and pass it, or omit hostWallId for a ` +
          `free-standing balcony (which is railed all round).`,
      };
    }
    if (ctx.stores.slab[cmd.slabId]) {
      return { valid: false, reason: `duplicate slab id: ${cmd.slabId}` };
    }
    if (ctx.stores.floor[cmd.floorId]) {
      return { valid: false, reason: `duplicate floor id: ${cmd.floorId}` };
    }
    // CA-3 — geometry non-degenerate. The Balcony schema refines this too, but failing
    // here means we fail with a `reason` instead of throwing mid-mutation.
    const parsed = Balcony.safeParse(this._recordOf(cmd));
    if (!parsed.success) {
      return { valid: false, reason: parsed.error.issues[0]?.message ?? 'invalid balcony' };
    }
    // ⭐ The railing count is a function of the OUTLINE, not of the payload's opinion
    // about it. Asked here so the refusal carries the real number.
    const free = resolveFreeEdges(parsed.data.boundary, cmd.hostSegment);
    if (cmd.railingIds.length !== free.length) {
      return {
        valid: false,
        reason:
          `expected ${free.length} pre-minted railing ids (one per FREE edge of this outline), ` +
          `got ${cmd.railingIds.length}`,
      };
    }
    return { valid: true };
  }

  execute(ctx: HandlerContext<BalconyHandlerStores>, cmd: CreateBalconyPayload): HandlerResult {
    return withHandlerSpan(this.type + '.handler', { 'pryzm.command.type': this.type }, () => {
      if (cmd.hostWallId !== undefined && cmd.hostSegment === undefined) {
        throw new BalconyHostWallError(
          `balcony names host wall ${cmd.hostWallId} but no hostSegment was resolved for it.`,
        );
      }

      const parsed = Balcony.safeParse(this._recordOf(cmd));
      if (!parsed.success) {
        throw new BalconyBoundaryError(parsed.error.issues[0]?.message ?? 'invalid balcony');
      }
      const balcony: BalconyData = parsed.data;

      // The PURE assembly (@pryzm/geometry-balcony). Every dimension it uses resolves
      // through `resolveBalconyDimensions()` — record → systemType → documented
      // default. There is not a single dimensional literal below, and the no-literals
      // guard in geometry-balcony enforces that at source level.
      let asm;
      try {
        asm = buildBalconyAssembly(
          balcony,
          { slabId: cmd.slabId, floorId: cmd.floorId, railingIds: cmd.railingIds },
          { hostSegment: cmd.hostSegment, systemType: cmd.systemType },
        );
      } catch (e) {
        // Re-typed, never swallowed: the assembly's only throw is the stale
        // railing-id count, and a typed error is what lets the tool surface it.
        throw new BalconyMemberIdError(e instanceof Error ? e.message : String(e));
      }

      // The balcony OWNS its members (C103 §2): `childrenIds` on the parent,
      // `parentId` on each member (the assembly stamps the latter). One thing to
      // select, move and delete — while each member stays independently selectable.
      const balconyRecord: BalconyData = {
        ...balcony,
        childrenIds: [cmd.slabId, cmd.floorId, ...cmd.railingIds],
      };

      // ── THE ONE PATCH PAIR ────────────────────────────────────────────────────
      const out = produceMultiStoreCommand(
        {
          balcony: ctx.stores.balcony,
          slab: ctx.stores.slab,
          floor: ctx.stores.floor,
          handrail: ctx.stores.handrail,
        },
        {
          balcony: (d) => {
            (d as Record<string, unknown>)[cmd.balconyId] = balconyRecord;
          },
          slab: (d) => {
            (d as Record<string, unknown>)[cmd.slabId] = asm.slab;
          },
          floor: (d) => {
            (d as Record<string, unknown>)[cmd.floorId] = asm.finish;
          },
          handrail: (d) => {
            const draft = d as Record<string, unknown>;
            for (const r of asm.railings) draft[r.id] = r;
          },
        },
      );

      return { forward: out.forward, inverse: out.inverse, nextStates: out.nextStates };
    }); // withHandlerSpan — CA-14 / C10 §2, merge-blocking
  }

  /** The balcony record as the schema sees it (used by BOTH canExecute and execute so
   *  they cannot disagree about what a valid balcony is). */
  private _recordOf(cmd: CreateBalconyPayload): unknown {
    return {
      id: cmd.balconyId,
      type: 'balcony',
      levelId: cmd.levelId,
      boundary: cmd.boundary,
      ...(cmd.hostWallId !== undefined ? { hostWallId: cmd.hostWallId } : {}),
      ...(cmd.hostOffset !== undefined ? { hostOffset: cmd.hostOffset } : {}),
      ...(cmd.width !== undefined ? { width: cmd.width } : {}),
      ...(cmd.projection !== undefined ? { projection: cmd.projection } : {}),
      ...(cmd.railingHeight !== undefined ? { railingHeight: cmd.railingHeight } : {}),
      ...(cmd.slabThickness !== undefined ? { slabThickness: cmd.slabThickness } : {}),
      ...(cmd.finishThickness !== undefined ? { finishThickness: cmd.finishThickness } : {}),
      ...(cmd.systemTypeId ? { systemTypeId: cmd.systemTypeId } : {}),
      ...(cmd.railingTypeId ? { railingTypeId: cmd.railingTypeId } : {}),
      ...(cmd.finishTypeId ? { finishTypeId: cmd.finishTypeId } : {}),
      ...(cmd.materialId ? { materialId: cmd.materialId } : {}),
      ...(cmd.materialColor ? { materialColor: cmd.materialColor } : {}),
    };
  }
}
