import { z } from 'zod';
import { defineElement } from '../base/BaseNode.js';
import { RetrofittedProvenanceSchema } from '../provenance/ValueOrigin.js';
import { RetrofittedConfidenceSchema } from '../provenance/ElementConfidence.js';
import { ElementDerivedFromSchema } from '../provenance/ElementDerivation.js';
import { Vec3 } from '../base/primitives.js';

/**
 * Linear or curved wall between two points on a level.
 *
 * The canonical schema; every other element family follows this template.
 *
 * Geometry: `baseLine` is a 2-tuple of world-XZ endpoints (the `y` component
 * holds the level elevation per PRYZM 1's §WALL-AUDIT-2026-M7 convention).
 * If `curve` is present, the wall is a quadratic-Bézier arc between those
 * endpoints via `curve.control`; absent means straight.
 */
const WallLayerFunction = z.enum([
  'finish-exterior',
  'substrate',
  'insulation',
  'air-barrier',
  'structure',
  'finish-interior',
]);

const WallLayer = z.object({
  name: z.string().min(1),
  function: WallLayerFunction,
  /** Layer thickness in metres; must be > 0. */
  thickness: z.number().positive(),
  materialId: z.string().optional(),
  materialColor: z.string().optional(),
});

const Opening = z.object({
  id: z.string().min(1),
  type: z.enum(['window', 'door']),
  doorType: z.enum(['single', 'double']).optional(),
  windowType: z.enum(['single', 'double']).optional(),
  /** Distance along the wall baseline from start, in metres. */
  offset: z.number().nonnegative(),
  width: z.number().positive(),
  height: z.number().positive(),
  sillHeight: z.number().nonnegative(),
  elementId: z.string().min(1),
});

const WallCurve = z.object({
  /** Quadratic-Bézier control point in world space (XZ plane). */
  control: Vec3,
  /** Tessellation segment count; min 4, recommend 16–32. */
  segments: z.number().int().min(4).default(16),
});

const WallSide = z.enum(['interior', 'exterior', 'unknown']);

export const Wall = defineElement('wall', {
  /**
   * PV-04 / C75 §2.4 — where this element's values came from: one of the five
   * (`ValueOrigin.ts`, which owns the vocabulary and is never restated here),
   * or an explicit unknown carrying its reason.
   *
   * ⚠ `RetrofittedProvenanceSchema`, spelled out at every kind rather than
   * spread from a shared constant or folded into `BaseNodeShape`, and that is
   * deliberate twice over. C75 §2.5 requires optional-with-an-UNKNOWN-default so
   * a snapshot written before this field existed parses unchanged and lands on
   * `predates-provenance` — never on a member of the five (§2.1 and §2.5 are the
   * same rule). And `check-provenance-coverage` measures the file that declares
   * `defineElement('<kind>')`: an indirection hides the field from the C3
   * retrofit-safety arm, so coverage you cannot see at the point of use is the
   * §4.d defect in a new place.
   */
  provenance: RetrofittedProvenanceSchema,
  /**
   * PV-06 / C75 §1.3 — how much this element's values can be TRUSTED. A
   * separate axis from `provenance`: that says where a value came from, this
   * says how sure we are of it, and C75 §1.2 forbids merging axes.
   *
   * ⚠ `RetrofittedConfidenceSchema`, spelled out at every kind rather than
   * spread from a shared constant or folded into `BaseNodeShape` — the same
   * instruction `RetrofittedProvenanceSchema` carries above, for the same
   * measured reason. Optional with an UNKNOWN-with-reason default, so a
   * record written before this field existed parses unchanged and lands on
   * `pending-implementation` — never on a tier, never on `score: 0`.
   *
   * The vocabulary is C62's (`site/metadata/DataConfidence.ts`, ADR-0280),
   * REUSED not reinvented: PV-06 says C62 owns confidence (§4.h).
   */
  confidence: RetrofittedConfidenceSchema,
  /**
   * §WALL-PROVENANCE (L-13117) — WHICH ELEMENT THIS WALL CAME OUT OF, and which edge
   * of it. The element-lineage half of provenance; `provenance` above is the ORIGIN
   * half and C75 §1.2 forbids merging the two axes.
   *
   * ⭐ WHY IT HAD TO EXIST. `provenance: {origin, detail?}` carries NO ELEMENT ID, so a
   * wall could say *"a machine computed me"* and could not say *"…out of envelope
   * E-ground, edge 3"*. That gap is why the envelope→wall relationship lived ONLY in a
   * semantic-graph side table that exactly ONE producer (`buildFromDesignExecutor.ts`)
   * writes — so a building generated by any other route reported *"No walls are linked
   * to this envelope yet"* on a face drag and moved nothing (L-13117). A link carried by
   * the wall itself is derivable from the model; a side table is N places to forget.
   *
   * ⛔ **OPTIONAL WITH NO DEFAULT, and never `.default([])`.** Absent means NOT RECORDED
   * — a wall saved before this field existed, or a producer that does not stamp. An
   * EMPTY array means a stamping producer looked and found no source. Those are
   * different facts (§CONTEXT-DATA-HONESTY) and a default would collapse the first into
   * the second on the first parse of every legacy record. Exactly the shape and the
   * rationale of `joinIntent` below (C47 §1.2 additive-optional — a pre-L-13117 snapshot
   * parses unchanged and re-serialises byte-identically).
   *
   * An ARRAY because one wall can bound two sources, and because C80's "two envelopes
   * placing one wall differently ⇒ CONTESTED, dropped and surfaced" is only statable if
   * both rival claims can be present. See `ElementDerivation.ts` for the full rationale.
   */
  derivedFrom: ElementDerivedFromSchema,
  /** Owning level id. Walls without a level are invalid. */
  levelId: z.string().default(''),
  baseLine: z
    .tuple([Vec3, Vec3])
    .default([
      { x: 0, y: 0, z: 0 },
      { x: 1, y: 0, z: 0 },
    ]),
  curve: WallCurve.optional(),
  /** Wall height in metres. */
  height: z.number().positive().default(2.5),
  /** Wall thickness in metres. */
  thickness: z.number().min(0.05).default(0.1),
  /** Vertical offset from level base, in metres. */
  baseOffset: z.number().default(0),
  openings: z.array(Opening).default([]),
  materialId: z.string().optional(),
  materialColor: z.string().optional(),
  systemTypeId: z.string().optional(),
  layers: z.array(WallLayer).optional(),
  frontSide: WallSide.optional(),
  backSide: WallSide.optional(),
  /**
   * §WALL-JOIN-INTENT (L-251 → L-923 → L-927) — what the AUTHOR DID at each endpoint.
   *
   * A mitred corner and a T-junction are the SAME GEOMETRY: two collinear walls meeting a
   * third at a node is either a through-wall plus a stem (square caps) or a committed
   * mitred L plus a butting newcomer (freeze the corner). L-923 proved they are not
   * separable after the fact — identical topology, identical types, differing ONLY in
   * draw order — so this records the gesture at creation instead of asking the resolver
   * to guess. `'butt'` = snapped onto an already-committed junction; `'through'` =
   * continuing a run.
   *
   * OPTIONAL, AND DELIBERATELY WITHOUT A DEFAULT (C47 §1.2 additive-optional). Absent
   * means "unknown / legacy", and the resolver's behaviour for absent is EXACTLY what it
   * was before this field existed — which is what lets every snapshot written before
   * L-927 parse unchanged. A default would be worse than useless here: it would assert a
   * gesture the author never made, and (unlike provenance/confidence above) there is no
   * honest UNKNOWN member to land on, because the resolver branches on presence.
   */
  joinIntent: z
    .object({
      start: z.enum(['butt', 'through']).optional(),
      end: z.enum(['butt', 'through']).optional(),
    })
    .optional(),
})
  // (1) MIN_WALL_LEN: planar baseline length must clear the join-resolver
  //     minimum so the wall is non-degenerate. Y axis is intentionally ignored
  //     because baseLine.y carries the level elevation, not planar length.
  //     Mirrors `WallDataSchema` §WALL-AUDIT-2026 (RESOLVED 2026-04-24).
  .refine(
    (w) => {
      const [a, b] = w.baseLine;
      return Math.hypot(a.x - b.x, a.z - b.z) >= 0.05;
    },
    { message: 'Wall too short: baseLine endpoints must be ≥ 0.05 m apart in the XZ plane.' },
  )
  // (2) baseLine endpoint y-consistency: both endpoints must share the same
  //     elevation. A wall baseLine is a horizontal segment by contract;
  //     divergent y values indicate a stale cascade or mis-projected drag.
  .refine(
    (w) => w.baseLine[0].y === w.baseLine[1].y,
    { message: 'Wall baseLine endpoints must share the same y (level elevation).' },
  )
  // (3) Derived-index invariant: `childrenIds` must be a set-superset of
  //     `openings[*].elementId`. Mirrors WallStore's belt-and-braces guard
  //     so the parametric-vs-geometric child sets cannot drift.
  .refine(
    (w) => {
      if (w.openings.length === 0) return true;
      const have = new Set(w.childrenIds);
      return w.openings.every((o) => have.has(o.elementId));
    },
    { message: 'Wall.childrenIds must be a superset of openings[*].elementId.' },
  );

export type Wall = z.infer<typeof Wall>;
