import { z } from 'zod';

/**
 * Finish layer schema — compatible with WindowFinishLayer in WindowSystemTypeStore.
 * Defines a named finish material applied to a window component (frame, sill, glass).
 * Stamped onto WindowOpening at creation time from the selected WindowSystemType.
 */
export const WindowFinishLayerSchema = z.object({
    name:          z.string(),
    materialColor: z.string().default('#e8e8e8'),
    materialId:    z.string().optional(),
    description:   z.string().optional(),
});
export type WindowFinishLayerData = z.infer<typeof WindowFinishLayerSchema>;

/**
 * Rich parametric window record stored in WindowStore.
 *
 * KEY DESIGN RULE: `id` == `Opening.elementId` in WallData.openings[].
 * OFFSET ENCODING (PLAN-09 — CENTER convention): `offset` is the absolute distance
 * in metres from baseLine[0] to the CENTRE of the opening.
 * LEFT_EDGE = offset − width/2; RIGHT_EDGE = offset + width/2.
 * Same convention as DoorTypes.ts and Opening.offset in WallTypes.ts.
 */
export const WindowOpeningSchema = z.object({
    // Identity
    id:        z.string().min(1),   // == Opening.elementId
    openingId: z.string().min(1),   // == Opening.id
    wallId:    z.string().min(1),

    // Geometry
    offset:     z.number().nonnegative(),
    width:      z.number().positive(),
    height:     z.number().positive(),
    sillHeight: z.number().nonnegative(),

    // Frame
    frameThickness: z.number().positive().default(0.05),
    frameDepth:     z.number().positive().default(0.07),
    frameColor:     z.string().default('#e8e8e8'),

    // Glazing grid — adopted from Pascal WindowNode (gold standard)
    // [0.5, 0.5] = two equal panes, [1] = single pane
    columnRatios:           z.array(z.number().positive()).min(1).default([1]),
    rowRatios:              z.array(z.number().positive()).min(1).default([1]),
    columnDividerThickness: z.number().nonnegative().default(0.03),
    rowDividerThickness:    z.number().nonnegative().default(0.03),

    // Sill
    sill:           z.boolean().default(true),
    sillDepth:      z.number().nonnegative().default(0.08),
    sillThickness:  z.number().nonnegative().default(0.03),

    // Glass
    glassOpacity: z.number().min(0).max(1).default(0.3),

    // IFC / BIM fields
    windowType: z.enum(['single', 'double']).default('single'),
    fireRating: z.string().optional(),

    // DW-12 FIX: Persistent mark stored on the element instance.
    // Format: W-<NNN> (e.g. "W-001", "W-002").
    // Auto-generated by CreateWallOpeningCommand at placement time.
    // Editable by the user via the property panel markInput.
    mark: z.string().optional(),

    // Finish — structured finish layers stamped from WindowSystemType at creation time.
    // These are the primary BIM finish records; frameColor is derived from frameFinish
    // for the 3-D renderer (backward-compatible render field preserved).
    frameFinish: WindowFinishLayerSchema.optional(),
    sillFinish:  WindowFinishLayerSchema.optional(),

    // Derived finish material name for room finish schedules (auto-set from frameFinish.name)
    finishMaterial: z.string().optional(),

    // Type system — reference to the WindowSystemType that generated this window's finish defaults
    systemTypeId:   z.string().optional(),
});

export type WindowOpening = z.infer<typeof WindowOpeningSchema>;
