// §MATERIAL-UPSTREAM-LEDGER (L-9700) — C100 §1.1 / §10.6 / §10.14.
//
// ═════════════════════════════════════════════════════════════════════════════
// WHY A LEDGER, AND WHY IT IS CODE RATHER THAN A COMMENT
// ═════════════════════════════════════════════════════════════════════════════
//
// The rule this file makes structural was already TRUE and already WRITTEN — in
// three separate prose places, none of which a compiler or a gate can read:
//
//   · `tools/texture-pipeline/README.md`   — "No file from pascalorg/editor is
//     copied, downloaded, vendored or derived from. We take the taxonomy only."
//   · `tools/texture-pipeline/sources/materials.json` `$comment` — the same
//     sentence, in a JSON comment key.
//   · `docs/04-reference/PASCAL-FINISHES-RESEARCH.md` §0.2 — the measurement
//     behind it.
//
// ⛔ A rule stated in three prose places and enforced in one script's allowlist
// is enforced for exactly the path that runs that script. It says nothing about a
// row typed straight into `materialCatalog.ts`, which is how EVERY procedural row
// and every hand-authored row arrives. So the ledger moves next to the DATA.
//
// ⭐ THE SHAPE IS NOT INVENTED HERE. It is lane RATE53's, adopted deliberately:
// `packages/core-app-model/src/quantities/RegionalRates.ts` established that a
// source carries a three-valued licence verdict PLUS `licenceNote` — "the
// sentence in the licence that decided it" — and that `NOT_ESTABLISHED` is the
// honest default and is NOT a synonym for "probably fine". Minting a second
// spelling of that idea one package over would be C100 §1.1's own "MUST NOT mint
// a second enumeration", applied to licensing instead of to colour.
//
// ⚠ STILL PURE (P5 / C03 §1.2). Plain strings and frozen arrays. No I/O, no
// THREE, no DOM, no network. Nothing here READS a licence; it RECORDS that a
// human did, and what the licence said.
// ═════════════════════════════════════════════════════════════════════════════

/**
 * ⛔ THE FIELD THAT DECIDES WHETHER A CATALOGUE ROW MAY SHIP AT ALL.
 *
 * Adopted verbatim from `RateLicenceStatus` (lane RATE53) so the repository has
 * ONE licence vocabulary rather than one per subsystem.
 */
export type MaterialLicenceStatus =
    /** A licence text was READ and permits redistribution inside this product. Cite it in `licenceNote`. */
    | 'CLEARED_FOR_REDISTRIBUTION'
    /** A licence text was READ and FORBIDS redistribution (or does not grant it). The bytes stay out. */
    | 'LICENSED_NOT_REDISTRIBUTABLE'
    /**
     * ⛔ Nobody has read a licence that covers this, or the chain of title cannot be
     * established. NOT "probably fine". No shipped row may name an upstream in this
     * state, and `unclearedMaterialUpstreams()` exists to prove none does.
     */
    | 'NOT_ESTABLISHED';

/**
 * WHAT we took from an upstream. ⭐ This axis is SEPARATE from the licence verdict
 * on purpose, and separating them is the whole finding of lane PASCALMAT58:
 *
 * `pascalorg/editor` is ONE repository with TWO different answers. Its TypeScript
 * is MIT and reusable; its 288 texture binaries have no statement of origin
 * anywhere in a complete tree walk, and MIT covers what the authors had the right
 * to license — it is not a warranty over third-party binaries someone committed
 * into `public/`. Collapsing "the repo is MIT" into "therefore the pixels are
 * ours to ship" is exactly the conflation this type prevents at the type level.
 */
export type MaterialUpstreamTake =
    /** Bitmap files that ship to a user's browser. The strictest case. */
    | 'PIXELS'
    /** Source code or data structures copied or adapted. */
    | 'CODE'
    /**
     * The IDEA of which finishes a building editor needs, and nothing expressive.
     * ⭐ A taxonomy is an idea, not an expression, and is not a licensing question
     * at all — recorded anyway, because "we looked at it" is a fact a diligence
     * review is entitled to see stated rather than inferred.
     */
    | 'TAXONOMY'
    /** Generated by our own arithmetic, or authored by us from trade product ranges. */
    | 'ORIGINAL';

/** Stable ids for every upstream any catalogue row may name. */
export type MaterialUpstreamId =
    | 'pryzm-authored'
    | 'pryzm-procedural'
    | 'ambientcg'
    | 'pascalorg-editor-taxonomy'
    | 'pascalorg-editor-textures';

/**
 * One upstream a material's data or bytes may have come from.
 *
 * ⛔ `licenceNote` is `null` ONLY where `licence` is `NOT_ESTABLISHED`. A verdict
 * with no sentence behind it is an opinion, and RATE53 already ruled that an
 * opinion may not stand in for a licence reading.
 */
export interface MaterialUpstream {
    readonly id: MaterialUpstreamId;
    /** The upstream in its own name, as it would be cited in a diligence review. */
    readonly name: string;
    /** Where to go and check. `null` only for our own work. */
    readonly homepage: string | null;
    /** SPDX id where one applies, else a short description. `null` when unestablished. */
    readonly licence: string | null;
    readonly status: MaterialLicenceStatus;
    /**
     * ⭐ THE SENTENCE IN THE LICENCE THAT DECIDED IT — quoted, not paraphrased.
     * A paraphrase is a second reading of a text the reader cannot see.
     */
    readonly licenceNote: string | null;
    /** ISO `YYYY-MM-DD` a human read the licence text. `null` when unread. */
    readonly verifiedOn: string | null;
    /** What we took. See {@link MaterialUpstreamTake}. */
    readonly take: MaterialUpstreamTake;
    /**
     * ⭐ Whether shipping this obliges us to reproduce a notice. When TRUE the text
     * in `attributionText` MUST appear in the shipped `NOTICE.md`, and
     * `materialUpstreamsRequiringNotice()` is what proves it does.
     */
    readonly attributionRequired: boolean;
    /** Exactly what must be reproduced. `null` iff `attributionRequired` is false. */
    readonly attributionText: string | null;
    /** Why this verdict, in one line — the reasoning, kept beside the quote. */
    readonly rationale: string;
}

/**
 * THE LEDGER. Every upstream, with the sentence that decided it.
 *
 * ⚠ Two rows for one repository is deliberate and is the point of the file.
 */
export const MATERIAL_UPSTREAMS: readonly MaterialUpstream[] = Object.freeze([
    {
        id: 'pryzm-authored',
        name: 'PRYZM (authored)',
        homepage: null,
        licence: 'Proprietary — PRYZM',
        status: 'CLEARED_FOR_REDISTRIBUTION',
        licenceNote: 'Authored in this repository. No third-party grant is relied upon.',
        verifiedOn: '2026-08-23',
        take: 'ORIGINAL',
        attributionRequired: false,
        attributionText: null,
        rationale:
            'The ~245 colour/roughness/metalness rows that carry no maps. Scalars authored from '
            + 'trade product ranges; a hex and a roughness are facts about a product, not an '
            + "expression copied from anyone's file.",
    },
    {
        id: 'pryzm-procedural',
        name: 'PRYZM (@pryzm/procedural-textures)',
        homepage: null,
        licence: 'Proprietary — PRYZM',
        status: 'CLEARED_FOR_REDISTRIBUTION',
        licenceNote: 'Generated by arithmetic in this repository. There is no upstream file.',
        verifiedOn: '2026-08-23',
        take: 'ORIGINAL',
        attributionRequired: false,
        attributionText: null,
        rationale:
            "⭐ The half that CANNOT have a licence problem, because it has no file. A generator "
            + 'id is not an asset: the pixels are computed from millimetre product dimensions at '
            + 'run time. C100 §10.9.c: "no file, no bucket, no CORS and no decoder" — and, it '
            + 'follows, no chain of title to establish.',
    },
    {
        id: 'ambientcg',
        name: 'ambientCG',
        homepage: 'https://ambientcg.com',
        licence: 'CC0-1.0',
        status: 'CLEARED_FOR_REDISTRIBUTION',
        licenceNote:
            'You can copy, modify, distribute and perform the assets, even for commercial '
            + 'purposes, all without asking permission.',
        verifiedOn: '2026-08-21',
        take: 'PIXELS',
        attributionRequired: false,
        attributionText: null,
        rationale:
            'Read at https://docs.ambientcg.com/license/ by lane MAT-2 on 2026-08-21 and re-asserted '
            + 'mechanically before every network call by `tools/texture-pipeline/acquire.mjs`. '
            + 'Attribution is NOT required under CC0; `textures.manifest.json` records source URL, '
            + 'retrieval date and a SHA-256 per file anyway, because a library with no provenance '
            + 'record is how the row below came to exist.',
    },
    {
        id: 'pascalorg-editor-taxonomy',
        name: 'pascalorg/editor — the manifest and its taxonomy',
        homepage: 'https://github.com/pascalorg/editor',
        licence: 'MIT',
        status: 'CLEARED_FOR_REDISTRIBUTION',
        licenceNote:
            'The above copyright notice and this permission notice shall be included in all copies '
            + 'or substantial portions of the Software.',
        verifiedOn: '2026-08-23',
        take: 'TAXONOMY',
        attributionRequired: true,
        attributionText:
            'Portions of PRYZM’s material taxonomy — specifically the observation that a '
            + 'building editor’s finishes declare which element slots they suit — were informed '
            + 'by pascalorg/editor (MIT).\n\n'
            + 'MIT License\nCopyright (c) 2026 Pascal Group Inc.\n\n'
            + 'Permission is hereby granted, free of charge, to any person obtaining a copy of this '
            + 'software and associated documentation files (the "Software"), to deal in the Software '
            + 'without restriction, including without limitation the rights to use, copy, modify, '
            + 'merge, publish, distribute, sublicense, and/or sell copies of the Software, and to '
            + 'permit persons to whom the Software is furnished to do so, subject to the following '
            + 'conditions:\n\n'
            + 'The above copyright notice and this permission notice shall be included in all copies '
            + 'or substantial portions of the Software.\n\n'
            + 'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, '
            + 'INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A '
            + 'PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT '
            + 'HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF '
            + 'CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE '
            + 'OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
        rationale:
            '⭐ THE ATTRIBUTION IS RETAINED EVEN THOUGH IT IS ARGUABLY NOT OWED. A taxonomy is an '
            + 'idea and ideas are not licensable, so taking "materials declare their suitable '
            + 'surfaces" needs no grant at all. It is recorded and reproduced anyway because the '
            + 'cost of a NOTICE entry is nothing and the cost of being wrong about where the '
            + 'idea/expression line sits is not. ⛔ NO CODE and NO SHAPE was copied: Pascal’s '
            + '`MaterialCatalogItem` carries `side`, `flipY`, `wrapS`, `normalScaleX/Y`, '
            + '`lightMapIntensity` — renderer state that would breach P5 / C03 §1.2 at L0. See '
            + 'PASCAL-FINISHES-RESEARCH §0.2(a).',
    },
    {
        id: 'pascalorg-editor-textures',
        name: 'pascalorg/editor — the 288 texture binaries',
        homepage: 'https://github.com/pascalorg/editor',
        licence: null,
        status: 'NOT_ESTABLISHED',
        licenceNote: null,
        verifiedOn: null,
        take: 'PIXELS',
        attributionRequired: false,
        attributionText: null,
        rationale:
            '⛔ NO ROW MAY NAME THIS UPSTREAM. Re-measured 2026-08-23 on a complete local clone '
            + '(288 tracked files = 288 on disk, working tree clean): ZERO attribution, CREDITS, '
            + 'NOTICE or per-directory README anywhere under `apps/editor/public/material/**`, and '
            + 'ZERO occurrences of "ambientCG", "Poly Haven", "CC0" or "attribution" anywhere in '
            + 'the repository. The whole tree arrived in ONE squashed vendor-bump commit (45a8cce, '
            + '"Bump plugin-bones ... (#711)") whose message names no texture source. ⭐ And the '
            + 'repository demonstrably KNOWS the rule it did not apply here: '
            + '`wiki/blender-edit-mode-research.md:406` reads "Blender is GPL-licensed ... copying '
            + 'Blender source into this MIT repository requires license review." Licence review was '
            + 'applied to code and recorded for none of the 288 binaries. MIT covers what the '
            + 'authors had the right to license; it does not cure an unestablished chain of title.',
    },
] as const satisfies readonly MaterialUpstream[]);

const BY_ID: ReadonlyMap<MaterialUpstreamId, MaterialUpstream> = new Map(
    MATERIAL_UPSTREAMS.map((u) => [u.id, u]),
);

/** The one lookup. ⛔ Do not hand-roll `.find()` over the array (C100 §1.3). */
export function findMaterialUpstream(id: string): MaterialUpstream | undefined {
    return BY_ID.get(id as MaterialUpstreamId);
}

/**
 * ⛔ THE PREDICATE A SHIPPED ROW MUST SATISFY.
 *
 * `NOT_ESTABLISHED` and `LICENSED_NOT_REDISTRIBUTABLE` both mean "the bytes or the
 * expression stay out"; only the reason differs, and the reason is in the row.
 */
export function isUpstreamClearedToShip(id: string): boolean {
    return findMaterialUpstream(id)?.status === 'CLEARED_FOR_REDISTRIBUTION';
}

/**
 * Every upstream whose licence has NOT been read and cleared.
 *
 * ⭐ Shaped exactly like RATE53's `unclearedBuildingCostModels()` — a non-empty
 * result is not a warning, it is a statement that this repository may be
 * redistributing something nobody established a right to. It is expected to be
 * NON-empty here (the Pascal textures row lives in it deliberately), which is why
 * the enforcement is "no ROW names an uncleared upstream", not "the ledger is
 * empty". A ledger with no refusals in it has not been used.
 */
export function unclearedMaterialUpstreams(): readonly MaterialUpstream[] {
    return MATERIAL_UPSTREAMS.filter((u) => u.status !== 'CLEARED_FOR_REDISTRIBUTION');
}

/**
 * Every upstream whose licence obliges us to reproduce a notice.
 *
 * ⭐ THIS IS WHAT MAKES ATTRIBUTION STRUCTURAL RATHER THAN A COURTESY. The shipped
 * `NOTICE.md` is checked against this list by
 * `tools/ga-gate/check-material-single-source.ts` ARM F, so deleting the notice
 * breaks a gate instead of quietly breaching a licence condition.
 */
export function materialUpstreamsRequiringNotice(): readonly MaterialUpstream[] {
    return MATERIAL_UPSTREAMS.filter((u) => u.attributionRequired);
}
