import { readFileSync, writeFileSync } from 'node:fs';
const per_family = JSON.parse(readFileSync('audit/full-stack/2026-08-31/_p5/per-family-manual.json', 'utf8'));

const out = {
  head_at_start: 'd91d30d4af51bc67317ef8afc0b46b1dbef94038',
  method: {
    instrument: 'audit/full-stack/2026-08-31/_p5/scan.mjs — a REPLICA of tools/ga-gate/check-layer-boundaries.ts that imports the SAME layer table from eslint.config.js (never a copy), uses the same git ls-files pathspec, the same exclusions (__tests__, .d.ts, /dist/), the same IMPORT_RE, the same RESTRICTED_MODULES and the same @pryzm/X -> package.json name resolution. It differs in ONE respect: comments are stripped LINE-PRESERVINGLY so every row carries file:LINE. The gate itself prints only aggregates plus a per-package tally.',
    why_a_replica: 'The gate prints no per-file list unless a ratchet is exceeded, and prints no per-family anything ever. Attribution needed the rows. Running the gate with a lowered env ceiling would have printed two of the four lists and still no line numbers.',
    evidence_class: 'Every per-family number below is class (c) — an executed measurement — VALIDATED against class (a) by the cross-check immediately below. Where only a gate reading exists (P1, P5, P6, P7, P8) the row says so and stays class (a).',
    tools_ga_gate_untouched: 'Nothing under tools/ga-gate/ was modified. `git status --porcelain tools/` -> empty at end of phase.',
  },
  cross_check: {
    claim: 'The replica reproduces the gate EXACTLY on all four of its numbers.',
    replica: { scanned_files: 5245, workspace_packages: 167, upward_imports: 102, sdk_bypasses: 171, banned_third_party: 124, unclassified: 13, unreadable_sources: 0 },
    gate: { source: 'audit/full-stack/2026-08-31/gate-snapshot.json -> gates[check-layer-boundaries.ts].printed_numbers, rc=3', workspace_packages: 167, classified: 154, unclassified: 13, upward_imports: 102, sdk_bypasses: 171, banned_third_party: 124 },
    verdict: 'IDENTICAL on all four. 154 classified + 13 unclassified = 167. This is the strongest form available here: an independent executed measurement agreeing with a BLIND comparator does not make the gate sighted, but it does make the attribution below trustworthy.',
    caveat: 'RC=0 IS NOT 0 VIOLATIONS and this gate is rc=3, not rc=0. It is FAILING on the banned-third-party arm (124 > 113). The other three arms are at or below ceiling with ZERO headroom on two of them.',
  },
  layer_table: {
    source: 'eslint.config.js layerElements (imported, not copied, by both the gate and this replica)',
    package_counts_by_layer: { L0: 8, L1: 16, L2: 47, L3: 12, L4: 6, L5: 1, L6: 51, L7: 13, UNCLASSIFIED: 13 },
    unclassified_packages: ['packages/admin-overrides', 'packages/ai-spend', 'packages/api-rbac', 'packages/api-spec', 'packages/bench-visual-diff', 'packages/beta-signup', 'packages/email-transport', 'packages/eslint-plugin-pryzm', 'packages/legacy-shim', 'packages/rate-limit', 'packages/release', 'packages/wcag-audit', 'packages/webhooks'],
    note: 'NO element family is unclassified. All 13 unclassified packages are backend/tooling, matching CLAUDE.md\'s "Backend packages have no layer" note. The per-family rows below therefore have full layer coverage.',
  },
  settlements: {
    S1_banned_3p_ceiling: {
      question: 'Is the 113 ceiling legitimate, and what are the remaining 11 over baseline?',
      carried_forward_ANSWERED: 'The ceiling IS legitimate. 113 was frozen 2026-08-09 by acae9ea4 against this gate\'s own measurement; check-layer-boundaries.ts:331-334 documents the denominator in source: "eslint reports 122, this gate 113. Not a discrepancy to reconcile — eslint counts per LINE across every file including tests and .d.ts, this gate counts resolved specifiers in non-test source. Frozen at THIS gate\'s own measurement, because a ratchet must be comparable with itself." VERIFIED IN PLACE at this HEAD: `sed -n \'320,335p\' tools/ga-gate/check-layer-boundaries.ts`. The 123->124 delta is geometry-handrail/src/HandrailTool.ts:42 (pre-existing @thatopen/components import made visible by classification).',
      MY_PART_the_remaining_11: {
        finding: 'THE 11 CANNOT BE NAMED FROM THIS TREE, AND SAYING SO IS THE MEASUREMENT. The gate stores no per-import baseline — only the integer 113 — so "which 11 crossed" is not recoverable from any artefact in the repo. What IS recoverable is the exact 124-row set (audit/full-stack/2026-08-31/_p5/scan.json .restricted, every row file:line:module) and its distribution.',
        the_124_by_package: { 'packages/core-app-model': 32, 'apps/editor': 28, 'plugins/annotations': 24, 'packages/geometry-furniture': 8, 'packages/geometry-slab': 5, 'packages/input-host': 5, 'packages/file-format': 3, 'packages/geometry-plumbing': 3, 'packages/geometry-wall': 3, 'packages/geometry-column': 2, 'packages/geometry-door': 2, 'packages/geometry-roof': 2, 'packages/geometry-window': 2, 'packages/geometry-curtain-wall': 1, 'packages/geometry-handrail': 1, 'packages/geometry-lift': 1, 'packages/geometry-lighting': 1, 'packages/geometry-stair': 1 },
        by_module: { '@thatopen/components': 118, '@thatopen/components-front': 6, express: 0 },
        note_vs_gate: 'An apparent one-row discrepancy was RESOLVED rather than left standing. The gate prints core-app-model 31; the replica reads 32. Splitting by module: core-app-model is 31 [@thatopen/components] + 1 [@thatopen/components-front], and apps/editor is 23 + 5 — exactly the gate\'s own two apps/editor rows. The gate prints only the TOP 9 rows of its per-package tally and `core-app-model [@thatopen/components-front] x1` falls below that cut. The two measurements agree ROW FOR ROW; the gate\'s output is truncated, not different. (This is why the replica was built: a truncated tally reads as a disagreement.)',
        the_attributable_share: '33 of the 124 sit inside element-family packages measured per family below (annotation 24, furniture 8 ... geometry-stair 1). 91 sit in core-app-model / apps/editor / input-host / file-format, which are not element families.',
      },
    },
    S2_arm_intersection: {
      question: 'What is |banned-3p ∩ sdk-bypass|, and how must it be reported?',
      carried_forward_ANSWERED: '|intersection| = 23 BY FILE, 0 BY LINE, all 23 in plugins/annotations. The target sets are DISJOINT by construction: sdk-bypass counts only @pryzm/* specifiers resolving to a workspace package outside {L5, L6}; banned-3p counts only @thatopen/* and express. No single import LINE can score in both.',
      RE_MEASURED_AT_THIS_HEAD: {
        cmd: 'audit/full-stack/2026-08-31/_p5/scan.json — intersect the .file sets of .restricted and .sdkBypass',
        files_in_both: 23,
        all_23_in: 'plugins/annotations',
        lines_in_both: 0,
        annotation_arm_totals: 'plugins/annotations contributes 24 of 124 banned-3p AND 49 of 171 sdk-bypasses. It is the single largest contributor to TWO of the gate\'s four arms.',
      },
      THE_REPORTING_RULE_THIS_AXIS_OBEYS: 'Deleting or relocating any of those 23 files moves BOTH arms. That is ONE action with TWO effects and is reported here ONCE, with both effects named. It is NOT two independent wins and must never be counted as two. Concretely: emptying plugins/annotations of @thatopen/components would take banned-3p 124 -> 100 (BELOW the 113 ceiling, turning this gate green) and, if the same files also lost their @pryzm/* bypasses, sdk-bypass 171 -> as low as 122. Anyone quoting "we fixed the layer gate twice" would be double-counting one edit.',
    },
    S3_thatopen_concentration: {
      question: 'Per family: which @thatopen packages does it depend on — and SHOULD an L2 geometry package be reaching a third-party BIM toolkit at all?',
      concentration_re_measured: { total_banned_3p: 124, in_geometry_star_L2: 32, in_plugins_annotations_L6: 24, in_core_app_model_L2: 32, in_geometry_star_note: '32 = furniture 8, slab 5, plumbing 3, wall 3, column 2, door 2, roof 2, window 2, curtain-wall 1, handrail 1, lift 1, lighting 1, stair 1', in_apps_editor_L7: 28, in_input_host_L2: 5, in_file_format_L3: 3 },
      the_modules: 'Only two modules are on the ban list at all: @thatopen/components and @thatopen/components-front. EVERY element-family hit is @thatopen/components.',
      WHAT_THE_L2_PACKAGES_ACTUALLY_USE: {
        cmd: "grep -ohn 'OBC\\.[A-Za-z]*' packages/geometry-*/src -r | sort | uniq -c",
        symbol_surface: { 'OBC.TechnicalDrawing': 41, 'OBC.World': 31, 'OBC.Components': 10, 'OBC.RendererMode': 7, 'OBC.Raycasters': 5 },
        value_vs_type: 'Of 94 `OBC.` reference lines across packages/geometry-*, only ~34 are VALUE positions (and 3 of those are inside comments). The other ~60 are TYPE annotations — `private world: OBC.World`, `components: OBC.Components`, `drawing: OBC.TechnicalDrawing`. cmd: `grep -rn "OBC.TechnicalDrawing\\.|get(OBC\\.|new OBC\\.|OBC.RendererMode\\." packages/geometry-*/src | wc -l` -> 34; `grep -rn "OBC\\." packages/geometry-*/src | wc -l` -> 94.',
        the_entire_runtime_surface: 'THREE symbols. (1) `OBC.TechnicalDrawing.toDrawingSpace(segs, drawing)` — a pure 3D->2D projection, ~20 call sites, every plan/elevation symbol builder. (2) `components.get(OBC.Raycasters).get(world)` — a service-locator KEY, 5 sites. (3) `renderer.mode === OBC.RendererMode.MANUAL` — an enum comparison, ~5 sites. There is NO `new OBC.X(...)` anywhere in packages/geometry-* (`grep -rn "new OBC\\." packages/geometry-*/src` -> 0 hits).',
      },
      ANSWER: 'NO — and the measurement says the coupling is far shallower than the 30-import figure suggests. The dependency is one projection function, one DI token and one enum. That is an ADAPTER-SIZED surface: a `@pryzm/drawing-primitives` re-export of toDrawingSpace plus a PRYZM-owned World/Raycaster port would delete all 30 L2 imports without touching a line of geometry math. BUT the honest reason those imports exist is structural, not lazy — see the FINDING below: packages/geometry-* is where the ACTUAL user-facing tools live, so it is holding the tool layer\'s job at L2, and a tool legitimately needs a canvas, a world and a raycaster. Fix the misplacement and the toolkit import mostly evaporates with it.',
      caveat_the_ban_list_has_a_hole: 'RESTRICTED_MODULES names @thatopen/components and @thatopen/components-front ONLY. `@thatopen/ui` is imported at packages/geometry-slab/src/SlabTool.ts:3 (`import * as BUI from "@thatopen/ui"`) and is NOT counted by this gate at all. Reported as F-P5-07.',
    },
    S4_extension_contracts_above_implementations: {
      question: 'Is PluginRegistration still declared exactly once at packages/plugin-sdk/src/registration.ts (L5), with no rival at L6 or L7?',
      cmd: 'grep -rn "interface PluginRegistration|type PluginRegistration" packages plugins apps --include=*.ts (node_modules excluded)',
      result: '2 hits, BOTH in packages/plugin-sdk/src/registration.ts — :82 `export type PluginRegistrationDeps` and :121 `export interface PluginRegistration`. packages/plugin-sdk is L5.',
      rival_search_by_CAPABILITY_not_name: {
        cmd: 'grep -rn "readonly buildHandlers|buildHandlers\\??:" packages plugins apps --include=*.ts — i.e. who DECLARES the registration shape rather than who spells its name',
        result: 'ONE declaration: packages/plugin-sdk/src/registration.ts:146. Every other hit is a USE (an object literal supplying buildHandlers). apps/editor/src/PluginRegistry.ts:198 is `export type PluginDescriptor = PluginRegistration<PluginContribution, RoomEventRuntime>` — an ALIAS of the L5 type, not a second declaration.',
        also_excluded: 'The five plugins/ai-*/src/descriptor.ts interfaces (AiFloorplanPluginDescriptor etc.) are NOT registration contracts for the store/handler pipeline — they declare AI-panel descriptors and none of them names buildStore or buildHandlers.',
      },
      VERDICT: 'ADR-0367 HOLDS at the contract. Exactly one declaration, at L5, no rival at L6 or L7. The nine-undispatchable-families cost is not being re-incurred.',
      BUT: 'The DECLARATION SITES have not followed. 28 of 29 element families still register as inline object literals inside the L7 file apps/editor/src/PluginRegistry.ts. section-view is the ONLY family with plugins/<f>/src/registration.ts (`ls plugins/*/src/registration.ts` -> 1 file). That is not a layer VIOLATION (L7 may import downward) and this axis does not upgrade it to one — it is the arrangement ADR-0367 §"ONE family proves it" set out to end, still 1/29 done.',
    },
  },
  read_but_never_assigned: {
    doctrine: 'The dimensionTool defect class: a symbol READ by the registry and ASSIGNED NOWHERE, so a "not ready — engine not yet initialised" branch is PERMANENT rather than a startup race. Swept EVERY global read in apps/editor/src/PluginRegistry.ts.',
    method: 'grep -n "window|globalThis" apps/editor/src/PluginRegistry.ts -> 10 distinct symbols read. For each, `grep -rn <sym> apps packages plugins src --include=*.ts --include=*.tsx` and inspect for an assignment.',
    symbols_read: {
      annotationTool: 'ASSIGNED — PluginRegistry.ts:1086 (self-assigned in the same activator). OK.',
      bcfTool: 'ASSIGNED — PluginRegistry.ts:1100. OK.',
      cubeTool: 'ASSIGNED — PluginRegistry.ts:1224. OK.',
      furnitureTool: 'ASSIGNED — apps/editor/src/engine/initTools.ts:690. OK (this is the bridge PluginRegistry.ts:1129 cites as the REAL one, and it is).',
      gridPlacementTool: 'ASSIGNED — PluginRegistry.ts:1178. OK.',
      lightingTool: 'ASSIGNED — PluginRegistry.ts:1193 and initTools.ts:843 (TWO assignors, different classes: LightingPlacementTool at L6 vs LightingTool at L2. Last writer wins and the order is not asserted anywhere. Noted, not resolved.)',
      roomTool: 'ASSIGNED — initTools.ts:3358. OK.',
      structuralTool: 'ASSIGNED — PluginRegistry.ts:1208. OK.',
      wallSystemTypeStore: 'ASSIGNED — apps/editor/src/engine/initBuilders.ts:578. OK.',
      sectionTool: '⛔ NEVER ASSIGNED.',
      __pryzmScreenToWorld: '⛔ NEVER ASSIGNED.',
    },
    CONFIRMED_DEAD_BRANCHES: [
      {
        symbol: 'window.sectionTool',
        read_at: 'apps/editor/src/PluginRegistry.ts:1300',
        assigned_at: 'NOWHERE',
        proof: 'grep -rn "sectionTool" apps packages plugins src --include=*.ts --include=*.tsx -> exactly 2 hits: the read above, and apps/editor/__tests__/sectionViewReachableThroughComposedRuntime.test.ts:47 whose own comment says "that global is assigned NOWHERE in the ...". Zero assignments.',
        consequence: 'The `if (t?.activate)` branch of the section-view activator is PERMANENTLY dead. Severity is bounded because the else-branch dispatches section.panel.open, so the activator is not silently inert — but the source comment at :1297 ("Engine-stored bridge until SectionTool is instantiated with a canvas ref") describes a temporary state that is in fact permanent.',
        family: 'section',
      },
      {
        symbol: 'window.__pryzmScreenToWorld',
        read_at: 'apps/editor/src/PluginRegistry.ts:1055 (annotationScreenToWorld) and :1063 (eventScreenToWorld)',
        assigned_at: 'NOWHERE',
        proof: 'grep -rn "__pryzmScreenToWorld" apps packages plugins src server scripts tools --include=*.ts --include=*.tsx --include=*.js --include=*.mjs -> exactly 4 hits, ALL in apps/editor/src/PluginRegistry.ts: :1024 and :1051 are COMMENTS asserting "the engine sets window.__pryzmScreenToWorld during initTools()", :1055 and :1063 are the READS. Zero assignments. `grep -n "__pryzmScreenToWorld" apps/editor/src/engine/initTools.ts` -> 0 hits.',
        consequence: 'annotationScreenToWorld returns null forever; eventScreenToWorld returns undefined forever. Those two functions are the ONLY screenToWorld handed to the four L6 tools the registry constructs (TextNoteTool :1088, GridPlacementTool :1182, LightingPlacementTool :1197, StructuralPlacementTool :1212). Each tool guards `if (!p) return undefined` / `if (!isFiniteVec3(p)) return undefined` at the top of onPointerDown, so NONE of the four can ever dispatch its create verb.',
        families: ['annotation', 'grid', 'lighting', 'structural'],
        THE_SAME_FILE_ALREADY_KNOWS: 'PluginRegistry.ts:1116-1150 is a tombstone for exactly this defect on window.dimensionTool, ending "Do not re-pair them; verify the assignment site before claiming a window bridge exists." The tombstone is 60 lines BELOW a comment (:1024) making the identical unverified claim about __pryzmScreenToWorld. The correction landed on one symbol and not on the one three bullets above it.',
      },
    ],
    A_SECOND_INDEPENDENT_DEFECT_ON_THE_SAME_PATH: {
      claim: 'Even if window.__pryzmScreenToWorld were assigned tomorrow, grid / lighting / structural would still be dead — the argument SHAPES do not match, and an `as any` hides it.',
      the_mismatch: 'PluginRegistry.ts:1062-1067 `const eventScreenToWorld = (ev: { offsetX: number; offsetY: number }) => ... fn(ev.offsetX, ev.offsetY)`. The L6 contracts declare the opposite shape: plugins/grid/src/tool.ts:14-16 `GridScreenToWorld = (ev: { clientX: number; clientY: number; pointerId: number })`; plugins/lighting/src/tool.ts:12-14 and plugins/structural/src/tool.ts:15-17 identical. The tool calls `this.screenToWorld(ev)` with a clientX/clientY event, eventScreenToWorld reads .offsetX/.offsetY -> undefined -> fn(undefined, undefined).',
      why_it_compiles: 'PluginRegistry.ts:1181-1182, :1196-1197, :1211-1212 each carry `// eslint-disable-next-line @typescript-eslint/no-explicit-any` followed by `screenToWorld: eventScreenToWorld as any`. The cast is what let two incompatible contracts meet.',
      note: 'TextNoteTool is NOT affected by this second defect — annotationScreenToWorld is (x, y) and ScreenToWorldFn is (x, y). It is affected by the first.',
    },
  },
  incomplete: [
    'The 11 banned-3p imports that crossed the 113 ceiling cannot be named: the gate stores an integer baseline, not a row set, and no per-import baseline artefact exists in the repo. The full 124-row set IS recorded (scan.json .restricted).',
    'RESOLVED, kept here as a record: the gate/replica one-row gap on core-app-model was the gate truncating its tally to the top 9 rows, not a measurement difference. See settlements.S1.note_vs_gate.',
    'P6 and P8 cannot be attributed per family: check-no-direct-store-writes prints its 37 writes by METHOD NAME only, and check-otel-spans prints Zone B as a count of files against a baseline with no file list in the snapshot. Both are recorded per family as repo-wide class (a) readings.',
    'This axis did not run the gates itself; the class (a) readings for P1/P5/P6/P7/P8 are read from audit/full-stack/2026-08-31/gate-snapshot.json (P0 of this audit). Only check-layer-boundaries was independently reproduced.',
    'Whether the 16 never-constructed L6 tools have some OTHER activation route (a dynamic import by string, a registry keyed on a literal) was searched for by class NAME only; a purely string-keyed lazy loader would have been missed.',
  ],
  findings: [
    {
      id: 'F-P5-01',
      severity: 'CRITICAL',
      evidence_class: 'c — executed measurement',
      claim: 'NOT ONE of the 20 L6 element-family placement tools can place an element. 16 are never imported or constructed outside plugins/; the 4 that are constructed receive a screenToWorld built on a global that is assigned nowhere.',
      command: 'for c in BeamPlacementTool ... TextNoteTool; do grep -rn "new $c(|import .*\\b$c\\b|{ *$c *[,}]" apps packages src --include=*.ts --include=*.tsx | grep -v __tests__ | grep -v /dist/; done',
      result: {
        constructed_at_L7: ['GridPlacementTool (PluginRegistry.ts:73 import, :1178 new)', 'LightingPlacementTool (:74, :1193)', 'StructuralPlacementTool (:75, :1208)', 'TextNoteTool (:70, :1086)'],
        never_imported_never_constructed_outside_plugins: ['BeamPlacementTool', 'CeilingPlacementTool', 'ColumnPlacementTool', 'CurtainWallPlacementTool', 'DimensionTool', 'DoorPlacementTool', 'FurniturePlacementTool', 'HandrailPlacementTool', 'PlumbingPlacementTool', 'RoofPlacementTool', 'RoomSeedTool', 'SectionTool', 'SlabPlacementTool', 'StairPlacementTool', 'WallCreationTool', 'WindowPlacementTool'],
        count: '16 of 20 unreachable by construction; 4 of 20 constructed and dead on their screenToWorld dependency (see read_but_never_assigned).',
      },
      why_it_matters: 'PREFER UNREACHABLE OVER ABSENT — this is the ladder. The tools EXIST (25 of 29 families ship a plugins/<f>/src/tool.ts). Five of them are named outside their own package ONLY IN COMMENTS (FurniturePlacementTool, RoomSeedTool, SectionTool, WallCreationTool, DimensionTool), which reads as wiring and is not. The families still reach the canvas — via the L2 geometry tool that initTools.ts instantiates — so this is a RIVAL-TOOL structure, not a missing capability.',
    },
    {
      id: 'F-P5-02',
      severity: 'CRITICAL',
      evidence_class: 'c — executed measurement',
      claim: 'window.__pryzmScreenToWorld is READ twice in PluginRegistry.ts and ASSIGNED NOWHERE in the repo. Two comments in the same file assert the engine sets it. This is the dimensionTool defect class, un-fixed, sixty lines above its own tombstone.',
      command: 'grep -rn "__pryzmScreenToWorld" apps packages plugins src server scripts tools --include=*.ts --include=*.tsx --include=*.js --include=*.mjs',
      result: '4 hits, all in apps/editor/src/PluginRegistry.ts: :1024 comment, :1051 comment, :1055 read, :1063 read. ZERO assignments. grep of initTools.ts alone -> 0 hits.',
      blast_radius: 'annotation (TextNoteTool), grid, lighting, structural — the only four L6 element tools L7 constructs.',
    },
    {
      id: 'F-P5-03',
      severity: 'HIGH',
      evidence_class: 'c — executed measurement',
      claim: 'A SECOND, independent defect on the same path: eventScreenToWorld reads ev.offsetX/ev.offsetY, but every L6 tool contract it is passed to declares {clientX, clientY, pointerId}. Three `as any` casts are what let the two meet.',
      command: 'sed -n "1062,1067p" apps/editor/src/PluginRegistry.ts ; sed -n "14,16p" plugins/grid/src/tool.ts ; grep -n "eventScreenToWorld as any" apps/editor/src/PluginRegistry.ts',
      result: 'PluginRegistry.ts:1063 `(ev: { offsetX: number; offsetY: number })`; plugins/grid/src/tool.ts:14-16, plugins/lighting/src/tool.ts:12-14, plugins/structural/src/tool.ts:15-17 all `(ev: { clientX; clientY; pointerId })`. Casts at PluginRegistry.ts:1182, :1197, :1212.',
      why_it_matters: 'Fixing F-P5-02 alone would NOT revive grid/lighting/structural. Two stacked causes, and the type system was told to look away at exactly the seam. TextNoteTool is exempt — its (x, y) shape matches.',
    },
    {
      id: 'F-P5-04',
      severity: 'HIGH',
      evidence_class: 'c — executed measurement',
      claim: 'MORE THAN HALF the repo\'s entire upward-import debt is two L6 plugins being consumed as if they were contract layers. 54 of 102 upward imports TARGET plugins/annotations (45) or plugins/structural (9).',
      command: 'audit/full-stack/2026-08-31/_p5/attribute.mjs — violations whose resolved TARGET is inside a family directory',
      result: {
        'into plugins/annotations (45)': { 'packages/command-registry (L2)': 22, 'packages/persistence-client (L4)': 9, 'packages/file-format (L3)': 5, 'packages/core-app-model (L2)': 4, 'packages/geometry-roof (L2)': 2, 'packages/room-topology': 2, 'packages/input-host (L2)': 1 },
        'into plugins/structural (9)': { 'packages/geometry-column (L2)': 6, 'packages/geometry-beam (L2)': 2, 'packages/input-host (L2)': 1 },
      },
      why_it_matters: 'This is settlement 4\'s shape recurring one level down. ADR-0367 moved the REGISTRATION contract off L7; the ELEMENT contracts (annotation types, structural types) are still declared inside L6 plugins that seven lower packages must reach up to. It also explains the annotation double-count in S2: plugins/annotations is the largest single contributor to the banned-3p arm (24/124), the sdk-bypass arm (49/171) AND the inbound-upward arm (45/102).',
    },
    {
      id: 'F-P5-05',
      severity: 'MEDIUM',
      evidence_class: 'c — executed measurement',
      claim: 'The L2 geometry packages are holding the TOOL layer\'s job, and that — not carelessness — is why an L2 package imports a third-party BIM toolkit. 32 of the 124 banned-3p imports are in packages/geometry-*; 15 of those 32 are in a file named *Tool.ts and 14 in a *SymbolBuilder.ts (the plan/elevation drawing path).',
      command: 'audit/full-stack/2026-08-31/_p5/scan.json .restricted filtered to packages/geometry-*; grep -on "new [A-Z][A-Za-z]*Tool\\b" apps/editor/src/engine/initTools.ts; then resolve each class name with git ls-files',
      result: 'initTools.ts (L7) constructs 25 tools. Resolving the 24 that are their own file: 20 are defined at L2 (packages/geometry-* 15, packages/input-host 4, packages/room-topology 1) and only 2 at L7 (apps/editor/src/ui/kitchen, .../wardrobe). So the live tool layer is L2. The entire OBC RUNTIME surface those files use is THREE symbols: TechnicalDrawing.toDrawingSpace, components.get(OBC.Raycasters), OBC.RendererMode.MANUAL. `grep -rn "new OBC\\." packages/geometry-*/src` -> 0 hits.',
      why_it_matters: 'Answers settlement 3 without moralising: an L2 geometry package should NOT reach a BIM toolkit, and the reason these do is that they are not really geometry packages — they are the live tools, mislocated. Deleting the toolkit import is an adapter; deleting the misplacement is the actual fix and it deletes the import with it.',
    },
    {
      id: 'F-P5-06',
      severity: 'HIGH',
      evidence_class: 'c — executed measurement',
      claim: 'P4\'s ratchet is NAME-BLIND in the way CLAUDE.md warns about for commandManager: it counts the literal string "(window as any)" and there are 3.7x as many sites reaching the same untyped global under a different spelling.',
      command: 'grep -rn "window as unknown as" apps packages plugins src --include=*.ts --include=*.tsx | grep -v __tests__ | grep -v "\\.d\\.ts" | wc -l  (and the same for "globalThis as unknown as")',
      result: 'window as unknown as: 269 · globalThis as unknown as: 105 · TOTAL 374, against check-cast-count.ts\'s repo-wide reading of 100/100 literal casts. The evasion is DOCUMENTED IN SOURCE: apps/editor/src/PluginRegistry.ts:207 reads "Still NOT `(window as any)`. P4-compliant." — and check-cast-count.ts:215 quotes that very line as prose it must not count.',
      per_family: 'Largest element-family holder: rooms 22 (plugins/rooms). Then furniture 3, wall 3. Literal (window as any) inside element families: 8 total.',
      why_it_matters: 'A gate satisfiable by renaming enforces the name, not the invariant. Reported as a MEASUREMENT of the gate\'s denominator, not a claim that all 374 are defects — many are narrow, typed reaches. The point is that P4\'s number does not describe the surface P4 names.',
    },
    {
      id: 'F-P5-07',
      severity: 'MEDIUM',
      evidence_class: 'c — executed measurement',
      claim: 'The banned-third-party list has a hole: @thatopen/ui is imported by an L2 geometry package and the gate does not count it.',
      command: 'sed -n "1,4p" packages/geometry-slab/src/SlabTool.ts ; grep -n "RESTRICTED_MODULES" -A 6 tools/ga-gate/check-layer-boundaries.ts',
      result: 'packages/geometry-slab/src/SlabTool.ts:3 `import * as BUI from "@thatopen/ui"`. RESTRICTED_MODULES (check-layer-boundaries.ts:337-341) names @thatopen/components-front, @thatopen/components and express — not @thatopen/ui, not @thatopen/fragments.',
      why_it_matters: 'An L2 geometry package importing a third-party UI KIT is a strictly worse edge than importing the components library, and it is the one the ratchet cannot see. ABSENCE-CLAIM SCOPE: this was searched by MODULE PREFIX @thatopen/* over the element-family dirs; other unlisted third-party UI/BIM modules were not swept.',
    },
    {
      id: 'F-P5-08',
      severity: 'MEDIUM',
      evidence_class: 'c — executed measurement',
      claim: 'A plugin imports an app. CLAUDE.md justifies the apps-above-plugins ordering with "plugins -> apps 0 real import statements". At this HEAD it is 1.',
      command: 'audit/full-stack/2026-08-31/_p5/scan.json .violations | grep toy-cube',
      result: 'plugins/toy-cube/src/HelloCubeBoot.ts:26 -> @pryzm/editor [L6 -> L7]. It is counted in the gate\'s 102 and in the 171 (it is also an SDK-facade bypass).',
      why_it_matters: 'Not load-bearing — toy-cube is a demo plugin — but the CLAUDE.md sentence is quoted as the JUSTIFICATION for the whole layer ordering, and it is now false by one. Two canonical sources disagree: CLAUDE.md says 0, the gate\'s own row set says 1. REPORTED, NOT RESOLVED.',
    },
    {
      id: 'F-P5-09',
      severity: 'LOW',
      evidence_class: 'c — executed measurement',
      claim: 'window.lightingTool has TWO assignors of DIFFERENT classes and no asserted ordering.',
      command: 'grep -rn "lightingTool" apps packages plugins src --include=*.ts',
      result: 'apps/editor/src/PluginRegistry.ts:1193 assigns `new LightingPlacementTool` (L6); apps/editor/src/engine/initTools.ts:843 assigns `new LightingTool` (L2, packages/geometry-lighting). Same global, two classes, last writer wins.',
      why_it_matters: 'The lighting family is the one place where the L6 tool and the L2 tool collide on a single global. Which one a user gets depends on activation order, which nothing in either file asserts. This is the RIVAL-TOOL structure of F-P5-01 made concrete in one variable.',
    },
    {
      id: 'F-P5-10',
      severity: 'LOW',
      evidence_class: 'c — executed measurement',
      claim: 'P2 and P3 are clean across every element family — stated as a positive measurement, not inferred from a green gate.',
      command: 'audit/full-stack/2026-08-31/_p5/principles.mjs over 1044 non-test source files in the 29 families\' directories',
      result: "0 raw `from 'three'` specifiers (all THREE arrives via @pryzm/renderer-three/three) and 0 requestAnimationFrame( call sites, in every one of the 29 families. Matches check-three-imports (0 outside renderer-three, 8182 files) and check-raf-count (1 owner, 5442 files) — two independent readings agreeing.",
    },
  ],
};

writeFileSync('audit/full-stack/2026-08-31/_p5/manual.json', JSON.stringify({ ...out, per_family }, null, 1));
console.log('ok');
