// §OFFICE-ARCH-FURNISH-SPLIT (Phase 1 of SPEC-OFFICE-GENERATION-ENGINE §1) — the seam between
// Command 1 (Generate Office Architecture) and Command 2 (Furnish Office).
//
// SPEC §1: architecture and furnishing are TWO independent systems. Architecture is NEVER
// regenerated by furnishing; furnishing only ADDS furniture to the EXISTING architecture. To
// make Command 2 (`pryzmFurnishOffice`) analyse "the existing architecture" WITHOUT re-running
// the generator, Command 1 stashes the minimal geometric context the furnish pass needs (the
// detailed-floor level ids + the plate radii) here. Command 2 reads it and places furniture on
// the already-built floors. No store writes, no THREE, no DOM — a plain in-memory handoff.

/** A support room / glazed enclosure the architecture placed — a host for an amenity module. */
export interface OfficeFurnishRoom {
    /** The architecture's room kind (support rooms) or a glazed-enclosure kind (SPEC §6). */
    readonly kind: 'meeting' | 'kitchenette' | 'storage' | 'plant' | 'glazed-exec' | 'glazed-focus' | 'glazed-interview';
    readonly x0: number;
    readonly z0: number;
    readonly x1: number;
    readonly z1: number;
}

/** The geometric context Command 2 (Furnish Office) needs to populate the built architecture. */
export interface OfficeFurnishContext {
    /** The representative (detailed) office floor level id. */
    readonly repLevelId: string;
    /** The ground-floor level id (reception + cafe). */
    readonly groundLevelId: string;
    /** Disc radius (m, origin-centred). */
    readonly discRadiusM: number;
    /** Core disc radius (m). */
    readonly coreRadiusM: number;
    /** Open-plan annulus inner radius (m). */
    readonly openPlanInnerR: number;
    /** Open-plan annulus outer radius (m). */
    readonly openPlanOuterR: number;
    /** Perimeter-office ring mid radius (m). */
    readonly perimMidR: number;
    /** Planned desk count (capped) for the open-plan grid. */
    readonly deskCount: number;
    /** Entrance heading (rad) — the reception faces this direction. */
    readonly entranceAngle: number;

    // ── Phase 2 (SPEC §5/§6/§7/§8/§9) — the circulation-first architecture the modular engine reads. ──
    /** Usable floor area (m²) — drives occupancy (§8). */
    readonly usableAreaM2: number;
    /** Primary circulation annulus (around the core) — a §7 keep-out. */
    readonly primaryCorridor: { readonly innerR: number; readonly outerR: number };
    /** Secondary circulation annulus (perimeter loop) — a §7 keep-out. */
    readonly secondaryCorridor: { readonly innerR: number; readonly outerR: number };
    /** Escape spoke headings (rad) — fire-egress routes the furniture must never block (§7/§9-8). */
    readonly escapeAngles: readonly number[];
    /** Support rooms + glazed enclosures — hosts for the meeting/exec/booth/kitchen amenity modules. */
    readonly rooms: readonly OfficeFurnishRoom[];
}

let _lastContext: OfficeFurnishContext | null = null;

/** §OFFICE-ARCH-FURNISH-SPLIT — Command 1 stashes the furnish context after building the
 *  architecture. Overwrites any previous build's context (only the most-recent tower is
 *  furnishable via the console/AI command). */
export function setOfficeFurnishContext(ctx: OfficeFurnishContext): void {
    _lastContext = ctx;
}

/** §OFFICE-ARCH-FURNISH-SPLIT — Command 2 reads the last-built architecture's furnish context.
 *  Returns null when no office architecture has been built this session (nothing to furnish). */
export function getOfficeFurnishContext(): OfficeFurnishContext | null {
    return _lastContext;
}

/** Clear the stashed context (used by tests + when a project is closed). */
export function clearOfficeFurnishContext(): void {
    _lastContext = null;
}
