/**
 * MarkGenerator — Contract §03-1.7
 *
 * Generates human-readable, project-unique element marks.
 *
 * Pattern:  PREFIX-FF-NNN
 *   PREFIX  — 2-letter element type code (WA, SL, CO, BM, DO, WN, …)
 *   FF      — zero-padded floor/level index (00 = Ground, 01 = L1, …)
 *             derived by sorting all project levels by elevation (ascending).
 *   NNN     — zero-padded sequential count of that element type
 *             on the same level (001, 002, …).
 *
 * Rules (Contract §03-1.7.3):
 *   - Marks are generated by Commands, NOT by Stores.
 *   - Stores MUST accept and preserve an incoming mark.
 *   - Stores may fall back to this generator only as a last resort.
 *   - Marks are stable — never re-computed after creation.
 *   - Marks are NOT IDs — they can be updated by UpdateElementMark.
 */

/** Registered 2-letter prefix codes per element type. */
export const ELEMENT_MARK_PREFIX: Record<string, string> = {
    wall:              'WA',
    slab:              'SL',
    column:            'CO',
    beam:              'BM',
    door:              'DO',
    window:            'WN',
    curtainwall:       'CW',
    stair:             'ST',
    handrail:          'HR',
    room:              'RM',
    furniture:         'FU',
    plumbing:          'PL',
    ceiling:           'CL',
    roof:              'RF',
    floor:             'FL',
    opening:           'OP',
    /** Room Bounding Line — virtual partition for room detection (§03-1.7) */
    roomboundingline:  'RB',
    /** Lighting fixture — pendant, downlight, floor lamp, table lamp (§03-1.7) */
    lighting:          'LI',
};

export interface MarkGeneratorDeps {
    /** Returns all project levels (BimManager.getLevels) */
    getLevels(): Array<{ id: string; elevation: number }>;
    /** Returns all elements of the requested type on a given level */
    countElementsOnLevel(elementType: string, levelId: string): number;
}

/**
 * Generate a mark for a new element.
 *
 * @param elementType  — store type key (e.g. 'wall', 'slab', 'door')
 * @param levelId      — the level the element belongs to
 * @param deps         — source of level list + per-level counts
 * @returns            — e.g. "WA-00-001"
 */
export function generateMark(
    elementType: string,
    levelId: string,
    deps: MarkGeneratorDeps
): string {
    const prefix = ELEMENT_MARK_PREFIX[elementType.toLowerCase()] ?? elementType.slice(0, 2).toUpperCase();

    // Derive floor index by sorting all levels by elevation ascending.
    const levels = [...deps.getLevels()].sort((a, b) => a.elevation - b.elevation);
    const floorIndex = levels.findIndex(l => l.id === levelId);
    const ff = (floorIndex < 0 ? 0 : floorIndex).toString().padStart(2, '0');

    // Sequential number = existing count on this level + 1.
    const existing = deps.countElementsOnLevel(elementType.toLowerCase(), levelId);
    const nnn = (existing + 1).toString().padStart(3, '0');

    return `${prefix}-${ff}-${nnn}`;
}

/**
 * Parse a mark string back into its components.
 * Returns null if the string does not match the pattern.
 */
export function parseMark(mark: string): { prefix: string; floorIndex: number; sequence: number } | null {
    const match = /^([A-Z]{2})-(\d{2})-(\d{3})$/.exec(mark);
    if (!match) return null;
    return {
        prefix:     match[1]!,
        floorIndex: parseInt(match[2]!, 10),
        sequence:   parseInt(match[3]!, 10),
    };
}

/**
 * Return true if the string follows the canonical mark pattern.
 */
export function isValidMark(mark: string): boolean {
    return parseMark(mark) !== null;
}
