// §PROCEDURAL-PATTERNS (L-1801) — HERRINGBONE.
//
// ─── The arithmetic that makes herringbone real, and the refusal it forces ─────
// ⭐ Herringbone by L×W blocks tiles the plane ONLY when `n = L / W` is a whole
// number. That is not a software convenience: it is why parquet blocks are sold as
// 70×280, 70×350, 90×360, 100×500 — an integer ratio — and why a joiner cannot lay
// herringbone from arbitrary offcuts. A generator that quietly accepted 70×300
// would produce a pattern that does not close, and the resulting texture would tile
// (the torus always tiles) while showing a visible fault line. So it REFUSES, and
// it refuses WITH BOTH NUMBERS.
//
// ─── The lattice, derived rather than eyeballed ────────────────────────────────
// Work in cell units of W. One "pair" is a horizontal block on cells
// {(0,0)…(n−1,0)} plus a vertical block on {(n,0)…(n,n−1)} — the L-shaped domino.
// The pairs tile under the lattice generated by
//     u = (−1, 1)          v = (n+1, n−1)
// whose determinant is −2n, exactly the pair's area in cells, which is the
// necessary condition. Solving for the axis-aligned sublattice:
//     (Px, 0) ∈ Λ  ⇒  Px = 2n        (0, Py) ∈ Λ  ⇒  Py = 2n
// ⭐ so the exact repeat cell is 2L × 2L, square, for every n. It is enumerated
// below by reducing lattice points modulo (2n, 2n) and taking the 2n distinct
// cosets — the count 2n is forced by the determinant, and the code ASSERTS it
// rather than trusting the derivation.

import { rectPiece, polygonArea, type PatternLayout, type Piece } from '../core/Piece.js';

export interface HerringboneParams {
  /** Stave WIDTH module, mm (block width + joint). Centre-to-centre. */
  readonly staveWidthMm: number;
  /** Whole-number length:width ratio. 4 and 5 are the common commercial blocks. */
  readonly lengthRatio: number;
  /** Visible joint, mm. Parquet is laid close: 0–0.5 mm is realistic. */
  readonly jointMm: number;
  /**
   * Optional cross-check. When supplied it must agree with
   * `staveWidthMm × lengthRatio` to within 1 mm, or the layout refuses — quoting
   * BOTH the stated length and the derived one.
   */
  readonly staveLengthMm?: number;
  /** Repeat the 2L × 2L cell this many times per axis, for per-stave variety. */
  readonly repeat?: number;
}

const mod = (a: number, n: number): number => ((a % n) + n) % n;

export function herringboneLayout(p: HerringboneParams): PatternLayout {
  const n = Math.round(p.lengthRatio);
  if (!(n >= 2) || Math.abs(n - p.lengthRatio) > 1e-9) {
    throw new RangeError(
      `herringbone: lengthRatio must be a whole number \u2265 2 (got ${p.lengthRatio}). ` +
        `Herringbone only closes when the block length is a whole multiple of its width — ` +
        `this is why parquet blocks are sold at 70\u00d7280, 70\u00d7350, 90\u00d7360.`,
    );
  }
  const W = p.staveWidthMm;
  if (!(W > 0)) throw new RangeError(`herringbone: staveWidthMm must be > 0 (got ${W})`);
  const L = W * n;
  if (p.staveLengthMm !== undefined && Math.abs(p.staveLengthMm - L) > 1) {
    throw new RangeError(
      `herringbone: staveLengthMm ${p.staveLengthMm} mm contradicts ` +
        `staveWidthMm ${W} mm \u00d7 lengthRatio ${n} = ${L} mm. ` +
        `Both numbers are quoted because one of them is the one you meant to change.`,
    );
  }
  if (p.jointMm < 0 || p.jointMm * 2 >= W) {
    throw new RangeError(`herringbone: jointMm ${p.jointMm} does not fit inside a ${W} mm stave`);
  }
  const rep = Math.max(1, Math.round(p.repeat ?? 1));
  const cellUnits = 2 * n * rep; // in units of W
  const cellWidthMm = cellUnits * W;
  const cellHeightMm = cellUnits * W;
  const inset = p.jointMm / 2;

  // Distinct lattice cosets modulo the repeat cell. Λ = <(−1,1), (n+1,n−1)>.
  const seen = new Set<string>();
  const offsets: Array<[number, number]> = [];
  for (let a = -2 * cellUnits; a <= 2 * cellUnits; a++) {
    for (let b = -2 * cellUnits; b <= 2 * cellUnits; b++) {
      const tx = mod(-a + b * (n + 1), cellUnits);
      const ty = mod(a + b * (n - 1), cellUnits);
      const key = `${tx},${ty}`;
      if (seen.has(key)) continue;
      seen.add(key);
      offsets.push([tx, ty]);
    }
  }
  const expected = 2 * n * rep * rep;
  if (offsets.length !== expected) {
    throw new Error(
      `herringbone: lattice enumeration produced ${offsets.length} cosets, expected ${expected} ` +
        `(n=${n}, repeat=${rep}). The tiling derivation and the code disagree — do not ship this.`,
    );
  }

  const pieces: Piece[] = [];
  let index = 0;
  for (const [tx, ty] of offsets) {
    // Horizontal block: cells (0,0)…(n−1,0) of the pair.
    pieces.push(
      rectPiece(index++, (tx + n / 2) * W, (ty + 0.5) * W, L, W, 0, inset),
    );
    // Vertical block: cells (n,0)…(n,n−1).
    pieces.push(
      rectPiece(index++, (tx + n + 0.5) * W, (ty + n / 2) * W, L, W, Math.PI / 2, inset),
    );
  }
  const pieceAreaMm2 = pieces.reduce((s, pc) => s + Math.abs(polygonArea(pc.poly)), 0);
  return { cellWidthMm, cellHeightMm, pieces, pieceAreaMm2 };
}
