/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Command
 * Phase:             Phase 1 (Current)
 * Files Modified:    CreateCurtainWallCommand.ts
 *
 * Critical Fixes (from CURTAIN-WALL-CONTRACT-AUDIT.md):
 *   #2  Removed direct builder call — store mutation triggers subscriber in main.ts
 *   #4  ID is required in payload (generated by CurtainWallTool, NOT inside execute())
 *   #5  baseLine stored at level-plane (Y=0); builder computes worldY from BimManager
 *   #7  No snapshot needed for create (undo deletes; redo re-executes with identical payload)
 *       Spatial registration determinism achieved by pre-generated ID in payload.
 *   Correct CommandType: CREATE_CURTAIN_WALL (was wrongly CREATE_CURTAIN_WALLS_FROM_SLAB)
 *
 * PERF-FIX-3 (10-CURTAIN-WALL-PERFORMANCE-PLAN §Fix3b):
 *   Gated window.dispatchEvent('bim-curtainwall-added') behind batchCoordinator.isBatching.
 *   During a batch of N walls this event previously fired N times, hitting FrustumCullingService,
 *   SelectionManager, SaveOrchestrator, and initScene listeners N times each. In batch mode,
 *   batchCoordinator.trackPostBatchWindowEvent() defers the event to a single consolidated
 *   dispatch in _executeFinalSweep() after all geometry and registrations are stable.
 *
 * Contract References:
 *   §2.7  No direct builder call in command
 *   §2.4  Spatial registration (bimManager + elementRegistry) in command, AFTER store mutation
 *   §3.5  Store is data-only — store.set() triggers subscriber via storeEventBus
 *   §01 §2.2  Snapshots for create: not needed (undo = delete; redo = re-execute same payload)
 *
 * Impact Assessment:
 *   Builder Impact:     None — builder receives data via subscriber
 *   Store Impact:       None — uses standard store.set() path
 *   Other Commands:     None
 *
 * Risk Level: Low
 */

import { Command, CommandType, CommandValidationResult, CommandResult, SerializedCommand, CommandContext } from '../types';
import { CurtainWallData } from '@pryzm/geometry-curtain-wall';
import { elementRegistry } from '@pryzm/core-app-model/element-registry';
import { batchCoordinator } from '@pryzm/core-app-model';
// §PERF-2026-Q2-CW-CREATE/F4 — Route window-event dispatch through the
// builder's placement-mode accumulator when the user is interactively
// drawing curtain walls. Mirrors the existing batchCoordinator coalescing
// for AI batches: one dispatch per unique event name per session.
import { CurtainWallBuilder } from '@pryzm/geometry-curtain-wall';
import { DOMEventBus } from '@pryzm/event-bus';
const _bus = new DOMEventBus();

export interface CreateCurtainWallPayload {
    /** §Critical #4: ID must be generated by the Tool and passed in — never inside execute(). */
    id: string;
    start: { x: number; z: number };
    end: { x: number; z: number };
    height: number;
    levelId: string;
    gridXSpacing?: number;
    gridYSpacing?: number;
    baseOffset?: number;
    /**
     * §PERSIST-L1 (DAILY-USE 2026-05-20) — Architect-set curtain-wall mullion +
     * glazing fields that the serializer already writes to the snapshot. Without
     * these, the loader silently fell back to the hard-coded defaults
     * (mullionSize=0.08, panelThickness=0.02, mullionColor='#333333') on every
     * reload, wiping any user customisation. Optional; absence preserves the
     * existing defaults for fresh creates via the CurtainWallTool.
     */
    mullionSize?: number;
    panelThickness?: number;
    mullionColor?: string;
    /**
     * §PERSIST-L1 — Non-uniform grid line system. The serializer persists
     * `gridSystem` for curtain walls whose grid was edited (Add/Remove grid
     * line commands). Without round-tripping it, a reload collapses any
     * custom grid back to uniform spacing.
     */
    gridSystem?: import('@pryzm/geometry-curtain-wall').CurtainGridSystem;
    /**
     * §PERSIST-L1 — Properties bag (mark + any architect tags).
     */
    properties?: Record<string, unknown>;
    /**
     * §PERSIST-L1 — IFC GUID continuity across reload (otherwise IFC export
     * generates a new GUID on every save, breaking external-tool linkage).
     */
    ifcGuid?: string;
}

export class CreateCurtainWallCommand implements Command {
    // §CURTAIN-WALL-AUDIT-2026 §13 — only the curtainWall store is mutated; the
    // level is a *read* dependency for spatial registration, not a mutation, so
    // including it here would mis-signal level subscribers.
    readonly affectedStores = ["curtainWall"] as const;
    readonly id = crypto.randomUUID();
    /** §Critical fix: Use CREATE_CURTAIN_WALL, not CREATE_CURTAIN_WALLS_FROM_SLAB */
    readonly type = CommandType.CREATE_CURTAIN_WALL;
    readonly timestamp = Date.now();
    targetIds: string[];

    constructor(private payload: CreateCurtainWallPayload) {
        this.targetIds = [payload.id];
    }

    canExecute(context: CommandContext): CommandValidationResult {
        if (!this.payload.levelId) return { ok: false, reason: 'levelId is required' };

        const level = context.bimManager.getLevelById(this.payload.levelId);
        if (!level) return { ok: false, reason: `Level '${this.payload.levelId}' not found` };

        if (this.payload.height <= 0) return { ok: false, reason: 'height must be positive' };

        if (context.stores.curtainWallStore.has?.(this.payload.id)) {
            return { ok: false, reason: `Curtain wall '${this.payload.id}' already exists` };
        }

        return { ok: true };
    }

    execute(context: CommandContext): CommandResult {
        const level = context.bimManager.getLevelById(this.payload.levelId);
        // canExecute already verified this — defensive guard only
        if (!level) throw new Error(`SpatialAuthorityError: Level '${this.payload.levelId}' not found`);

        const baseOffset = this.payload.baseOffset ?? 0.0;

        // §Critical #5 + §02 §1.2: baseLine stored at level-plane (Y = 0).
        // Builder computes worldY = level.elevation + baseOffset at projection time.
        // P0.3 DTO Migration: plain Point3D objects — no THREE.Vector3 in store data.
        const cwData: CurtainWallData = {
            id: this.payload.id,
            type: 'curtain-wall',
            levelId: this.payload.levelId,
            baseLine: [
                { x: this.payload.start.x, y: 0, z: this.payload.start.z },
                { x: this.payload.end.x,   y: 0, z: this.payload.end.z   }
            ],
            height: this.payload.height,
            baseOffset,
            gridXSpacing:   this.payload.gridXSpacing   ?? 1.2,
            gridYSpacing:   this.payload.gridYSpacing   ?? 1.5,
            // §PERSIST-L1 — honour caller-supplied mullion + glazing first,
            // fall back to the original defaults so fresh-create behaviour is
            // unchanged for the CurtainWallTool.
            mullionSize:    this.payload.mullionSize    ?? 0.08,
            panelThickness: this.payload.panelThickness ?? 0.02,
            mullionColor:   this.payload.mullionColor   ?? '#333333',
            // §PERSIST-L1 — non-uniform grid layout round-trips when the
            // architect added/removed grid lines pre-save.
            gridSystem:     this.payload.gridSystem,
            properties: {
                // Deterministic mark based on ID — no Math.random()
                mark: `CW-${this.payload.id.slice(0, 6).toUpperCase()}`,
                // §PERSIST-L1 — caller-supplied properties win, so the mark
                // and any architect tags survive a save/load round-trip.
                ...(this.payload.properties ?? {}),
            },
            // §2.4 redo symmetry: use payload.id as IFC GUID — deterministic and stable across redo.
            // §PERSIST-L1 — when restoring, prefer the snapshot's original IFC
            // GUID so external tools (Solibri, BIMcollab) keep their linkage.
            ifcData: { guid: this.payload.ifcGuid ?? this.payload.id, ifcClass: 'IfcCurtainWall' }
        };

        // 1️⃣ Store first — emits storeEventBus → subscriber in main.ts triggers builder.build()
        context.stores.curtainWallStore.add(cwData);

        // 2️⃣ Spatial registration AFTER successful store mutation (§5 ordering)
        context.bimManager.registerElement(this.payload.id, this.payload.levelId);

        // 3️⃣ ElementRegistry registration — mirrors undo's unregister
        if (!elementRegistry.getStoreType(this.payload.id)) {
            elementRegistry.registerSemantic(this.payload.id, 'curtainwall');
        }

        // 4️⃣ Invalidate SelectionManager's selectable-object cache so the new curtain wall
        // is immediately clickable. SelectionManager.init() listens for 'bim-curtainwall-added'
        // to null-out _selectableCache — without this event the cache stays stale and the
        // freshly-built Three.js group is invisible to raycasting until another event fires.
        //
        // PERF-FIX-3: Gate window event dispatch behind batch check.
        // During a batch (e.g. 44 walls via AI), dispatching this event per-wall causes
        // FrustumCullingService, SelectionManager, SaveOrchestrator, and initScene listeners
        // to run N times. Instead, trackPostBatchWindowEvent() defers to a single dispatch
        // after all geometry is stable (_executeFinalSweep). The Set<string> in BatchCoordinator
        // deduplicates so exactly ONE event fires per unique name regardless of wall count.
        // §PERF-2026-Q2-CW-CREATE/F4: Three-way routing.
        //   1. Inside an AI/coordinator batch  → batchCoordinator coalesces.
        //   2. Inside an interactive placement → builder accumulator coalesces.
        //   3. Otherwise (programmatic/tests)  → direct dispatch as before.
        if (batchCoordinator.isBatching) {
            batchCoordinator.trackPostBatchWindowEvent('bim-curtainwall-added');
        } else if (CurtainWallBuilder.isPlacementModeActive) {
            CurtainWallBuilder.trackPlacementWindowEvent('bim-curtainwall-added', { id: this.payload.id });
        } else {
            _bus.emit('bim-curtainwall-added', { id: this.payload.id }); // F.events.17
        }

        return { success: true, affectedElementIds: [this.payload.id] };
    }

    undo(context: CommandContext): CommandResult {
        // §2.4: Unregister first, then delete from store (reverse of execute ordering)
        context.bimManager.unregisterElement(this.payload.id);
        elementRegistry.unregister(this.payload.id);

        // Store deletion triggers storeEventBus → subscriber in main.ts calls builder.remove()
        context.stores.curtainWallStore.remove(this.payload.id);

        // §CURTAIN-WALL-AUDIT-2026 §6.5 — symmetric notification with execute().
        // SelectionManager / FrustumCullingService / UnifiedBrowserPanel all listen
        // for 'bim-curtainwall-removed' and need to drop cached references / refresh
        // their lists. During a batch undo (e.g. clearing N walls in one command)
        // we coalesce through batchCoordinator so exactly ONE event fires per unique
        // name after the batch finishes — same pattern as 'bim-curtainwall-added'.
        // §PERF-2026-Q2-CW-CREATE/F4: Same three-way routing as execute().
        if (batchCoordinator.isBatching) {
            batchCoordinator.trackPostBatchWindowEvent('bim-curtainwall-removed');
        } else if (CurtainWallBuilder.isPlacementModeActive) {
            CurtainWallBuilder.trackPlacementWindowEvent('bim-curtainwall-removed', { id: this.payload.id });
        } else {
            _bus.emit('bim-curtainwall-removed', { id: this.payload.id }); // F.events.17
        }

        return { success: true, affectedElementIds: [this.payload.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
            payload: this.payload as any
        };
    }
}
