/**
 * @file CreateAIElementCommand.ts
 *
 * MODIFICATION DECLARATION (04-BIM §1):
 *  Layer:          Command Layer
 *  Phase:          Phase 1 (Current)
 *  Classification: A — fully command-first, new feature, no core contract changes
 *  Risk:           Medium
 *
 * CONTRACT (04-BIM §3.2 / CreateAIWardrobeCommand pattern):
 *  ✅ ID generated by Tool layer (AICreatePanel) and passed in payload — never inside execute()
 *  ✅ canExecute() validates levelId against BimManager — fails explicitly if missing
 *  ✅ canExecute() runs AIElementValidator — fails explicitly on invalid config
 *  ✅ execute() uses level.elevation + baseOffset for Y — never cached
 *  ✅ store.add() triggers bim-furniture-added → FurnitureFragmentBuilder (no direct builder call)
 *  ✅ undo() unregisters from BimManager + store.remove() → bim-furniture-removed → builder
 *  ✅ aiElementConfig serialized via structuredClone — pure JSON, undo-safe
 *
 * NOTE: The direct builder call pattern (builder.updateFurniture) seen in
 * CreateAIWardrobeCommand and CreateFurnitureCommand is intentionally OMITTED here.
 * FurnitureFragmentBuilder is wired to the bim-furniture-added window event in main.ts,
 * which fires from store.add(). This keeps the command layer free of builder references.
 */

import { Command, CommandType, CommandValidationResult, CommandResult, SerializedCommand, CommandContext } from '../types';
import { FurnitureData, FurnitureMaterial } from '@pryzm/geometry-furniture';
import { AIElementConfig } from '@pryzm/geometry-furniture';
import { AIElementValidator } from '@pryzm/geometry-furniture';

export interface CreateAIElementPayload {
    /** Generated by AICreatePanel BEFORE this command is constructed — never here */
    id: string;
    levelId: string;
    baseOffset: number;
    position: { x: number; y: number; z: number };
    rotation: { x: number; y: number; z: number };
    material: FurnitureMaterial;
    color?: string;
    aiElementConfig: AIElementConfig;
}

export class CreateAIElementCommand implements Command {
    readonly affectedStores = ["furniture", "level"] as const;
    readonly id: string;
    readonly type = CommandType.CREATE_FURNITURE;
    readonly timestamp: number;
    targetIds: string[];

    constructor(private payload: CreateAIElementPayload) {
        this.id = `cmd-ai-element-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
        this.timestamp = Date.now();
        this.targetIds = [payload.id];
    }

    canExecute(context: CommandContext): CommandValidationResult {
        if (!this.payload.levelId) {
            return { ok: false, reason: 'CreateAIElementCommand: Missing levelId' };
        }

        const level = context.bimManager.getLevelById(this.payload.levelId);
        if (!level) {
            return {
                ok: false,
                reason: `CreateAIElementCommand: Level "${this.payload.levelId}" not found in BimManager`
            };
        }

        if (!this.payload.aiElementConfig) {
            return { ok: false, reason: 'CreateAIElementCommand: aiElementConfig is required' };
        }

        const validation = AIElementValidator.validate(this.payload.aiElementConfig);
        if (!validation.ok) {
            const summary = validation.errors.map(e => `${e.field}: ${e.message}`).join('; ');
            return { ok: false, reason: `CreateAIElementCommand: Invalid config — ${summary}` };
        }

        return { ok: true };
    }

    execute(context: CommandContext): CommandResult {
        const level = context.bimManager.getLevelById(this.payload.levelId);
        if (!level) {
            throw new Error(`CreateAIElementCommand: Level "${this.payload.levelId}" not found`);
        }

        // Spatial registration (BimManager is single spatial authority — 02-BIM §1.1)
        context.bimManager.registerElement(this.payload.id, this.payload.levelId);

        const config = this.payload.aiElementConfig;

        const data: FurnitureData = {
            id: this.payload.id,
            type: 'furniture',
            furnitureType: 'ai_element',
            position: {
                x: this.payload.position.x,
                y: level.elevation + this.payload.baseOffset,
                z: this.payload.position.z,
            },
            rotation: {
                x: this.payload.rotation.x,
                y: this.payload.rotation.y,
                z: this.payload.rotation.z,
            },
            levelId: this.payload.levelId,
            levelName: level.name,
            levelElevation: level.elevation,
            baseOffset: this.payload.baseOffset,
            // Mirror bounding box into generic dimensions for Inspector / schedules
            width:  config.boundingBox.w,
            length: config.boundingBox.d,
            height: config.boundingBox.h,
            material: this.payload.material,
            color: this.payload.color,
            properties: {},
            // Pure JSON — structuredClone-safe, undo-safe
            aiElementConfig: structuredClone(config),
        };

        const store = (context.stores as any).furnitureStore;
        if (!store) throw new Error('CreateAIElementCommand: furnitureStore not in context');

        // store.add() fires bim-furniture-added → main.ts listener → furnitureBuilder.updateFurniture()
        store.add(data);

        return { success: true, affectedElementIds: [this.payload.id] };
    }

    undo(context: CommandContext): CommandResult {
        // Full reversal: unregister spatial + remove from store
        // store.remove() fires bim-furniture-removed → furnitureBuilder.removeFurniture()
        context.bimManager.unregisterElement(this.payload.id);

        const store = (context.stores as any).furnitureStore;
        if (store) store.remove(this.payload.id);

        return { success: true, affectedElementIds: [this.payload.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            payload: {
                id: this.payload.id,
                levelId: this.payload.levelId,
                baseOffset: this.payload.baseOffset,
                position: { ...this.payload.position },
                rotation: { ...this.payload.rotation },
                material: this.payload.material,
                color: this.payload.color,
                aiElementConfig: structuredClone(this.payload.aiElementConfig),
            },
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
        };
    }
}