/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Command Layer — Data Platform: Template System
 * File:             src/commands/templates/CreateTemplateCommand.ts
 * Contract:         docs/00_Contracts/01-BIM-ENGINE-CORE-CONTRACT.md §2
 *                   docs/00_Contracts/03-BIM-SEMANTIC-MODEL-CONTRACT.md §2
 *
 * Creates a TemplateDefinition in TemplateStore.
 * Undo removes it from the store.
 * ID must be generated by the caller (§2.6 — never inside execute()).
 *
 * Note: isShared is a local-only flag in this phase.
 * FUTURE: Phase C — server template registry.
 */

import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext
} from '../types';
import type { TemplateDefinition, TemplateScope, TemplateRequirements } from '@pryzm/core-app-model';

export interface CreateTemplateInput {
    id: string;
    name: string;
    code: string;
    scope: TemplateScope;
    description?: string;
    isShared?: boolean;         // local-only flag — no cross-project sync in this phase
    requirements?: TemplateRequirements;
    createdBy?: string;
    tags?: string[];
}

export class CreateTemplateCommand implements Command {
    readonly affectedStores = ["template"] as const;
    id = crypto.randomUUID();
    type = CommandType.CREATE_TEMPLATE;
    timestamp = Date.now();
    targetIds: string[];

    constructor(private input: CreateTemplateInput) {
        this.targetIds = [input.id];
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        if (!ctx.stores.templateStore) {
            return { ok: false, reason: 'TemplateStore not available in CommandContext' };
        }
        if (!this.input.name.trim()) {
            return { ok: false, reason: 'Template name must not be empty' };
        }
        if (!this.input.code.trim()) {
            return { ok: false, reason: 'Template code must not be empty' };
        }
        if (ctx.stores.templateStore.has(this.input.id)) {
            return { ok: false, reason: `Template id already exists: ${this.input.id}` };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        const now = Date.now();
        const template: TemplateDefinition = {
            id: this.input.id,
            scope: this.input.scope,
            name: this.input.name.trim(),
            code: this.input.code.trim(),
            description: this.input.description,
            version: 1,
            // FUTURE: Phase C — server template registry (currently local-only flag)
            isShared: this.input.isShared ?? false,
            requirements: this.input.requirements ?? {},
            metadata: {
                createdAt: now,
                createdBy: this.input.createdBy ?? 'user',
                modifiedAt: now,
                modifiedBy: this.input.createdBy ?? 'user',
                tags: this.input.tags,
            },
        };

        ctx.stores.templateStore!.add(template);

        return { success: true, affectedElementIds: [this.input.id] };
    }

    undo(ctx: CommandContext): CommandResult {
        ctx.stores.templateStore?.remove(this.input.id);
        return { success: true, affectedElementIds: [this.input.id] };
    }

    serialize(): SerializedCommand {
        return {
            type: this.type,
            targetIds: this.targetIds,
            timestamp: this.timestamp,
            version: 1,
            payload: this.input,
        };
    }
}
