// @pryzm/auto-dimension — the 8-stage deterministic pipeline entry point.
//
// PURE DTO → DTO. Same input geometry → byte-identical DimensionString[] (ADR-0061):
// every ordering is a total order with an element-id final tiebreak; no Date.now,
// no Math.random, no Set/Map iteration order trusted for output. P8: the root and
// each stage open an OTel span (tracing.ts).
//
// See docs/03-execution/spikes/SPIKE-AUTODIMENSION-ENGINE.md (§FEAT-AUTODIMENSION-P1).

import {
  DimensionStringSchema,
  type DimensionString,
} from '@pryzm/schemas/annotation/dimension';
import type {
  AutoDimSnapshot, AutoDimOptions, AutoDimResult, AutoDimReport,
  AutoDimWall, PlannedString, WallRun, DimNode, ValidationWarning, TickRef,
} from './types.js';
import { buildGraph, tracePerimeter, splitRuns, type DimGraph } from './perimeter.js';
import { openingsOnRun, type RunOpening } from './openings.js';
import {
  planOverall, planWallChain, planOpeningChain, planOpeningLocations, dedupKey,
} from './planners.js';
import { withAutoDimSpan } from './tracing.js';

const DEFAULT_SNAP_EPS_M = 0.20;
const DEFAULT_MIN_SEGMENT_M = 0.05;
const DEFAULT_BASE_OFFSET_MM = 8;
const DEFAULT_ROW_SPACING_MM = 8;

// Innermost → outermost stack rows by rank (§SPIKE §8): location, opening-chain,
// wall-chain, then overall on the very outside.
const RANK_ROW: Readonly<Record<number, number>> = { 4: 0, 3: 1, 2: 2, 1: 3, 5: 0 };

function makeMonotonicIdFactory(): () => string {
  let n = 0;
  return () => `dim-auto-${(++n).toString().padStart(6, '0')}`;
}

/** Canonical wall sort (§SPIKE §14.1): (minX, minZ, id) — total order, id tiebreak. */
function sortWalls(walls: readonly AutoDimWall[]): AutoDimWall[] {
  return [...walls].sort((a, b) => {
    const amx = Math.min(a.a.x, a.b.x), bmx = Math.min(b.a.x, b.b.x);
    if (amx !== bmx) return amx - bmx;
    const amz = Math.min(a.a.z, a.b.z), bmz = Math.min(b.a.z, b.b.z);
    if (amz !== bmz) return amz - bmz;
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
}

/** Per-wall fallback (open perimeter): one aligned length dim per wall. */
function planPerWallFallback(walls: readonly AutoDimWall[], minSegmentM: number): PlannedString[] {
  const out: PlannedString[] = [];
  for (const w of walls) {
    const dx = w.b.x - w.a.x, dz = w.b.z - w.a.z;
    const L = Math.hypot(dx, dz);
    if (L < minSegmentM) continue;
    const a: TickRef = { elementId: w.id, anchor: 'start', station: 0 };
    const b: TickRef = { elementId: w.id, anchor: 'end', station: L };
    out.push({
      kind: 'linear-element',
      orientation: Math.abs(dx) >= Math.abs(dz) ? 'horizontal' : 'vertical',
      refs: [a, b], axisId: `wall:${w.id}`, rank: 5, rowIndex: 0,
      stationSpan: [0, L],
    });
  }
  return out;
}

function serialize(
  planned: readonly PlannedString[],
  opts: AutoDimOptions,
  idFactory: () => string,
): DimensionString[] {
  // Total order for positionally-stable ids (§SPIKE §14.4).
  const ordered = [...planned].sort((a, b) => {
    if (a.orientation !== b.orientation) return a.orientation < b.orientation ? -1 : 1;
    if (a.axisId !== b.axisId) return a.axisId < b.axisId ? -1 : 1;
    if (a.rank !== b.rank) return a.rank - b.rank;
    if (a.stationSpan[0] !== b.stationSpan[0]) return a.stationSpan[0] - b.stationSpan[0];
    if (a.stationSpan[1] !== b.stationSpan[1]) return a.stationSpan[1] - b.stationSpan[1];
    return dedupKey(a) < dedupKey(b) ? -1 : 1;
  });

  return ordered.map((p) => {
    const offsetMm = (opts.baseOffsetMm ?? DEFAULT_BASE_OFFSET_MM)
      + p.rowIndex * (opts.rowSpacingMm ?? DEFAULT_ROW_SPACING_MM);
    return DimensionStringSchema.parse({
      id: idFactory(),
      kind: p.kind,
      references: p.refs.map((r) => ({ elementId: r.elementId, anchor: r.anchor })),
      orientation: p.orientation,
      offsetMm,
      viewId: opts.viewId,
      ...(opts.levelId ? { levelId: opts.levelId } : {}),
      isAutoGenerated: true,
      autoMode: 'set-out',
    });
  });
}

function runQA(
  snapshot: AutoDimSnapshot,
  perimNodes: readonly DimNode[],
  planned: readonly PlannedString[],
  hasPerimeter: boolean,
): ValidationWarning[] {
  const warnings: ValidationWarning[] = [];
  if (snapshot.walls.length === 0) {
    warnings.push({ code: 'no-walls', detail: 'snapshot has no walls' });
    return warnings;
  }
  if (!hasPerimeter) {
    warnings.push({ code: 'open-perimeter', detail: 'no closed building perimeter — per-wall fallback used' });
  }

  // QA-1 opening coverage.
  const referenced = new Set<string>();
  for (const p of planned) for (const r of p.refs) referenced.add(r.elementId);
  for (const w of snapshot.walls) {
    for (const op of w.openings) {
      if (!referenced.has(op.id)) {
        warnings.push({ code: 'opening-undimensioned', detail: op.id });
      }
    }
  }

  // QA-3 overall consistency (bbox extent within 0.5%).
  if (perimNodes.length > 0) {
    let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity;
    for (const n of perimNodes) {
      if (n.point.x < minX) minX = n.point.x;
      if (n.point.x > maxX) maxX = n.point.x;
      if (n.point.z < minZ) minZ = n.point.z;
      if (n.point.z > maxZ) maxZ = n.point.z;
    }
    const spanW = maxX - minX, spanH = maxZ - minZ;
    for (const p of planned) {
      if (p.kind !== 'overall') continue;
      const measured = Math.abs(p.stationSpan[1] - p.stationSpan[0]);
      const expected = p.orientation === 'horizontal' ? spanW : spanH;
      if (expected > 1e-6 && Math.abs(measured - expected) / expected > 0.005) {
        warnings.push({ code: 'overall-mismatch', detail: `${p.orientation} ${measured.toFixed(3)}≠${expected.toFixed(3)}` });
      }
    }
  }
  return warnings;
}

/**
 * Plan a non-redundant, architect-grade dimension set for a floor plan.
 *
 * P1 scope: overall (rank 1) + exterior wall-chain (rank 2) + opening chain
 * (rank 3) + opening location (rank 4) on rectangular + L plans. Full multi-row
 * conflict resolution and interior-room chains are P2/P3 (§SPIKE §16).
 */
export function planAutoDimensions(
  snapshot: AutoDimSnapshot,
  opts: AutoDimOptions,
): AutoDimResult {
  return withAutoDimSpan('plan', () => {
    const idFactory = opts.idFactory ?? makeMonotonicIdFactory();
    const snapEps = opts.snapEpsilonM ?? DEFAULT_SNAP_EPS_M;
    const minSeg = opts.minSegmentM ?? DEFAULT_MIN_SEGMENT_M;
    const walls = sortWalls(snapshot.walls);
    const wallsById = new Map<string, AutoDimWall>(walls.map((w) => [w.id, w]));

    // ── Stage 1: connectivity graph + perimeter ─────────────────────────────
    const { runs, perimNodes, hasPerimeter } = withAutoDimSpan('graph', () => {
      const g: DimGraph = buildGraph(walls, snapEps);
      const ring = tracePerimeter(g);
      if (!ring) return { runs: [] as WallRun[], perimNodes: g.nodes, hasPerimeter: false };
      const rs = splitRuns(ring, g);
      const perimNodeSet = new Set(ring.nodeIds);
      const pn = g.nodes.filter((n) => perimNodeSet.has(n.id));
      return { runs: rs, perimNodes: pn, hasPerimeter: true };
    }, { wall_count: walls.length });

    // ── Stage 2/3: openings per run ─────────────────────────────────────────
    const runOpenings = withAutoDimSpan('segment', () => {
      const m = new Map<string, RunOpening[]>();
      for (const run of runs) m.set(run.id, openingsOnRun(run, wallsById));
      return m;
    });

    // ── Stage 4/5: chain planning ───────────────────────────────────────────
    const planned = withAutoDimSpan('chain', () => {
      let list: PlannedString[] = [];
      if (hasPerimeter && runs.length > 0) {
        list.push(...planOverall(perimNodes));
        for (const run of runs) {
          const ops = runOpenings.get(run.id) ?? [];
          list.push(...planWallChain(run, minSeg));
          list.push(...planOpeningChain(run, ops, minSeg));
          list.push(...planOpeningLocations(run, ops, minSeg));
        }
      } else {
        list.push(...planPerWallFallback(walls, minSeg));
      }
      // Dedup identical (orientation, ref-pair) strings — never dimension the
      // same distance twice; keep the higher-rank (lower rank number) one.
      const byKey = new Map<string, PlannedString>();
      for (const p of list.sort((a, b) => a.rank - b.rank)) {
        const k = dedupKey(p);
        if (!byKey.has(k)) byKey.set(k, p);
      }
      list = [...byKey.values()];
      return list;
    });

    // ── Stage 6: placement (assign outward stack rows) ──────────────────────
    const placed = withAutoDimSpan('place', () =>
      planned.map((p) => ({ ...p, rowIndex: RANK_ROW[p.rank] ?? 0 })),
    );

    // Serialize (deterministic id order).
    const strings = serialize(placed, opts, idFactory);

    // ── Stage 8: QA ─────────────────────────────────────────────────────────
    const warnings = withAutoDimSpan('qa', () => runQA(snapshot, perimNodes, placed, hasPerimeter));

    const openingCount = snapshot.walls.reduce((s, w) => s + w.openings.length, 0);
    const dimensioned = new Set<string>();
    for (const p of placed) for (const r of p.refs) dimensioned.add(r.elementId);
    let openingsDimensioned = 0;
    for (const w of snapshot.walls) for (const op of w.openings) if (dimensioned.has(op.id)) openingsDimensioned++;

    const report: AutoDimReport = {
      coverage: {
        wallCount: snapshot.walls.length,
        openingCount,
        openingsDimensioned,
        stringCount: strings.length,
        runCount: runs.length,
      },
      warnings,
      skipped: [],
    };
    return { strings, report };
  }, { wall_count: snapshot.walls.length });
}
