// PRYZM 2 — sheet-schema barrel (S37 / Phase 2C).

export {
  PAPER_SIZES,
  type PaperSize,
  type Orientation,
  getSheetDimensions,
  isPaperSize,
  isOrientation,
} from './paper-size.js';

export {
  ViewportSchema,
  WidgetSchema,
  SheetSchema,
  PLACEHOLDER_TITLE_BLOCK_ID,
  type ViewportDto,
  type WidgetDto,
  type SheetData,
  type SheetId,
} from './sheet.js';

export {
  WIDGET_KINDS,
  WidgetPayloadSchema,
  TextWidgetPayloadSchema,
  ImageWidgetPayloadSchema,
  NorthArrowWidgetPayloadSchema,
  ScaleBarWidgetPayloadSchema,
  LegendEntrySchema,
  LegendWidgetPayloadSchema,
  RevisionRowSchema,
  RevisionsTableWidgetPayloadSchema,
  ScheduleSnapshotWidgetPayloadSchema,
  BimTagWidgetPayloadSchema,
  LineWidgetPayloadSchema,
  RegionWidgetPayloadSchema,
  isWidgetKind,
  parseWidgetPayload,
  type WidgetKind,
  type TextWidgetPayload,
  type ImageWidgetPayload,
  type NorthArrowWidgetPayload,
  type ScaleBarWidgetPayload,
  type LegendEntry,
  type LegendWidgetPayload,
  type RevisionRow,
  type RevisionsTableWidgetPayload,
  type ScheduleSnapshotWidgetPayload,
  type BimTagWidgetPayload,
  type LineWidgetPayload,
  type RegionWidgetPayload,
  type WidgetPayload,
} from './widget-payloads.js';

export {
  TitleBlockFieldSchema,
  TitleBlockBorderLineSchema,
  TitleBlockLogoAreaSchema,
  TitleBlockLayoutSchema,
  TitleBlockTemplateSchema,
  TitleBlockYAnchorSchema,
  TitleBlockTextAlignSchema,
  ProjectMetadataSchema,
  EMPTY_PROJECT_METADATA,
  BUILTIN_TITLE_BLOCK_IDS,
  DEFAULT_TITLE_BLOCK_ID,
  type TitleBlockField,
  type TitleBlockBorderLine,
  type TitleBlockLogoArea,
  type TitleBlockLayout,
  type TitleBlockTemplate,
  type TitleBlockTemplateId,
  type TitleBlockYAnchor,
  type TitleBlockTextAlign,
  type ProjectMetadata,
  type BuiltinTitleBlockId,
} from './title-block.js';
