import { ProjectState } from './types';

export const initialState: ProjectState = {
  projectName: 'Project',
  site: { id: 'site-1', name: 'Site' },
  building: { id: 'bld-1', name: 'Building' },
  activeStoreyId: 'storey-ground',
  storeys: [
    {
      id: 'storey-ground',
      localName: 'Ground',
      elevation: 0,
      origin: 'native',
      editable: true,
      adoptedLevel: false,
      sourceFileIds: [],
      ifcGUID: null,
      elementCount: 7,
      visible: true,
    },
    {
      id: 'storey-found',
      localName: 'T.O. Found',
      elevation: -3,
      origin: 'ifc',
      editable: false,
      adoptedLevel: true,
      sourceFileIds: ['ifc-structural'],
      ifcGUID: '2HkJ9mNpQrStUvWxYz0A',
      elementCount: 14,
      visible: true,
    },
    {
      id: 'storey-l1',
      localName: 'Level 1',
      elevation: 4,
      origin: 'ifc',
      editable: false,
      adoptedLevel: true,
      sourceFileIds: ['ifc-structural', 'ifc-mep'],
      ifcGUID: '3AbC4dEfGhIjKlMnOpQr',
      elementCount: 156,
      visible: true,
    },
    {
      id: 'storey-l2',
      localName: 'Level 2',
      elevation: 8,
      origin: 'ifc',
      editable: false,
      adoptedLevel: true,
      sourceFileIds: ['ifc-structural'],
      ifcGUID: '4StUvWxYz0AbCdEfGhIj',
      elementCount: 57,
      visible: true,
    },
    {
      id: 'storey-roof',
      localName: 'Roof',
      elevation: 14,
      origin: 'ifc',
      editable: false,
      adoptedLevel: true,
      sourceFileIds: ['ifc-arch'],
      ifcGUID: '5KlMnOpQrStUvWxYz0Ab',
      elementCount: 34,
      visible: true,
    },
    {
      id: 'storey-unassigned',
      localName: 'Unassigned',
      elevation: null,
      origin: 'ifc',
      editable: false,
      adoptedLevel: false,
      sourceFileIds: ['ifc-structural', 'ifc-mep', 'ifc-arch'],
      ifcGUID: null,
      elementCount: 217,
      visible: true,
    },
  ],
  elements: [
    // Ground - native elements
    { id: 'el-g-wall-1', type: 'wall', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-g-wall-2', type: 'wall', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-g-wall-3', type: 'wall', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-g-slab-1', type: 'slab', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-g-door-1', type: 'door', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-g-door-2', type: 'door', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-g-window-1', type: 'window', storeyId: 'storey-ground', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    // Level 1 - mixed
    { id: 'el-l1-col-1', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g1', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-2', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g2', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-3', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g3', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-4', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g4', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-5', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g5', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-6', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g6', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-7', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g7', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-8', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g8', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-9', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g9', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-10', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g10', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-11', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g11', ifcType: 'IfcColumn' },
    { id: 'el-l1-col-12', type: 'column', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-structural', ifcGUID: 'g12', ifcType: 'IfcColumn' },
    { id: 'el-l1-wall-1', type: 'wall', storeyId: 'storey-l1', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-l1-wall-2', type: 'wall', storeyId: 'storey-l1', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-l1-wall-3', type: 'wall', storeyId: 'storey-l1', origin: 'native', editable: true, sourceFileId: null, ifcGUID: null, ifcType: null },
    { id: 'el-l1-duct-1', type: 'duct', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-mep', ifcGUID: 'm1', ifcType: 'IfcDuctSegment' },
    { id: 'el-l1-duct-2', type: 'duct', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-mep', ifcGUID: 'm2', ifcType: 'IfcDuctSegment' },
    { id: 'el-l1-pipe-1', type: 'pipe', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-mep', ifcGUID: 'm3', ifcType: 'IfcPipeSegment' },
    { id: 'el-l1-pipe-2', type: 'pipe', storeyId: 'storey-l1', origin: 'ifc', editable: false, sourceFileId: 'ifc-mep', ifcGUID: 'm4', ifcType: 'IfcPipeSegment' },
  ],
  ifcFiles: [
    {
      id: 'ifc-structural',
      filename: 'structural.ifc',
      schema: 'IFC4',
      importedAt: '2026-04-18',
      elementCount: 412,
      status: 'ok',
      visible: true,
      adoptedStoreyIds: ['storey-found', 'storey-l1', 'storey-l2'],
    },
    {
      id: 'ifc-mep',
      filename: 'mep.ifc',
      schema: 'IFC4',
      importedAt: '2026-04-18',
      elementCount: 420,
      status: 'ok',
      visible: true,
      adoptedStoreyIds: ['storey-l1'],
    },
    {
      id: 'ifc-arch',
      filename: 'architecture.ifc',
      schema: 'IFC2X3',
      importedAt: '2026-04-17',
      elementCount: 254,
      status: 'outdated',
      visible: true,
      adoptedStoreyIds: ['storey-roof'],
    },
  ],
};
