/**
 * @file FloorPlanBatchExecutor.ts
 * @description Executes FloorPlan CommandProposals in a strict dependency order:
 *   1. Walls  (CREATE_WALL)
 *   2. Slab   (CREATE_SLAB)
 *   3. Doors  (ADD_OPENING where intentType contains "DOOR")
 *   4. Windows(ADD_OPENING where intentType contains "WINDOW")
 *   5. Other  (furniture, plumbing, …)
 *
 * CONTRACT (04-BIM §3.1 Tool Layer / 05-BIM-UI-ARCHITECTURE-CONTRACT):
 *  - NEVER mutates stores directly.
 *  - NEVER calls builders directly.
 *  - All mutations go through CommandManager.execute() accessed via commandManager.
 *  - Does NOT fire ai-proposal-added events — bypasses popup UI intentionally.
 *  - Appends every executed command to the immutable AIApprovalStore audit log.
 *  - This module is isolated: it imports only from the commands layer and the AI
 *    approval infrastructure, leaving all other tool logic untouched.
 */

import { CommandProposal, CommandType } from '@pryzm/command-registry';
import { aiApprovalStore } from './AIApprovalStore.js';

// ── Types ────────────────────────────────────────────────────────────────────

export interface BatchExecutionResult {
    succeeded: number;
    failed: number;
    summary: {
        walls: number;
        slab: number;
        doors: number;
        windows: number;
        other: number;
    };
    failedProposals: Array<{ proposal: CommandProposal; reason: string }>;
}

export type BatchProgressCallback = (
    stage: string,
    done: number,
    total: number
) => void;

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Determine opening sub-type from intentType tag set by FloorPlanCommandBatcher. */
function getOpeningSubType(p: CommandProposal): 'door' | 'window' | 'other' {
    const t = p.intentType.toUpperCase();
    if (t.includes('DOOR')) return 'door';
    if (t.includes('WINDOW')) return 'window';
    return 'other';
}

/**
 * Sort proposals into the execution order that respects BIM dependencies:
 *   walls must exist before openings can be hosted.
 */
function sortIntoExecutionOrder(proposals: CommandProposal[]): CommandProposal[] {
    const walls:   CommandProposal[] = [];
    const slabs:   CommandProposal[] = [];
    const doors:   CommandProposal[] = [];
    const windows: CommandProposal[] = [];
    const other:   CommandProposal[] = [];

    for (const p of proposals) {
        switch (p.command.type) {
            case CommandType.CREATE_WALL:
                walls.push(p);
                break;
            case CommandType.CREATE_SLAB:
                slabs.push(p);
                break;
            case CommandType.ADD_OPENING: {
                const sub = getOpeningSubType(p);
                if (sub === 'door')   doors.push(p);
                else if (sub === 'window') windows.push(p);
                else other.push(p);
                break;
            }
            default:
                other.push(p);
        }
    }

    return [...walls, ...slabs, ...doors, ...windows, ...other];
}

function appendAudit(proposal: CommandProposal, approvedBy: string): void {
    try {
        aiApprovalStore.append({
            id: crypto.randomUUID(),
            proposalId: proposal.id,
            intent: proposal.intentType as any,
            commandType: proposal.command.type,
            commandSnapshot: proposal.command.serialize(),
            approvedBy,
            approvedAt: new Date().toISOString(),
            rationale: proposal.rationale,
            confidence: proposal.confidence,
            validationSummary: proposal.validation.ok
                ? 'VALID'
                : (proposal.validation.reason || 'FAILED'),
        });
    } catch (e) {
        console.warn('[FloorPlanBatchExecutor] Audit append failed:', e);
    }
}

// ── Main executor ─────────────────────────────────────────────────────────────

export class FloorPlanBatchExecutor {
    /**
     * Execute all proposals in dependency order.
     *
     * For ADD_OPENING commands whose host wall is not yet in the store but is
     * present in the proposals list, the wall is executed first automatically
     * (same guard logic as AIPanel.approveProposal).
     *
     * @param proposals - All proposals generated by FloorPlanCommandBatcher.
     * @param onProgress - Optional callback for UI progress updates.
     * @returns BatchExecutionResult with counts and any failures.
     */
    static execute(
        proposals: CommandProposal[],
        onProgress?: BatchProgressCallback
    ): BatchExecutionResult {
        const manager = window.commandManager; // TODO(TASK-06)
        if (!manager) {
            console.error('[FloorPlanBatchExecutor] commandManager not available'); // TODO(TASK-06)
            const failedAll = proposals.map(p => ({
                proposal: p,
                reason: 'CommandManager unavailable — page may need a refresh',
            }));
            return {
                succeeded: 0,
                failed: proposals.length,
                summary: { walls: 0, slab: 0, doors: 0, windows: 0, other: 0 },
                failedProposals: failedAll,
            };
        }

        const sorted = sortIntoExecutionOrder(proposals);
        const total  = sorted.length;

        let succeeded = 0;
        let failed    = 0;
        const failedProposals: Array<{ proposal: CommandProposal; reason: string }> = [];
        const summary = { walls: 0, slab: 0, doors: 0, windows: 0, other: 0 };

        // Track wall UUIDs created during this batch so we can detect pending deps
        const executedProposalIds = new Set<string>();

        for (let i = 0; i < sorted.length; i++) {
            const proposal = sorted[i]!;
            const cmd = proposal.command;

            // Skip if this proposal was already executed as an auto-dependency
            if (executedProposalIds.has(proposal.id)) continue;

            onProgress?.(`Executing ${proposal.intentType}…`, i, total);

            try {
                // ── Auto-execute parent wall for ADD_OPENING commands ──────────
                if (cmd.type === CommandType.ADD_OPENING && cmd.targetIds[0]) {
                    const wallId   = cmd.targetIds[0];
                    const wallStore = window.wallStore; // TODO(TASK-08)
                    const wallExists = wallStore
                        ? !!wallStore.getById(wallId)
                        : false;

                    if (!wallExists) {
                        const wallProposal = sorted.find(
                            p =>
                                p.command.type === CommandType.CREATE_WALL &&
                                p.command.targetIds[0] === wallId &&
                                !executedProposalIds.has(p.id)
                        );

                        if (wallProposal) {
                            console.log('[FloorPlanBatchExecutor] Auto-executing parent wall:', wallId);
                            const wallResult = manager.execute(wallProposal.command, {
                                source: 'PDF_IMPORT_BATCH',
                                proposalId: wallProposal.id,
                            });

                            if (wallResult.success) {
                                executedProposalIds.add(wallProposal.id);
                                summary.walls++;
                                succeeded++;
                                appendAudit(wallProposal, 'System (auto-dependency)');
                            } else {
                                const reason = wallResult.info?.join(', ') || 'Failed to auto-create parent wall';
                                console.warn('[FloorPlanBatchExecutor] Parent wall failed:', reason);
                            }
                        }
                    }
                }

                // ── Execute this proposal ─────────────────────────────────────
                const result = manager.execute(cmd, {
                    source: 'PDF_IMPORT_BATCH',
                    proposalId: proposal.id,
                });

                if (result.success) {
                    executedProposalIds.add(proposal.id);
                    succeeded++;

                    // Update typed summary counters
                    switch (cmd.type) {
                        case CommandType.CREATE_WALL:
                            summary.walls++;
                            break;
                        case CommandType.CREATE_SLAB:
                            summary.slab++;
                            break;
                        case CommandType.ADD_OPENING: {
                            const sub = getOpeningSubType(proposal);
                            if (sub === 'door')        summary.doors++;
                            else if (sub === 'window') summary.windows++;
                            else                       summary.other++;
                            break;
                        }
                        default:
                            summary.other++;
                    }

                    appendAudit(proposal, 'User (batch)');
                } else {
                    failed++;
                    const reason = result.info?.join(', ') || 'Execution failed';
                    failedProposals.push({ proposal, reason });
                    console.warn(`[FloorPlanBatchExecutor] Failed: ${proposal.intentType} — ${reason}`);
                }
            } catch (err) {
                failed++;
                const reason = err instanceof Error ? err.message : String(err);
                failedProposals.push({ proposal, reason });
                console.error(`[FloorPlanBatchExecutor] Error: ${proposal.intentType}`, err);
            }
        }

        onProgress?.('Complete', total, total);

        // Dispatch update events once at the end (not per-element, to avoid N re-renders)
        window.dispatchEvent(new CustomEvent('model-updated')); // TODO(TASK-12)
        window.dispatchEvent(new CustomEvent('ai-model-update')); // TODO(TASK-12)
        window.dispatchEvent(new CustomEvent('update-view-browser')); // TODO(TASK-12)

        console.log(
            `[FloorPlanBatchExecutor] Done — ${succeeded} succeeded / ${failed} failed`,
            summary
        );

        return { succeeded, failed, summary, failedProposals };
    }
}
