import { z } from 'zod';

/**
 * Finish layer schema — compatible with DoorFinishLayer in DoorSystemTypeStore.
 * Defines a named finish material applied to a door component (frame, leaf, glass).
 * Stamped onto DoorOpening at creation time from the selected DoorSystemType.
 */
export const DoorFinishLayerSchema = z.object({
    name:          z.string(),
    materialColor: z.string().default('#f2f0ed'),
    materialId:    z.string().optional(),
    description:   z.string().optional(),
});
export type DoorFinishLayerData = z.infer<typeof DoorFinishLayerSchema>;

/**
 * A single horizontal row of the door leaf, with its own column division.
 * Adopted directly from Pascal DoorNode.segments (audited as gold standard).
 */
export const DoorSegmentSchema = z.object({
    type: z.enum(['panel', 'glass', 'empty']),
    heightRatio: z.number().positive(),
    columnRatios: z.array(z.number().positive()).min(1).default([1]),
    dividerThickness: z.number().nonnegative().default(0.03),
    panelDepth: z.number().default(0.01),
    panelInset: z.number().nonnegative().default(0.04),
});
export type DoorSegment = z.infer<typeof DoorSegmentSchema>;

/**
 * Rich parametric door record stored in DoorStore.
 *
 * KEY DESIGN RULE: `id` == `Opening.elementId` in WallData.openings[].
 * `wallId` == the host wall's id in WallStore.
 * `openingId` == `Opening.id` in WallData.openings[] (the geometry key).
 *
 * OFFSET ENCODING (PLAN-09 — CENTER convention): `offset` is the absolute distance
 * in metres from baseLine[0] to the CENTRE of the opening.
 * LEFT_EDGE = offset − width/2; RIGHT_EDGE = offset + width/2.
 * Same convention as Opening.offset in WallTypes.ts. NOT a wall-local [x,y,z] tuple.
 */
export const DoorOpeningSchema = z.object({
    // Identity
    id:         z.string().min(1),   // == Opening.elementId
    openingId:  z.string().min(1),   // == Opening.id
    wallId:     z.string().min(1),

    // Geometry (mirrors Opening for bi-directional lookups)
    offset:     z.number().nonnegative(),
    width:      z.number().positive(),
    height:     z.number().positive(),
    sillHeight: z.number().nonnegative(),

    // Frame
    frameThickness: z.number().positive().default(0.05),
    frameDepth:     z.number().positive().default(0.07),
    frameColor:     z.string().default('#f2f0ed'),

    // Leaf
    leafThickness:    z.number().positive().default(0.04),
    leafColor:        z.string().default('#f2f0ed'),
    leafVisibleInPlan: z.boolean().default(false),
    hingesSide:       z.enum(['left', 'right']).default('left'),
    swingDirection:   z.enum(['inward', 'outward']).default('inward'),
    segments: z.array(DoorSegmentSchema).min(1).default([
        { type: 'panel', heightRatio: 0.4, columnRatios: [1], dividerThickness: 0.03, panelDepth: 0.01, panelInset: 0.04 },
        { type: 'panel', heightRatio: 0.6, columnRatios: [1], dividerThickness: 0.03, panelDepth: 0.01, panelInset: 0.04 },
    ]),
    contentPadding: z.tuple([z.number(), z.number()]).default([0.04, 0.04]),

    // Handle
    handle:       z.boolean().default(true),
    handleHeight: z.number().positive().default(1.05),
    handleSide:   z.enum(['left', 'right']).default('right'),

    // Threshold
    threshold:       z.boolean().default(true),
    thresholdHeight: z.number().nonnegative().default(0.02),

    // IFC / BIM fields
    doorType:          z.enum(['single', 'double']).default('single'),
    fireRating:        z.string().optional(),
    accessibilityType: z.string().optional(),

    // DW-12 FIX: Persistent mark stored on the element instance.
    // Format: D-<NNN> (e.g. "D-001", "D-002").
    // Auto-generated by CreateWallOpeningCommand at placement time.
    // Editable by the user via the property panel markInput.
    mark: z.string().optional(),

    // Finish — structured finish layers stamped from DoorSystemType at creation time.
    // These are the primary BIM finish records; frameColor / leafColor are derived
    // from these for the 3-D renderer (backward-compatible render fields preserved).
    frameFinish: DoorFinishLayerSchema.optional(),
    leafFinish:  DoorFinishLayerSchema.optional(),

    // Derived finish material name for room finish schedules (auto-set from leafFinish.name)
    finishMaterial:    z.string().optional(),

    // Type system — reference to the DoorSystemType that generated this door's finish defaults
    systemTypeId:      z.string().optional(),
});

export type DoorOpening = z.infer<typeof DoorOpeningSchema>;
