// editor/bootstrap — wires the L0→L5 data half (S05-T8).
//
// Spec: `phases/PHASE-1A-Q1-M1-M3-SKELETON-RAILS.md` §S05-T8 (line 549):
//   "bootstrap.ts wires protocol, command-bus, persistence-client,
//    stores, scene-committer.  bootstrap.start() is no-op stub until
//    S06 D5 (render half).  Smoke test: bootstrap() builds without
//    throw + returns tearDown function."
//
// What this file does at S05:
//   1. Constructs a CommandBus + PatchEmitter + UndoStack (L2).
//   2. Constructs the L1 stores requested by the caller (defaults
//      to a single CubeStore so the Hello-Cube demo just works).
//   3. Wires the bus's PatchEmitter to the stores via attachStores
//      (one-call routing of per-store patches).
//   4. Constructs a CommitterHost (L5) and binds each store to it
//      via bindStore (per-tick batched dispatcher).
//   5. Returns an EditorRuntime exposing the bus, stores, host, and
//      a `start()` stub + `tearDown()` function.
//
// What this file deliberately DOES NOT do at S05:
//   • No FrameScheduler integration — `start()` is a no-op until S06.
//   • No renderer construction — that's S06 D5.
//   • No persistence-client wiring — the EventLog adapter lands in S06
//     once the rAF→commit pump is live.  The reservation appears here
//     as a typed (`persistenceClient?: unknown`) input so the bootstrap
//     surface doesn't churn when S06 fills it in.

import {
  CommandBus,
  PatchEmitter,
  UndoStack,
  type AuditDefaults,
  type CommandHandler,
} from '@pryzm/command-bus';
import { attachStores, CubeStore, type Store } from '@pryzm/stores';
import {
  bindStore,
  CommitterHost,
  type BindStoreHandle,
  type PrimitiveCommitter,
} from '@pryzm/scene-committer';

export interface BootstrapOptions {
  /** Caller-side audit defaults stamped onto every event emitted by this
   *  runtime.  Per-command `timestamp` is generated by the bus itself
   *  (see `AuditDefaults` in `@pryzm/command-bus`), so it is intentionally
   *  excluded from this surface. */
  readonly audit: AuditDefaults;
  /** L1 stores to register.  Default: `{ cube: new CubeStore() }`. */
  readonly stores?: Readonly<Record<string, Store<object>>> | undefined;
  /** Command handlers to register on the bus before it's returned. */
  readonly handlers?: readonly CommandHandler<unknown, never>[] | undefined;
  /** Primitive committers to register on the host before binding stores.
   *  Each entry's `primitiveType` MUST match a store key in `stores` for
   *  the binding to take effect — un-bound primitives produce a warning
   *  via `onUnboundPrimitive`. */
  readonly committers?: readonly PrimitiveCommitter[] | undefined;
  /** Called when a registered committer has no matching store key.
   *  Default: silent (bootstrap-friendly). */
  readonly onUnboundPrimitive?: ((primitiveType: string) => void) | undefined;
  /** Reserved for S06 — the persistence-client EventLog adapter. */
  readonly persistenceClient?: unknown;
}

export interface EditorRuntime {
  readonly bus: CommandBus;
  readonly emitter: PatchEmitter;
  readonly undoStack: UndoStack;
  readonly stores: Readonly<Record<string, Store<object>>>;
  readonly host: CommitterHost;
  readonly bindings: readonly BindStoreHandle[];
  /** No-op stub at S05.  S06 D5 attaches the FrameScheduler tick. */
  start(): void;
  /** Idempotent.  Disposes bindings, host, and detaches the bus
   *  emitter routing.  Subsequent calls are no-ops. */
  tearDown(): void;
}

export function bootstrap(opts: BootstrapOptions): EditorRuntime {
  // L1 stores — default to a single cube store so the demo wiring
  // works without ceremony.
  const stores: Readonly<Record<string, Store<object>>> =
    opts.stores ?? { cube: new CubeStore() as Store<object> };

  // L2 command bus.  The storesProvider hands handlers a Record<id, dto>
  // view of every Store<T>; produced via getState() snapshots that are
  // identity-stable across mutations.  Handlers `produceCommand` against
  // these views; the bus emits patches; `attachStores` re-applies the
  // forward patches to the canonical Store<T>.
  const emitter = new PatchEmitter();
  const undoStack = new UndoStack({ maxSize: 200 });
  const storesView = makeMemoizedStoresRecordView(stores);
  const bus = new CommandBus({
    audit: opts.audit,
    storesProvider: storesView.provider,
    emitter,
    undoStack,
  });
  for (const handler of opts.handlers ?? []) {
    bus.register(handler as CommandHandler<unknown>);
  }

  // PatchEmitter → Stores (per-store patch routing).
  const detachStores = attachStores(emitter, stores);

  // L5 committer host + bindings.
  const host = new CommitterHost();
  for (const c of opts.committers ?? []) {
    host.register(c);
  }
  const bindings: BindStoreHandle[] = [];
  for (const c of opts.committers ?? []) {
    const store = stores[c.primitiveType];
    if (store === undefined) {
      opts.onUnboundPrimitive?.(c.primitiveType);
      continue;
    }
    bindings.push(bindStore(store, c.primitiveType, host));
  }

  let torn = false;

  return {
    bus,
    emitter,
    undoStack,
    stores,
    host,
    bindings,
    start(): void {
      // S06 D5 — wire `scheduler.requestFrame` here so flushes land
      // on the rAF tick.  Today: no-op (bindStore's default
      // `queueMicrotask` schedule is sufficient for tests + bench).
    },
    tearDown(): void {
      if (torn) return;
      torn = true;
      for (const b of bindings) b.dispose();
      detachStores();
      host.dispose();
      storesView.dispose();
    },
  };
}

/** §PERF-STORESVIEW-MEMO (2026-09-02 perf lane, diagnosis fix 6) — the memoised
 *  `Record<storeKey, Record<id, T>>` view the bus's storesProvider returns.
 *
 *  The predecessor (`storesAsRecordView`) rebuilt `Object.fromEntries` over
 *  EVERY store's whole Map on EVERY dispatch, and its own comment promised
 *  "for S06 we'll add a memoised view if it shows up in the bench" — it showed
 *  up: BASE-INNER measured 0.117 → 0.672 ms/dispatch as the wall store grew to
 *  1000 elements, paid by every verb.
 *
 *  Invalidation is PER-STORE via `Store.subscribeDirty` — sound because
 *  `applyPatch` is the Store's only mutation door (attachStores routes every
 *  bus patch through it, and it fires the dirty listeners on each call), so a
 *  handler context still always sees the latest state (C03).  A store's inner
 *  view object keeps its identity until that store actually changes; the outer
 *  record is rebuilt only when any store changed, so an unchanged runtime
 *  serves one stable snapshot.  Asserted (freshness + identity + granularity +
 *  disposal) by `__tests__/bootstrapStoresViewMemo.test.ts`. */
function makeMemoizedStoresRecordView(
  stores: Readonly<Record<string, Store<object>>>,
): {
  provider: () => Readonly<Record<string, Readonly<Record<string, unknown>>>>;
  dispose: () => void;
} {
  const inner = new Map<string, Readonly<Record<string, unknown>>>();
  const dirty = new Set<string>(Object.keys(stores));
  const disposers: Array<() => void> = [];
  for (const [key, store] of Object.entries(stores)) {
    disposers.push(store.subscribeDirty(() => { dirty.add(key); }));
  }
  let outer: Readonly<Record<string, Readonly<Record<string, unknown>>>> | null = null;
  const provider = (): Readonly<Record<string, Readonly<Record<string, unknown>>>> => {
    if (dirty.size > 0 || outer === null) {
      for (const key of dirty) {
        const store = stores[key];
        if (store !== undefined) inner.set(key, Object.fromEntries(store.getState()));
      }
      dirty.clear();
      outer = Object.fromEntries(inner);
    }
    return outer;
  };
  return {
    provider,
    dispose: () => { for (const d of disposers) d(); disposers.length = 0; },
  };
}
