/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Export — Design Rationale (NEW FILE)
 * Phase:             Phase G — G-4 (Auto-Generated Design Rationale Document)
 * Files Modified:    src/export/RationaleExporter.ts (new)
 * Classification:    A
 *
 * Contract:
 *   docs/00_PRZYM/PRYZM_WORLD_MODEL_MASTER_PLAN_2026.md § G-4
 *   docs/00_Contracts/05-BIM-UI-ARCHITECTURE-CONTRACT.md — no BIM engine imports
 *
 * Impact Assessment:
 *   Store Reads:      YES — reads DecisionRecordStore, TemporalGraph, ConstraintEngine
 *                    via lazy window.* access (same pattern as WorldModelAdapter)
 *   Store Writes:     NO — pure read-only exporter
 *   Event Bus:        NO
 *   Builder Calls:    NO
 *   Command Dispatch: NO
 *
 * Risk Level:   Zero (read-only, output is a string — no side effects)
 * Rationale:
 *   Reads all DecisionRecord entries, all ConstraintEngine violations, and the
 *   full temporal graph to produce a structured Markdown document that serves
 *   as a planning submission annex.
 *
 *   The output is in Markdown format (primary). The caller can trigger browser
 *   printing for a PDF output.
 *
 *   generate() is synchronous and safe to call at any point during a session.
 *   It is resilient to empty stores — all sections degrade gracefully.
 */

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmt(ts: number | undefined): string {
    if (!ts) return '—';
    return new Date(ts).toLocaleDateString(undefined, {
        year: 'numeric', month: 'long', day: 'numeric',
    });
}

function fmtDateTime(ts: number | undefined): string {
    if (!ts) return '—';
    return new Date(ts).toLocaleString(undefined, {
        year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
    });
}

function safeGet<T>(fn: () => T, fallback: T): T {
    try { return fn(); } catch { return fallback; }
}

// ── RationaleExporter ─────────────────────────────────────────────────────────

export interface RationaleExportOptions {
    projectName: string;
    projectId?:  string;
}

export class RationaleExporter {

    /**
     * Generate a complete Markdown design rationale document.
     * Returns a string that is syntactically valid Markdown.
     * Never throws — all sections degrade gracefully on empty data.
     */
    static generate(opts: RationaleExportOptions): string {
        const { projectName } = opts;
        const now = fmtDateTime(Date.now());

        const sections: string[] = [];

        sections.push(`# Design Rationale Report — ${projectName}`);
        sections.push(`*Generated by PRYZM on ${now}*\n`);

        sections.push(this._section1_overview());
        sections.push(this._section2_programme());
        sections.push(this._section3_decisions());
        sections.push(this._section4_overrides());
        sections.push(this._section5_evolution());
        sections.push(this._footer());

        return sections.join('\n\n---\n\n');
    }

    // ── Section 1: Project Overview ───────────────────────────────────────────

    private static _section1_overview(): string {
        const lines: string[] = ['## 1. Project Overview'];

        const hs = safeGet(() => window.hierarchyStore, null); // TODO(TASK-08)
        if (!hs) {
            lines.push('*No hierarchy data available.*');
            return lines.join('\n');
        }

        try {
            const sites     = safeGet(() => hs.getAllSites?.()     ?? [], []);
            const buildings = safeGet(() => hs.getAllBuildings?.() ?? [], []);
            const levels    = safeGet(() => hs.getAllLevels?.()    ?? [], []);
            const units     = safeGet(() => hs.getAllUnits?.()     ?? [], []);

            if (sites.length > 0)     lines.push(`**Sites:** ${sites.map((s: any) => s.name ?? s.id).join(', ')}`);
            if (buildings.length > 0) lines.push(`**Buildings:** ${buildings.map((b: any) => b.name ?? b.id).join(', ')}`);
            if (levels.length > 0)    lines.push(`**Levels:** ${levels.length} (${levels.map((l: any) => l.name ?? l.id).join(', ')})`);
            if (units.length > 0)     lines.push(`**Planning Units:** ${units.length}`);

            if (lines.length === 1) lines.push('*No hierarchy data available.*');
        } catch {
            lines.push('*Error reading hierarchy data.*');
        }

        return lines.join('\n');
    }

    // ── Section 2: Programme Compliance Summary ───────────────────────────────

    private static _section2_programme(): string {
        const lines: string[] = ['## 2. Programme Compliance Summary'];

        const ss = safeGet(() => window.syncStateEngine, null);
        if (!ss) {
            lines.push('*Programme data not available.*');
            return lines.join('\n');
        }

        try {
            const summary = safeGet(() => ss.getSummary?.(), null);
            if (!summary) {
                lines.push('*No programme summary available.*');
                return lines.join('\n');
            }
            const { totalNodes = 0, synced = 0, derived = 0, conflict = 0, pending = 0 } = summary as any;
            lines.push(`| State | Count |`);
            lines.push(`|---|---|`);
            lines.push(`| ✅ Synced    | ${synced}  |`);
            lines.push(`| 🟡 Derived  | ${derived} |`);
            lines.push(`| 🔴 Conflict | ${conflict} |`);
            lines.push(`| ⏳ Pending  | ${pending}  |`);
            lines.push(`| **Total**   | **${totalNodes}** |`);
        } catch {
            lines.push('*Error reading programme data.*');
        }

        return lines.join('\n');
    }

    // ── Section 3: Non-Standard Decisions ────────────────────────────────────

    private static _section3_decisions(): string {
        const lines: string[] = ['## 3. Non-Standard Decisions'];

        const drs = safeGet(() => window.decisionRecordStore, null); // TODO(TASK-08)
        if (!drs) {
            lines.push('*Decision record store not available.*');
            return lines.join('\n');
        }

        const records = safeGet(() => (drs as any).getNonDismissed?.() ?? [], []);
        const nonOverrides = records.filter((r: any) => r.decisionType !== 'override');

        if (nonOverrides.length === 0) {
            lines.push('*No non-standard decisions recorded in this project.*');
            return lines.join('\n');
        }

        for (const r of nonOverrides) {
            const codeStr = safeGet(
                () => window.elementCodeStore?.getCode?.(r.elementId) ?? r.elementId, // TODO(TASK-08)
                r.elementId
            );
            const typeLabel: Record<string, string> = {
                deviation:  'Deviation',
                preference: 'Preference',
                external:   'External constraint',
            };
            const label = typeLabel[r.decisionType] ?? r.decisionType;
            lines.push(`> **[${codeStr}]** — *${label}*`);
            if (r.decision) lines.push(`> Rationale: ${r.decision}`);
            if (r.templateRequirementId) lines.push(`> Template requirement: \`${r.templateRequirementId}\``);
            lines.push(`> Recorded: ${fmt(r.recordedAt)}`);
            lines.push('');
        }

        return lines.join('\n');
    }

    // ── Section 4: Constraint Overrides ──────────────────────────────────────

    private static _section4_overrides(): string {
        const lines: string[] = ['## 4. Constraint Overrides'];

        const drs = safeGet(() => window.decisionRecordStore, null); // TODO(TASK-08)
        if (!drs) {
            lines.push('*Decision record store not available.*');
            return lines.join('\n');
        }

        const records  = safeGet(() => (drs as any).getAll?.() ?? [], []);
        const overrides = records.filter((r: any) => r.decisionType === 'override');

        if (overrides.length === 0) {
            lines.push('*No constraint overrides recorded in this project.*');
            return lines.join('\n');
        }

        for (const r of overrides) {
            const codeStr = safeGet(
                () => window.elementCodeStore?.getCode?.(r.elementId) ?? r.elementId, // TODO(TASK-08)
                r.elementId
            );
            lines.push(`> **[${codeStr}]** — *Constraint override*`);
            if (r.constraintRuleId) lines.push(`> Rule overridden: \`${r.constraintRuleId}\``);
            if (!r.dismissed && r.decision) lines.push(`> Rationale: ${r.decision}`);
            else if (r.dismissed) lines.push(`> *(Dismissed — no rationale recorded)*`);
            lines.push(`> Date: ${fmt(r.triggeredAt)}`);
            lines.push('');
        }

        return lines.join('\n');
    }

    // ── Section 5: Design Evolution Summary ──────────────────────────────────

    private static _section5_evolution(): string {
        const lines: string[] = ['## 5. Design Evolution Summary'];

        const tg = safeGet(() => window.temporalGraphManager, null);
        if (!tg) {
            lines.push('*Temporal graph not available.*');
            return lines.join('\n');
        }

        try {
            const sessions  = safeGet(() => (tg as any).getSessionSummaries?.() ?? [], []);
            const edgeCount = safeGet(() => (tg as any).edgeCount?.()     ?? 0, 0);
            const mutCount  = safeGet(() => (tg as any).mutationCount?.() ?? 0, 0);

            lines.push(`**Total mutations recorded:** ${mutCount}`);
            lines.push(`**Total relationship changes:** ${edgeCount}`);
            lines.push(`**Design sessions:** ${sessions.length}`);

            if (sessions.length > 0) {
                lines.push('');
                lines.push('| Session | Started | Mutations | Edges |');
                lines.push('|---|---|---|---|');
                for (const s of sessions) {
                    const started  = fmt(s.startedAt);
                    const current  = s.isCurrent ? ' *(current)*' : '';
                    lines.push(`| \`${(s.sessionId as string).slice(-8).toUpperCase()}\`${current} | ${started} | ${s.mutationCount} | ${s.edgeCount} |`);
                }
            }
        } catch {
            lines.push('*Error reading temporal graph data.*');
        }

        return lines.join('\n');
    }

    // ── Footer ────────────────────────────────────────────────────────────────

    private static _footer(): string {
        return [
            '---',
            '*This document was generated automatically by PRYZM World Model.*',
            '*All decision records, constraint violations, and design evolution data*',
            '*are derived from the project\'s semantic graph and temporal log.*',
            '*This document may be used as a planning submission annex.*',
        ].join('\n');
    }

    // ── Download helper ───────────────────────────────────────────────────────

    /**
     * Triggers a browser download of the rationale document as a .md file.
     * Safe to call from any UI panel.
     */
    static download(opts: RationaleExportOptions): void {
        const md       = this.generate(opts);
        const blob     = new Blob([md], { type: 'text/markdown;charset=utf-8' });
        const url      = URL.createObjectURL(blob);
        const a        = document.createElement('a');
        a.href         = url;
        a.download     = `${opts.projectName.replace(/[^a-zA-Z0-9_-]/g, '_')}_design_rationale.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        console.log(`[RationaleExporter] Downloaded design rationale for: ${opts.projectName}`);
    }
}
