// §WORLD-COVERAGE-LEDGER — the tripwire that keeps `docs/04-reference/WORLD-COVERAGE-LEDGER.md`
// from rotting into another hand-copied list.
//
// WHY THIS TEST EXISTS
// --------------------
// The ledger answers "what does PRYZM actually serve HERE?" — the question the founder has been
// answering BY CLICKING (Ciudad Real had no measured heights; the Middle East is five city boxes;
// Japan/Mexico/Canada do not exist). It is generated by `tools/coverage-ledger/build.mjs`, and a
// generator is only worth having if something FAILS when the page and the code disagree.
//
// Without this spec the failure mode is silent and familiar: a lane adds `japan` to `bake.mjs`
// ALL_REGIONS, nobody re-runs the builder, and the page keeps saying Japan is ABSENT — a coverage
// document that CERTIFIES A GAP AS COVERED, or the reverse. CLAUDE.md records that exact shape five
// times over for the contract count/range, where the rule "the row and the range move together" was
// stated in three places and enforced by nothing. This is the enforcement.
//
// WHAT IT ASSERTS (all four are SET comparisons, never a count — a count can be right while the
// membership is wrong, which is how C76 slipped through a correct total):
//   A. every `bake.mjs` ALL_REGIONS region is NAMED on the page                  ← the brief's ask
//   B. every `terrain.mjs` NATIONAL_REGIONS region is NAMED on the page
//   C. every parcel `registry.ts` regionCode is NAMED on the page
//   D. every region slug has a country in COUNTRY_OF_SLUG — an unmapped slug would be a SILENTLY
//      DROPPED row, which is the defect the page exists to kill, reproduced inside the page.
//
// It also pins the summary counts the page prints, so a stale page fails even when every name
// happens to survive (a region REMOVED from bake.mjs but left on the page is a false claim too).
//
// ⚠ OFFLINE BY CONSTRUCTION. This spec never touches the network: it reads the CURRENT source
// tables through the builder's own exported readers and the CURRENT page off disk. The R2 probe is
// the builder's job, not CI's — a test that needed a live bucket would go red on someone's train.
//
// LAYERING: a build/inspection tool test, like its bake.mjs siblings — no OTel span (P8 binds
// exported package functions, not bake tooling).
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// The builder is ESM with a CLI-only `main()` guard, so importing it is inert.
import {
    readBakeRegions,
    readTerrainNational,
    readTerrainCities,
    readParcelJurisdictions,
    countryOfBakeRegion,
    COUNTRY_OF_SLUG,
    COUNTRY_NAME,
    LEDGER_PATH,
    // @ts-expect-error — plain .mjs tooling module, no types shipped (same as its bake.mjs siblings)
} from '../../coverage-ledger/build.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../../..');

const ledger = (): string => {
    const path = LEDGER_PATH as string;
    if (!existsSync(path)) {
        throw new Error(
            `docs/04-reference/WORLD-COVERAGE-LEDGER.md does not exist. Generate it: node tools/coverage-ledger/build.mjs`,
        );
    }
    return readFileSync(path, 'utf8');
};

interface BakeRegion { name: string; heightJoin: string | null }
interface NationalRegion { name: string; group: string }
interface ParcelRow { regionCode: string; kind: string }

describe('§WORLD-COVERAGE-LEDGER — the page cannot drift from the code', () => {
    it('A · every bake.mjs ALL_REGIONS region is named on the page', () => {
        const page = ledger();
        const regions = readBakeRegions() as BakeRegion[];
        expect(regions.length).toBeGreaterThan(0);
        const missing = regions.filter((r) => !page.includes(`\`${r.name}\``)).map((r) => r.name);
        expect(
            missing,
            `${missing.length} bake region(s) exist in bake.mjs but are NOT on the coverage ledger. ` +
            `That is a coverage page that omits real coverage — regenerate it: node tools/coverage-ledger/build.mjs`,
        ).toEqual([]);
    });

    it('A2 · the page names no region that bake.mjs has dropped', () => {
        const page = ledger();
        const names = new Set((readBakeRegions() as BakeRegion[]).map((r) => r.name));
        // §3's region table is the authoritative rendering of ALL_REGIONS; a row there for a
        // region bake.mjs no longer has is a claim about coverage that does not exist.
        const section = page.slice(page.indexOf('## §3 · Context bake regions'), page.indexOf('## §3b'));
        const rendered = [...section.matchAll(/^\| `([a-z0-9]+)` \|/gm)].map((m) => m[1]!);
        expect(rendered.length).toBe(names.size);
        expect(rendered.filter((n) => !names.has(n))).toEqual([]);
    });

    it('B · every terrain.mjs NATIONAL_REGIONS region is named on the page', () => {
        const page = ledger();
        const national = readTerrainNational() as NationalRegion[];
        expect(national.length).toBeGreaterThan(0);
        const missing = national.filter((r) => !page.includes(`\`${r.name}\``)).map((r) => r.name);
        expect(missing, 'terrain regions missing from the coverage ledger').toEqual([]);
    });

    it('C · every parcel registry regionCode is named on the page', () => {
        const page = ledger();
        const parcels = readParcelJurisdictions() as ParcelRow[];
        expect(parcels.length).toBeGreaterThan(0);
        const missing = parcels.filter((p) => !page.includes(`\`${p.regionCode}\``)).map((p) => p.regionCode);
        expect(missing, 'parcel jurisdictions missing from the coverage ledger').toEqual([]);
    });

    it('D · every bake + terrain region slug resolves to a country (no silently dropped row)', () => {
        const map = COUNTRY_OF_SLUG as Record<string, string>;
        const resolve1 = countryOfBakeRegion as (r: unknown) => string | null;
        const bake = readBakeRegions() as BakeRegion[];
        // Same two-step the builder uses: the bake row states its own country in its
        // Geofabrik path; a terrain row inherits from the bake row of the SAME SLUG.
        const byBake = new Map<string, string>();
        for (const r of bake) { const c = resolve1(r); if (c) byBake.set(r.name, c); }
        const unresolved = [
            ...bake.filter((r) => !resolve1(r)).map((r) => r.name),
            ...(readTerrainNational() as NationalRegion[])
                .filter((r) => !map[r.name] && !byBake.has(r.name))
                .map((r) => r.name),
        ];
        expect(
            [...new Set(unresolved)],
            'these region slugs resolve to NO country — the ledger would DROP them silently. ' +
            'Either the Geofabrik extract is new (add it to ISO_OF_GEOFABRIK) or the row is a ' +
            'metro/city inside a multi-country extract (add it to COUNTRY_OF_SLUG), in ' +
            'tools/coverage-ledger/build.mjs.',
        ).toEqual([]);
        // Every mapped country must also have a display name, or the page prints a bare code.
        // ⚠ FLATTEN: a slug may map to an ARRAY (one Geofabrik extract spanning several
        // countries — `gcc-states` is six). Reading the values un-flattened compared an
        // array against a name table and reported the whole array as "nameless".
        const names = COUNTRY_NAME as Record<string, string>;
        const codes = Object.values(map).flatMap((v) => (Array.isArray(v) ? v : [v])) as string[];
        const nameless = [...new Set(codes.filter((c) => !names[c]))];
        expect(nameless, 'country codes with no name in COUNTRY_NAME').toEqual([]);
    });

    it('E · the summary counts on the page match the tables today', () => {
        const page = ledger();
        const bake = (readBakeRegions() as BakeRegion[]).length;
        const national = (readTerrainNational() as NationalRegion[]).length;
        const cities = (readTerrainCities() as { name: string }[]).length;
        const parcels = (readParcelJurisdictions() as ParcelRow[]).length;
        const num = (label: string): number => {
            const row = page.split('\n').find((l) => l.startsWith(`| ${label}`));
            if (!row) throw new Error(`summary row not found on the ledger: "${label}"`);
            const m = row.match(/\*\*(\d+)\*\*/);
            if (!m) throw new Error(`summary row has no bolded count: ${row}`);
            return Number(m[1]);
        };
        expect(num('Context bake regions')).toBe(bake);
        expect(num('Terrain national regions')).toBe(national);
        expect(num('Terrain city regions')).toBe(cities);
        expect(num('Parcel jurisdictions registered')).toBe(parcels);
    });

    it('F · the page carries no UNMAPPED marker and no un-regenerated placeholder', () => {
        const page = ledger();
        expect(page).not.toContain('⛔UNMAPPED');
        expect(page).not.toContain('UNMAPPED SLUGS');
        // The builder always stamps a probe record; its absence means the page was hand-written.
        expect(page).toContain('## §0 · Probe record');
        expect(page).toContain('GENERATED FILE — DO NOT HAND-EDIT');
    });

    it('G · the builder is committed alongside the page (a generated page with no generator rots)', () => {
        expect(existsSync(resolve(REPO, 'tools/coverage-ledger/build.mjs'))).toBe(true);
        expect(existsSync(resolve(REPO, 'tools/coverage-ledger/manifest-snapshot.json'))).toBe(true);
    });
});
