import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext,
} from '../types';
import { elementRegistry } from '@pryzm/core-app-model/element-registry';
import { serializeWallSnapshot, deserializeWallSnapshot } from '../walls/wallSnapshotUtils';
import { Point3D } from '@pryzm/core-app-model';
import { semanticGraphManager } from '@pryzm/core-app-model';

export type CopyableElementType = 'wall' | 'furniture';

export interface CopyElementInput {
    sourceId: string;
    /** New ID for the pasted copy — must be generated by the Tool layer (§01 §2.6). */
    newId: string;
    /** World-space translation to apply to the copied element. */
    offset: { x: number; y: number; z: number };
    /** Source element type — defaults to 'wall' for backward compatibility. */
    elementType?: CopyableElementType;
}

/**
 * CopyElementCommand
 *
 * Creates a new element at `sourceId.baseLine + offset`.
 * The copy is on the same level as the source with all parametric properties
 * (height, thickness, layers, systemTypeId, materialId) cloned.
 * Hosted openings (doors/windows) are intentionally NOT copied — they must be
 * re-placed manually (same-level only, Phase 1).
 *
 * Phase 1 scope: wall elements only.
 *
 * Undo: removes the copy and unregisters it from BimManager / elementRegistry.
 *
 * Contract compliance:
 *   §01 §2.1 — mutations via wallStore.add() / wallStore.remove().
 *   §01 §2.6 — newId supplied by the Tool layer.
 */
export class CopyElementCommand implements Command {
    readonly affectedStores: readonly string[];
    readonly id: string;
    readonly type  = CommandType.COPY_ELEMENT;
    readonly timestamp: number;
    readonly targetIds: string[];

    private executed = false;
    /** Child IDs created by furniture cloning (e.g., dining-chair clones). */
    private clonedChildIds: string[] = [];
    private readonly elementType: CopyableElementType;

    constructor(private readonly input: CopyElementInput) {
        this.id          = crypto.randomUUID();
        this.timestamp   = Date.now();
        this.elementType = input.elementType ?? 'wall';
        this.affectedStores = this.elementType === 'furniture' ? ['furniture'] : ['wall'];
        this.targetIds = [input.sourceId, input.newId];
        Object.freeze(this.targetIds);
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        if (this.elementType === 'furniture') {
            const fStore = (ctx.stores as any).furnitureStore;
            if (!fStore) return { ok: false, reason: 'STORE_UNAVAILABLE', blockingIssues: ['FurnitureStore not initialized'] };
            const source = fStore.get(this.input.sourceId);
            if (!source) return { ok: false, reason: 'SOURCE_NOT_FOUND', blockingIssues: [`Furniture not found: ${this.input.sourceId}`] };
            if (fStore.get(this.input.newId)) {
                return { ok: false, reason: 'NEW_ID_CONFLICT', blockingIssues: [`ID already in use: ${this.input.newId}`] };
            }
            return { ok: true };
        }
        const source = ctx.stores.wallStore.getById(this.input.sourceId);
        if (!source) return { ok: false, reason: 'SOURCE_NOT_FOUND', blockingIssues: [`Element not found: ${this.input.sourceId}`] };
        if (ctx.stores.wallStore.getById(this.input.newId)) {
            return { ok: false, reason: 'NEW_ID_CONFLICT', blockingIssues: [`ID already in use: ${this.input.newId}`] };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        if (this.executed) return { success: false, affectedElementIds: [], info: ['Already executed'] };

        if (this.elementType === 'furniture') {
            return this._executeFurniture(ctx);
        }

        const source = ctx.stores.wallStore.getById(this.input.sourceId)!;
        const { x: ox, y: oy, z: oz } = this.input.offset;

        const copy = deserializeWallSnapshot(serializeWallSnapshot(source));
        copy.id       = this.input.newId;
        copy.baseLine = [
            { x: source.baseLine[0].x + ox, y: source.baseLine[0].y + oy, z: source.baseLine[0].z + oz },
            { x: source.baseLine[1].x + ox, y: source.baseLine[1].y + oy, z: source.baseLine[1].z + oz },
        ] as [Point3D, Point3D];
        copy.openings    = [];
        copy.childrenIds = [];
        copy._renderVersion = 1;

        ctx.stores.wallStore.add(copy);

        const bimMgr = ctx.bimManager ?? window.bimManager;
        bimMgr?.registerElement?.(this.input.newId, source.levelId);
        try { elementRegistry.registerSemantic(this.input.newId, 'wall'); } catch (_) {}

        this.executed = true;
        return { success: true, affectedElementIds: [this.input.newId] };
    }

    /** Furniture clone path — supports child duplication (e.g., dining-table chairs). */
    private _executeFurniture(ctx: CommandContext): CommandResult {
        const fStore = (ctx.stores as any).furnitureStore;
        const source = fStore.get(this.input.sourceId);
        if (!source) return { success: false, affectedElementIds: [], info: ['Source furniture vanished'] };

        const { x: ox, y: oy, z: oz } = this.input.offset;
        const bimMgr = ctx.bimManager ?? window.bimManager;
        const allFurniture: any[] = typeof fStore.getAll === 'function' ? fStore.getAll() : [];

        // Translate every Point3D-like field by the offset.
        const cloneAndOffset = (data: any, newId: string): any => {
            const out = JSON.parse(JSON.stringify(data));
            out.id = newId;
            const shift = (p: any) => p && typeof p === 'object'
                ? { x: (p.x ?? 0) + ox, y: (p.y ?? 0) + oy, z: (p.z ?? 0) + oz }
                : p;
            out.position   = shift(out.position);
            if (out.startPoint)  out.startPoint  = shift(out.startPoint);
            if (out.cornerPoint) out.cornerPoint = shift(out.cornerPoint);
            if (out.endPoint)    out.endPoint    = shift(out.endPoint);
            return out;
        };

        // Clone parent
        const parentCopy = cloneAndOffset(source, this.input.newId);
        // Drop parent linkage so the copy is independent.
        if (parentCopy.properties?.parentFurnitureId) {
            delete parentCopy.properties.parentFurnitureId;
            delete parentCopy.properties.parentType;
        }
        bimMgr?.registerElement?.(this.input.newId, source.levelId);
        fStore.add(parentCopy);
        try { elementRegistry.registerSemantic(this.input.newId, 'furniture'); } catch (_) {}
        try {
            semanticGraphManager.addRelationship({
                type: 'sitsOn',
                sourceId: this.input.newId,
                targetId: source.levelId,
                createdBy: 'CopyElementCommand',
                metadata: { addedBy: 'CopyElementCommand' },
            });
        } catch (_) { /* non-fatal */ }

        // Clone any direct children that reference the source as parent.
        const children = allFurniture.filter(f => f?.properties?.parentFurnitureId === this.input.sourceId);
        for (const child of children) {
            const childNewId = crypto.randomUUID();
            const childCopy  = cloneAndOffset(child, childNewId);
            if (childCopy.properties) {
                childCopy.properties.parentFurnitureId = this.input.newId;
            }
            bimMgr?.registerElement?.(childNewId, child.levelId);
            fStore.add(childCopy);
            try { elementRegistry.registerSemantic(childNewId, 'furniture'); } catch (_) {}
            this.clonedChildIds.push(childNewId);
        }

        this.executed = true;
        return { success: true, affectedElementIds: [this.input.newId, ...this.clonedChildIds] };
    }

    undo(ctx: CommandContext): CommandResult {
        if (!this.executed) return { success: false, affectedElementIds: [], info: ['Nothing to undo'] };

        const bimMgr = ctx.bimManager ?? window.bimManager;

        if (this.elementType === 'furniture') {
            const fStore = (ctx.stores as any).furnitureStore;
            for (const childId of this.clonedChildIds) {
                bimMgr?.unregisterElement?.(childId);
                elementRegistry.unregister(childId);
                fStore?.remove(childId);
            }
            try { semanticGraphManager.removeAllRelationshipsForElement(this.input.newId); } catch (_) {}
            bimMgr?.unregisterElement?.(this.input.newId);
            elementRegistry.unregister(this.input.newId);
            fStore?.remove(this.input.newId);
            const affected = [this.input.newId, ...this.clonedChildIds];
            this.clonedChildIds = [];
            this.executed = false;
            return { success: true, affectedElementIds: affected };
        }

        bimMgr?.unregisterElement?.(this.input.newId);
        elementRegistry.unregister(this.input.newId);
        ctx.stores.wallStore.remove(this.input.newId);

        this.executed = false;
        return { success: true, affectedElementIds: [this.input.newId] };
    }

    serialize(): SerializedCommand {
        return {
            type:      this.type,
            timestamp: this.timestamp,
            targetIds: [...this.targetIds],
            version:   1,
            payload: {
                sourceId:    this.input.sourceId,
                newId:       this.input.newId,
                offset:      { ...this.input.offset },
                elementType: this.elementType,
            },
        };
    }
}
