import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext,
} from '../types';
import { elementRegistry } from '@pryzm/core-app-model/element-registry';
import { serializeWallSnapshot, deserializeWallSnapshot } from '../walls/wallSnapshotUtils';
import { Point3D } from '@pryzm/core-app-model';

export interface MirrorElementInput {
    sourceId: string;
    /** New ID for the mirrored copy — must be generated by the Tool layer (§01 §2.6). */
    newId: string;
    /** First point defining the mirror axis line (XZ plane). */
    mirrorLineStart: Point3D;
    /** Second point defining the mirror axis line (XZ plane). */
    mirrorLineEnd: Point3D;
}

/**
 * MirrorElementCommand
 *
 * Creates a new element that is a mirrored copy of `sourceId` across the
 * provided mirror axis line (infinite line through mirrorLineStart → mirrorLineEnd
 * in the XZ plane).  The original element is preserved unchanged.
 *
 * Phase 1 scope: wall elements only.
 * Phase 2 will extend to slabs, columns, and curtain walls via the Topology Layer.
 *
 * Algorithm:
 *   - Reflect each baseline endpoint across the mirror axis using the standard
 *     2D point-reflection formula.
 *   - Assign the reflected baseLine to a new wall that copies all other
 *     properties (height, thickness, levelId, layers, systemTypeId, materialId).
 *
 * Undo: removes the mirrored copy from the wall store and unregisters it.
 *
 * Contract compliance:
 *   §01 §2.1 — mutations via wallStore.add() / wallStore.remove().
 *   §01 §2.2 — snapshot of the created element stored in execute() for undo.
 *   §01 §2.6 — newId is supplied by the Tool layer, never generated here.
 */
export class MirrorElementCommand implements Command {
    readonly affectedStores = ['wall'] as const;
    readonly id: string;
    readonly type  = CommandType.MIRROR_ELEMENT;
    readonly timestamp: number;
    readonly targetIds: string[];

    private executed = false;

    constructor(private readonly input: MirrorElementInput) {
        this.id        = crypto.randomUUID();
        this.timestamp = Date.now();
        this.targetIds = [input.sourceId, input.newId];
        Object.freeze(this.targetIds);
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        const source = ctx.stores.wallStore.getById(this.input.sourceId);
        if (!source) return { ok: false, reason: 'SOURCE_NOT_FOUND', blockingIssues: [`Element not found: ${this.input.sourceId}`] };
        if (ctx.stores.wallStore.getById(this.input.newId)) {
            return { ok: false, reason: 'NEW_ID_CONFLICT', blockingIssues: [`ID already in use: ${this.input.newId}`] };
        }
        const dx = this.input.mirrorLineEnd.x - this.input.mirrorLineStart.x;
        const dz = this.input.mirrorLineEnd.z - this.input.mirrorLineStart.z;
        if (Math.sqrt(dx * dx + dz * dz) < 1e-6) {
            return { ok: false, reason: 'DEGENERATE_MIRROR_AXIS', blockingIssues: ['Mirror axis start and end are the same point'] };
        }
        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        if (this.executed) return { success: false, affectedElementIds: [], info: ['Already executed'] };

        const source = ctx.stores.wallStore.getById(this.input.sourceId)!;
        const { mirrorLineStart: ls, mirrorLineEnd: le } = this.input;

        const r0 = _reflectPointXZ(source.baseLine[0], ls, le);
        const r1 = _reflectPointXZ(source.baseLine[1], ls, le);

        const mirrored = deserializeWallSnapshot(serializeWallSnapshot(source));
        mirrored.id       = this.input.newId;
        mirrored.baseLine = [
            { x: r0.x, y: source.baseLine[0].y, z: r0.z },
            { x: r1.x, y: source.baseLine[1].y, z: r1.z },
        ] as [Point3D, Point3D];
        mirrored.openings    = [];
        mirrored.childrenIds = [];
        mirrored._renderVersion = 1;

        ctx.stores.wallStore.add(mirrored);

        const bimMgr = ctx.bimManager ?? window.bimManager;
        bimMgr?.registerElement?.(this.input.newId, source.levelId);
        try { elementRegistry.registerSemantic(this.input.newId, 'wall'); } catch (_) {}

        this.executed = true;
        return { success: true, affectedElementIds: [this.input.newId] };
    }

    undo(ctx: CommandContext): CommandResult {
        if (!this.executed) return { success: false, affectedElementIds: [], info: ['Nothing to undo'] };

        const bimMgr = ctx.bimManager ?? window.bimManager;
        bimMgr?.unregisterElement?.(this.input.newId);
        elementRegistry.unregister(this.input.newId);
        ctx.stores.wallStore.remove(this.input.newId);

        this.executed = false;
        return { success: true, affectedElementIds: [this.input.newId] };
    }

    serialize(): SerializedCommand {
        return {
            type:      this.type,
            timestamp: this.timestamp,
            targetIds: [...this.targetIds],
            version:   1,
            payload: {
                sourceId:       this.input.sourceId,
                newId:          this.input.newId,
                mirrorLineStart: this.input.mirrorLineStart,
                mirrorLineEnd:   this.input.mirrorLineEnd,
            },
        };
    }
}

// ── XZ reflection helper ───────────────────────────────────────────────────

/**
 * Reflects point P across the infinite line through L1 and L2 in the XZ plane.
 * Y coordinate is returned unchanged.
 *
 * Formula: P' = 2*(P·d̂ - L1·d̂)*d̂ + 2*(L1 - P⊥) where d̂ is the unit direction.
 * Equivalent closed form (standard 2D reflection):
 *   P' = 2 * proj(P - L1, d̂) * d̂ + L1 - (P - L1) + 2*(P - L1) · ...
 * Using the canonical formula: P' = 2*(d̂·(P-L1))*d̂ - (P-L1) + L1*2 ... simplified:
 */
function _reflectPointXZ(p: Point3D, l1: Point3D, l2: Point3D): Point3D {
    const dx = l2.x - l1.x;
    const dz = l2.z - l1.z;
    const lenSq = dx * dx + dz * dz;
    // Vector from l1 to p
    const ex = p.x - l1.x;
    const ez = p.z - l1.z;
    // Scalar projection of (p-l1) onto the axis direction
    const dot = (ex * dx + ez * dz) / lenSq;
    // Foot of perpendicular (closest point on axis to p)
    const fx = l1.x + dot * dx;
    const fz = l1.z + dot * dz;
    // Reflect across the foot
    return { x: 2 * fx - p.x, y: p.y, z: 2 * fz - p.z };
}
