import {
    Command, CommandType, CommandValidationResult,
    CommandResult, SerializedCommand, CommandContext,
} from '../types';
import { elementRegistry } from '@pryzm/core-app-model/element-registry';
import { serializeWallSnapshot, deserializeWallSnapshot } from '../walls/wallSnapshotUtils';
import { Point3D } from '@pryzm/core-app-model';

export interface OffsetElementInput {
    sourceId: string;
    /** New ID for the offset copy — must be generated by the Tool layer (§01 §2.6). */
    newId: string;
    /**
     * Signed perpendicular offset distance in metres.
     * Positive  →  left of the wall direction (A0→A1 with XZ right-hand normal: +X rotated 90° CW in XZ = +Z).
     * Negative  →  right of the wall direction.
     * The Tool layer determines sign from the user's pick point / direction input.
     */
    distance: number;
}

/**
 * OffsetElementCommand
 *
 * Creates a new parallel wall at `distance` metres from `sourceId`.
 * The offset direction is perpendicular to the wall baseline in the XZ plane,
 * computed as the 90°-clockwise rotation of the normalised direction vector:
 *
 *   dir  = normalise(A1 - A0)        — along the wall
 *   perp = (dir.z, 0, -dir.x)       — perpendicular (right-hand XZ, positive = "left" in BIM coords)
 *
 * All structural properties are inherited from the source wall.
 * Hosted openings are not copied (same policy as CopyElementCommand).
 *
 * Undo: removes the offset copy and unregisters it.
 *
 * Contract compliance:
 *   §01 §2.1 — mutations via wallStore.add() / wallStore.remove().
 *   §01 §2.6 — newId supplied by the Tool layer.
 */
export class OffsetElementCommand implements Command {
    readonly affectedStores = ['wall'] as const;
    readonly id: string;
    readonly type  = CommandType.OFFSET_ELEMENT;
    readonly timestamp: number;
    readonly targetIds: string[];

    private executed = false;

    constructor(private readonly input: OffsetElementInput) {
        this.id        = crypto.randomUUID();
        this.timestamp = Date.now();
        this.targetIds = [input.sourceId, input.newId];
        Object.freeze(this.targetIds);
    }

    canExecute(ctx: CommandContext): CommandValidationResult {
        const source = ctx.stores.wallStore.getById(this.input.sourceId);
        if (!source) return { ok: false, reason: 'SOURCE_NOT_FOUND', blockingIssues: [`Element not found: ${this.input.sourceId}`] };
        if (ctx.stores.wallStore.getById(this.input.newId)) {
            return { ok: false, reason: 'NEW_ID_CONFLICT', blockingIssues: [`ID already in use: ${this.input.newId}`] };
        }
        if (Math.abs(this.input.distance) < 0.01) {
            return { ok: false, reason: 'DISTANCE_TOO_SMALL', blockingIssues: ['Offset distance must be at least 0.01 m'] };
        }

        const bl = source.baseLine;
        const dx = bl[1].x - bl[0].x, dz = bl[1].z - bl[0].z;
        if (Math.sqrt(dx * dx + dz * dz) < 1e-6) {
            return { ok: false, reason: 'DEGENERATE_WALL', blockingIssues: ['Source wall has zero length'] };
        }

        return { ok: true };
    }

    execute(ctx: CommandContext): CommandResult {
        if (this.executed) return { success: false, affectedElementIds: [], info: ['Already executed'] };

        const source = ctx.stores.wallStore.getById(this.input.sourceId)!;
        const perp = _perpXZ(source.baseLine[0], source.baseLine[1]);

        const ox = perp.x * this.input.distance;
        const oz = perp.z * this.input.distance;

        const offset = deserializeWallSnapshot(serializeWallSnapshot(source));
        offset.id       = this.input.newId;
        offset.baseLine = [
            { x: source.baseLine[0].x + ox, y: source.baseLine[0].y, z: source.baseLine[0].z + oz },
            { x: source.baseLine[1].x + ox, y: source.baseLine[1].y, z: source.baseLine[1].z + oz },
        ] as [Point3D, Point3D];
        offset.openings    = [];
        offset.childrenIds = [];
        offset._renderVersion = 1;

        ctx.stores.wallStore.add(offset);

        const bimMgr = ctx.bimManager ?? window.bimManager;
        bimMgr?.registerElement?.(this.input.newId, source.levelId);
        try { elementRegistry.registerSemantic(this.input.newId, 'wall'); } catch (_) {}

        this.executed = true;
        return { success: true, affectedElementIds: [this.input.newId] };
    }

    undo(ctx: CommandContext): CommandResult {
        if (!this.executed) return { success: false, affectedElementIds: [], info: ['Nothing to undo'] };

        const bimMgr = ctx.bimManager ?? window.bimManager;
        bimMgr?.unregisterElement?.(this.input.newId);
        elementRegistry.unregister(this.input.newId);
        ctx.stores.wallStore.remove(this.input.newId);

        this.executed = false;
        return { success: true, affectedElementIds: [this.input.newId] };
    }

    serialize(): SerializedCommand {
        return {
            type:      this.type,
            timestamp: this.timestamp,
            targetIds: [...this.targetIds],
            version:   1,
            payload: {
                sourceId: this.input.sourceId,
                newId:    this.input.newId,
                distance: this.input.distance,
            },
        };
    }
}

// ── Geometry helper ────────────────────────────────────────────────────────

/**
 * Returns the unit perpendicular vector of the wall direction in XZ.
 * Convention: rotate direction 90° clockwise when looking down (−Y) →
 *   dir = (dx, 0, dz)  →  perp = (dz, 0, −dx)
 * This matches the standard BIM "left of travel" convention.
 */
function _perpXZ(a0: Point3D, a1: Point3D): { x: number; z: number } {
    const dx = a1.x - a0.x, dz = a1.z - a0.z;
    const len = Math.sqrt(dx * dx + dz * dz);
    return { x: dz / len, z: -dx / len };
}
