// @migration S90-WIRE — moved from src/generative/types/GenerativeTypes.ts
// Pure types; no imports. Stays in src/ai/generative/ (L7.5) until src/constraints/
// migrates to packages/constraint-solver/, at which point LayoutGenerator.ts
// can also move to packages/ai-host/src/generative/ (Wave 11).
/**
 * ## MODIFICATION DECLARATION
 *
 * Layer Affected:    Generative (World Model Layer 4)
 * Phase:             Phase I — Generative Design from Brief
 * Files Modified:    src/generative/types/GenerativeTypes.ts
 * Classification:    A
 *
 * Core type definitions for the Generative Design from Brief subsystem.
 * All geometry is in metres; grid cells are 1m × 1m.
 */

// ── Brief input types ─────────────────────────────────────────────────────────

export interface GenerativeDesignBrief {
    rooms: GenerativeBriefRoom[];
    boundingBox: { width_m: number; depth_m: number };
    templateSetId: string;
    gridSize_m: number;         // default 1.0m — snaps generated rooms to grid
    targetGIA_m2: number;
    maxVariants: number;        // default 10
}

export interface GenerativeBriefRoom {
    roomType: string;
    count: number;
    minArea_m2: number;
    maxArea_m2?: number;
    adjacencyRequirements: string[];    // room types this must be adjacent to
    circulationRequired: boolean;       // whether a corridor access is needed
    templateId?: string;
}

// ── Layout generation output types ───────────────────────────────────────────

/** A single room placement on the grid. */
export interface GeneratedRoom {
    id: string;
    name: string;
    roomType: string;
    templateId?: string;
    /** Grid origin in cells (col, row) */
    gridCol: number;
    gridRow: number;
    /** Room dimensions in grid cells */
    widthCells: number;
    depthCells: number;
    /** World-space coords in metres (bottom-left corner) */
    x_m: number;
    z_m: number;
    /** Room dimensions in metres */
    width_m: number;
    depth_m: number;
    /** Area in m² */
    area_m2: number;
    /** Original brief room type (for adjacency matching) */
    briefRoomType: string;
}

/** Scoring breakdown for a layout variant. */
export interface LayoutScore {
    total: number;              // 0–100 percentage
    compliance: number;         // 0–100 (40% weight)
    circulation: number;        // 0–100 (30% weight)
    adjacency: number;          // 0–100 (30% weight)
}

/** An adjacency pair that is satisfied or not. */
export interface AdjacencyResult {
    roomId: string;
    requiredType: string;
    satisfied: boolean;
    neighbourId?: string;
}

/** A complete layout variant generated by LayoutGenerator. */
export interface GeneratedLayout {
    variantIndex: number;       // 0-based, corresponds to seed
    seed: number;
    rooms: GeneratedRoom[];
    score: LayoutScore;
    adjacencyResults: AdjacencyResult[];
    totalGIA_m2: number;
    complianceViolations: string[];
    boundingBox: { width_m: number; depth_m: number };
    isCompliant: boolean;
}

// ── Advisor types ─────────────────────────────────────────────────────────────

export interface AdvisorSuggestion {
    id: string;
    type: 'resize_bbox' | 'reorder_adjacency' | 'reduce_programme' | 'general';
    title: string;
    description: string;
    /** If set, clicking Apply patches this field of the brief. */
    briefPatch?: Partial<GenerativeDesignBrief>;
}

export interface AdvisorResponse {
    canGenerate: boolean;
    suggestions: AdvisorSuggestion[];
    rawText: string;
}
